/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_RandomAccessFile
#define _Included_java_io_RandomAccessFile

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_RandomAccessFile */

typedef struct Classjava_io_RandomAccessFile {
  struct Hjava_io_FileDescriptor* fd;
} Classjava_io_RandomAccessFile;
HandleTo(java_io_RandomAccessFile);

extern void java_io_RandomAccessFile_open(struct Hjava_io_RandomAccessFile*, struct Hjava_lang_String*, jbool);
extern jint java_io_RandomAccessFile_read(struct Hjava_io_RandomAccessFile*);
extern jint java_io_RandomAccessFile_readBytes(struct Hjava_io_RandomAccessFile*, HArrayOfByte*, jint, jint);
extern void java_io_RandomAccessFile_write(struct Hjava_io_RandomAccessFile*, jint);
extern void java_io_RandomAccessFile_writeBytes(struct Hjava_io_RandomAccessFile*, HArrayOfByte*, jint, jint);
extern jlong java_io_RandomAccessFile_getFilePointer(struct Hjava_io_RandomAccessFile*);
extern void java_io_RandomAccessFile_seek(struct Hjava_io_RandomAccessFile*, jlong);
extern jlong java_io_RandomAccessFile_length(struct Hjava_io_RandomAccessFile*);
extern void java_io_RandomAccessFile_close(struct Hjava_io_RandomAccessFile*);

#ifdef __cplusplus
}
#endif

#endif
