/* Warning ! This is a generated file. Use build_mathnamespace to regenerate it */
#define acos KaffeMath_acos
#define asin KaffeMath_asin
#define atan KaffeMath_atan
#define atan2 KaffeMath_atan2
#define cos KaffeMath_cos
#define sin KaffeMath_sin
#define tan KaffeMath_tan
#define cosh KaffeMath_cosh
#define sinh KaffeMath_sinh
#define exp KaffeMath_exp
#define frexp KaffeMath_frexp
#define ldexp KaffeMath_ldexp
#define log KaffeMath_log
#define modf KaffeMath_modf
#define pow KaffeMath_pow
#define sqrt KaffeMath_sqrt
#define ceil KaffeMath_ceil
#define fabs KaffeMath_fabs
#define floor KaffeMath_floor
#define fmod KaffeMath_fmod
#define erf KaffeMath_erf
#define erfc KaffeMath_erfc
#define gamma KaffeMath_gamma
#define hypot KaffeMath_hypot
#define isnan KaffeMath_isnan
#define finite KaffeMath_finite
#define j0 KaffeMath_j0
#define j1 KaffeMath_j1
#define jn KaffeMath_jn
#define lgamma KaffeMath_lgamma
#define y0 KaffeMath_y0
#define y1 KaffeMath_y1
#define yn KaffeMath_yn
#define acosh KaffeMath_acosh
#define asinh KaffeMath_asinh
#define cbrt KaffeMath_cbrt
#define logb KaffeMath_logb
#define nextafter KaffeMath_nextafter
#define remainder KaffeMath_remainder
#define logb KaffeMath_logb
#define scalb KaffeMath_scalb
#define significand KaffeMath_significand
#define logbf KaffeMath_logbf
#define scalbf KaffeMath_scalbf
#define significandf KaffeMath_significandf
#define copysign KaffeMath_copysign
#define ilogb KaffeMath_ilogb
#define rint KaffeMath_rint
#define rintf KaffeMath_rintf
#define scalbn KaffeMath_scalbn
