/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_ClassLoader
#define _Included_java_lang_ClassLoader

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_ClassLoader */

typedef struct Hjava_lang_ClassLoader {
  Hjava_lang_Object base;
  struct Hjava_util_Hashtable* loadedClasses;
  struct Hjava_security_ProtectionDomain* defaultProtectionDomain;
  struct Hjava_lang_ClassLoader* parent;
} Hjava_lang_ClassLoader;

extern struct Hjava_lang_Class* java_lang_ClassLoader_defineClass0(struct Hjava_lang_ClassLoader*, struct Hjava_lang_String*, HArrayOfByte*, jint, jint);
extern struct Hjava_lang_Class* java_lang_ClassLoader_findLoadedClass0(struct Hjava_lang_ClassLoader*, struct Hjava_lang_String*);
extern void java_lang_ClassLoader_resolveClass0(struct Hjava_lang_ClassLoader*, struct Hjava_lang_Class*);

#ifdef __cplusplus
}
#endif

#endif
