/* LocaleInformation_sk.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML sk.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_sk extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "m\u00e1j",
    "j\u00fan",
    "j\u00fal",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "janu\u00e1r",
    "febru\u00e1r",
    "marec",
    "apr\u00edl",
    "m\u00e1j",
    "j\u00fan",
    "j\u00fal",
    "august",
    "september",
    "okt\u00f3ber",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Ne",
    "Po",
    "Ut",
    "St",
    "\u0160t",
    "Pi",
    "So",
  };

  private static final String[] weekdays = {
    null,
    "Nede\u013ea",
    "Pondelok",
    "Utorok",
    "Streda",
    "\u0160tvrtok",
    "Piatok",
    "Sobota",
  };

  private static final String[] eras = {
    "pred n.l.",
    "n.l.",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "V\u00fdchodn\u00fd Timor");
        put("TK", "Tokelau");
        put("TJ", "Tad\u017eikistan");
        put("TH", "Thajsko");
        put("TG", "Togo");
        put("TF", "Franc\u00fazske ju\u017en\u00e9 \u00fazemia");
        put("GY", "Guayana");
        put("TD", "\u010cad");
        put("TC", "Turks a Caicos");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Ju\u017en\u00e1 Georgia a Ju\u017en\u00e9 Sandwichove ostrovy");
        put("GR", "Gr\u00e9cko");
        put("GQ", "Rovn\u00edkov\u00e1 Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Svazijsko");
        put("SY", "S\u00fdrska arabsk\u00e1 republika");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f3nsko");
        put("SV", "Salvador");
        put("ST", "Sv\u00e4t\u00fd Tom\u00e1\u0161 a Princove ostrovy");
        put("GI", "Gibralt\u00e1r");
        put("GH", "Ghana");
        put("SR", "Surinam");
        put("GF", "Franc\u00fazska Guayana");
        put("SP", "Serbia");
        put("GE", "Gruz\u00ednsko");
        put("SO", "Som\u00e1lsko");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Mar\u00edno");
        put("GB", "Spojen\u00e9 kr\u00e1\u013eovstvo");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovensk\u00e1 republika");
        put("SJ", "\u0160picbergy a Jan Mayen");
        put("SI", "Slovinsko");
        put("SH", "Sv\u00e4t\u00e1 Helena");
        put("SG", "Singapur");
        put("SE", "\u0160v\u00e9dsko");
        put("SD", "Sud\u00e1n");
        put("SC", "Seychelsk\u00e9 ostrovy");
        put("SB", "\u0160alam\u00fanove ostrovy");
        put("SA", "Saudsk\u00e1 Ar\u00e1bia");
        put("FR", "Franc\u00fazsko");
        put("FO", "Faersk\u00e9 ostrovy");
        put("FM", "Mikron\u00e9zia, Federat\u00edvne \u0161t\u00e1ty");
        put("RW", "Rwanda");
        put("FK", "Falklandsk\u00e9 ostrovy");
        put("RU", "Rusk\u00e1 feder\u00e1cia");
        put("FJ", "Fid\u017ei");
        put("FI", "F\u00ednsko");
        put("RO", "Rumunsko");
        put("RE", "Reunion");
        put("ET", "Eti\u00f3pia");
        put("ES", "\u0160panielsko");
        put("ER", "Eritrea");
        put("EH", "Z\u00e1padn\u00e1 Sahara");
        put("EG", "Egypt");
        put("EE", "Est\u00f3nsko");
        put("EC", "Ekv\u00e1dor");
        put("DZ", "Al\u017e\u00edrsko");
        put("QA", "Katar");
        put("DO", "Dominik\u00e1nska republika");
        put("PY", "Paraguaj");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "D\u00e1nsko");
        put("DJ", "D\u017eibuti");
        put("PT", "Portugalsko");
        put("PS", "Palest\u00ednske \u00fazemie");
        put("PR", "Portoriko");
        put("DE", "Nemecko");
        put("PN", "Pitcairnove ostrovy");
        put("PM", "Saint Pierre a Miquelon");
        put("PL", "Po\u013esko");
        put("PK", "Pakistan");
        put("PH", "Filip\u00edny");
        put("PG", "Papua Nov\u00e1 Guinea");
        put("PF", "Franc\u00fazska Polyn\u00e9zia");
        put("CZ", "\u010cesk\u00e1 republika");
        put("PE", "Peru");
        put("CY", "Cyprus");
        put("CX", "Viano\u010dn\u00fd ostrov");
        put("CV", "Kapverdy");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kostarika");
        put("CO", "Kolumbia");
        put("CN", "\u010c\u00edna");
        put("CM", "Kamerun");
        put("CL", "\u010cile");
        put("CK", "Cookove ostrovy");
        put("CI", "Pobre\u017eie Slonoviny");
        put("CH", "\u0160vaj\u010diarsko");
        put("CG", "Kongo");
        put("CF", "Stredoafrick\u00e1 republika");
        put("CD", "Kon\u017esk\u00e1 demokratick\u00e1 republika");
        put("CC", "Kokosov\u00e9 (Keelingove) ostrovy");
        put("OM", "Om\u00e1n");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Bielorusko");
        put("BW", "Botswana");
        put("BV", "Bouvetov ostrov");
        put("BT", "But\u00e1n");
        put("BS", "Bahamy");
        put("BR", "Braz\u00edlia");
        put("NZ", "Nov\u00fd Z\u00e9land");
        put("BO", "Bol\u00edvia");
        put("BN", "Brunej");
        put("BM", "Bermudy");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrajn");
        put("NR", "Nauru");
        put("BG", "Bulharsko");
        put("BF", "Burkina Faso");
        put("NP", "Nep\u00e1l");
        put("BE", "Belgicko");
        put("NO", "N\u00f3rsko");
        put("BD", "Banglad\u00e9\u0161");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Holandsko");
        put("BA", "Bosna a Hercegovina");
        put("NI", "Nikaragua");
        put("NG", "Nig\u00e9ria");
        put("NF", "Norfolkov ostrov");
        put("AZ", "Azerbajd\u017ean");
        put("NE", "Niger");
        put("NC", "Nov\u00e1 Kaled\u00f3nia");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Nam\u00edbia");
        put("AU", "Austr\u00e1lia");
        put("AT", "Rak\u00fasko");
        put("AS", "Americk\u00e1 Samoa");
        put("AR", "Argent\u00edna");
        put("AQ", "Antarctica");
        put("MZ", "Mozambik");
        put("AO", "Angola");
        put("MY", "Malajzia");
        put("AN", "Holandsk\u00e9 Antily");
        put("MX", "Mexiko");
        put("AM", "Arm\u00e9nsko");
        put("MW", "Malawi");
        put("AL", "Alb\u00e1nsko");
        put("MV", "Maldivy");
        put("ZA", "Ju\u017en\u00e1 Afrika");
        put("MU", "Maur\u00edcius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Maurit\u00e1nia");
        put("AG", "Antigua a Barbados");
        put("MQ", "Martinik");
        put("AF", "Afganistan");
        put("MP", "Severn\u00e9 Mari\u00e1ny");
        put("AE", "Spojen\u00e9 arabsk\u00e9 emir\u00e1ty");
        put("MO", "Makao S.A.R. \u010c\u00edny");
        put("AD", "Andorra");
        put("MN", "Mongolsko");
        put("MM", "Mjanmarsko");
        put("ML", "Mali");
        put("MK", "Maced\u00f3nsko, republika");
        put("YU", "Juhosl\u00e1via");
        put("YT", "Mayotte");
        put("MH", "Marshallove ostrovy");
        put("MG", "Madagaskar");
        put("MD", "Moldavsko, republika");
        put("MC", "Monako");
        put("MA", "Maroko");
        put("YE", "Jemen");
        put("LY", "L\u00fdbijsk\u00e1 arabsk\u00e1 d\u017eamah\u00edrija");
        put("LV", "Loty\u0161sko");
        put("LU", "Luxembursko");
        put("LT", "Litva");
        put("LS", "Lesotho");
        put("LR", "Lib\u00e9ria");
        put("LK", "Sr\u00ed Lanka");
        put("LI", "Lichten\u0161tajnsko");
        put("LC", "Sv\u00e4t\u00e1 Lucia");
        put("LB", "Libanon");
        put("LA", "Laosk\u00e1 \u013eudovodemokratick\u00e1 republika");
        put("KZ", "Kazachstan");
        put("KY", "Kajmansk\u00e9 ostrovy");
        put("KW", "Kuvajt");
        put("KR", "K\u00f3rea, Ju\u017en\u00e1");
        put("KP", "K\u00f3rea, Severn\u00e1");
        put("KN", "Saint Kitts a Nevis");
        put("KM", "Komory");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambod\u017ea");
        put("KG", "Kirgizsko");
        put("KE", "Ke\u0148a");
        put("WF", "Wallis a Futuna");
        put("JP", "Japonsko");
        put("JO", "Jord\u00e1nsko");
        put("JM", "Jamajka");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Panensk\u00e9 ostrovy - USA");
        put("VG", "Britsk\u00e9 panensk\u00e9 ostrovy");
        put("VE", "Venezuela");
        put("VC", "Sv\u00e4t\u00fd Vincent a Grenad\u00edny");
        put("VA", "Sv\u00e4t\u00e1 stolica (Vatik\u00e1nsky mestsk\u00fd \u0161t\u00e1t)");
        put("IT", "Taliansko");
        put("IS", "Island");
        put("IR", "Ir\u00e1n");
        put("IQ", "Irak");
        put("UZ", "Uzbekistan");
        put("IO", "Britsk\u00e9 \u00fazemie v Indickom oce\u00e1ne");
        put("UY", "Uruguaj");
        put("IN", "India");
        put("IL", "Izrael");
        put("US", "Spojen\u00e9 \u0161t\u00e1ty");
        put("IE", "\u00cdrsko");
        put("ID", "Indon\u00e9zia");
        put("UM", "Men\u0161ie od\u013eahl\u00e9 ostrovy USA");
        put("UG", "Uganda");
        put("UA", "Ukrajina");
        put("HU", "Ma\u010farsko");
        put("HT", "Haiti");
        put("HR", "Chorv\u00e1tsko");
        put("TZ", "Tanz\u00e1nia");
        put("HN", "Honduras");
        put("HM", "Heardove ostrovy a McDonaldove ostrovy");
        put("TW", "Tajwan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R. \u010c\u00edny");
        put("TT", "Trinidad a Tobago");
        put("TR", "Turecko");
        put("TO", "Tonga");
        put("TN", "Tunisko");
        put("TM", "Turkm\u00e9nsko");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "d.M.yyyy" },
    { "mediumDateFormat", "d.M.yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE, d. MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss z" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
