/* LocaleInformation_tr.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_tr extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "\u00dcrd\u00fcn Dinar\u0131\u00A6Bolivya Mvdol\u00A6Alt\u0131n\u00A6Faroe Adalar\u0131 Kronu\u00A6L\u00fcbnan Liras\u0131\u00A6Euro\u00A6Vietnam Dongu\u00A6Tanzanya \u015eilini\u00A6Bolivya Pezosu\u00A6Kambo\u00e7ya Rieli\u00A6Asya Para Birimi\u00A6Bolivya Bolivyanosu (1863-1962)\u00A6Eski Kambo\u00e7ya Rieli\u00A6Zambiya Liras\u0131\u00A6Avustralya Liras\u0131\u00A6CFA Frang\u0131 BEAC\u00A6Malta Liras\u0131\u00A6Yeni Gana Sedisi\u00A6Zambiya Kva\u00e7as\u0131\u00A6Asya Hesap Birimi Dinar\u0131\u00A6Gana Liras\u0131\u00A6Bolivya Bolivyanosu\u00A6Eski Gana Sedisi\u00A6Malta Liras\u0131\u00A6Avustralya Dolar\u0131\u00A6ABD Dolar\u0131 (Ayn\u0131 g\u00fcn)\u00A6\u0130talyan Lireti\u00A6ABD Dolar\u0131 (Ertesi g\u00fcn)\u00A6Gana Sedisi\u00A6Singapur Dolar\u0131\u00A6Panama Balboas\u0131\u00A6Laos Kipi\u00A6K\u0131rg\u0131z Somu\u00A6\u0130svi\u00e7re Frang\u0131\u00A6Avusturya \u015eilini\u00A6ABD Dolar\u0131\u00A6Etiyopya Dolar\u0131\u00A6Brunei Dolar\u0131\u00A6Jamaika Liras\u0131\u00A6Etiyopya Birri\u00A6Cezayir Frang\u0131 (Germinal)\u00A6Yeni Cezayir Frang\u0131\u00A6Cezayir Dinar\u0131\u00A6Paraguay Guaranisi\u00A6Libya Liras\u0131\u00A6Jamaika Dolar\u0131\u00A6\u0130zlanda Kronu\u00A6\u0130spanyol Pezetas\u0131\u00A6Bermuda Liras\u0131\u00A6Libya Dinar\u0131\u00A6Libya \u0130ngiliz Askeri Y\u00f6netimi Liras\u0131\u00A6Bermuda Dolar\u0131\u00A6Hollanda Florini\u00A6Moritanya Ouguiyas\u0131\u00A6\u0130ran Riyali\u00A6\u0130sve\u00e7 Kronu\u00A6Eritre Nakfas\u0131\u00A6Kenya \u015eilini\u00A6Orta Afrika Cumhuriyeti Frang\u0131\u00A6Arjantin Pezosu\u00A6Arjantin Pezosu (1983-1985)\u00A6Arjantin Pezosu Moneda Nacional\u00A6Yeni Tayvan Dolar\u0131\u00A6Sudan Liras\u0131\u00A6G\u00fcrcistan Larisi\u00A6G\u00fcrcistan Kupon Larisi\u00A6Martinik Frang\u0131\u00A6Falkland Adalar\u0131 Liras\u0131\u00A6Arjantin Australi\u00A6Sudan Dinar\u0131\u00A6Irak Dinar\u0131\u00A6Tuvalu Dolar\u0131\u00A6Sey\u015feller Rupisi\u00A6Letonya Rublesi\u00A6Fiji Liras\u0131\u00A6Letonya Lat\u0131\u00A6Kongo Zairesi\u00A6Kongo Cumhuriyeti Frang\u0131\u00A6Kongo Frang\u0131\u00A6Fiji Dolar\u0131\u00A6Nikaragua Kordobas\u0131 (Oro)\u00A6Makao Patacas\u0131\u00A6Alt\u0131n Nikaragua Kordobas\u0131\u00A6Nikaragua Kordobas\u0131\u00A6COMECON Transfer Edilebilir Rublesi\u00A6Fin Markkas\u0131 (1860-1962)\u00A6Fin Markkas\u0131\u00A6Solomon Adalar\u0131 Dolar\u0131\u00A6L\u00fcksemburg Frang\u0131\u00A6Eski Trinidad ve Tobago Dolar\u0131\u00A6Angola Esk\u00fcdosu\u00A6Angola Kvanzas\u0131 Reajustado (1995-1999)\u00A6Mo\u011fol Tugriki\u00A6Macar Forinti\u00A6Burundi Frang\u0131\u00A6Yeni Angola Kvanzas\u0131 (1990-2000)\u00A6Angola Kvanzas\u0131 (1977-1990)\u00A6Trinidad ve Tobago Dolar\u0131\u00A6Swaziland Lilangenisi\u00A6Yeni Hebridler CFP Frang\u0131\u00A6\u0130ngiliz Sterlini\u00A6Suudi Arabistan Riyali (Sovereign)\u00A6Suudi Arabistan Riyali\u00A6Litvanya Talonu\u00A6Hindistan Rupisi\u00A6Portekiz Esk\u00fcdosu\u00A6Angola Kvanzas\u0131\u00A6Portekiz Conto\u00A6Litvanya Litas\u0131\u00A6Kazakistan Tengesi\u00A6Kazakistan Rublesi\u00A6\u0130ngiliz Virgin Adalar\u0131 Dolar\u0131\u00A6Nijerya Liras\u0131\u00A6Myanmar Dolar\u0131 FEC\u00A6Nijerya Nairas\u0131\u00A6Haiti Gurdu\u00A6Suriye Liras\u0131\u00A6Filistin Liras\u0131\u00A6Bahreyn Dinar\u0131\u00A6Myanmar Kyat\u0131\u00A6Hollanda Antilleri Guldeni\u00A6\u00c7ek Cumhuriyeti Korunas\u0131\u00A6Man Adas\u0131 Sterlini\u00A6Bulgar Levas\u0131 FEC\u00A6Lesotho Lotisi\u00A6Gabon CFA Frang\u0131\u00A6Bulgar Levas\u0131 (1879-1952)\u00A6Yeni Bulgar Levas\u0131\u00A6Sosyalist Bulgar Levas\u0131\u00A6Kanada Dolar\u0131\u00A6Bulgar Levas\u0131 (Hard)\u00A6T\u00fcrk Liras\u0131\u00A6Kayman Adalar\u0131 Dolar\u0131\u00A6G\u00fcney K\u0131br\u0131s Liras\u0131\u00A6Yeni \u0130srail \u015eekeli\u00A6Guyana Dolar\u0131\u00A6Ermenistan Dram\u0131\u00A6\u0130srail Liras\u0131\u00A6Mali Frang\u0131\u00A6\u0130srail \u015eekeli\u00A6Venezuela Bolivar\u0131\u00A6Arnavut Dolar\u0131 FEC\u00A6Liberya Dolar\u0131\u00A6Arnavutluk Leki Valute\u00A6H\u0131rvat Kunas\u0131\u00A6Reunion Frang\u0131\u00A6H\u0131rvat Dinar\u0131\u00A6Arnavutluk Leki\u00A6Jersey Sterlini\u00A6Arnavutluk Leki (1946-1961)\u00A6Makedonya Dinar\u0131 (1992-1993)\u00A6Kuzey Vietnam Viet Minh Piastre Dong Viet\u00A6Yeni Kuzey Vietnam Dongu\u00A6Makedonya Dinar\u0131\u00A6Kuzey Vietnam Piastre Dong Viet\u00A6Timor Patacas\u0131\u00A6CFP Frang\u0131\u00A6Bel\u00e7ika Frang\u0131 (finansal)\u00A6Gine-Bissau Pezosu\u00A6Kuveyt Dinar\u0131\u00A6Portekiz Ginesi Mil Reis\u00A6Bel\u00e7ika Frang\u0131\u00A6Timor Esk\u00fcdosu\u00A6Bel\u00e7ika Frang\u0131 (konvertibl)\u00A6Portekiz Ginesi Esk\u00fcdosu\u00A6El Salvador Kolonu\u00A6Kurasao Florini\u00A6Banglade\u015f Takas\u0131\u00A6Tonga Sterlini\u00A6Tonga Pa\u02bbangas\u0131\u00A6CFA Frang\u0131 BCEAO\u00A6Sovyet Rublesi\u00A6Yeni Sovyet Rublesi\u00A6Yeni Kaledonya Frang\u0131 (Germinal)\u00A6Cape Verde Esk\u00fcdosu\u00A6Frans\u0131z Antilleri CFA Frang\u0131\u00A6G\u00fcney Afrika Rand\u0131\u00A6Dominik Pezosu\u00A6K\u00fcba FEC\u00A6G\u00fcney Afrika Liras\u0131\u00A6G\u00fcney Afrika Rand\u0131 (finansal)\u00A6Tunus Dinar\u0131\u00A6K\u00fcba Pezosu\u00A6Frans\u0131z Guyanas\u0131 Frang\u0131\u00A6Uganda \u015eilini\u00A6Seylan Rupisi\u00A6Afarlar ve \u0130ssalar Frang\u0131\u00A6Vatikan \u015eehir Devleti Liras\u0131\u00A6Sao Tome ve Principe Esk\u00fcdosu\u00A6Uganda \u015eilini (1966-1987)\u00A6Sao Tome ve Principe Dobras\u0131\u00A6Marshall Adalar\u0131 Dolar\u0131\u00A6Yeni Zelanda Liras\u0131\u00A6Bat\u0131 Samoa Talas\u0131\u00A6Bat\u0131 Samoa Liras\u0131\u00A6Honduras Lempiras\u0131\u00A6Ana Fransa yeni Frang\u0131\u00A6T\u00fcrkmenistan Manat\u0131\u00A6Guatemala Ketzali\u00A6Yeni Zelanda Dolar\u0131\u00A6\u0130sko\u00e7ya Liras\u0131\u00A6Barbados Dolar\u0131\u00A6Namibya Dolar\u0131\u00A6Madagaskar Frang\u0131\u00A6Madagaskar Ariary\u00A6M\u0131s\u0131r Liras\u0131\u00A6\u0130ngiliz Honduras\u0131 Dolar\u0131\u00A6Polonya Zlotisi (1950-1995)\u00A6Yeni Bosna Hersek Dinar\u0131\u00A6Polonya ABD Dolar\u0131 FEC\u00A6Konvertibl Bosna Hersek Mark\u0131\u00A6Belize Dolar\u0131\u00A6Bosna Hersek Dinar\u0131\u00A6Polonya Zlotisi\u00A6Yemen Riyali\u00A6Surinam Guldeni\u00A6\u00c7ekoslavak Korunas\u0131 (Hard)\u00A6G\u00fcney Kore Wonu\u00A6Beyaz Rusya Rublesi\u00A6Yemen Riyali (Imadi)\u00A6Beyaz Rusya Rublesi (1992-1994)\u00A6\u00c7ekoslavak Korunas\u0131\u00A6Eski G\u00fcney Kore Wonu\u00A6G\u00fcney Kore Hwan\u0131\u00A6Yeni Beyaz Rusya Rublesi (1994-1999)\u00A6Somaliland \u015eilini\u00A6Yeni Yunan Drahmisi\u00A6Pakistan Rupisi\u00A6Afganistan Afganisi\u00A6Zimbabwe Dolar\u0131\u00A6Sri Lanka Rupisi\u00A6Yunan Drahmisi\u00A6\u0130rlanda Liras\u0131\u00A6Afganistan Afganisi (1927-2002)\u00A6Yemen Dinar\u0131\u00A6Ruanda Frang\u0131\u00A6Kosta Rika Kolonu\u00A6Tacikistan Somonisi\u00A6Tacikistan Rublesi\u00A6Estonya Krunu\u00A6Ekvator Ginesi Pezetas\u0131\u00A6Moldova Rublesi (Cupon)\u00A6Hong Kong Dolar\u0131\u00A6Danimarka Kronu\u00A6Moldova Leyi\u00A6Ekvator Ginesi Frang\u0131\u00A6Ekvator Ginesi Ekuelesi\u00A6Endonezya Rupiah\u0131\u00A6Birle\u015fik Arap Emirlikleri Dirhemi\u00A6Kuzey Kore Wonu\u00A6Yeni Endonezya Rupiah\u0131\u00A6Botsvana Pulas\u0131\u00A6Moldova Leyi (Cupon)\u00A6Endonezya Java Rupiah\u0131\u00A6Kuzey Kore Halk Cumhuriyeti Wonu\u00A6Endonezya Nica Florini\u00A6Vanuatu Vatusu\u00A6\u0130slam Dinar\u0131\u00A6Somali \u015eilini\u00A6Andora Pezetas\u0131\u00A6Rus Rublesi (1991-1998)\u00A6Guadeloupe Frang\u0131\u00A6Cibuti Frang\u0131\u00A6Andora Dinar\u0131\u00A6Fas Frang\u0131 (Germinal)\u00A6Yeni Fas Frang\u0131\u00A6Ekvator Unidad de Valor Constante (UVC)\u00A6Ekvator Sukresi\u00A6Liechtenstein Frang\u0131\u00A6Rus Rublesi\u00A6Filipinler Pezosu\u00A6\u00d6zbekistan Sumu\u00A6Kolombiya Pezosu\u00A6Tayland Baht\u0131\u00A6Kuzey \u0130rlanda Liras\u0131\u00A6Burma Rupisi\u00A6Kongo CFA Frang\u0131\u00A6Burma Kyat\u0131\u00A6Kolombiya Ka\u011f\u0131t Pezosu\u00A6\u00d6zbekistan Sumu (Coupon)\u00A6Ukrayna Karbovanetz\u00A6Katar Riyali\u00A6Ukrayna Grivnas\u0131\u00A6Gine Syli\u00A6\u00c7in Yuan\u0131 Renminbi\u00A6Mozambik Metical\u0131\u00A6\u00c7in ABD Dolar\u0131 FEC\u00A6Uruguay Pezosu (Uruguayo)\u00A6Gine Frang\u0131 (1960-1972)\u00A6San Marino Liras\u0131\u00A6\u00c7in Jen Min Piao Yuan\u0131\u00A6Mozambik Esk\u00fcdosu\u00A6Gine Frang\u0131\u00A6Umman Riyali (Saidi)\u00A6Papua Yeni Gine Kinas\u0131\u00A6Umman Riyali\u00A6Uruguay Pezosu (1975-1993)\u00A6Frans\u0131z UIC-Frang\u0131\u00A6Bhutan Rupisi\u00A6Zaire Zairesi\u00A6Fas Frang\u0131\u00A6Fas Dirhemi\u00A6Bhutan Ngultrumu\u00A6Frans\u0131z Alt\u0131n Frang\u0131\u00A6Uruguay Pezosu (Fuerte)\u00A6Malezya Ringiti\u00A6Yeni Zaire Zairesi\u00A6Azerbaycan Manat\u0131\u00A6Gambiya Liras\u0131\u00A6Komorlar Frang\u0131\u00A6Sierra Leone Leonesi\u00A6Gambiya Dalasisi\u00A6Avrupa Para Birimi\u00A6Bahama Liras\u0131\u00A6Kamerun CFA Frang\u0131\u00A6Meksika Unidad de Inversion (UDI)\u00A6CFA Frank BCEAEC\u00A6Bahama Dolar\u0131\u00A6G\u00fcm\u00fc\u015f Meksika Pezosu (1861-1992)\u00A6Meksika Pezosu\u00A6Peru Solu\u00A6Gr\u00f6nland Kronu\u00A6Brezilya Kruzeirosu (1942-1967)\u00A6Yeni Peru Solu\u00A6\u015eili Pezosu\u00A6Slovak Korunas\u0131\u00A6Peru \u0130nti\u00A6Brezilya Kruzeirosu\u00A6\u00d6zel \u00c7ekme Hakk\u0131 (SDR)\u00A6Frans\u0131z Frang\u0131 (Germinal/Franc Poincare)\u00A6Frans\u0131z Frang\u0131\u00A6Yeni Brezilya Kruzadosu\u00A6\u015eili Unidades de Fomento\u00A6\u015eili Esk\u00fcdosu\u00A6Brezilya Reali\u00A6\u015eili Condor\u00A6Brezilya Kruzeirosu (1990-1993)\u00A6Alman Sperrmark\u00A6Malavi Liras\u0131\u00A6Brezilya Kruzadosu\u00A6Yeni Brezilya Kruzeirosu (1967-1986)\u00A6Malavi Kva\u00e7as\u0131\u00A6Transdniestria Rublesi\u00A6Alman Mark\u0131\u00A6\u00c7ad CFA Frang\u0131\u00A6Yeni Transdniestria Rublesi\u00A6Transdniestria Rublesi (Kupon)\u00A6Nepal Rupisi\u00A6Cook Adalar\u0131 Dolar\u0131\u00A6Japon Yeni\u00A6Maldiv Adalar\u0131 Rufiyaa\u00A6CFA Yeni Frank\u00A6Maldiv Adalar\u0131 Rupisi\u00A6Do\u011fu Karayip Dolar\u0131\u00A6Slovenya Tolar\u0131\u00A6Yugoslav Dinar\u0131 (Reformed)\u00A6Aruba Florini\u00A6Yugoslav Ekim Dinar\u0131\u00A6Do\u011fu Alman Mark\u0131\u00A6Konvertibl Yugoslav Dinar\u0131\u00A6Yeni Yugoslav Dinar\u0131\u00A6Turks ve Caicos Adalar\u0131 Crownu\u00A6Yugoslav 1994 Dinar\u0131\u00A6Yugoslav Federasyonu Dinar\u0131\u00A6Yeni Romen Leyi\u00A6Yugoslav Dinar\u0131 (Hard)\u00A6Romen Leyi\u00A6Slovenya Tolar\u0131 (Bons)\u00A6Norve\u00e7 Kronu\u00A6Mauritius Rupisi\u00A6Avrupa Hesap Birimi (XBD)\u00A6Cebelitar\u0131k Liras\u0131\u00A6Vietnam Ulusal Dongu\u00A6Avrupa Hesap Birimi (XBC)\u00A6Vietnam Cumhuriyeti Dongu\u00A6Avrupa Para Birimi\u00A6Birle\u015fik Avrupa Birimi\u00A6Kiribati Dolar\u0131\u00A6Saint Helena Liras\u0131\u00A6Yeni Vietnam Dongu";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LL\u00A6VND\u00A6T Sh\u00A6BOP\u00A6CR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6Bs\u00A6GHO\u00A6Lm\u00A6$A\u00A6USS\u00A6USN\u00A6GHC\u00A6S$\u00A6PAB\u00A6LAK\u00A6som\u00A6SwF\u00A6ATS\u00A6US$\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6LYB\u00A6Ber$\u00A6NLG\u00A6UM\u00A6RI\u00A6SKr\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6Ft\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SRl\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6CZK\u00A6IMP\u00A6BGX\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6Can$\u00A6lev\u00A6TL\u00A6KYD\u00A6\u00a3C\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6T$\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6XNF\u00A6R\u00A6RD$\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6XMF\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Af\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6AFA\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HK$\u00A6DKr\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6Y\u00A6Mt\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GF\u00A6OMS\u00A6PGK\u00A6RO\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6Nu\u00A6XFO\u00A6UYF\u00A6RM\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6CF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6Ch$\u00A6Sk\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6leu\u00A6SIB\u00A6NKr\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "Oca",
    "\u015eub",
    "Mar",
    "Nis",
    "May",
    "Haz",
    "Tem",
    "A\u011fu",
    "Eyl",
    "Eki",
    "Kas",
    "Ara",
    null,
  };

  private static final String[] months = {
    "Ocak",
    "\u015eubat",
    "Mart",
    "Nisan",
    "May\u0131s",
    "Haziran",
    "Temmuz",
    "A\u011fustos",
    "Eyl\u00fcl",
    "Ekim",
    "Kas\u0131m",
    "Aral\u0131k",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Paz",
    "Pzt",
    "Sal",
    "\u00c7ar",
    "Per",
    "Cum",
    "Cmt",
  };

  private static final String[] weekdays = {
    null,
    "Pazar",
    "Pazartesi",
    "Sal\u0131",
    "\u00c7ar\u015famba",
    "Per\u015fembe",
    "Cuma",
    "Cumartesi",
  };

  private static final String[] eras = {
    "M\u00d6",
    "MS",
  };


  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Do\u011fu Timor\u00A6Tokelau\u00A6Tacikistan\u00A6Tayland\u00A6Togo\u00A6Frans\u0131z G\u00fcney B\u00f6lgeleri\u00A6Guyana\u00A6\u00c7ad\u00A6Turks ve Caicos Adalar\u0131\u00A6Gine-Bissau\u00A6Guam\u00A6Guatemala\u00A6G\u00fcney Georgia ve G\u00fcney Sandwich Adalar\u0131\u00A6Yunanistan\u00A6Ekvator Ginesi\u00A6Guadeloupe\u00A6Svaziland\u00A6Suriye\u00A6Gine\u00A6Gambia\u00A6Gr\u00f6nland\u00A6El Salvador\u00A6Sao Tome ve Principe\u00A6Cebelitar\u0131k\u00A6Gana\u00A6Surinam\u00A6Frans\u0131z Guyanas\u0131\u00A6G\u00fcrcistan\u00A6Somali\u00A6Granada\u00A6Senegal\u00A6San Marino\u00A6Birle\u015fik Krall\u0131k\u00A6Sierra Leone\u00A6Gabon\u00A6Slovakya\u00A6Svalbard ve Jan Mayen\u00A6Slovenya\u00A6Saint Helena\u00A6Singapur\u00A6\u0130sve\u00e7\u00A6Sudan\u00A6Sey\u015feller\u00A6Solomon Adalar\u0131\u00A6Suudi Arabistan\u00A6Fransa\u00A6Faroe Adalar\u0131\u00A6Mikronezya Federal Eyaletleri\u00A6Ruanda\u00A6Falkland Adalar\u0131 (Malvinalar)\u00A6Rusya Federasyonu\u00A6Fiji\u00A6Finlandiya\u00A6Romanya\u00A6Reunion\u00A6Etiyopya\u00A6\u0130spanya\u00A6Eritre\u00A6Bat\u0131 Sahara\u00A6M\u0131s\u0131r\u00A6Estonya\u00A6Ekvator\u00A6Cezayir\u00A6Katar\u00A6Dominik Cumhuriyeti\u00A6Paraguay\u00A6Dominik\u00A6Palau\u00A6Danimarka\u00A6Cibuti\u00A6Portekiz\u00A6Filistin B\u00f6lgesi\u00A6Porto Riko\u00A6Almanya\u00A6Pitcairn\u00A6Saint Pierre ve Miquelon\u00A6Polonya\u00A6Pakistan\u00A6Filipinler\u00A6Papua Yeni Gine\u00A6Frans\u0131z Polinezyas\u0131\u00A6\u00c7ek Cumhuriyeti\u00A6Peru\u00A6K\u0131br\u0131s\u00A6Christmas Adas\u0131\u00A6Cape Verde\u00A6Panama\u00A6K\u00fcba\u00A6Kosta Rika\u00A6Kolombiya\u00A6\u00c7in\u00A6Kamerun\u00A6\u015eili\u00A6Cook Adalar\u0131\u00A6Fildi\u015fi Sahilleri\u00A6\u0130svi\u00e7re\u00A6Kongo\u00A6Orta Afrika Cumhuriyeti\u00A6Kongo Demokratik Cumhuriyeti\u00A6Cocos (Keeling) Adalar\u0131\u00A6Umman\u00A6Kanada\u00A6Belize\u00A6Beyaz Rusya\u00A6Botsvana\u00A6Bouvet Adas\u0131\u00A6Bhutan\u00A6Bahamalar\u00A6Brezilya\u00A6Yeni Zelanda\u00A6Bolivya\u00A6Brunei\u00A6Bermuda\u00A6Niue Adalar\u0131\u00A6Benin\u00A6Burundi\u00A6Bahreyn\u00A6Nauru Adas\u0131\u00A6Bulgaristan\u00A6Burkina Faso\u00A6Nepal\u00A6Bel\u00e7ika\u00A6Norve\u00e7\u00A6Banglade\u015f\u00A6Barbados\u00A6Zimbabwe\u00A6Hollanda\u00A6Bosna Hersek\u00A6Nikaragua\u00A6Nijerya\u00A6Norfolk Adas\u0131\u00A6Azerbaycan\u00A6Nijer\u00A6Yeni Kaledonya\u00A6Aruba\u00A6Zambiya\u00A6Namibya\u00A6Avustralya\u00A6Avusturya\u00A6Amerikan Samoas\u0131\u00A6Arjantin\u00A6Antarktika\u00A6Mozambik\u00A6Angola\u00A6Malezya\u00A6Hollanda Antilleri\u00A6Meksika\u00A6Ermenistan\u00A6Malavi\u00A6Arnavutluk\u00A6Maldivler\u00A6G\u00fcney Afrika\u00A6Mauritius\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Moritanya\u00A6Antigua ve Barbuda\u00A6Martinik\u00A6Afganistan\u00A6Kuzey Mariana Adalar\u0131\u00A6Birle\u015fik Arap Emirlikleri\u00A6Makao S.A.R. \u00c7in\u00A6Andora\u00A6Mo\u011folistan\u00A6Myanmar\u00A6Mali\u00A6Makedonya Cumhuriyeti\u00A6Yugoslavya\u00A6Mayotte\u00A6Marshall Adalar\u0131\u00A6Madagaskar\u00A6Moldovya Cumhuriyeti\u00A6Monako\u00A6Fas\u00A6Yemen\u00A6Libya\u00A6Letonya\u00A6L\u00fcksemburg\u00A6Litvanya\u00A6Lesotho\u00A6Liberya\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Saint Lucia\u00A6L\u00fcbnan\u00A6Laos\u00A6Kazakistan\u00A6Kayman Adalar\u0131\u00A6Kuveyt\u00A6G\u00fcney Kore\u00A6Kuzey Kore\u00A6Saint Kittler ve Neviler\u00A6Komorlar\u00A6Kiribati\u00A6Samoa\u00A6Kambo\u00e7ya\u00A6K\u0131rg\u0131zistan\u00A6Kenya\u00A6Wallis ve Futuna\u00A6Japonya\u00A6\u00dcrd\u00fcn\u00A6Jamaika\u00A6Vanuatu\u00A6Vietnam\u00A6ABD Virgin Adalar\u0131\u00A6\u0130ngiliz Virgin Adalar\u0131\u00A6Venezuela\u00A6Saint Vincent ve Grenadinler\u00A6Kutsal Devlet (Vatikan \u015eehir Devleti)\u00A6\u0130talya\u00A6\u0130zlanda\u00A6\u0130ran\u00A6Irak\u00A6\u00d6zbekistan\u00A6Hint Okyanusu \u0130ngiliz B\u00f6lgesi\u00A6Uruguay\u00A6Hindistan\u00A6\u0130srail\u00A6Amerika Birle\u015fik Devletleri\u00A6\u0130rlanda\u00A6Endonezya\u00A6Amerika Birle\u015fik Devletleri K\u00fc\u00e7\u00fck D\u0131\u015f Adalar\u0131\u00A6Uganda\u00A6Ukrayna\u00A6Macaristan\u00A6Haiti\u00A6H\u0131rvatistan\u00A6Tanzanya\u00A6Honduras\u00A6Heard Adas\u0131 ve McDonald Adalar\u0131\u00A6Tayvan\u00A6Tuvalu\u00A6Hong Kong SAR - \u00c7in\u00A6Trinidad ve Tobago\u00A6T\u00fcrkiye\u00A6Tonga\u00A6Tunus\u00A6T\u00fcrkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "es\u00A6ku\u00A6eo\u00A6ks\u00A6en\u00A6el\u00A6qu\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6wo\u00A6ka\u00A6dz\u00A6jv\u00A6pt\u00A6ps\u00A6de\u00A6pl\u00A6da\u00A6vo\u00A6ja\u00A6vi\u00A6cy\u00A6pa\u00A6cs\u00A6iu\u00A6it\u00A6co\u00A6is\u00A6uz\u00A6or\u00A6ik\u00A6ur\u00A6om\u00A6ca\u00A6ie\u00A6id\u00A6uk\u00A6ia\u00A6oc\u00A6ug\u00A6hy\u00A6br\u00A6hu\u00A6bo\u00A6bn\u00A6hr\u00A6bi\u00A6tw\u00A6bh\u00A6bg\u00A6tt\u00A6no\u00A6be\u00A6ts\u00A6hi\u00A6tr\u00A6nl\u00A6zu\u00A6ba\u00A6to\u00A6he\u00A6tn\u00A6tl\u00A6tk\u00A6ha\u00A6ne\u00A6az\u00A6ti\u00A6ay\u00A6th\u00A6tg\u00A6na\u00A6te\u00A6zh\u00A6ar\u00A6ta\u00A6gu\u00A6my\u00A6am\u00A6za\u00A6mt\u00A6ms\u00A6gn\u00A6sw\u00A6mr\u00A6sv\u00A6gl\u00A6su\u00A6af\u00A6st\u00A6mo\u00A6ss\u00A6mn\u00A6sr\u00A6sq\u00A6ml\u00A6ab\u00A6mk\u00A6aa\u00A6so\u00A6sn\u00A6mi\u00A6gd\u00A6sm\u00A6sl\u00A6mg\u00A6sk\u00A6ga\u00A6yo\u00A6si\u00A6sh\u00A6sg\u00A6yi\u00A6sd\u00A6fy\u00A6sa\u00A6fr\u00A6lv\u00A6lt\u00A6fo\u00A6rw\u00A6ru\u00A6lo\u00A6fj\u00A6ln\u00A6fi\u00A6ro\u00A6rn\u00A6rm\u00A6fa\u00A6la\u00A6xh\u00A6eu\u00A6ky\u00A6et";

  private static final String languagesValues = "\u0130spanyolca\u00A6K\u00fcrt\u00e7e\u00A6Esperanto\u00A6Ke\u015fmirce\u00A6\u0130ngilizce\u00A6Yunanca\u00A6Quechua\u00A6Korece\u00A6Kannada\u00A6Kambo\u00e7ya Dili\u00A6Gr\u00f6nland Dili\u00A6Kazak Dili\u00A6Wolof\u00A6G\u00fcrc\u00fcce\u00A6Bhutan Dili\u00A6Java Dili\u00A6Portekizce\u00A6Pe\u015ftun Dili\u00A6Almanca\u00A6Polonya Dili\u00A6Danca\u00A6Volapuk\u00A6Japonca\u00A6Vietnam Dili\u00A6Gal Dili\u00A6Pencap Dili\u00A6\u00c7ek\u00e7e\u00A6Inuktitut\u00A6\u0130talyanca\u00A6Korsika Dili\u00A6\u0130zlandaca\u00A6\u00d6zbek\u00e7e\u00A6Oriya\u00A6Inupiak\u00A6Urduca\u00A6Oromo (Afan)\u00A6Katalan Dili\u00A6Interlingue\u00A6Endonezya Dili\u00A6Ukraynaca\u00A6Interlingua\u00A6Occitan\u00A6Uygurca\u00A6Ermenice\u00A6Breton Dili\u00A6Macarca\u00A6Tibet\u00e7e\u00A6Bengal Dili\u00A6H\u0131rvat\u00e7a\u00A6Bislama\u00A6Twi\u00A6Bihari\u00A6Bulgarca\u00A6Tatarca\u00A6Norve\u00e7\u00e7e\u00A6Beyaz Rus\u00e7a\u00A6Tsonga\u00A6Hint Dili\u00A6T\u00fcrk\u00e7e\u00A6Hollanda Dili\u00A6Zulu\u00A6Ba\u015fk\u0131rt Dili\u00A6Tonga\u00A6\u0130branice\u00A6Setswana\u00A6Tagalog\u00A6T\u00fcrkmence\u00A6Hausa\u00A6Nepal Dili\u00A6Azerice\u00A6Tigrinya\u00A6Aymara\u00A6Tay Dili\u00A6Tacik Dili\u00A6Nauru\u00A6Telugu\u00A6\u00c7ince\u00A6Arap\u00e7a\u00A6Tamil\u00A6Gujarati\u00A6Birmanya Dili\u00A6Amharik\u00A6Zhuang\u00A6Malta Dili\u00A6Malay\u00A6Guarani\u00A6Swahili\u00A6Marathi\u00A6\u0130sve\u00e7\u00e7e\u00A6Gali\u00e7ya Dili\u00A6Sudan Dili\u00A6Afrikaan Dili\u00A6Sesotho\u00A6Moldavya Dili\u00A6Siswati\u00A6Mo\u011fol Dili\u00A6S\u0131rp\u00e7a\u00A6Arnavut\u00e7a\u00A6Malayalam\u00A6Abazca\u00A6Makedonca\u00A6Afar\u00A6Somali Dili\u00A6Shona\u00A6Maori\u00A6\u0130sko\u00e7 Gal Dili\u00A6Samoa Dili\u00A6Slovence\u00A6Malaga Dili\u00A6Slovak\u00e7a\u00A6\u0130rlanda Dili\u00A6Yoruba\u00A6Sinhal Dili\u00A6S\u0131rp-H\u0131rvat Dili\u00A6Sangho\u00A6Yiddi\u015f\u00A6Sindhi\u00A6Frizye Dili\u00A6Sanskrit\u00e7e\u00A6Frans\u0131zca\u00A6Letonya Dili\u00A6Litvanya Dili\u00A6Faroe Dili\u00A6Kinyarwanda\u00A6Rus\u00e7a\u00A6Laos Dili\u00A6Fiji Dili\u00A6Lingala\u00A6Fince\u00A6Romence\u00A6Kirundi\u00A6Rhaeto-Roman Dili\u00A6Fars\u00e7a\u00A6Latince\u00A6Xhosa\u00A6Bask Dili\u00A6K\u0131rg\u0131zca\u00A6Estonya Dili";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "shortDateFormat", "dd.MM.yyyy" },
    { "mediumDateFormat", "dd.MMM.yyyy" },
    { "longDateFormat", "dd MMMM yyyy EEEE" },
    { "fullDateFormat", "dd MMMM yyyy EEEE" },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
