/* LocaleInformation_eu.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_eu extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "ESP";

  private static final String currenciesDisplayNameValues = "ESP";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "ESP";

  private static final String currenciesSymbolValues = "\u20a7";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "urt",
    "ots",
    "mar",
    "api",
    "mai",
    "eka",
    "uzt",
    "abu",
    "ira",
    "urr",
    "aza",
    "abe",
    null,
  };

  private static final String[] months = {
    "urtarrila",
    "otsaila",
    "martxoa",
    "apirila",
    "maiatza",
    "ekaina",
    "uztaila",
    "abuztua",
    "iraila",
    "urria",
    "azaroa",
    "abendua",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "ig",
    "al",
    "as",
    "az",
    "og",
    "or",
    "lr",
  };

  private static final String[] weekdays = {
    null,
    "igandea",
    "astelehena",
    "asteartea",
    "asteazkena",
    "osteguna",
    "ostirala",
    "larunbata",
  };

  private static final String territoriesKeys = "TD\u00A6GW\u00A6AQ\u00A6MZ\u00A6MY\u00A6MX\u00A6GR\u00A6ZA\u00A6MV\u00A6GQ\u00A6SZ\u00A6MU\u00A6SY\u00A6GN\u00A6AG\u00A6AF\u00A6ST\u00A6AE\u00A6SR\u00A6YU\u00A6MK\u00A6MH\u00A6SL\u00A6MG\u00A6SK\u00A6SI\u00A6MD\u00A6MC\u00A6SG\u00A6MA\u00A6SE\u00A6SC\u00A6SB\u00A6LY\u00A6FR\u00A6LV\u00A6LU\u00A6LT\u00A6RW\u00A6FM\u00A6RU\u00A6FI\u00A6RO\u00A6LC\u00A6LB\u00A6ET\u00A6ES\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6EH\u00A6EG\u00A6KH\u00A6EC\u00A6KG\u00A6KE\u00A6DZ\u00A6QA\u00A6PY\u00A6DO\u00A6DM\u00A6JP\u00A6DK\u00A6JO\u00A6DJ\u00A6JM\u00A6DE\u00A6PL\u00A6PH\u00A6PG\u00A6CZ\u00A6CY\u00A6CV\u00A6CU\u00A6VC\u00A6VA\u00A6IT\u00A6CO\u00A6IS\u00A6CN\u00A6CM\u00A6IQ\u00A6CL\u00A6UY\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6US\u00A6CA\u00A6IE\u00A6BY\u00A6BS\u00A6BR\u00A6UA\u00A6NZ\u00A6HU\u00A6BO\u00A6HR\u00A6TT\u00A6NO\u00A6BE\u00A6TR\u00A6NL\u00A6BA\u00A6NI\u00A6TJ\u00A6TH";

  private static final String territoriesValues = "Txad\u00A6Ginea-Bissau\u00A6Antartika\u00A6Mozambike\u00A6Malasia\u00A6Mexiko\u00A6Grezia\u00A6Hegoafrika\u00A6Maldivak\u00A6Ekuatore Ginea\u00A6Swazilandia\u00A6Maurizio\u00A6Siria\u00A6Ginea\u00A6Antigua eta Barbuda\u00A6Afganistan\u00A6Sao Tom\u00e9 eta Principe\u00A6Arabiar Emirrerri Batuak\u00A6Surinam\u00A6Serbia eta Montenegro\u00A6Mazedonia\u00A6Marshall uharteak\u00A6Sierra Leona\u00A6Madagaskar\u00A6Eslovakia\u00A6Eslovenia\u00A6Moldavia\u00A6Monako\u00A6Singapur\u00A6Maroko\u00A6Suedia\u00A6Seychelleak\u00A6Salomon uharteak\u00A6Libia\u00A6Frantzia\u00A6Letonia\u00A6Luxenburgo\u00A6Lituania\u00A6Ruanda\u00A6Mikronesia\u00A6Errusia\u00A6Finlandia\u00A6Errumania\u00A6Santa Luzia\u00A6Libano\u00A6Etiopia\u00A6Espainia\u00A6Hego Korea\u00A6Ipar Korea\u00A6Saint Kitts eta Nevis\u00A6Komoreak\u00A6Mendebaldeko Sahara\u00A6Egipto\u00A6Kanbodia\u00A6Ekuador\u00A6Kirgizistan\u00A6Kenia\u00A6Aljeria\u00A6Katar\u00A6Paraguai\u00A6Dominikar Errepublika\u00A6Dominika\u00A6Japonia\u00A6Danimarka\u00A6Jordania\u00A6Djibuti\u00A6Jamaika\u00A6Alemania\u00A6Polonia\u00A6Filipinak\u00A6Papua Ginea Berria\u00A6Txekiar errepublika\u00A6Zipre\u00A6Cabo Verde\u00A6Kuba\u00A6Saint Vincent eta Grenadinak\u00A6Vatikano\u00A6Italia\u00A6Kolonbia\u00A6Islandia\u00A6Txina\u00A6Kamerun\u00A6Irak\u00A6Txile\u00A6Uruguai\u00A6Boli Kosta\u00A6Suitza\u00A6Kongo\u00A6Afrika Erdiko Errepublika\u00A6Ameriketako Estatu Batuak\u00A6Kanada\u00A6Irlanda\u00A6Bielorrusia\u00A6Bahamak\u00A6Brasil\u00A6Ukraina\u00A6Zeelanda Berria\u00A6Hungaria\u00A6Bolibia\u00A6Kroazia\u00A6Trinidad eta Tobago\u00A6Norvegia\u00A6Belgika\u00A6Turkia\u00A6Herbehereak\u00A6Bosnia-Herzegovina\u00A6Nikaragua\u00A6Tadjikistan\u00A6Tailandia";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "eu";

  private static final String languagesValues = "euskara";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
