/* LocaleInformation_vi.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML vi.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_vi extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "thg 1",
    "thg 2",
    "thg 3",
    "thg 4",
    "thg 5",
    "thg 6",
    "thg 7",
    "thg 8",
    "thg 9",
    "thg 10",
    "thg 11",
    "thg 12",
    null,
  };

  private static final String[] months = {
    "th\u00e1ng m\u1ed9t",
    "th\u00e1ng hai",
    "th\u00e1ng ba",
    "th\u00e1ng t\u01b0",
    "th\u00e1ng n\u0103m",
    "th\u00e1ng s\u00e1u",
    "th\u00e1ng b\u1ea3y",
    "th\u00e1ng t\u00e1m",
    "th\u00e1ng ch\u00edn",
    "th\u00e1ng m\u01b0\u1eddi",
    "th\u00e1ng m\u01b0\u1eddi m\u1ed9t",
    "th\u00e1ng m\u01b0\u1eddi hai",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "CN",
    "Th 2",
    "Th 3",
    "Th 4",
    "Th 5",
    "Th 6",
    "Th 7",
  };

  private static final String[] weekdays = {
    null,
    "Ch\u1ee7 nh\u1eadt",
    "Th\u1ee9 hai",
    "Th\u1ee9 ba",
    "Th\u1ee9 t\u01b0",
    "Th\u1ee9 n\u0103m",
    "Th\u1ee9 s\u00e1u",
    "Th\u1ee9 b\u1ea3y",
  };

  private static final String[] eras = {
    "tr. CN",
    "sau CN",
  };

  private static final String[] ampms = {
    "SA",
    "CH",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TJ", "T\u00e1t-gi-ki-xtan");
        put("TH", "Th\u00e1i Lan");
        put("TG", "T\u00f4-g\u00f4");
        put("GY", "Guy-a-na");
        put("TD", "S\u00e1t");
        put("GW", "Ghi-n\u00ea B\u00edt-xao");
        put("GT", "Goa-t\u00ea-ma-la");
        put("GR", "Hy L\u1ea1p");
        put("GQ", "Ghi-n\u00ea X\u00edch-\u0111\u1ea1o");
        put("SZ", "Xoa-di-len");
        put("SY", "Xi-ri");
        put("GN", "Ghi-n\u00ea");
        put("GM", "G\u0103m-bi-a");
        put("SV", "En-san-va-\u0111o");
        put("ST", "Xao T\u00f4-m\u00ea v\u00e0 Prin-xi-p\u00ea");
        put("GH", "Gha-na");
        put("SR", "Xu-ri-nam");
        put("SP", "S\u00e9c-bia");
        put("GE", "Gru-di-a");
        put("SO", "X\u00f4-ma-li");
        put("GD", "Gr\u00ea-na-\u0111a");
        put("SN", "X\u00ea-n\u00ea-gan");
        put("SM", "Xan Ma-ri-n\u00f4");
        put("GB", "V\u01b0\u01a1ng qu\u1ed1c Anh");
        put("SL", "Xi-\u00ea-ra L\u00ea-\u00f4n");
        put("GA", "Ga-b\u00f4ng");
        put("SK", "Xl\u00f4-va-ki-a");
        put("SI", "Xl\u00f4-ven-ni-a");
        put("SG", "Xin-ga-po");
        put("SE", "Th\u1ee5y \u0110i\u1ec3n");
        put("SD", "Xu-\u0111\u0103ng");
        put("SC", "X\u00e2y-sen");
        put("SB", "Qu\u1ea7n \u0111\u1ea3o X\u00f4-l\u00f4-m\u00f4ng");
        put("SA", "A-r\u1eadp X\u00ea-\u00fat");
        put("FR", "Ph\u00e1p");
        put("FM", "Mi-cr\u00f4-n\u00ea-xi-a");
        put("RW", "Ru-an-\u0111a");
        put("RU", "Nga");
        put("FJ", "Phi-gi");
        put("FI", "Ph\u1ea7n Lan");
        put("RO", "Ru-ma-ni");
        put("ET", "\u00ca-ti-\u00f4-pi-a");
        put("ES", "T\u00e2y Ban Nha");
        put("ER", "\u00ca-ri-t\u01a1-r\u00ea-a");
        put("EH", "T\u00e2y Sahara");
        put("EG", "Ai C\u1eadp");
        put("EE", "E-xt\u00f4-ni-a");
        put("EC", "\u00ca-cu-a-\u0111o");
        put("DZ", "An-gi\u00ea-ri");
        put("QA", "Ca-ta");
        put("PY", "Pa-ra-goay");
        put("DK", "\u0110an M\u1ea1ch");
        put("DJ", "Gi-bu-ti");
        put("PT", "B\u1ed3 \u0110\u00e0o Nha");
        put("DE", "\u0110\u1ee9c");
        put("PL", "Ba Lan");
        put("PK", "Pa-ki-xtan");
        put("PH", "Phi-lip-pin");
        put("PG", "Pa-pu-a Niu Ghi-n\u00ea");
        put("CZ", "C\u1ed9ng h\u00f2a S\u00e9c");
        put("PE", "P\u00ea-ru");
        put("CY", "S\u00edp");
        put("CV", "C\u00e1p-ve");
        put("PA", "Pa-na-ma");
        put("CU", "Cu Ba");
        put("CR", "C\u1ed1t-xta Ri-ca");
        put("CO", "C\u00f4-l\u00f4m-bi-a");
        put("CN", "Trung Qu\u1ed1c");
        put("CM", "Ca-m\u01a1-run");
        put("CL", "Chi-l\u00ea");
        put("CI", "B\u1edd Bi\u1ec3n Ng\u00e0");
        put("CH", "Th\u1ee5y S\u0129");
        put("CG", "C\u00f4ng-g\u00f4");
        put("CF", "C\u1ed9ng h\u00f2a Trung Phi");
        put("OM", "\u00d4-man");
        put("CA", "Ca-na-\u0111a");
        put("BZ", "B\u00ea-li-x\u00ea");
        put("BY", "B\u00ea-la-r\u00fat");
        put("BW", "B\u1ed1t-xoa-na");
        put("BS", "Ba-ha-ma");
        put("BR", "Bra-xin");
        put("NZ", "Niu Di-l\u00e2n");
        put("BO", "B\u00f4-li-vi-a");
        put("BN", "Bru-n\u00e2y");
        put("BJ", "B\u00ea-nanh");
        put("BI", "Bu-run-\u0111i");
        put("BH", "Ba-ren");
        put("BG", "Bun-ga-ri");
        put("BF", "Bu\u1ed1c-ki-na Pha-x\u00f4");
        put("NP", "N\u00ea-pan");
        put("BE", "B\u1ec9");
        put("NO", "Na Uy");
        put("BD", "B\u0103ng-la-\u0111\u00e9t");
        put("BB", "B\u00e1c-ba-\u0111\u1ed1t");
        put("ZW", "Dim-ba-bu-\u00ea");
        put("NL", "H\u00e0 Lan");
        put("BA", "B\u00f4-xni-a H\u00e9c-x\u00ea-g\u00f4-vi-na");
        put("NI", "Ni-ca-ra-goa");
        put("NG", "Ni-gi\u00ea-ri-a");
        put("AZ", "Ai-d\u00e9c-bai-gian");
        put("NE", "Ni-gi\u00ea");
        put("ZM", "D\u0103m-bi-a");
        put("AU", "\u00dac");
        put("NA", "Nam-mi-bi-a");
        put("AT", "\u00c1o");
        put("AR", "\u00c1c-hen-ti-na");
        put("MZ", "M\u00f4-d\u0103m-b\u00edch");
        put("AO", "\u0102ng-g\u00f4-la");
        put("MY", "Ma-lay-xi-a");
        put("MX", "M\u00ea-hi-c\u00f4");
        put("AM", "\u00c1c-m\u00ea-ni-a");
        put("MW", "Ma-la-uy");
        put("AL", "An-ba-ni");
        put("MV", "Man-\u0111i-v\u01a1");
        put("ZA", "Nam Phi");
        put("MU", "M\u00f4-ri-x\u01a1");
        put("MT", "Man-ta");
        put("MR", "M\u00f4-ri-ta-ni");
        put("AG", "An-ti-gu-a v\u00e0 Ba-bu-\u0111a");
        put("AF", "\u00c1p-ga-ni-xtan");
        put("AE", "C\u00e1c Ti\u1ec3u V\u01b0\u01a1ng qu\u1ed1c A-r\u1eadp Th\u1ed1ng nh\u1ea5t");
        put("MN", "M\u00f4ng C\u1ed5");
        put("MM", "Mi-an-ma");
        put("ML", "Ma-li");
        put("MK", "Ma-x\u00ea-\u0111\u00f4-ni-a");
        put("YU", "Nam T\u01b0");
        put("MH", "Qu\u1ea7n \u0111\u1ea3o M\u00e1c-san");
        put("MG", "Ma-\u0111a-g\u00e1t-xca");
        put("MD", "M\u00f4n-\u0111\u00f4-va");
        put("MC", "M\u00f4-na-c\u00f4");
        put("MA", "Ma-r\u1ed1c");
        put("YE", "Y-\u00ea-men");
        put("LY", "Li-bi");
        put("LV", "L\u00e1t-vi-a");
        put("LU", "L\u00fac-x\u0103m-bua");
        put("LT", "Li-tu-a-ni-a");
        put("LS", "L\u00ea-x\u00f4-th\u00f4");
        put("LR", "Li-b\u00ea-ri-a");
        put("LK", "Xri Lan-ca");
        put("LI", "Lich-ten-xt\u00ean");
        put("LC", "Xan Lu-xi");
        put("LB", "Li-b\u0103ng");
        put("LA", "L\u00e0o");
        put("KZ", "Ka-d\u1eafc-xtan");
        put("KW", "C\u00f4-o\u00e9t");
        put("KR", "H\u00e0n Qu\u1ed1c");
        put("KP", "B\u1eafc Tri\u1ec1u Ti\u00ean");
        put("KN", "Xan-k\u00edt v\u00e0 N\u00ea-vi");
        put("KM", "C\u00f4-m\u00f4");
        put("KI", "Ki-ri-ba-ti");
        put("WS", "Xa-moa");
        put("KH", "Campuchia");
        put("KG", "C\u01b0-r\u01a1-g\u01b0-xtan");
        put("KE", "K\u00ea-ni-a");
        put("JP", "Nh\u1eadt B\u1ea3n");
        put("JO", "Gi\u00f3c-\u0111a-ni");
        put("JM", "Ha-mai-ca");
        put("VU", "Va-nu-a-tu");
        put("VN", "Vi\u1ec7t Nam");
        put("VE", "V\u00ea-n\u00ea-zu-\u00ea-la");
        put("VC", "Xan Vin-xen v\u00e0 Gr\u00ea-na-din");
        put("VA", "Va-ti-c\u0103ng");
        put("IT", "\u00dd");
        put("IS", "Ai-x\u01a1-len");
        put("IR", "I-ran");
        put("IQ", "I-r\u1eafc");
        put("UZ", "U-d\u01a1-b\u00ea-ki-xtan");
        put("UY", "U-ru-goay");
        put("IN", "\u1ea4n \u0110\u1ed9");
        put("IL", "I-xra-en");
        put("US", "Hoa K\u1ef3");
        put("IE", "Ai-len");
        put("ID", "Nam D\u01b0\u01a1ng");
        put("UG", "U-gan-\u0111a");
        put("UA", "U-crai-na");
        put("HU", "Hung-ga-ri");
        put("HT", "Ha-i-ti");
        put("HR", "Cr\u00f4-a-ti-a");
        put("TZ", "Tan-da-ni-a");
        put("HN", "H\u00f4n-\u0111u-r\u00e1t");
        put("TW", "\u0110\u00e0i Loan");
        put("TV", "Tu-va-lu");
        put("TT", "Tri-ni-\u0111\u00e1t v\u00e0 T\u00f4-ba-g\u00f4");
        put("TR", "Th\u1ed5 Nh\u0129 K\u1ef3");
        put("TO", "T\u00f4ng-ga");
        put("TN", "Tuy-ni-di");
        put("TM", "Tu\u1ed1c-m\u00ea-ni-xtan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "currencyFormat", "#,##0.00 \u00a4;-#,##0.00 \u00a4" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "dd/MM/yyyy" },
    { "mediumDateFormat", "dd-MM-yyyy" },
    { "longDateFormat", "'Ng\u00e0y' dd 'th\u00e1ng' M 'n\u0103m' yyyy" },
    { "fullDateFormat", "EEEE, 'ng\u00e0y' dd MMMM 'n\u0103m' yyyy" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
