/* LocaleInformation_cs.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_cs extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6MKD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GNF\u00A6UYP\u00A6OMR\u00A6XFU\u00A6ZRZ\u00A6BTR\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6XBC\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP";

  private static final String currenciesDisplayNameValues = "Din\u00e1r jord\u00e1nsk\u00fd\u00A6Mvdol\u00A6Zlato\u00A6Koruna Faersk\u00fdch ostrov\u016f\u00A6Libra libanonsk\u00e1\u00A6Euro\u00A6\u0160ilink tanzansk\u00fd\u00A6Peso\u00A6Riel\u00A6Asijsk\u00e1 pen\u011b\u017en\u00ed jednotka\u00A6Boliviano (1863-1962)\u00A6Riel star\u00fd\u00A6Libra zambijsk\u00e1\u00A6Libra australsk\u00e1\u00A6Frank BEAC/CFA\u00A6Libra maltsk\u00e1\u00A6Ghana Revalued Cedi\u00A6Kwacha\u00A6Libra ghansk\u00e1\u00A6Boliviano\u00A6Ghana Old Cedi\u00A6Lira maltsk\u00e1\u00A6Dolar australsk\u00fd\u00A6Dolar americk\u00fd (t\u00fd\u017e den)\u00A6Lira italsk\u00e1\u00A6Dolar americk\u00fd (p\u0159\u00ed\u0161t\u00ed den)\u00A6Cedi\u00A6Dolar singapursk\u00fd\u00A6Balboa\u00A6Kip\u00A6Som\u00A6Frank \u0161v\u00fdcarsk\u00fd\u00A6\u0160ilink\u00A6Dolar americk\u00fd\u00A6Dolar etiopsk\u00fd\u00A6Dolar brunejsk\u00fd\u00A6Libra jamajsk\u00e1\u00A6Birr etiopsk\u00fd\u00A6Frank al\u017e\u00edrsk\u00fd germinal\u00A6Frank nov\u00fd al\u017e\u00edrsk\u00fd\u00A6Din\u00e1r al\u017e\u00edrsk\u00fd\u00A6Guarani\u00A6Libra lybijsk\u00e1\u00A6Dolar jamajsk\u00fd\u00A6Koruna islandsk\u00e1\u00A6Peseta \u0161pan\u011blsk\u00e1\u00A6Libra bermudsk\u00e1\u00A6Din\u00e1r lybijsk\u00fd\u00A6Dolar bermudsk\u00fd\u00A6Zlat\u00fd holandsk\u00fd\u00A6Ouguiya\u00A6Rij\u00e1l \u00edr\u00e1nsk\u00fd\u00A6Koruna \u0161v\u00e9dsk\u00e1\u00A6Nakfa\u00A6\u0160ilink ke\u0148sk\u00fd\u00A6Frank St\u0159edoafrick\u00e9 republiky CFA\u00A6Peso argentinsk\u00e9\u00A6Peso argentinsk\u00e9 (1983-1985)\u00A6Peso argentinsk\u00e9 Moneda Nacional\u00A6Dolar tchajvansk\u00fd nov\u00fd\u00A6Libra s\u00fad\u00e1nsk\u00e1\u00A6Lari\u00A6Georgian Kupon Larit\u00A6Frank martiniksk\u00fd\u00A6Libra falklandsk\u00e1\u00A6Austral\u00A6Din\u00e1r s\u00fad\u00e1nsk\u00fd\u00A6Din\u00e1r ir\u00e1ck\u00fd\u00A6Dolar tuvalsk\u00fd\u00A6Rupie seychelsk\u00e1\u00A6Rubl loty\u0161sk\u00fd\u00A6Libra fid\u017eijsk\u00e1\u00A6Lat loty\u0161sk\u00fd\u00A6Zaire kon\u017esk\u00fd\u00A6Frank Kon\u017esk\u00e9 republiky\u00A6Frank kon\u017esk\u00fd\u00A6Dolar fid\u017eijsk\u00fd\u00A6Cordoba oro\u00A6Pataca\u00A6Cordoba zlat\u00e1\u00A6Cordoba\u00A6Markka (1860-1962)\u00A6Markka\u00A6Dolar \u0160alamounov\u00fdch ostrov\u016f\u00A6Frank lucembursk\u00fd\u00A6Dolar star\u00fd Trinidad a Tobago\u00A6Escudo angolsk\u00e9\u00A6Kwanza reajustado (1995-1999)\u00A6Tugrik\u00A6Forint\u00A6Frank burundsk\u00fd\u00A6Kwanza nov\u00e1 (1990-2000)\u00A6Kwanza (1977-1990)\u00A6Dolar Trinidad a Tobago\u00A6Lilangeni\u00A6Frank Nov\u00fdch Hebrid CFP\u00A6Libra \u0161terlink\u016f\u00A6Rij\u00e1l saudsk\u00fd sovereign\u00A6Rij\u00e1l saudsk\u00fd\u00A6Talon\u00A6Rupie indick\u00e1\u00A6Escudo portugalsk\u00e9\u00A6Kwanza\u00A6Conto portugalsk\u00e9\u00A6Litus litevsk\u00fd\u00A6Tenge\u00A6Rubl kaza\u0161sk\u00fd\u00A6Dolar Britsk\u00fdch Panensk\u00fdch ostrov\u016f\u00A6Libra nigerijsk\u00e1\u00A6Naira\u00A6Gourde\u00A6Libra syrsk\u00e1\u00A6Libra palestinsk\u00e1\u00A6Din\u00e1r bahrajnsk\u00fd\u00A6Kyat\u00A6Zlat\u00fd Nizozemsk\u00fdch Antil\u00A6Koruna \u010desk\u00e1\u00A6Libra \u0161terlink\u016f Ostrov Man\u00A6Loti\u00A6Frank gabonsk\u00fd CFA\u00A6Lev Bulharsk\u00fd (1879-1952)\u00A6Lev Bulharsk\u00fd\u00A6Lev Bulharsk\u00fd socialistick\u00fd\u00A6Dolar kanadsk\u00fd\u00A6Lev\u00A6Lira tureck\u00e1\u00A6Dolar Kajmansk\u00fdch ostrov\u016f\u00A6Libra kypersk\u00e1\u00A6\u0160ekel nov\u00fd izraelsk\u00fd\u00A6Dolar guyansk\u00fd\u00A6Dram arm\u00e9nsk\u00fd\u00A6Libra izraelsk\u00e1\u00A6Frank malijsk\u00fd\u00A6\u0160ekel izraelsk\u00fd\u00A6Bolivar\u00A6Dolar liberijsk\u00fd\u00A6Albanian Lek Valute\u00A6Kuna chorvatsk\u00e1\u00A6Frank Reunion\u00A6Dinar chorvatsk\u00fd\u00A6Lek\u00A6Libra \u0161terlink\u016f Jersey\u00A6Lek (1946-1961)\u00A6Den\u00e1r (1992-1993)\u00A6Den\u00e1r\u00A6Pataca timorsk\u00e1\u00A6Frank CFP\u00A6Frank finan\u010dn\u00ed\u00A6Peso Guinnea-Bissau\u00A6Din\u00e1r kuvajtsk\u00fd\u00A6Portuguese Guinea Mil Reis\u00A6Frank belgick\u00fd\u00A6Escudo timorsk\u00e9\u00A6Frank konvertibiln\u00ed\u00A6Escudo guinejsk\u00e9\u00A6Colon salvadorsk\u00fd\u00A6Zlat\u00fd Curacao\u00A6Taka\u00A6Libra \u0161terlink\u016f ton\u017esk\u00e1\u00A6Frank BCEAO/CFA\u00A6Rubl\u00A6Rubl nov\u00fd\u00A6Frank Nov\u00e9 Kaledonie germinal\u00A6Escudo kapverdsk\u00e9\u00A6Frank Francouzsk\u00fdch Antil CFA\u00A6Rand\u00A6Peso dominik\u00e1nsk\u00e9\u00A6Libra jihoafrick\u00e1\u00A6Rand finan\u010dn\u00ed\u00A6Din\u00e1r tunisk\u00fd\u00A6Peso kub\u00e1nsk\u00e9\u00A6French Guyana Franc Guiana\u00A6\u0160ilink ugandsk\u00fd\u00A6Rupie cejlonsk\u00e1\u00A6Affars and Issas Franc\u00A6Lira Vatik\u00e1nu\u00A6Escudo Svat\u00e9ho Tom\u00e1\u0161e\u00A6\u0160ilink ugandsk\u00fd (1966-1987)\u00A6Dobra\u00A6Dolar Marshallov\u00fdch ostrov\u016f\u00A6Libra novoz\u00e9landsk\u00e1\u00A6Tala\u00A6Libra Z\u00e1padn\u00ed Samoa\u00A6Lempira\u00A6Manat\u00A6Quetzal\u00A6Dolar novoz\u00e9landsk\u00fd\u00A6Libra skotsk\u00e1\u00A6Dolar barbadosk\u00fd\u00A6Dolar namibijsk\u00fd\u00A6Frank madagaskarsk\u00fd\u00A6Ariary madagaskarsk\u00fd\u00A6Libra egyptsk\u00e1\u00A6Dolar Britsk\u00e9ho Hondurasu\u00A6Zlot\u00fd (1950-1995)\u00A6Nov\u00fd Din\u00e1r Bosny a Hercegoviny\u00A6Marka konvertibiln\u00ed\u00A6Dolar belizsk\u00fd\u00A6Din\u00e1r Bosny a Hercegoviny\u00A6Zlot\u00fd\u00A6Rij\u00e1l jemensk\u00fd\u00A6Zlat\u00fd surinamsk\u00fd\u00A6Koruna \u010deskoslovensk\u00e1\u00A6Won jihokorejsk\u00fd\u00A6Rubl b\u011blorusk\u00fd\u00A6Rij\u00e1l jemensk\u00fd imadi\u00A6Rubl b\u011blorusk\u00fd (1992-1994)\u00A6Koruna \u010deskoslovensk\u00e1\u00A6Won star\u00fd jihokorejsk\u00fd\u00A6Hwan jihokorejsk\u00fd\u00A6Rubl nov\u00fd b\u011blorusk\u00fd (1994-1999)\u00A6Somaliland Shilling\u00A6Drachma nov\u00e1 \u0159eck\u00e1\u00A6Rupie p\u00e1kist\u00e1nsk\u00e1\u00A6Afgh\u00e1n\u00A6Dolar zimbabwsk\u00fd\u00A6Rupie sr\u00edlansk\u00e1\u00A6Drachma\u00A6Libra irsk\u00e1\u00A6Afgh\u00e1n (1927-2002)\u00A6Din\u00e1r jemensk\u00fd\u00A6Frank rwandsk\u00fd\u00A6Col\u00f3n kostarick\u00fd\u00A6Somoni\u00A6Tajikistan Ruble\u00A6Kroon\u00A6Equatorial Guinea Peseta Guineana\u00A6Moldovan Ruble Cupon\u00A6Dolar hongkongsk\u00fd\u00A6Koruna d\u00e1nsk\u00e1\u00A6Leu moldavsk\u00fd\u00A6Equatorial Guinea Franco\u00A6Equatorial Guinea Ekwele Guineana\u00A6Rupie indon\u00e9zsk\u00e1\u00A6Dirham SAE\u00A6Won severokorejsk\u00fd\u00A6Indonesian New Rupiah\u00A6Pula\u00A6Moldovan Leu Cupon\u00A6Indonesian Java Rupiah\u00A6Indonesian Nica Guilder\u00A6Vatu\u00A6Din\u00e1r isl\u00e1msk\u00fd\u00A6\u0160ilink som\u00e1lsk\u00fd\u00A6Peseta andorrsk\u00e1\u00A6Rubl rusk\u00fd (1991-1998)\u00A6Frank guadeloupsk\u00fd\u00A6Frank d\u017eibutsk\u00fd\u00A6Diner andorrsk\u00fd\u00A6Frank monack\u00fd germinal\u00A6Frank nouveau monack\u00fd\u00A6Ecuador Unidad de Valor Constante (UVC)\u00A6Sucre ekv\u00e1dorsk\u00fd\u00A6Frank lichten\u0161tejnsk\u00fd\u00A6Rubl rusk\u00fd\u00A6Peso filip\u00ednsk\u00e9\u00A6Sum uzbeck\u00fd\u00A6Peso kolumbijsk\u00e9\u00A6Baht\u00A6Libra severoirsk\u00e1\u00A6Rupie barmsk\u00e1\u00A6Krank kon\u017esk\u00fd CFA\u00A6Kyat barmsk\u00fd\u00A6Peso kolumbijsk\u00e9\u00A6Uzbekistan Coupon Som\u00A6Karbovanec\u00A6Rij\u00e1l katarsk\u00fd\u00A6H\u0159ivna\u00A6Guinea Syli\u00A6Juan renminbi\u00A6Metical\u00A6Dolar lidov\u00e9 banky\u00A6Peso uruguaysk\u00e9\u00A6Frank guinejsk\u00fd (1960-1972)\u00A6Lira San Marino\u00A6Escudo Mosambiku\u00A6Juan jen min piao\u00A6Kina\u00A6Rij\u00e1l om\u00e1nsk\u00fd saidi\u00A6Frank guinejsk\u00fd\u00A6Peso uruguaysk\u00e9 (1975-1993)\u00A6Rij\u00e1l om\u00e1nsk\u00fd\u00A6Frank UIC\u00A6Zaire\u00A6Rupie bh\u00fat\u00e1nsk\u00e1\u00A6Frank marock\u00fd\u00A6Dirham marock\u00fd\u00A6Ngultrum\u00A6Frank zlat\u00fd\u00A6Peso uruguaysk\u00e9 fuerte\u00A6Ringgit malajskijsk\u00fd\u00A6Zaire nov\u00fd\u00A6Manat \u00e1zerbajd\u017e\u00e1nsk\u00fd\u00A6Libra gambijsk\u00e1\u00A6Frank komorsk\u00fd\u00A6Dalasi\u00A6Evropsk\u00e1 m\u011bnov\u00e1 jednotka\u00A6Libra bahamsk\u00e1\u00A6Frank kamerunsk\u00fd CFA\u00A6Mexican Unidad de Inversion (UDI)\u00A6Frank BCEAEC/CFA\u00A6Dolar bahamsk\u00fd\u00A6Peso st\u0159\u00edbrn\u00e9 mexick\u00e9 (1861-1992)\u00A6Peso mexick\u00e9\u00A6Sol\u00A6Greenland Krone\u00A6Cruzeiro (1942-1967)\u00A6Nuevo sol\u00A6Peso chilsk\u00e9\u00A6Koruna slovensk\u00e1\u00A6Inti\u00A6Cruzeiro real\u00A6SDR\u00A6Frank francouzsk\u00fd germinal/Frank poincare\u00A6Frank francouzsk\u00fd\u00A6Cruzado nov\u00e9\u00A6Unidades de fomento\u00A6Escudo chilsk\u00e9\u00A6Real brazilsk\u00fd\u00A6Condor chilsk\u00fd\u00A6Cruzeiro (1990-1993)\u00A6Sperrmark n\u011bmeck\u00e1\u00A6Libra malawijsk\u00e1\u00A6Cruzado\u00A6Cruzeiro (1967-1986)\u00A6Kwacha\u00A6Transdniestria Ruble\u00A6Marka n\u011bmeck\u00e1\u00A6Frank \u010dadsk\u00fd CFA\u00A6Transdniestria New Ruble\u00A6Transdniestria Ruble Kupon\u00A6Rupie nep\u00e1lsk\u00e1\u00A6Dolar Cookov\u00fdch ostrov\u016f\u00A6Jen\u00A6Rufiyaa\u00A6Frank Nouveau CFA\u00A6Rupie maledivsk\u00e1\u00A6Dolar v\u00fdchodokaribsk\u00fd\u00A6Tolar\u00A6Din\u00e1r jugosl\u00e1vsk\u00fd reformovan\u00fd\u00A6Zlat\u00fd arubsk\u00fd\u00A6Marka NDR\u00A6Din\u00e1r jugosl\u00e1vsk\u00fd\u00A6Din\u00e1r jugosl\u00e1vsk\u00fd\u00A6Koruna Turks a Caicos\u00A6Din\u00e1r jugosl\u00e1vsk\u00fd 1994\u00A6Din\u00e1r jugosl\u00e1vsk\u00fd federativn\u00ed\u00A6Lei nov\u00fd\u00A6Din\u00e1r jugosl\u00e1vsk\u00fd nov\u00fd\u00A6Lei\u00A6Slovenia Tolar Bons\u00A6Koruna norsk\u00e1\u00A6Rupie mauricijsk\u00e1\u00A6Evropsk\u00e1 jednotka \u00fa\u010dtu 17 (XBD)\u00A6Libra gibraltarsk\u00e1\u00A6Evropsk\u00e1 jednotka \u00fa\u010dtu 9 (XBC)\u00A6Evropsk\u00e1 pen\u011b\u017en\u00ed jednotka\u00A6Evropsk\u00e1 sm\u00ed\u0161en\u00e1 jednotka\u00A6Dolar kiribatsk\u00fd\u00A6Libra Svat\u00e9 Heleny";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6MKD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GNF\u00A6UYP\u00A6OMR\u00A6XFU\u00A6ZRZ\u00A6BTR\u00A6MAF\u00A6MAD\u00A6XFO\u00A6BTN\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6XBC\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP";

  private static final String currenciesSymbolValues = "JD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LL\u00A6T Sh\u00A6BOP\u00A6CR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6Bs\u00A6GHO\u00A6Lm\u00A6$A\u00A6USS\u00A6USN\u00A6GHC\u00A6S$\u00A6PAB\u00A6LAK\u00A6som\u00A6SwF\u00A6ATS\u00A6US$\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6Ber$\u00A6NLG\u00A6UM\u00A6RI\u00A6SKr\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6Ft\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SRl\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6K\u010d\u00A6IMP\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6Can$\u00A6lev\u00A6TL\u00A6KYD\u00A6\u00a3\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6MDen\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6XNF\u00A6R\u00A6RD$\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Af\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6AFA\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HK$\u00A6DKr\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6Y\u00A6Mt\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GF\u00A6UYP\u00A6RO\u00A6XFU\u00A6ZRZ\u00A6BTR\u00A6MAF\u00A6MAD\u00A6XFO\u00A6Nu\u00A6UYF\u00A6RM\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6CF\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6Ch$\u00A6Sk\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6leu\u00A6SIB\u00A6NKr\u00A6MUR\u00A6XBD\u00A6GIP\u00A6XBC\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "1.",
    "2.",
    "3.",
    "4.",
    "5.",
    "6.",
    "7.",
    "8.",
    "9.",
    "10.",
    "11.",
    "12.",
    null,
  };

  private static final String[] months = {
    "Leden",
    "\u00danor",
    "B\u0159ezen",
    "Duben",
    "Kv\u011bten",
    "\u010cerven",
    "\u010cervenec",
    "Srpen",
    "Z\u00e1\u0159\u00ed",
    "\u0158\u00edjen",
    "Listopad",
    "Prosinec",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "ne",
    "po",
    "\u00fat",
    "st",
    "\u010dt",
    "p\u00e1",
    "so",
  };

  private static final String[] weekdays = {
    null,
    "ned\u011ble",
    "pond\u011bl\u00ed",
    "\u00fater\u00fd",
    "st\u0159eda",
    "\u010dtvrtek",
    "p\u00e1tek",
    "sobota",
  };

  private static final String[] eras = {
    "p\u0159.Kr.",
    "po Kr.",
  };

  private static final String[] ampms = {
    "dop.",
    "odp.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "V\u00fdchodn\u00ed standardn\u00ed \u010das", "EST", "V\u00fdchodn\u00ed standardn\u00ed \u010das"},
    {  "America/Halifax", "AST", "Atlantick\u00fd standardn\u00ed \u010das", "ADT", "Atlantick\u00fd letn\u00ed \u010das"},
    {  "Pacific/Honolulu", "HST", "Havajsk\u00fd standardn\u00ed \u010das", "HST", "Havajsk\u00fd standardn\u00ed \u010das"},
    {  "America/Denver", "MST", "Horsk\u00fd standardn\u00ed \u010das", "MDT", "Horsk\u00fd letn\u00ed \u010das"},
    {  "America/Anchorage", "AST", "Alja\u0161sk\u00fd standardn\u00ed \u010das", "ADT", "Alja\u0161sk\u00fd letn\u00ed \u010das"},
    {  "America/St_Johns", "CNT", "Newfoundlandsk\u00fd standardn\u00ed \u010das", "CDT", "Newfoundlandsk\u00fd letn\u00ed \u010das"},
    {  "Africa/Casablanca", "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das", "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das"},
    {  "America/Chicago", "CST", "Centr\u00e1ln\u00ed standardn\u00ed \u010das", "CDT", "Centr\u00e1ln\u00ed letn\u00ed \u010das"},
    {  "Asia/Shanghai", "CTT", "\u010c\u00ednsk\u00fd standardn\u00ed \u010das", "CDT", "\u010c\u00ednsk\u00fd standardn\u00ed \u010das"},
    {  "Asia/Tokyo", "JST", "Japonsk\u00fd standardn\u00ed \u010das", "JST", "Japonsk\u00fd standardn\u00ed \u010das"},
    {  "America/New_York", "EST", "V\u00fdchodn\u00ed standardn\u00ed \u010das", "EDT", "V\u00fdchodn\u00ed letn\u00ed \u010das"},
    {  "Europe/Bucharest", "EET", "V\u00fdchodoevropsk\u00fd standardn\u00ed \u010das", "EEST", "V\u00fdchodoevropsk\u00fd letn\u00ed \u010das"},
    {  "America/Los_Angeles", "PST", "Pacifick\u00fd standardn\u00ed \u010das", "PDT", "Pacifick\u00fd letn\u00ed \u010das"},
    {  "America/Phoenix", "MST", "Horsk\u00fd standardn\u00ed \u010das", "MST", "Horsk\u00fd standardn\u00ed \u010das"},
    {  "Etc/GMT", "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das", "GMT", "Greenwichsk\u00fd st\u0159edn\u00ed \u010das"},
    {  "Asia/Jerusalem", "IST", "Izraelsk\u00fd standardn\u00ed \u010das", "IDT", "Izraelsk\u00fd letn\u00ed \u010das"},
    {  "Europe/Paris", "CET", "St\u0159edoevropsk\u00fd standardn\u00ed \u010das", "CEST", "St\u0159edoevropsk\u00fd letn\u00ed \u010das"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "V\u00fdchodn\u00ed Timor\u00A6Tokelau\u00A6T\u00e1d\u017eikist\u00e1n\u00A6Thajsko\u00A6Togo\u00A6Francouzsk\u00e1 ji\u017en\u00ed teritoria\u00A6Guyana\u00A6\u010cad\u00A6Ostrovy Caicos a Turks\u00A6Guinea-Bissau\u00A6Guam\u00A6Guatemala\u00A6Ji\u017en\u00ed Georgie a Ji\u017en\u00ed Sandwichovy ostrovy\u00A6\u0158ecko\u00A6Rovn\u00edkov\u00e1 Guinea\u00A6Guadeloupe\u00A6Svazijsko\u00A6S\u00fdrie\u00A6Guinea\u00A6Gambie\u00A6Gr\u00f3nsko\u00A6El Salvador\u00A6Svat\u00fd Tom\u00e1\u0161\u00A6Gibraltar\u00A6Ghana\u00A6Surinam\u00A6Francouzsk\u00e1 Guyana\u00A6Gruzie\u00A6Som\u00e1lsko\u00A6Grenada\u00A6Senegal\u00A6San Marino\u00A6Velk\u00e1 Brit\u00e1nie\u00A6Sierra Leone\u00A6Gabon\u00A6Slovensko\u00A6Svalbard a Jan Mayen\u00A6Slovinsko\u00A6Svat\u00e1 Helena\u00A6Singapur\u00A6\u0160v\u00e9dsko\u00A6S\u00fad\u00e1n\u00A6Seychely\u00A6\u0160alamounovy ostrovy\u00A6Sa\u00fadsk\u00e1 Ar\u00e1bie\u00A6Francie\u00A6Faersk\u00e9 ostrovy\u00A6Mikron\u00e9sie, federativn\u00ed st\u00e1t\u00A6Rwanda\u00A6Falklandsk\u00e9 ostrovy\u00A6Rusko\u00A6Fid\u017ei\u00A6Finsko\u00A6Rumunsko\u00A6R\u00e9union\u00A6Etiopie\u00A6\u0160pan\u011blsko\u00A6Eritrea\u00A6Z\u00e1padn\u00ed Sahara\u00A6Egypt\u00A6Estonsko\u00A6Ekv\u00e1dor\u00A6Al\u017e\u00edrsko\u00A6Katar\u00A6Dominik\u00e1nsk\u00e1 republika\u00A6Paraguay\u00A6Dominika\u00A6Palau\u00A6D\u00e1nsko\u00A6D\u017eibuti\u00A6Portugalsko\u00A6Palestinian Territory\u00A6Portoriko\u00A6N\u011bmecko\u00A6Pitcairn\u00A6Svat\u00fd Pierre a Miquelon\u00A6Polsko\u00A6P\u00e1kist\u00e1n\u00A6Filip\u00edny\u00A6Papua-Nov\u00e1 Guinea\u00A6Francouzsk\u00e1 Polyn\u00e9sie\u00A6\u010cesk\u00e1 republika\u00A6Peru\u00A6Kypr\u00A6V\u00e1no\u010dn\u00ed ostrovy\u00A6Kapverdy\u00A6Panama\u00A6Kuba\u00A6Kostarika\u00A6Kolumbie\u00A6\u010c\u00edna\u00A6Kamerun\u00A6Chile\u00A6Cookovy ostrovy\u00A6Pob\u0159e\u017e\u00ed slonoviny\u00A6\u0160v\u00fdcarsko\u00A6Kongo\u00A6St\u0159edoafrick\u00e1 republika\u00A6Kongo, demokratick\u00e1 republika\u00A6Kokosov\u00e9 ostrovy\u00A6Om\u00e1n\u00A6Kanada\u00A6Belize\u00A6B\u011blorusko\u00A6Botswana\u00A6Ostrov Bouvet\u00A6Bh\u00fat\u00e1n\u00A6Bahamy\u00A6Braz\u00edlie\u00A6Nov\u00fd Z\u00e9land\u00A6Bol\u00edvie\u00A6Brunej Darussalam\u00A6Bermudy\u00A6Niue\u00A6Benin\u00A6Burundi\u00A6Bahrajn\u00A6Nauru\u00A6Bulharsko\u00A6Burkina Faso\u00A6Nep\u00e1l\u00A6Belgie\u00A6Norsko\u00A6Banglad\u00e9\u0161\u00A6Barbados\u00A6Zimbabwe\u00A6Nizozemsko\u00A6Bosna a Hercegovina\u00A6Nikaragua\u00A6Nig\u00e9rie\u00A6Norfolk\u00A6\u00c1zerb\u00e1jd\u017e\u00e1n\u00A6Niger\u00A6Nov\u00e1 Kaledonie\u00A6Aruba\u00A6Zambie\u00A6Namibie\u00A6Austr\u00e1lie\u00A6Rakousko\u00A6Americk\u00e1 Samoa\u00A6Argentina\u00A6Antarktida\u00A6Mosambik\u00A6Angola\u00A6Malajsie\u00A6Nizozemsk\u00e9 Antily\u00A6Mexiko\u00A6Arm\u00e9nie\u00A6Malawi\u00A6Alb\u00e1nie\u00A6Maladivy\u00A6Ji\u017en\u00ed Afrika\u00A6Mauricius\u00A6Malta\u00A6Anguila\u00A6Montserrat\u00A6Maurit\u00e1nie\u00A6Antigua a Barbuda\u00A6Martinik\u00A6Afgh\u00e1nist\u00e1n\u00A6Severn\u00ed Mariany\u00A6Spojen\u00e9 arabsk\u00e9 emir\u00e1ty\u00A6Macao S.A.R., China\u00A6Andorra\u00A6Mongolsko\u00A6Myanmar (Burma)\u00A6Mali\u00A6Macedonia\u00A6Jugosl\u00e1vie\u00A6Mayotte\u00A6Marshallovy ostrovy\u00A6Madagaskar\u00A6Moldavsko, republika\u00A6Monako\u00A6Maroko\u00A6Jemen\u00A6Libye\u00A6Loty\u0161sko\u00A6Lucembursko\u00A6Litva\u00A6Lesotho\u00A6Lib\u00e9rie\u00A6Sr\u00ed Lanka\u00A6Lichten\u0161tejnsko\u00A6Svat\u00e1 Lucie\u00A6Libanon\u00A6Lidov\u011b demokratick\u00e1 republika Laos\u00A6Kazachst\u00e1n\u00A6Kajmansk\u00e9 ostrovy\u00A6Kuvajt\u00A6Ji\u017en\u00ed Korea\u00A6Severn\u00ed Korea\u00A6Svat\u00fd Kitts a Nevis\u00A6Komory\u00A6Kiribati\u00A6Samoa\u00A6Kambod\u017ea\u00A6Kyrgyzst\u00e1n\u00A6Ke\u0148a\u00A6Wallis a Futuna\u00A6Japonsko\u00A6Jord\u00e1nsko\u00A6Jamajka\u00A6Vanuatu\u00A6Vietnam\u00A6Americk\u00e9 Panensk\u00e9 ostrovy\u00A6Britsk\u00e9 Panensk\u00e9 ostrovy\u00A6Venezuela\u00A6Svat\u00fd Vincent a Grenadiny\u00A6Svat\u00fd stolec\u00A6It\u00e1lie\u00A6Island\u00A6\u00cdr\u00e1n\u00A6Ir\u00e1k\u00A6Uzbekist\u00e1n\u00A6Britsk\u00e9 \u00fazem\u00ed v Indick\u00e9m oce\u00e1nu\u00A6Uruguay\u00A6Indie\u00A6Izrael\u00A6Spojen\u00e9 st\u00e1ty\u00A6Irsko\u00A6Indon\u00e9sie\u00A6Men\u0161\u00ed odlehl\u00e9 ostrovy USA\u00A6Uganda\u00A6Ukrajina\u00A6Ma\u010farsko\u00A6Haiti\u00A6Chorvatsko\u00A6Tanzanie\u00A6Honduras\u00A6Ostrovy Heard a McDonald\u00A6Tchaj-wan\u00A6Tuvalu\u00A6Hongkong, zvl\u00e1\u0161tn\u00ed administrativn\u00ed oblast \u010c\u00edny\u00A6Trinidad a Tobago\u00A6Turecko\u00A6Tonga\u00A6Tunisko\u00A6Turkmenist\u00e1n";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "es\u00A6ku\u00A6eo\u00A6ks\u00A6en\u00A6el\u00A6qu\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6wo\u00A6ka\u00A6dz\u00A6jv\u00A6pt\u00A6ps\u00A6de\u00A6pl\u00A6da\u00A6vo\u00A6ja\u00A6vi\u00A6cy\u00A6pa\u00A6cs\u00A6iu\u00A6it\u00A6co\u00A6is\u00A6uz\u00A6or\u00A6ik\u00A6ur\u00A6om\u00A6ca\u00A6ie\u00A6id\u00A6uk\u00A6ia\u00A6oc\u00A6ug\u00A6hy\u00A6br\u00A6hu\u00A6bo\u00A6bn\u00A6hr\u00A6bi\u00A6tw\u00A6bh\u00A6bg\u00A6tt\u00A6no\u00A6be\u00A6ts\u00A6hi\u00A6tr\u00A6nl\u00A6zu\u00A6ba\u00A6to\u00A6he\u00A6tn\u00A6tl\u00A6tk\u00A6ha\u00A6ne\u00A6az\u00A6ti\u00A6ay\u00A6th\u00A6tg\u00A6na\u00A6te\u00A6zh\u00A6as\u00A6ar\u00A6ta\u00A6gu\u00A6my\u00A6am\u00A6za\u00A6mt\u00A6ms\u00A6gn\u00A6sw\u00A6mr\u00A6sv\u00A6gl\u00A6su\u00A6af\u00A6st\u00A6mo\u00A6ss\u00A6mn\u00A6sr\u00A6sq\u00A6ml\u00A6ab\u00A6mk\u00A6aa\u00A6so\u00A6sn\u00A6mi\u00A6gd\u00A6sm\u00A6sl\u00A6mg\u00A6sk\u00A6ga\u00A6yo\u00A6si\u00A6sh\u00A6sg\u00A6yi\u00A6sd\u00A6fy\u00A6sa\u00A6fr\u00A6lv\u00A6lt\u00A6fo\u00A6rw\u00A6ru\u00A6lo\u00A6fj\u00A6ln\u00A6fi\u00A6ro\u00A6rn\u00A6rm\u00A6fa\u00A6la\u00A6xh\u00A6eu\u00A6ky\u00A6et";

  private static final String languagesValues = "\u0160pan\u011bl\u0161tina\u00A6Kurd\u0161tina\u00A6Esperanto\u00A6Ka\u0161m\u00edr\u0161tina\u00A6Angli\u010dtina\u00A6\u0158e\u010dtina\u00A6Ke\u010du\u00e1n\u0161tina\u00A6Korej\u0161tina\u00A6Kannad\u0161tina\u00A6Kambod\u017e\u0161tina\u00A6Gr\u00f3n\u0161tina\u00A6Kazach\u0161tina\u00A6Wolof\u00A6Gruz\u00edn\u0161tina\u00A6Bh\u00fat\u00e1n\u0161tina\u00A6Jav\u00e1n\u0161tina\u00A6Portugal\u0161tina\u00A6Pashto (Pushto)\u00A6N\u011bm\u010dina\u00A6Pol\u0161tina\u00A6D\u00e1n\u0161tina\u00A6Volapuk\u00A6Japon\u0161tina\u00A6Vietnam\u0161tina\u00A6Vel\u0161tina\u00A6Pa\u0148d\u017e\u00e1b\u0161tina\u00A6\u010ce\u0161tina\u00A6Inuktitut\u0161tina\u00A6Ital\u0161tina\u00A6Korsi\u010dtina\u00A6Island\u0161tina\u00A6Uzbe\u010dtina\u00A6Oriya\u00A6Inupiak\u0161tina\u00A6Urd\u0161tina\u00A6Oromo (Afan)\u00A6Katal\u00e1n\u0161tina\u00A6Interlingue\u00A6Indon\u00e9\u0161tina\u00A6Ukrajin\u0161tina\u00A6Interlingua\u00A6Occitan\u00A6Uighur\u0161tina\u00A6Arm\u00e9n\u0161tina\u00A6Breta\u0148\u0161tina\u00A6Ma\u010far\u0161tina\u00A6Tibet\u0161tina\u00A6Beng\u00e1l\u0161tina\u00A6Chorvat\u0161tina\u00A6Bisl\u00e1m\u0161tina\u00A6Twi\u00A6Bihar\u0161tina\u00A6Bulhar\u0161tina\u00A6Tatar\u0161tina\u00A6Nor\u0161tina\u00A6B\u011bloru\u0161tina\u00A6Tsonga\u00A6Hind\u0161tina\u00A6Ture\u010dtina\u00A6Holand\u0161tina\u00A6Zulu\u00A6Baskir\u0161tina\u00A6Tonga\u00A6Hebrej\u0161tina\u00A6Setswan\u0161tina\u00A6Tagalog\u00A6Turkmen\u0161tina\u00A6Hausa\u00A6Nep\u00e1l\u0161tina\u00A6Azerbajd\u017e\u00e1n\u0161tina\u00A6Tigrinij\u0161tina\u00A6Aym\u00e1r\u0161tina\u00A6Thaj\u0161tina\u00A6T\u00e1d\u017ei\u010dtina\u00A6Nauru\u00A6Telug\u0161tina\u00A6\u010c\u00edn\u0161tina\u00A6Assam\u00e9\u0161tina\u00A6Arab\u0161tina\u00A6Tamil\u0161tina\u00A6Gujarat\u0161tina\u00A6Barm\u0161tina\u00A6Amhar\u0161tina\u00A6Zhuang\u00A6Malt\u0161tina\u00A6Malaj\u0161tina\u00A6Guaran\u0161tina\u00A6Svahil\u0161tina\u00A6Marathi\u00A6\u0160v\u00e9d\u0161tina\u00A6Hali\u010d\u0161tina\u00A6Sundan\u0161tina\u00A6Afrik\u00e1n\u0161tina\u00A6Sesotho\u00A6Moldav\u0161tina\u00A6Siswat\u0161tina\u00A6Mongol\u0161tina\u00A6Srb\u0161tina\u00A6Alb\u00e1n\u0161tina\u00A6Malabar\u0161tina\u00A6Abch\u00e1z\u0161tina\u00A6Makedon\u0161tina\u00A6Afar\u0161tina\u00A6Som\u00e1l\u0161tina\u00A6Shona\u00A6Maor\u0161tina\u00A6Skotsk\u00e1 gal\u0161tina\u00A6Samoy\u0161tina\u00A6Slovin\u0161tina\u00A6Malga\u0161tina\u00A6Sloven\u0161tina\u00A6Ir\u0161tina\u00A6Yoruba\u00A6Sinh\u00e1l\u0161tina\u00A6Srbochorvat\u0161tina\u00A6Sangho\u00A6Jidi\u0161\u00A6Sindhi\u00A6Fr\u00ed\u0161tina\u00A6Sanskrt\u00A6Francouz\u0161tina\u00A6Loty\u0161tina\u00A6Litev\u0161tina\u00A6Faer\u0161tina\u00A6Kinyarwand\u0161tina\u00A6Ru\u0161tina\u00A6Lao\u0161tina\u00A6Fid\u017ei\u00A6Lingal\u0161tina\u00A6Fin\u0161tina\u00A6Rumun\u0161tina\u00A6Kirundi\u00A6R\u00e9torom\u00e1n\u0161tina\u00A6Per\u0161tina\u00A6Latina\u00A6Xhosa\u00A6Baski\u010dtina\u00A6Kirgiz\u0161tina\u00A6Eston\u0161tina";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "d.M.yy" },
    { "mediumDateFormat", "d.M.yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE, d. MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
