/* LocaleInformation_it.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_it extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "Dinaro Giordano\u00A6Mvdol Boliviano\u00A6Oro\u00A6Kronur delle Isole Faeroe\u00A6Sterlina Libanese\u00A6Euro\u00A6Dong Vietnamita\u00A6Scellino della Tanzania\u00A6Peso Boliviano\u00A6Riel Cambogiano\u00A6Unit\u00e0 Monetaria Asiatica\u00A6Boliviano (1863-1962)\u00A6Vecchio riel cambogiano\u00A6Sterlina dello Zambia\u00A6Sterlina Australiana\u00A6Franco CFA BEAC\u00A6Sterlina Maltese\u00A6Cedi rivalutato del Ghana\u00A6Kwacha dello Zambia\u00A6Unit\u00e0 di conto in dinari asiatica\u00A6Sterlina del Ghana\u00A6Boliviano\u00A6Vecchi cedi del Ghana\u00A6Lira Maltese\u00A6Dollaro Australiano\u00A6Dollaro Statunitense (Same day)\u00A6Lira Italiana\u00A6Dollaro Statunitense (Next day)\u00A6Cedi del Ghana\u00A6Dollaro di Singapore\u00A6Balboa di Panama\u00A6Kip Laotiano\u00A6Som  Kirghiso\u00A6Franco Svizzero\u00A6Scellino Austriaco\u00A6Dollaro Statunitense\u00A6Dollaro Etiopico\u00A6Dollaro del Brunei\u00A6Sterlina Giamaicana\u00A6Birr Etiopico\u00A6Franco germinale algerino\u00A6Nuovo franco algerino\u00A6Dinaro Algerino\u00A6Guarani del Paraguay\u00A6Sterlina Libica\u00A6Dollaro Giamaicano\u00A6Corona Islandese\u00A6Peseta Spagnola\u00A6Sterlina delle Bermuda\u00A6Dinaro Libico\u00A6Lira libica della British Military Authority\u00A6Dollaro delle Bermuda\u00A6Fiorino Olandese\u00A6Ouguiya della Mauritania\u00A6Rial Iraniano\u00A6Corona Svedese\u00A6Nakfa Eritreo\u00A6Scellino Keniota\u00A6Franco CFA della Repubblica dell\u2019Africa Centrale\u00A6Peso Argentino\u00A6Peso Argentino (vecchio Cod.)\u00A6Peso Moneda Nacional argentino\u00A6Nuovo dollaro taiwanese\u00A6Sterlina Sudanese\u00A6Lari Georgiano\u00A6Kupon Larit Georgiano\u00A6Franco della Martinica\u00A6Sterlina delle Falkland\u00A6Austral Argentino\u00A6Dinaro Sudanese\u00A6Dinaro Iracheno\u00A6Dollaro di Tuvalu\u00A6Rupia delle Seychelles\u00A6Rublo Lettone\u00A6Sterlina delle Figi\u00A6Lat Lettone\u00A6Zaire Congolese\u00A6Franco della Repubblica Congolese\u00A6Franco Congolese\u00A6Dollaro delle Figi\u00A6C\u00f3rdoba oro nicaraguense\u00A6Pataca di Macao\u00A6C\u00f3rdoba d\u2019oro nicaraguense\u00A6Cordoba Nicaraguense\u00A6Rublo Trasferibile COMECON\u00A6Markka Finlandese (1860-1962)\u00A6Markka Finlandese\u00A6Dollaro delle Isole Solomon\u00A6Franco del Lussemburgo\u00A6Vecchio dollaro di Trinidad e Tobago\u00A6Escudo Angolano\u00A6Kwanza Reajustado Angolano (1995-1999)\u00A6Tugrik Mongolo\u00A6Fiorino Ungherese\u00A6Franco del Burundi\u00A6Nuovo Kwanza Angolano (1990-2000)\u00A6Kwanza Angolano (1977-1990)\u00A6Dollaro di Trinidad e Tobago\u00A6Lilangeni dello Swaziland\u00A6Franco CFP delle Nuove Ebridi\u00A6Sterlina Inglese\u00A6Riyal sovrano saudita\u00A6Ryal Saudita\u00A6Talonas Lituani\u00A6Rupia Indiana\u00A6Escudo Portoghese\u00A6Kwanza Angolano\u00A6Conto Portoghese\u00A6Lita Lituana\u00A6Tenge Kazaco\u00A6Rublo Kazaco\u00A6Dollaro delle Isole Vergini britanniche\u00A6Sterlina Nigeriana\u00A6Certificati di cambio esteri in dollari Myanmar\u00A6Naira Nigeriana\u00A6Gourde Haitiano\u00A6Sterlina Siriana\u00A6Sterlina della Palestina\u00A6Dinaro del Bahraini\u00A6Kyat di Myanmar\u00A6Fiorino delle Antille Olandesi\u00A6Corona Ceca\u00A6Lira Sterlina dell\u2019Isola di Man\u00A6Certificati di cambio esteri in Lev bulgari\u00A6Loti del Lesotho\u00A6Franco CFA Gabon\u00A6Lev Bulgaro (1879-1952)\u00A6Nuovo Lev Bulgaro\u00A6Lev Bulgaro Socialista\u00A6Dollaro Canadese\u00A6Lev Bulgaro\u00A6Lira Turca\u00A6Dollaro delle Isole Cayman\u00A6Sterlina Cipriota\u00A6Nuovo sheqel israeliano\u00A6Dollaro della Guyana\u00A6Dram Armeno\u00A6Sterlina Israeliana\u00A6Franco di Mali\u00A6Sheqel Israeliano\u00A6Bolivar Venezuelano\u00A6Certificati di cambio esteri albanesi in dollari\u00A6Dollaro Liberiano\u00A6Lek Valute Albanese\u00A6Kuna Croata\u00A6Franco di Reunion\u00A6Dinaro Croato\u00A6Lek Albanese\u00A6Lira Sterlina di Jersey\u00A6Lek Albanese (1946-1961)\u00A6Dinaro Macedone (1992-1993)\u00A6Viet Minh Piastre Dong Viet nordvietnamita\u00A6Nuovo Dong nordvietnamita\u00A6Dinaro Macedone\u00A6Piastre Dong Viet nordvietnamita\u00A6Pataca di Timor\u00A6Franco CFP\u00A6Franco Belga (finanziario)\u00A6Peso della Guinea-Bissau\u00A6Dinaro Kuwaitiano\u00A6Mil Reis della Guinea portoghese\u00A6Franco Belga\u00A6Escudo di Timor\u00A6Franco Belga (convertibile)\u00A6Escudo della Guinea portoghese\u00A6Col\u00f3n Salvadoregno\u00A6Guilder del Curacao\u00A6Taka Bangladese\u00A6Lira sterlina di Tonga\u00A6Pa\u02bbanga di Tonga\u00A6Franco CFA BCEAO\u00A6Rublo Sovietico\u00A6Nuovo rublo sovietico\u00A6Franco germinale della Nuova Caledonia\u00A6Escudo del Capo Verde\u00A6Franco CFA delle Antille Francesi\u00A6Rand Sudafricano\u00A6Peso Dominicano\u00A6Certificati di cambio esteri cubani\u00A6Sterlina Sudafricana\u00A6Rand Sudafricano (finanziario)\u00A6Dinaro Tunisino\u00A6Peso Cubano\u00A6Franco Guiana della Guyana francese\u00A6Scellino Ugandese\u00A6Rupia di Ceylon\u00A6Franco di Affars e Issas\u00A6Lira della Citt\u00e0 del Vaticano\u00A6Escudo di S\u00e3o Tom\u00e9 e Principe\u00A6Scellino Ugandese (1966-1987)\u00A6Dobra di S\u00e3o Tom\u00e9 e Principe\u00A6Dollaro delle Isole Marshall\u00A6Sterlina Neozelandese\u00A6Tala della Samoa Occidentale\u00A6Sterlina della Samoa Occidentale\u00A6Lempira Hoduregno\u00A6Nouveau Franc francese metropolitano\u00A6Manat Turkmeno\u00A6Quetzal Guatemalteco\u00A6Dollaro Neozelandese\u00A6Sterlina Scozzese\u00A6Dollaro di Barbados\u00A6Dollaro Namibiano\u00A6Franco Malgascio\u00A6Ariary Malgascio\u00A6Sterlina Egiziana\u00A6Dollaro Honduras Britannico\u00A6Zloty Polacco (1950-1995)\u00A6Nuovo Dinar Bosnia-Herzegovina\u00A6Certificati di cambio esteri polacchi in dollari statunitensi\u00A6Marco Conv. Bosnia-Erzegovina\u00A6Dollaro Belize\u00A6Dinar Bosnia-Herzegovina\u00A6Zloty Polacco\u00A6Rial dello Yemen\u00A6Fiorino del Suriname\u00A6Corona forte cecoslovacca\u00A6Won Sudcoreano\u00A6Rublo Bielorussia\u00A6Riyal Imadi dello Yemen\u00A6Rublo Bielorussia (1992-1994)\u00A6Corona Cecoslovacca\u00A6Vecchi won sudcoreano\u00A6Hwan sudcoreano\u00A6Nuovo Rublo Bielorussia (1994-1999)\u00A6Scellino del Somaliland\u00A6Nuova dracma greca\u00A6Rupia del Pakistan\u00A6Afgani\u00A6Dollaro dello Zimbabwe\u00A6Rupia di Sri Lanka\u00A6Dracma Greca\u00A6Lira Irlandese\u00A6Afgani (1927-2002)\u00A6Dinaro dello Yemen\u00A6Franco Ruandese\u00A6Col\u00f3n Costaricano\u00A6Somoni del Tajikistan\u00A6Rublo del Tajikistan\u00A6Corona dell\u2019Estonia\u00A6Peseta Guineana della Guinea Equatoriale\u00A6Coupon Rublo della Moldavia\u00A6Dollaro di Hong Kong\u00A6Corona Danese\u00A6Leu Moldavo\u00A6Franco della Guinea Equatoriale\u00A6Ekwele della Guinea Equatoriale\u00A6Rupia Indiana\u00A6Dirham degli Emirati Arabi Uniti\u00A6Won Nordcoreano\u00A6Nuova rupia indonesiana\u00A6Pula del Botswana\u00A6Coupon Leu della Moldavia\u00A6Rupia indonesiana di Java\u00A6Won della Repubblica popolare democratica nordcoreana\u00A6Fiorino Nica indonesiano\u00A6Vatu di Vanuatu\u00A6Dinaro Islamico\u00A6Scellino Somalo\u00A6Peseta Andorrana\u00A6Rublo della CSI\u00A6Franco della Guadalupa\u00A6Franco Gibutiano\u00A6Diner Andorrano\u00A6Franco germinale di Monaco\u00A6Franc Nouveau di Monaco\u00A6Unidad de Valor Constante (UVC) dell\u2019Ecuador\u00A6Sucre dell\u2019Ecuador\u00A6Franco del Liechtenstein\u00A6Rublo Russo\u00A6Peso delle Filippine\u00A6Sum dell\u2019Uzbekistan\u00A6Peso Colombiano\u00A6Baht Tailandese\u00A6Sterlina dell\u2019Irlanda del Nord\u00A6Rupia Birmana\u00A6Franco CFA del Congo\u00A6Kyat Birmano\u00A6Peso in banconote colombiano\u00A6Som Coupon dell\u2019Uzbekistan\u00A6Karbovanetz Ucraino\u00A6Rial del Qatar\u00A6Hrivna Ucraina\u00A6Syli della Guinea\u00A6Renmimbi Cinese\u00A6Metical del Mozambico\u00A6Certificati di cambio esteri cinesi in dollari statunitensi\u00A6Peso Uruguayo uruguaiano\u00A6Franco della Guinea (1960-1972)\u00A6Lira di San Marino\u00A6Jen Min Piao Yuan Cinese\u00A6Escudo del Mozambico\u00A6Franco della Guinea\u00A6Rial Saidi dell\u2019Oman\u00A6Kina della Papua Nuova Guinea\u00A6Rial Omanita\u00A6Peso Uruguaiano (1975-1993)\u00A6Franco UIC Francese\u00A6Rupia Butanese\u00A6Zaire dello Zaire\u00A6Franco Marocchino\u00A6Dirham Marocchino\u00A6Ngultrum Butanese\u00A6Franco Oro Francese\u00A6Peso Fuerte dell\u2019Uruguaiano\u00A6Ringgit della Malesia\u00A6Nuovo Zaire dello Zaire\u00A6Manat Azero\u00A6Sterlina del Gambia\u00A6Franco Comoriano\u00A6Leone della Sierra Leone\u00A6Dalasi del Gambia\u00A6Unit\u00e0 Monetaria Europea\u00A6Libra delle Bahamas\u00A6Franco CFA del Camerun\u00A6Unidad de Inversion (UDI) Messicana\u00A6Franco CFA BCEAEC\u00A6Dollaro delle Bahamas\u00A6Peso messicano d\u2019argento (1861-1992)\u00A6Peso Messicano\u00A6Sol Peruviano\u00A6Corona della Groenlandia\u00A6Cruzeiro Brasiliano (1942-1967)\u00A6Sol Nuevo Peruviano\u00A6Peso Cileno\u00A6Corona Slovacca\u00A6Inti Peruviano\u00A6Cruzeiro Brasiliano\u00A6Diritti Speciali di Incasso\u00A6Franco germinale/franco Poincare francese\u00A6Franco Francese\u00A6Cruzado Novo Brasiliano\u00A6Unidades de Fomento Chilene\u00A6Escudo Cileno\u00A6Real Brasiliano\u00A6Condor Cileno\u00A6Cruzeiro Brasiliano (1990-1993)\u00A6Sperrmark Tedesco\u00A6Sterlina Malawiana\u00A6Cruzado Brasiliano\u00A6Cruzeiro Novo Brasiliano (1967-1986)\u00A6Kwacha Malawiano\u00A6Rublo della Transdniestria\u00A6Marco Tedesco\u00A6Franco CFA del Chad\u00A6Nuovo rublo della Transdniestria\u00A6Coupon in rubli della Transdniestria\u00A6Rupia Nepalese\u00A6Dollaro delle Isole Cook\u00A6Yen Giapponese\u00A6Rufiyaa delle Maldive\u00A6Nuovo Franco CFA\u00A6Rupia delle Maldive\u00A6Dollaro dei Caraibi Orientali\u00A6Tallero Sloveno\u00A6Dinaro Riformato Yugoslavo\u00A6Fiorino di Aruba\u00A6Dinaro di Ottobre Yugoslavo\u00A6Ostmark della Germania Orientale\u00A6Dinaro Convertibile Yugoslavo\u00A6Dinaro Noviy Yugoslavo\u00A6Corona di Turks e Caicos\u00A6Dinaro 1994 Yugoslavo\u00A6Dinaro della Federazione Yugoslava\u00A6Nuovo Leu della Romania\u00A6Dinaro Forte Yugoslavo\u00A6Leu della Romania\u00A6Tallero Bons Sloveno\u00A6Corona Norvegese\u00A6Rupia Mauriziana\u00A6Unit\u00e0 di acconto europea (XBD)\u00A6Sterlina di Gibilterra\u00A6Dong Nazionale Vietnamita\u00A6Unit\u00e0 di acconto europea (XBC)\u00A6Dong della Repubblica Vietnamita\u00A6Unit\u00e0 monetaria europea\u00A6Unit\u00e0 composita europea\u00A6Dollaro di Kiribati\u00A6Sterlina di Sant\u2019Elena\u00A6Nuovo dong vietnamita";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LL\u00A6VND\u00A6T Sh\u00A6BOP\u00A6CR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6Lm\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6som\u00A6SFr.\u00A6ATS\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6LYB\u00A6Ber$\u00A6NLG\u00A6UM\u00A6RI\u00A6SEK\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6HUF\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6CZK\u00A6IMP\u00A6BGX\u00A6M\u00A6GAF\u00A6BGO\u00A6lev\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6T$\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6XNF\u00A6ZAR\u00A6RD$\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6XMF\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Af\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6AFA\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6Mt\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6GF\u00A6OMS\u00A6PGK\u00A6RO\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6Nu\u00A6XFO\u00A6UYF\u00A6RM\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6CF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6Sk\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "gen",
    "feb",
    "mar",
    "apr",
    "mag",
    "giu",
    "lug",
    "ago",
    "set",
    "ott",
    "nov",
    "dic",
    null,
  };

  private static final String[] months = {
    "gennaio",
    "febbraio",
    "marzo",
    "aprile",
    "maggio",
    "giugno",
    "luglio",
    "agosto",
    "settembre",
    "ottobre",
    "novembre",
    "dicembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dom",
    "lun",
    "mar",
    "mer",
    "gio",
    "ven",
    "sab",
  };

  private static final String[] weekdays = {
    null,
    "domenica",
    "luned\u00ec",
    "marted\u00ec",
    "mercoled\u00ec",
    "gioved\u00ec",
    "venerd\u00ec",
    "sabato",
  };

  private static final String[] eras = {
    "aC",
    "dC",
  };

  private static final String[] ampms = {
    "m.",
    "p.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "Ora Standard Orientale", "EST", "Ora Standard Orientale"},
    {  "America/Halifax", "AST", "Ora Standard Atlantico", "ADT", "Ora Legale Atlantico"},
    {  "Pacific/Honolulu", "HST", "Ora Standard Hawaii", "HST", "Ora Standard Hawaii"},
    {  "America/Denver", "MST", "Ora Standard Mountain", "MDT", "Ora Legale Mountain"},
    {  "America/Anchorage", "AST", "Ora Standard Alaska", "ADT", "Ora Legale Alaska"},
    {  "America/St_Johns", "CNT", "Ora Standard Newfoundland", "CDT", "Ora Legale Newfoundland"},
    {  "Africa/Casablanca", "GMT", "Ora Meridiano Greenwich", "GMT", "Ora Meridiano Greenwich"},
    {  "America/Chicago", "CST", "Ora Standard Centrale", "CDT", "Ora Legale Centrale"},
    {  "Asia/Shanghai", "CTT", "Ora Standard Cina", "CDT", "Ora Standard Cina"},
    {  "Asia/Tokyo", "JST", "Ora Standard Giappone", "JST", "Ora Standard Giappone"},
    {  "America/New_York", "EST", "Ora Standard Orientale", "EDT", "Ora Legale Orientale"},
    {  "Europe/Bucharest", "EET", "Ora Standard Europa Orientale", "EEST", "Ora Legale Europa Orientale"},
    {  "America/Los_Angeles", "PST", "Ora Standard Pacifico", "PDT", "Ora Legale Pacifico"},
    {  "America/Phoenix", "MST", "Ora Standard Mountain", "MST", "Ora Standard Mountain"},
    {  "Etc/GMT", "GMT", "Ora Meridiano Greenwich", "GMT", "Ora Meridiano Greenwich"},
    {  "Asia/Jerusalem", "IST", "Ora Standard Israele", "IDT", "Ora Legale Israele"},
    {  "Europe/Paris", "CET", "Ora Standard Centrale Europeo", "CEST", "Ora Legale Centrale Europeo"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6SP\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Timor Est\u00A6Tokelau\u00A6Tagikistan\u00A6Tailandia\u00A6Togo\u00A6Territori australi francesi\u00A6Guyana\u00A6Ciad\u00A6Isole Turks e Caicos\u00A6Guinea-Bissau\u00A6Guam\u00A6Guatemala\u00A6Georgia del Sud e Isole Sandwich del Sud\u00A6Grecia\u00A6Guinea Equatoriale\u00A6Guadalupa\u00A6Swaziland\u00A6Siria\u00A6Guinea\u00A6Gambia\u00A6Groenlandia\u00A6El Salvador\u00A6S\u00e3o Tom\u00e9 e Pr\u00edncipe\u00A6Gibilterra\u00A6Ghana\u00A6Suriname\u00A6Guiana Francese\u00A6Serbia\u00A6Georgia\u00A6Somalia\u00A6Grenada\u00A6Senegal\u00A6San Marino\u00A6Regno Unito\u00A6Sierra Leone\u00A6Gabon\u00A6Slovacchia\u00A6Svalbard e Jan Mayen\u00A6Slovenia\u00A6Sant\u2019Elena\u00A6Singapore\u00A6Svezia\u00A6Sudan\u00A6Seychelles\u00A6Isole Solomon\u00A6Arabia Saudita\u00A6Francia\u00A6Isole Faroe\u00A6Micronesia\u00A6Ruanda\u00A6Isole Falkland\u00A6Federazione Russa\u00A6Fiji\u00A6Finlandia\u00A6Romania\u00A6R\u00e9union\u00A6Etiopia\u00A6Spagna\u00A6Eritrea\u00A6Sahara Occidentale\u00A6Egitto\u00A6Estonia\u00A6Ecuador\u00A6Algeria\u00A6Qatar\u00A6Repubblica Dominicana\u00A6Paraguay\u00A6Dominica\u00A6Palau\u00A6Danimarca\u00A6Gibuti\u00A6Portogallo\u00A6Palestina\u00A6Portorico\u00A6Germania\u00A6Pitcairn\u00A6Saint Pierre e Miquelon\u00A6Polonia\u00A6Pakistan\u00A6Filippine\u00A6Papua Nuova Guinea\u00A6Polinesia Francese\u00A6Repubblica Ceca\u00A6Per\u00f9\u00A6Cipro\u00A6Isola Christmas\u00A6Capo Verde\u00A6Panama\u00A6Cuba\u00A6Costa Rica\u00A6Colombia\u00A6Cina\u00A6Camerun\u00A6Cile\u00A6Isole Cook\u00A6Costa d\u2019Avorio\u00A6Svizzera\u00A6Congo\u00A6Repubblica Centrafricana\u00A6Repubblica Democratica del Congo\u00A6Isole Cocos (Keeling)\u00A6Oman\u00A6Canada\u00A6Belize\u00A6Bielorussia\u00A6Botswana\u00A6Isola Bouvet\u00A6Bhutan\u00A6Bahamas\u00A6Brasile\u00A6Nuova Zelanda\u00A6Bolivia\u00A6Brunei\u00A6Bermuda\u00A6Niue\u00A6Benin\u00A6Burundi\u00A6Bahrein\u00A6Nauru\u00A6Bulgaria\u00A6Burkina Faso\u00A6Nepal\u00A6Belgio\u00A6Norvegia\u00A6Bangladesh\u00A6Barbados\u00A6Zimbabwe\u00A6Paesi Bassi\u00A6Bosnia Erzegovina\u00A6Nicaragua\u00A6Nigeria\u00A6Isola Norfolk\u00A6Azerbaigian\u00A6Niger\u00A6Nuova Caledonia\u00A6Aruba\u00A6Zambia\u00A6Namibia\u00A6Australia\u00A6Austria\u00A6Samoa Americane\u00A6Argentina\u00A6Antartide\u00A6Mozambico\u00A6Angola\u00A6Malesia\u00A6Antille Olandesi\u00A6Messico\u00A6Armenia\u00A6Malawi\u00A6Albania\u00A6Maldive\u00A6Sud Africa\u00A6Mauritius\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Mauritania\u00A6Antigua e Barbuda\u00A6Martinica\u00A6Afghanistan\u00A6Isole Marianne Settentrionali\u00A6Emirati Arabi Uniti\u00A6Regione Amministrativa Speciale di Macao, Cina\u00A6Andorra\u00A6Mongolia\u00A6Myanmar\u00A6Mali\u00A6Macedonia, Repubblica\u00A6Yugoslavia\u00A6Mayotte\u00A6Isole Marshall\u00A6Madagascar\u00A6Moldavia\u00A6Monaco\u00A6Marocco\u00A6Yemen\u00A6Libia\u00A6Lettonia\u00A6Lussemburgo\u00A6Lituania\u00A6Lesotho\u00A6Liberia\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Saint Lucia\u00A6Libano\u00A6Laos\u00A6Kazakistan\u00A6Isole Cayman\u00A6Kuwait\u00A6Corea del Sud\u00A6Corea del Nord\u00A6Saint Kitts e Nevis\u00A6Comore\u00A6Kiribati\u00A6Samoa\u00A6Cambogia\u00A6Kirghizistan\u00A6Kenya\u00A6Wallis e Futuna\u00A6Giappone\u00A6Giordania\u00A6Giamaica\u00A6Vanuatu\u00A6Vietnam\u00A6Isole Vergini Americane\u00A6Isole Vergini Britanniche\u00A6Venezuela\u00A6Saint Vincent e Grenadines\u00A6Vaticano\u00A6Italia\u00A6Islanda\u00A6Iran\u00A6Iraq\u00A6Uzbekistan\u00A6Territorio Britannico dell\u2019Oceano Indiano\u00A6Uruguay\u00A6India\u00A6Israele\u00A6Stati Uniti\u00A6Irlanda\u00A6Indonesia\u00A6Isole Minori lontane dagli Stati Uniti\u00A6Uganda\u00A6Ucraina\u00A6Ungheria\u00A6Haiti\u00A6Croazia\u00A6Tanzania\u00A6Honduras\u00A6Isole Heard ed Isole McDonald\u00A6Taiwan\u00A6Tuvalu\u00A6Regione Amministrativa Speciale di Hong Kong, Cina\u00A6Trinidad e Tobago\u00A6Turchia\u00A6Tonga\u00A6Tunisia\u00A6Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6kut\u00A6mic\u00A6wa\u00A6kum\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6bai\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tl\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sn\u00A6sm\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpf\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6snk\u00A6cop\u00A6yap\u00A6ach\u00A6yao\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6sms\u00A6bua\u00A6mas\u00A6smn\u00A6os\u00A6map\u00A6or\u00A6man\u00A6smj\u00A6smi\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6sma\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6ng\u00A6sla\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6kv\u00A6ku\u00A6sio\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6jv\u00A6gil\u00A6znd\u00A6shn\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6ath\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6ypk\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6tup\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6moh\u00A6luo\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6mno\u00A6wak\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6sal\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6pra\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "gwich\u02bbin\u00A6accado\u00A6ekajuka\u00A6xosa\u00A6sumero\u00A6susu\u00A6lingue diverse\u00A6lozi\u00A6tonga (nyasa)\u00A6ponape\u00A6menangkabau\u00A6sukuma\u00A6volof\u00A6lolo (bantu)\u00A6kutenai\u00A6micmac\u00A6walloon\u00A6kumyk\u00A6zapotec\u00A6cuscitica (altra lingua)\u00A6lojban\u00A6dogri\u00A6volap\u00fck\u00A6lingue otomi\u00A6vietnamita\u00A6rarotonga\u00A6venda\u00A6rapanui\u00A6rajasthani\u00A6turco ottomano (1500-1928)\u00A6nzima\u00A6napoletano\u00A6usbeco\u00A6ugaritico\u00A6tamashek\u00A6indiano del Nord America (altra lingua)\u00A6nahuatl\u00A6urdu\u00A6fanti\u00A6ucraino\u00A6egiziano (antico)\u00A6uigurico\u00A6nilo-sahariana (altra lingua)\u00A6irlandese medio (900-1200)\u00A6baltica (altra lingua)\u00A6nyoro\u00A6basa\u00A6nyankole\u00A6nyamwezi\u00A6hmong\u00A6balinese\u00A6osage\u00A6beluci\u00A6taitiano\u00A6lingue bamileke\u00A6ci\u00A6serer\u00A6tlingit\u00A6tatarico\u00A6tsonga\u00A6banda\u00A6turco\u00A6tonga (Isole Tonga)\u00A6tswana\u00A6tagalog\u00A6turcomanno\u00A6tigrinya\u00A6thai\u00A6kurukh\u00A6tagicco\u00A6blin\u00A6telugu\u00A6kru\u00A6kashubian\u00A6tamil\u00A6tokelau\u00A6efik\u00A6swahili\u00A6svedese\u00A6sundanese\u00A6karachay-Balkar\u00A6sotho del sud\u00A6swati\u00A6serbo\u00A6albanese\u00A6mende\u00A6creola e Pidgins (altra lingua)\u00A6somalo\u00A6afrihili\u00A6shona\u00A6samoano\u00A6sloveno\u00A6greco, antico (fino al 1453)\u00A6slovacco\u00A6gerbo\u00A6singalese\u00A6serbo-croato\u00A6turco crimeo; tatar crimeo\u00A6afro-asiatica (altra lingua)\u00A6sango\u00A6sami del nord\u00A6sindhi\u00A6udmurt\u00A6sardo\u00A6sanscrito\u00A6kinyarwanda\u00A6russo\u00A6mandar\u00A6romeno\u00A6rundi\u00A6lingua rhaeto-romance\u00A6moksha\u00A6adyghe\u00A6zuni\u00A6kpelle\u00A6quechua\u00A6tigre\u00A6songhai\u00A6creolo e pidgins, basato sul portoghese (altra lingua)\u00A6sogdiano\u00A6adangme\u00A6Kosraean\u00A6hittite\u00A6creolo e pidgins, basato sul francese (altra lingua)\u00A6creolo e pidgins, basato sull\u2019inglese (altra lingua)\u00A6himachali\u00A6konkani\u00A6hiligayna\u00A6gotico\u00A6gorontalo\u00A6gondi\u00A6dinca\u00A6nubiano\u00A6portoghese\u00A6pashto\u00A6friulano\u00A6fenicio\u00A6tedesco, antico alto (ca.750-1050)\u00A6soninke\u00A6copto\u00A6Yapese\u00A6acioli\u00A6yao (bantu)\u00A6filippino (altra lingua)\u00A6polacco\u00A6accinese\u00A6pali\u00A6punjabi\u00A6bugi\u00A6iban\u00A6sami skolt\u00A6buriat\u00A6masai\u00A6sami inari\u00A6ossetico\u00A6austronesiano\u00A6oriya\u00A6mandingo\u00A6sami lule\u00A6lingue sami (altra lingua)\u00A6makasar\u00A6oromo\u00A6maithili\u00A6ojibwa\u00A6magahi\u00A6madurese\u00A6sami del sud\u00A6occitano (post 1500); provenzale\u00A6sotho del nord\u00A6batak\u00A6erzya\u00A6dogrib\u00A6nyanja; chichewa; chewa\u00A6lingue maya\u00A6navajo\u00A6kimbundu\u00A6ndebele del sud\u00A6tedesco, medio alto (ca.1050-1500)\u00A6norvegese\u00A6norvegese nynorsk\u00A6olandese\u00A6ndonga\u00A6slavo (altra lingua)\u00A6nepali\u00A6ndebele del nord\u00A6lingue chamic\u00A6tetum\u00A6norvegese bokm\u00e5l\u00A6nauru\u00A6tereno\u00A6temne\u00A6burmese\u00A6lezghian\u00A6maltese\u00A6antico persiano (600-400 A.C.)\u00A6malay\u00A6marathi\u00A6francese, antico (842-ca.1400)\u00A6moldavo\u00A6francese, medio (ca.1400-1600)\u00A6mongolo\u00A6giudeo arabo\u00A6malayalam\u00A6macedone\u00A6maori\u00A6marshallese\u00A6malagasy\u00A6marwari\u00A6braj\u00A6slave\u00A6lettone\u00A6luba-katanga\u00A6delaware\u00A6lituano\u00A6lao\u00A6lingala\u00A6limburgish\u00A6ewondo\u00A6ganda\u00A6lussemburghese\u00A6latino\u00A6giudeo persiano\u00A6voto\u00A6sino-tibetano (altra lingua)\u00A6kirghiso\u00A6cornico\u00A6komi\u00A6curdo\u00A6lingue sioux\u00A6kashmiri\u00A6kanuri\u00A6awadhi\u00A6coreano\u00A6kannada\u00A6khmer\u00A6kalaallisut\u00A6kazako\u00A6romani\u00A6kuanyama\u00A6sidamo\u00A6kikuyu\u00A6kongo\u00A6norse antico\u00A6georgiano\u00A6creek\u00A6lingua romanza (altra lingua)\u00A6nogai\u00A6munda (altra lingua)\u00A6multilingua\u00A6giavanese\u00A6gilbertese\u00A6zande\u00A6shan\u00A6kalmyk\u00A6lingue australiane\u00A6khotanese\u00A6giapponese\u00A6khoisan (altra lingua)\u00A6palau\u00A6cheyenne\u00A6tailandese (altra lingua)\u00A6inuktitut\u00A6papiamento\u00A6italiano\u00A6lingue sign\u00A6islandese\u00A6khasi\u00A6cherokee\u00A6pampanga\u00A6pahlavi\u00A6chipewyan\u00A6ido\u00A6choctaw\u00A6gergo chinook\u00A6mari\u00A6tuvinian\u00A6bantu\u00A6pangasinan\u00A6inupiak\u00A6chuukese\u00A6sichuan yi\u00A6hawaiano\u00A6lamba\u00A6igbo\u00A6ciagataico\u00A6irlandese, antico (fino al \u2019900)\u00A6papuano-australiano (altra lingua)\u00A6interlingue\u00A6indonesiano\u00A6lahnda\u00A6dayak\u00A6chibcha\u00A6interlingua\u00A6ladino\u00A6herero\u00A6haida\u00A6dargwa\u00A6armeno\u00A6lingue athabaska\u00A6ungherese\u00A6haitian\u00A6dakota\u00A6croato\u00A6hiri motu\u00A6hindi\u00A6diula\u00A6ebraico\u00A6asturiano\u00A6haussa\u00A6sorabo\u00A6manx\u00A6gujarati\u00A6semitico (altra lingua)\u00A6selkup\u00A6lingue irochesi\u00A6guarana\u00A6galiziano\u00A6aruaco\u00A6geez\u00A6artificiale (altra lingua)\u00A6gaelico scozzese\u00A6iraniana\u00A6irlandese\u00A6arapaho\u00A6araucano\u00A6frisone\u00A6siksika\u00A6germanica (altra lingua)\u00A6lingue yupik\u00A6aramaico\u00A6francese\u00A6faroese\u00A6celtica altra lingua\u00A6figiano\u00A6finlandese\u00A6fulah\u00A6tuvalu\u00A6cebuano\u00A6persiano\u00A6basco\u00A6scozzese\u00A6estone\u00A6spagnolo\u00A6esperanto\u00A6inglese\u00A6greco\u00A6turco-tatarica (altra lingua)\u00A6niue\u00A6lingue tupi\u00A6ewe\u00A6tumbuka\u00A6mossi\u00A6dzongkha\u00A6niger - cordofan (altra lingua)\u00A6lushai\u00A6ugrofinnica (altra lingua)\u00A6divehi\u00A6mohawk\u00A6luo (Kenia e Tanzania)\u00A6lunda\u00A6lingue apache\u00A6luiseno\u00A6hupa\u00A6bini\u00A6tedesco\u00A6luba-lulua\u00A6bicol\u00A6washo\u00A6lingua imprecisata\u00A6waray\u00A6danese\u00A6olandese, medio (ca. 1050-1350)\u00A6walamo\u00A6manobo\u00A6lingue wakash\u00A6santali\u00A6gallese\u00A6sasak\u00A6kabardia\u00A6chuvash\u00A6slavo della Chiesa\u00A6manipuri\u00A6ceco\u00A6aramaico samaritano\u00A6cree\u00A6lingue salish\u00A6duala\u00A6corso\u00A6indiano del Sud America (altra lingua)\u00A6manchu\u00A6yakut\u00A6kawi\u00A6ingush\u00A6gbaya\u00A6sandawe\u00A6chamorro\u00A6indoeuropea (altra lingua)\u00A6bhojpuri\u00A6inglese, medio (1100-1500)\u00A6karen\u00A6indiana (altra lingua)\u00A6ceceno\u00A6gayo\u00A6catalano\u00A6mbundu\u00A6siriaco\u00A6kamba\u00A6tsimshian\u00A6inglese, antico (ca.450-1100)\u00A6kachin\u00A6caucasica (altra lingua)\u00A6kabyle\u00A6kara-kalpak\u00A6bosniaco\u00A6caribico\u00A6bretone\u00A6tibetano\u00A6bengalese\u00A6bambara\u00A6ga\u00A6indiana dell\u2019America Centrale (altra lingua)\u00A6bislama\u00A6bihari\u00A6bulgaro\u00A6bielorusso\u00A6caddo\u00A6baschiro\u00A6zulu\u00A6zenaga\u00A6provenzale, antico (fino al 1500)\u00A6alto sorabo\u00A6azerbaigiano\u00A6aymara\u00A6avaro\u00A6assamese\u00A6basso sorabo\u00A6arabo\u00A6ilocano\u00A6elamitico\u00A6cinese\u00A6aragonese\u00A6pracrito\u00A6amarico\u00A6newari\u00A6akan\u00A6zhuang\u00A6afrikaans\u00A6avestan\u00A6abkhazian\u00A6afar\u00A6yoruba\u00A6lingue algonchine\u00A6aleuto\u00A6mon-khmer (altra lingua)\u00A6yiddish\u00A6dravidica (altra lingua)\u00A6berbero\u00A6basso tedesco; basso sassone\u00A6wemba\u00A6begia\u00A6tok pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final String variantsKeys = "REVISED";

  private static final String variantsValues = "Modificato";

  private static final Hashtable variants;
  static
  {
    variants = new Hashtable();
    Enumeration keys = new StringTokenizer(variantsKeys, "\u00A6");
    Enumeration values = new StringTokenizer(variantsValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         variants.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "dd/MM/yy" },
    { "mediumDateFormat", "dd/MMM/yy" },
    { "longDateFormat", "dd MMMM yyyy" },
    { "fullDateFormat", "EEEE d MMMM yyyy" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
