/* LocaleInformation_pt.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_pt extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "Dinar jordaniano\u00A6Mvdol boliviano\u00A6Ouro\u00A6Coroa das Ilhas Fero\u00e9\u00A6Libra libanesa\u00A6Euro\u00A6Dong vietnamita\u00A6Xelim de Tanz\u00e2nia\u00A6Peso boliviano\u00A6Riel cambojano\u00A6Unidade Monet\u00e1ria Asi\u00e1tica\u00A6Boliviano (1863-1962)\u00A6Riel Antigo do Camboja\u00A6Libra zambiana\u00A6Libra australiana\u00A6Franco CFA BEAC\u00A6Libra maltesa\u00A6Cedi reajustado de Gana\u00A6Cuacha zambiano\u00A6Unidade de Conta asi\u00e1tica em dinares\u00A6Libra de Gana\u00A6Boliviano\u00A6Cedi Antigo de Gana\u00A6Lira maltesa\u00A6D\u00f3lar australiano\u00A6D\u00f3lar norte-americano (Mesmo dia)\u00A6Lira italiana\u00A6D\u00f3lar norte-americano (Dia seguinte)\u00A6Cedi de Gana\u00A6D\u00f3lar de Cingapura\u00A6Balboa panamenho\u00A6Kip de Laos\u00A6Som de Quirguist\u00e3o\u00A6Franco su\u00ed\u00e7o\u00A6Xelim austr\u00edaco\u00A6D\u00f3lar norte-americano\u00A6D\u00f3lar et\u00edope\u00A6D\u00f3lar do Brunei\u00A6Libra jamaicana\u00A6Birr et\u00edope\u00A6Franco Germinal argelino\u00A6Franco Novo argelino\u00A6Dinar argelino\u00A6Guarani paraguaio\u00A6Libra l\u00edbia\u00A6D\u00f3lar jamaicano\u00A6Coroa islandesa\u00A6Peseta espanhola\u00A6Libra das Bermudas\u00A6Dinar l\u00edbio\u00A6Lira l\u00edbia da Autoridade Militar Brit\u00e2nica\u00A6D\u00f3lar das Bermudas\u00A6Guilder holand\u00eas\u00A6Ouguiya da Maurit\u00e2nia\u00A6Rial iraniano\u00A6Coroa sueca\u00A6Nakfa da Eritr\u00e9ia\u00A6Xelim queniano\u00A6Franco da Rep\u00fablica Centro-Africana CFA\u00A6Peso argentino\u00A6Peso argentino (1983-1985)\u00A6Peso moneda nacional argentino\u00A6D\u00f3lar Novo de Taiwan\u00A6Libra sudanesa\u00A6Lari georgiano\u00A6Cupom Lari georgiano\u00A6Franco da Martinica\u00A6Libra das Malvinas\u00A6Austral argentino\u00A6Dinar sudan\u00eas\u00A6Dinar iraquiano\u00A6D\u00f3lar de Tuvalu\u00A6Rupia das Seychelles\u00A6Rublo let\u00e3o\u00A6Libra de Fiji\u00A6Lats let\u00e3o\u00A6Zaire congol\u00eas\u00A6Franco da Rep\u00fablica do Congo\u00A6Franco congol\u00eas\u00A6D\u00f3lar de Fiji\u00A6C\u00f3rdoba Ouro nicaraguano\u00A6Pataca macaense\u00A6C\u00f3rdoba Ouro nicaraguano\u00A6C\u00f3rdoba nicaraguano\u00A6Rublo transfer\u00edvel do COMECON\u00A6Marca finlandesa (1860-1962)\u00A6Marca finlandesa\u00A6D\u00f3lar das Ilhas Salom\u00e3o\u00A6Franco luxemburgu\u00eas\u00A6D\u00f3lar Antigo de Trinidad e Tobago\u00A6Escudo angolano\u00A6Cuanza angolano reajustado (1995-1999)\u00A6Tugrik mongol\u00A6Forinte h\u00fangaro\u00A6Franco do Burundi\u00A6Cuanza novo angolano (1990-2000)\u00A6Cuanza angolano (1977-1990)\u00A6D\u00f3lar de Trinidad e Tobago\u00A6Lilangeni da Suazil\u00e2ndia\u00A6Franco CFP das Novas H\u00e9bridas\u00A6Libra esterlina brit\u00e2nica\u00A6Rial Soberano saudita\u00A6Rial saudita\u00A6Talonas lituano\u00A6Rupia indiana\u00A6Escudo portugu\u00eas\u00A6Cuanza angolano\u00A6Conto portugu\u00eas\u00A6Lita lituano\u00A6Tenge do Cazaquist\u00e3o\u00A6Rublo do Cazaquist\u00e3o\u00A6D\u00f3lar das Ilhas Virgens Brit\u00e2nicas\u00A6Libra nigeriana\u00A6Certificados de c\u00e2mbio birmaneses em d\u00f3lares\u00A6Naira nigeriana\u00A6Gurde do Haiti\u00A6Libra s\u00edria\u00A6Libra palestina\u00A6Dinar bareinita\u00A6Kyat de Mianmar\u00A6Guilder das Antilhas Holandesas\u00A6Coroa da Rep\u00fablica Checa\u00A6Libra esterlina da Ilha de Man\u00A6Certificados de c\u00e2mbio b\u00falgaros em leva\u00A6Loti de Lesoto\u00A6Franco do Gab\u00e3o CFA\u00A6Lev b\u00falgaro (1879-1952)\u00A6Lev novo b\u00falgaro\u00A6Lev socialista b\u00falgaro\u00A6D\u00f3lar canadense\u00A6Lev forte b\u00falgaro\u00A6Lira turca\u00A6D\u00f3lar das Ilhas Caim\u00e3o\u00A6Libra de Chipre\u00A6Sheqel Novo israelita\u00A6D\u00f3lar da Guiana\u00A6Dram Arm\u00e9nio\u00A6Libra israelita\u00A6Franco de Mali\u00A6Sheqel israelita\u00A6Bol\u00edvar venezuelano\u00A6Certificados de c\u00e2mbio albaneses em d\u00f3lares\u00A6D\u00f3lar liberiano\u00A6Lek Valute Alban\u00eas\u00A6Kuna croata\u00A6Franco de Reuni\u00e3o\u00A6Dinar croata\u00A6Lek Alban\u00eas\u00A6Libra esterlina de Jersey\u00A6Dinar maced\u00f4nio (1992-1993)\u00A6Viet Minh Piastre Dong Viet do Vietn\u00e3 do Norte\u00A6Dong Novo do Vietn\u00e3 do Norte\u00A6Dinar maced\u00f4nio\u00A6Piastre Dong Viet do Vietn\u00e3 do Norte\u00A6Pataca timorense\u00A6Franco CFP\u00A6Franco belga (financeiro)\u00A6Peso da Guin\u00e9-Bissau\u00A6Dinar coveitiano\u00A6Mil-r\u00e9is da Guin\u00e9 Portuguesa\u00A6Franco belga\u00A6Escudo timorense\u00A6Franco belga (convers\u00edvel)\u00A6Escudo da Guin\u00e9 Portuguesa\u00A6Colom salvadorenho\u00A6Guilder de Cura\u00e7au\u00A6Taka de Bangladesh\u00A6Libra esterlina de Tonga\u00A6Pa\u02bbanga de Tonga\u00A6Franco CFA BCEAO\u00A6Rublo sovi\u00e9tico\u00A6Rublo Novo sovi\u00e9tico\u00A6Franco Germinal da Nova Caled\u00f4nia\u00A6Escudo cabo-verdiano\u00A6Franco CFA das Antilhas Francesas\u00A6Rand sul-africano\u00A6Peso dominicano\u00A6Certificados de c\u00e2mbio cubanos\u00A6Libra sul-africana\u00A6Rand sul-africano (financeiro)\u00A6Dinar tunisiano\u00A6Peso cubano\u00A6Franco da Guiana Francesa\u00A6Xelim ugandense\u00A6Rupia do Ceil\u00e3o\u00A6Franco de Affars e Issas\u00A6Lira da Cidade do Vaticano\u00A6Escudo de S\u00e3o Tom\u00e9 e Pr\u00edncipe\u00A6Xelim ugandense (1966-1987)\u00A6Dobra de S\u00e3o Tom\u00e9 e Pr\u00edncipe\u00A6D\u00f3lar das Ilhas Marshall\u00A6Libra da Nova Zel\u00e2ndia\u00A6Tala de Samoa Ocidental\u00A6Libra de Samoa Ocidental\u00A6Lempira de Honduras\u00A6Franco Novo Metropolitano franc\u00eas\u00A6Manat do Turcomenist\u00e3o\u00A6Quet\u00e7al da Guatemala\u00A6D\u00f3lar da Nova Zel\u00e2ndia\u00A6Libra escocesa\u00A6D\u00f3lar de Barbados\u00A6D\u00f3lar da Nam\u00edbia\u00A6Franco de Madagascar\u00A6Ariary de Madagascar\u00A6Libra eg\u00edpcia\u00A6D\u00f3lar de Honduras Brit\u00e2nica\u00A6Zloti polon\u00eas (1950-1995)\u00A6Dinar novo da B\u00f3snia-Herzeg\u00f3vina\u00A6Certificados de c\u00e2mbio poloneses em d\u00f3lares\u00A6Marco b\u00f3snio-herzeg\u00f3vino convers\u00edvel\u00A6D\u00f3lar do Belize\u00A6Dinar da B\u00f3snia-Herzeg\u00f3vina\u00A6Zloti polon\u00eas\u00A6Rial iemenita\u00A6Guilder do Suriname\u00A6Coroa Forte checoslovaca\u00A6Won sul-coreano\u00A6Rublo bielo-russo\u00A6Rial Imadi iemenita\u00A6Rublo bielo-russo (1992-1994)\u00A6Coroa checoslovaca\u00A6Won Antigo sul-coreano\u00A6Hwan sul-coreano\u00A6Rublo novo bielo-russo (1994-1999)\u00A6Xelim de Somalil\u00e2ndia\u00A6Dracma Novo grego\u00A6Rupia paquistanesa\u00A6Afegane\u00A6D\u00f3lar do Zimb\u00e1bwe\u00A6Rupia de Sri Lanka\u00A6Dracma grego\u00A6Libra irlandesa\u00A6Afegane (1927-2002)\u00A6Dinar iemenita\u00A6Franco ruand\u00eas\u00A6Colon da Costa Rica\u00A6Somoni tadjique\u00A6Rublo do Tadjiquist\u00e3o\u00A6Coroa estoniana\u00A6Peseta Guineana de Guin\u00e9 Equatorial\u00A6Cupom rublo mol\u00e1vio\u00A6D\u00f3lar de Hong Kong\u00A6Coroa dinamarquesa\u00A6Leu de Mold\u00e1via\u00A6Franco de Guin\u00e9 Equatorial\u00A6Ekwele de Guin\u00e9 Equatorial\u00A6Rupia indon\u00e9sia\u00A6Dir\u00e9m dos Emirados \u00c1rabes Unidos\u00A6Won norte-coreano\u00A6Rupia Nova indon\u00e9sia\u00A6Pula botsuanesa\u00A6Cupom leu mold\u00e1vio\u00A6Rupia Java indon\u00e9sia\u00A6Won da Rep\u00fablica Popular da Cor\u00e9ia do Norte\u00A6Guilder Nica indon\u00e9sio\u00A6Vatu de Vanuatu\u00A6Dinar isl\u00e2mico\u00A6Xelim somali\u00A6Peseta de Andorra\u00A6Rublo russo (1991-1998)\u00A6Franco de Guadalupe\u00A6Franco do Djibuti\u00A6Diner de Andorra\u00A6Franco Germinal de M\u00f4naco\u00A6Franco Novo de M\u00f4naco\u00A6Unidad de Valor Constante (UVC) do Equador\u00A6Sucre equatoriano\u00A6Franco de Liechtenstein\u00A6Rublo russo\u00A6Peso filipino\u00A6Sum do Usbequist\u00e3o\u00A6Peso colombiano\u00A6Baht tailand\u00eas\u00A6Libra da Irlanda do Norte\u00A6Rupia birmanesa\u00A6Franco do Congo CFA\u00A6Kyat birman\u00eas\u00A6Peso de Papel colombiano\u00A6Coupon Som do Usbequist\u00e3o\u00A6Karbovanetz ucraniano\u00A6Rial catariano\u00A6Hryvnia ucraniano\u00A6Syli de Guin\u00e9\u00A6Yuan Renminbi chin\u00eas\u00A6Metical de Mo\u00e7ambique\u00A6Certificados de c\u00e2mbio chineses em d\u00f3lares dos EUA\u00A6Peso uruguaio\u00A6Franco de Guin\u00e9 (1960-1972)\u00A6Lira de San Marino\u00A6Jen Min Piao Yuan chin\u00eas\u00A6Escudo de Mo\u00e7ambique\u00A6Franco de Guin\u00e9\u00A6Rial Saidi de Om\u00e3\u00A6Kina da Papua-Nova Guin\u00e9\u00A6Rial de Om\u00e3\u00A6Peso uruguaio (1975-1993)\u00A6Franco UIC franc\u00eas\u00A6Rupia do But\u00e3o\u00A6Zaire zairense\u00A6Franco marroquino\u00A6Dir\u00e9m marroquino\u00A6Ngultrum do But\u00e3o\u00A6Franco-ouro franc\u00eas\u00A6Peso Fuerte uruguaio\u00A6Ringgit malaio\u00A6Zaire Novo zairense\u00A6Manat azerbaijano\u00A6Libra de G\u00e2mbia\u00A6Franco de Comores\u00A6Leone de Serra Leoa\u00A6Dalasi de G\u00e2mbia\u00A6Unidade Monet\u00e1ria Europ\u00e9ia\u00A6Libra das Bahamas\u00A6Franco dos Camar\u00f5es CFA\u00A6Unidad de Inversion (UDI) mexicana\u00A6Franco CFA BCEAEC\u00A6D\u00f3lar das Bahamas\u00A6Peso Plata mexicano (1861-1992)\u00A6Peso mexicano\u00A6Sol peruano\u00A6Coroa de Groenl\u00e2ndia\u00A6Cruzeiro brasileiro (1942-1967)\u00A6Sol Novo peruano\u00A6Peso chileno\u00A6Coroa eslovaca\u00A6Inti peruano\u00A6Cruzeiro brasileiro\u00A6Direitos Especiais de Giro\u00A6Franco Germinal franc\u00eas/Franco Poincar\u00e9\u00A6Franco franc\u00eas\u00A6Cruzado novo brasileiro\u00A6Unidades de Fomento chilenas\u00A6Escudo chileno\u00A6Real brasileiro\u00A6Condor chileno\u00A6Cruzeiro brasileiro (1990-1993)\u00A6Sperrmark alem\u00e3o\u00A6Libra do Mal\u00e1ui\u00A6Cruzado brasileiro\u00A6Cruzeiro novo brasileiro(1967-1986)\u00A6Cuacha do Mal\u00e1ui\u00A6Rublo de Transdniestria\u00A6Marco alem\u00e3o\u00A6Franco CFA de Chade\u00A6Rublo Novo de Transdniestria\u00A6Cupom rublo de Transdniestria\u00A6Rupia nepalesa\u00A6D\u00f3lar das Ilhas Cook\u00A6Iene japon\u00eas\u00A6Rupias das Ilhas Maldivas\u00A6Franco Novo CFA\u00A6Rupia das Ilhas Maldivas\u00A6D\u00f3lar do Caribe Oriental\u00A6Tolar Bons esloveno\u00A6Dinar reformado iugoslavo\u00A6Guilder de Aruba\u00A6Dinar de outubro iugoslavo\u00A6Ostmark da Alemanha Oriental\u00A6Dinar convers\u00edvel iugoslavo\u00A6Super Dinar iugoslavo\u00A6Coroa de Turcas e Caicos\u00A6Dinar iugoslavo de 1994\u00A6Dinar da Federa\u00e7\u00e3o Iugoslava\u00A6Leu Novo romeno\u00A6Dinar forte iugoslavo\u00A6Leu romeno\u00A6Tolar Bons esloveno\u00A6Coroa norueguesa\u00A6Rupia de Maur\u00edcio\u00A6Unidade de Conta Europ\u00e9ia (XBD)\u00A6Libra de Gibraltar\u00A6Dong Nacional vietnamita\u00A6Unidade de Conta Europ\u00e9ia (XBC)\u00A6Dong da Rep\u00fablica do Vietn\u00e3\u00A6Unidade Monet\u00e1ria Europ\u00e9ia\u00A6Unidade Composta Europ\u00e9ia\u00A6D\u00f3lar do Quiribati\u00A6Libra de Santa Helena\u00A6Dong Novo vietnamita";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6\u0111\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6Esc.\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YRl\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFA\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "jan",
    "fev",
    "mar",
    "abr",
    "mai",
    "jun",
    "jul",
    "ago",
    "set",
    "out",
    "nov",
    "dez",
    null,
  };

  private static final String[] months = {
    "janeiro",
    "fevereiro",
    "mar\u00e7o",
    "abril",
    "maio",
    "junho",
    "julho",
    "agosto",
    "setembro",
    "outubro",
    "novembro",
    "dezembro",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dom",
    "seg",
    "ter",
    "qua",
    "qui",
    "sex",
    "s\u00e1b",
  };

  private static final String[] weekdays = {
    null,
    "domingo",
    "segunda-feira",
    "ter\u00e7a-feira",
    "quarta-feira",
    "quinta-feira",
    "sexta-feira",
    "s\u00e1bado",
  };

  private static final String[] eras = {
    "a.C.",
    "d.C.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "Hor\u00e1rio Padr\u00e3o Oriental", "EST", "Hor\u00e1rio Padr\u00e3o Oriental"},
    {  "America/Halifax", "AST", "Hor\u00e1rio Padr\u00e3o Atl\u00e2ntico", "ADT", "Hor\u00e1rio de Ver\u00e3o Atl\u00e2ntico"},
    {  "Pacific/Honolulu", "HST", "Hor\u00e1rio Padr\u00e3o do Hava\u00ed", "HST", "Hor\u00e1rio Padr\u00e3o do Hava\u00ed"},
    {  "America/Denver", "MST", "Hor\u00e1rio Padr\u00e3o Montanha", "MDT", "Hor\u00e1rio de Ver\u00e3o Montanha"},
    {  "America/Anchorage", "AST", "Hor\u00e1rio Padr\u00e3o do Alasca", "ADT", "Hor\u00e1rio de Ver\u00e3o do Alasca"},
    {  "America/St_Johns", "CNT", "Hor\u00e1rio Padr\u00e3o de Terra Nova", "CDT", "Hor\u00e1rio de Ver\u00e3o de Terra Nova"},
    {  "Africa/Casablanca", "GMT", "Hor\u00e1rio do Meridiano de Greenwich", "GMT", "Hor\u00e1rio do Meridiano de Greenwich"},
    {  "America/Chicago", "CST", "Hor\u00e1rio Padr\u00e3o Central", "CDT", "Hor\u00e1rio de Ver\u00e3o Central"},
    {  "Asia/Shanghai", "CTT", "Hor\u00e1rio Padr\u00e3o da China", "CDT", "Hor\u00e1rio Padr\u00e3o da China"},
    {  "Asia/Tokyo", "JST", "Hor\u00e1rio Padr\u00e3o do Jap\u00e3o", "JST", "Hor\u00e1rio Padr\u00e3o do Jap\u00e3o"},
    {  "America/New_York", "EST", "Hor\u00e1rio Padr\u00e3o Oriental", "EDT", "Hor\u00e1rio de Ver\u00e3o Oriental"},
    {  "Europe/Bucharest", "EET", "Hor\u00e1rio Padr\u00e3o da Europa Oriental", "EEST", "Hor\u00e1rio de Ver\u00e3o da Europa Oriental"},
    {  "America/Los_Angeles", "PST", "Hor\u00e1rio Padr\u00e3o do Pac\u00edfico", "PDT", "Hor\u00e1rio de Ver\u00e3o do Pac\u00edfico"},
    {  "America/Phoenix", "MST", "Hor\u00e1rio Padr\u00e3o Montanha", "MST", "Hor\u00e1rio Padr\u00e3o Montanha"},
    {  "Etc/GMT", "GMT", "Hor\u00e1rio do Meridiano de Greenwich", "GMT", "Hor\u00e1rio do Meridiano de Greenwich"},
    {  "Asia/Jerusalem", "IST", "Hor\u00e1rio Padr\u00e3o de Israel", "IDT", "Hor\u00e1rio de Ver\u00e3o de Israel"},
    {  "Europe/Paris", "CET", "Hor\u00e1rio Padr\u00e3o Europa Central", "CEST", "Hor\u00e1rio de Ver\u00e3o Europa Central"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Timor Leste\u00A6Tokelau\u00A6Tadjiquist\u00e3o\u00A6Tail\u00e2ndia\u00A6Togo\u00A6Territ\u00f3rios Franceses do Sul\u00A6Guiana\u00A6Chade\u00A6Ilhas Turks e Caicos\u00A6Guin\u00e9 Bissau\u00A6Guam\u00A6Guatemala\u00A6Ge\u00f3rgia do Sul e Ilhas Sandwich do Sul\u00A6Gr\u00e9cia\u00A6Guin\u00e9 Equatorial\u00A6Guadalupe\u00A6Suazil\u00e2ndia\u00A6S\u00edria\u00A6Guin\u00e9\u00A6G\u00e2mbia\u00A6Gro\u00eanlandia\u00A6El Salvador\u00A6S\u00e3o Tom\u00e9 e Pr\u00edncipe\u00A6Gibraltar\u00A6Gana\u00A6Suriname\u00A6Guiana Francesa\u00A6Ge\u00f3rgia\u00A6Som\u00e1lia\u00A6Granada\u00A6Senegal\u00A6San Marino\u00A6Reino Unido\u00A6Serra Leoa\u00A6Gab\u00e3o\u00A6Eslov\u00e1quia\u00A6Svalbard e Jan Mayen\u00A6Eslov\u00eania\u00A6Santa Helena\u00A6Cingapura\u00A6Su\u00e9cia\u00A6Sud\u00e3o\u00A6Seychelles\u00A6Ilhas Salom\u00e3o\u00A6Ar\u00e1bia Saudita\u00A6Fran\u00e7a\u00A6Ilhas Faroe\u00A6Micron\u00e9sia, Estados Federados da\u00A6Ruanda\u00A6Ilhas Malvinas\u00A6R\u00fassia\u00A6Fiji\u00A6Finl\u00e2ndia\u00A6Rom\u00eania\u00A6Reuni\u00e3o\u00A6Eti\u00f3pia\u00A6Espanha\u00A6Eritr\u00e9ia\u00A6Saara Ocidental\u00A6Egito\u00A6Est\u00f4nia\u00A6Equador\u00A6Arg\u00e9lia\u00A6Catar\u00A6Rep\u00fablica Dominicana\u00A6Paraguai\u00A6Dominica\u00A6Palau\u00A6Dinamarca\u00A6Djibuti\u00A6Portugal\u00A6Territ\u00f3rio da Palestina\u00A6Porto Rico\u00A6Alemanha\u00A6Pitcairn\u00A6Saint Pierre e Miquelon\u00A6Pol\u00f4nia\u00A6Paquist\u00e3o\u00A6Filipinas\u00A6Papua-Nova Guin\u00e9\u00A6Polin\u00e9sia Francesa\u00A6Rep\u00fablica Tcheca\u00A6Peru\u00A6Chipre\u00A6Ilhas Natal\u00A6Cabo Verde\u00A6Panam\u00e1\u00A6Cuba\u00A6Costa Rica\u00A6Col\u00f4mbia\u00A6China\u00A6Rep\u00fablica dos Camar\u00f5es\u00A6Chile\u00A6Ilhas Cook\u00A6Costa do Marfim\u00A6Su\u00ed\u00e7a\u00A6Congo\u00A6Rep\u00fablica Centro-Africana\u00A6Congo, Rep\u00fablica Democr\u00e1tica do\u00A6Ilhas Cocos (Keeling)\u00A6Om\u00e3\u00A6Canad\u00e1\u00A6Belize\u00A6Belarus\u00A6Botsuana\u00A6Ilha Bouvet\u00A6But\u00e3o\u00A6Bahamas\u00A6Brasil\u00A6Nova Zel\u00e2ndia\u00A6Bol\u00edvia\u00A6Brunei\u00A6Bermudas\u00A6Niue\u00A6Benin\u00A6Burundi\u00A6Bareine\u00A6Nauru\u00A6Bulg\u00e1ria\u00A6Burquina Faso\u00A6Nepal\u00A6B\u00e9lgica\u00A6Noruega\u00A6Bangladesh\u00A6Barbados\u00A6Zimb\u00e1bwe\u00A6Pa\u00edses Baixos\u00A6B\u00f3snia-Herzeg\u00f3vina\u00A6Nicar\u00e1gua\u00A6Nig\u00e9ria\u00A6Ilha Norfolk\u00A6Azerbaij\u00e3o\u00A6N\u00edger\u00A6Nova Caled\u00f4nia\u00A6Aruba\u00A6Z\u00e2mbia\u00A6Nam\u00edbia\u00A6Austr\u00e1lia\u00A6\u00c1ustria\u00A6Samoa Americana\u00A6Argentina\u00A6Ant\u00e1rtida\u00A6Mo\u00e7ambique\u00A6Angola\u00A6Mal\u00e1sia\u00A6Antilhas Holandesas\u00A6M\u00e9xico\u00A6Arm\u00eania\u00A6Malawi\u00A6Alb\u00e2nia\u00A6Maldivas\u00A6\u00c1frica do Sul\u00A6Maur\u00edcio\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Maurit\u00e2nia\u00A6Ant\u00edgua e Barbuda\u00A6Martinica\u00A6Afeganist\u00e3o\u00A6Ilhas Marianas do Norte\u00A6Emirados \u00c1rabes Unidos\u00A6Macau, Regi\u00e3o Admin. Especial da China\u00A6Andorra\u00A6Mong\u00f3lia\u00A6Mianm\u00e1\u00A6Mali\u00A6Maced\u00f4nia, Rep\u00fablica da\u00A6Iugosl\u00e1via\u00A6Mayotte\u00A6Ilhas Marshall\u00A6Madagascar\u00A6Moldova, Rep\u00fablica de\u00A6M\u00f4naco\u00A6Marrocos\u00A6I\u00eamen\u00A6L\u00edbia\u00A6Let\u00f4nia\u00A6Luxemburgo\u00A6Litu\u00e2nia\u00A6Lesoto\u00A6Lib\u00e9ria\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Santa L\u00facia\u00A6L\u00edbano\u00A6Rep\u00fablica Democr\u00e1tica Popular de Lao\u00A6Casaquist\u00e3o\u00A6Ilhas Caiman\u00A6Kuwait\u00A6Cor\u00e9ia, Sul\u00A6Cor\u00e9ia, Norte\u00A6S\u00e3o Cristov\u00e3o e Nevis\u00A6Comores\u00A6Quiribati\u00A6Samoa\u00A6Camboja\u00A6Quirguist\u00e3o\u00A6Qu\u00eania\u00A6Wallis e Futuna\u00A6Jap\u00e3o\u00A6Jord\u00e2nia\u00A6Jamaica\u00A6Vanuatu\u00A6Vietn\u00e3\u00A6Ilhas Virgens dos EUA\u00A6Ilhas Virgens Brit\u00e2nicas\u00A6Venezuela\u00A6S\u00e3o Vicente e Granadinas\u00A6Vaticano\u00A6It\u00e1lia\u00A6Isl\u00e2ndia\u00A6Ir\u00e3\u00A6Iraque\u00A6Uzbequist\u00e3o\u00A6Territ\u00f3rio Brit\u00e2nico do Oceano \u00cdndico\u00A6Uruguai\u00A6\u00cdndia\u00A6Israel\u00A6Estados Unidos\u00A6Irlanda\u00A6Indon\u00e9sia\u00A6Ilhas Menores Distantes dos Estados Unidos\u00A6Uganda\u00A6Ucr\u00e2nia\u00A6Hungria\u00A6Haiti\u00A6Cro\u00e1cia\u00A6Tanz\u00e2nia\u00A6Honduras\u00A6Ilha Heard e Ilhas McDonald\u00A6Taiwan\u00A6Tuvalu\u00A6Hong Kong, Regi\u00e3o Admin. Especial da China\u00A6Trinidad e Tobago\u00A6Turquia\u00A6Tonga\u00A6Tun\u00edsia\u00A6Turcomenist\u00e3o";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6kut\u00A6mic\u00A6wa\u00A6kum\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6fan\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6bai\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpf\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6cop\u00A6yap\u00A6ach\u00A6yao\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6bua\u00A6mas\u00A6os\u00A6map\u00A6or\u00A6man\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6ng\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6kv\u00A6ku\u00A6sio\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6gil\u00A6znd\u00A6shn\u00A6fon\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6ath\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6ypk\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6tup\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6nia\u00A6moh\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6mno\u00A6wak\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6sal\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6pra\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "gwich\u02bbin\u00A6acadiano\u00A6ekajuk\u00A6xosa\u00A6sum\u00e9rio\u00A6sosso\u00A6idiomas diversos\u00A6lozi\u00A6togan\u00eas (Nyasa)\u00A6pohnpeian\u00A6minangkabau\u00A6sukuma\u00A6uolofe\u00A6mongo\u00A6kutenai\u00A6miquemaque\u00A6walloon\u00A6kumyk\u00A6zapoteca\u00A6cuxitas (outros)\u00A6lojban\u00A6dogri\u00A6volapuque\u00A6idiomas otomanos\u00A6vietnamita\u00A6rarotongano\u00A6venda\u00A6rapanui\u00A6rajastani\u00A6turco, otomano (1500-1928)\u00A6nzima\u00A6napolitano\u00A6usbeque\u00A6ugar\u00edtico\u00A6tamaxeque\u00A6ind\u00edgenas norte-americanos (outros)\u00A6n\u00e1uatle\u00A6urdu\u00A6fanti\u00A6ucraniano\u00A6eg\u00edpcio (arcaico)\u00A6uighur\u00A6fangue\u00A6nilo-saarianos (outros)\u00A6irland\u00eas, medieval (900-1200)\u00A6b\u00e1lticos (outros)\u00A6nyoro\u00A6basa\u00A6nyankole\u00A6nyamwezi\u00A6hmong\u00A6balin\u00eas\u00A6osage\u00A6bal\u00fachi\u00A6taitiano\u00A6bamileke Languages\u00A6twi\u00A6serere\u00A6tlinguite\u00A6tatar\u00A6tsonga\u00A6banda\u00A6turco\u00A6tonga (ilhas tonga)\u00A6tswana\u00A6turcomano\u00A6tigr\u00ednia\u00A6tailand\u00eas\u00A6kurukh\u00A6tadjique\u00A6Blin\u00A6telugu\u00A6kru\u00A6kashubian\u00A6t\u00e2mil\u00A6toquelauano\u00A6efique\u00A6sua\u00edli\u00A6sueco\u00A6sundan\u00eas\u00A6karachay-Balkar\u00A6soto, do sul\u00A6swati\u00A6s\u00e9rvio\u00A6alban\u00eas\u00A6mende\u00A6crioulos e p\u00eddgins (outros)\u00A6somali\u00A6Afrihili\u00A6eslov\u00eanio\u00A6grego, arcaico (at\u00e9 1453)\u00A6eslovaco\u00A6Gerbo\u00A6cingal\u00eas\u00A6servo-croata\u00A6crimean turkish; crimean tatar\u00A6afro-asi\u00e1tico (outros)\u00A6sango\u00A6northern sami\u00A6sindi\u00A6udmurt\u00A6sardo\u00A6s\u00e2nscrito\u00A6kinyarwanda\u00A6russo\u00A6mandar\u00A6romeno\u00A6rundi\u00A6rhaeto-romance\u00A6mocsa\u00A6adyghe\u00A6zunhi\u00A6kpelle\u00A6qu\u00edchua\u00A6tigr\u00e9\u00A6songai\u00A6crioulos e p\u00eddgin, portugu\u00eas (outros)\u00A6sogdien\u00A6adangme\u00A6kosraean\u00A6hitita\u00A6crioulos e p\u00eddgin, franc\u00eas (outros)\u00A6crioulos e p\u00eddgin, ingl\u00eas (outros)\u00A6himachali\u00A6concani\u00A6hiligaynon\u00A6g\u00f3tico\u00A6gorontalo\u00A6gondi\u00A6dinka\u00A6idiomas n\u00fabios\u00A6portugu\u00eas\u00A6pashto (pushto)\u00A6friulano\u00A6fen\u00edcio\u00A6alem\u00e3o, arcaico alto (aprox.750-1050)\u00A6copta\u00A6yapese\u00A6acoli\u00A6iao\u00A6filipinos (outros)\u00A6polon\u00eas\u00A6achinese\u00A6p\u00e1li\u00A6panjabi\u00A6Buginese\u00A6Iban\u00A6Buriat\u00A6massai\u00A6ossetic\u00A6austron\u00e9sio\u00A6oriya\u00A6mandinga\u00A6makasar\u00A6oromo\u00A6maithili\u00A6ojibwa\u00A6magahi\u00A6madur\u00eas\u00A6occit\u00e2nico (ap\u00f3s 1500); proven\u00e7al\u00A6soto, setentrional\u00A6bataque\u00A6erzya\u00A6dogrib\u00A6nianja; chicheua; cheua\u00A6maia\u00A6navajo\u00A6quimbundo\u00A6ndebele, south\u00A6alem\u00e3o, medieval alto (aprox.1050-1500)\u00A6noruegu\u00eas\u00A6nynorsk noruegu\u00eas\u00A6holand\u00eas\u00A6dongo\u00A6nepali\u00A6ndebele, north\u00A6chamic languages\u00A6t\u00e9tum\u00A6bokm\u00e5l noruegu\u00eas\u00A6nauruano\u00A6tereno\u00A6timne\u00A6birman\u00eas\u00A6lezghian\u00A6malt\u00eas\u00A6persa arcaico (aprox. 600-400 a.C.)\u00A6malaio\u00A6marata\u00A6franc\u00eas, arcaico (842-aprox.1400)\u00A6mold\u00e1vio\u00A6franc\u00eas, medieval (aprox.1400-1600)\u00A6mongol\u00A6judaico-ar\u00e1bico\u00A6malaiala\u00A6maced\u00f4nio\u00A6maori\u00A6marshall\u00eas\u00A6malgaxe\u00A6marwari\u00A6braj\u00A6slave\u00A6let\u00e3o\u00A6luba-catanga\u00A6delaware\u00A6lituano\u00A6laosiano\u00A6lingala\u00A6limburgish\u00A6ewondo\u00A6luganda\u00A6luxemburgu\u00eas\u00A6latim\u00A6judaico-persa\u00A6votic\u00A6sino-tibetanos (outros)\u00A6quirguiz\u00A6c\u00f3rnico\u00A6komi\u00A6curdo\u00A6idiomas sioux\u00A6kashmiri\u00A6can\u00fari\u00A6Awadhi\u00A6coreano\u00A6canar\u00eas\u00A6cmer\u00A6groenland\u00eas\u00A6cazaque\u00A6romani\u00A6Kuanyama\u00A6sidamo\u00A6quicuio\u00A6congol\u00eas\u00A6norse, old\u00A6georgiano\u00A6creek\u00A6romances (outros)\u00A6nogai\u00A6idiomas munda\u00A6idiomas m\u00faltiplos\u00A6gilbert\u00eas\u00A6zande\u00A6shan\u00A6fom\u00A6kalmyk\u00A6idiomas australianos\u00A6khotanese\u00A6japon\u00eas\u00A6khoisan (other)\u00A6palauano\u00A6cheiene\u00A6tai (outros)\u00A6inuktitut\u00A6papiamento\u00A6italiano\u00A6linguages de sinais\u00A6island\u00eas\u00A6khasi\u00A6cheroqui\u00A6pampanga\u00A6p\u00e1lavi\u00A6chipewyan\u00A6ido\u00A6choctaw\u00A6chinook jargon\u00A6mari\u00A6tuvinian\u00A6banto\u00A6pangasin\u00e3\u00A6Inupiaq\u00A6chuukese\u00A6sichuan yi\u00A6havaiano\u00A6lamba\u00A6ibo\u00A6chagatai\u00A6irland\u00eas, arcaico (at\u00e9 900)\u00A6papuanos (outros)\u00A6interlingue\u00A6indon\u00e9sio\u00A6lahnda\u00A6dayak\u00A6chibcha\u00A6interl\u00edngua\u00A6ladino\u00A6herero\u00A6haida\u00A6dargwa\u00A6arm\u00eanio\u00A6idiomas atabascanos\u00A6h\u00fangaro\u00A6haitiano\u00A6dacota\u00A6croata\u00A6hiri motu\u00A6hindi\u00A6di\u00fala\u00A6hebraico\u00A6asturiano\u00A6hau\u00e7\u00e1\u00A6sorbian languages\u00A6manx\u00A6guzerate\u00A6sem\u00edticos (outros)\u00A6selkup\u00A6idiomas iroqueses\u00A6guarani\u00A6galego\u00A6arauaqui\u00A6geez\u00A6artificiais (outros)\u00A6ga\u00e9lico escoc\u00eas\u00A6iraniano\u00A6irland\u00eas\u00A6arapaho\u00A6araucano\u00A6fris\u00e3o\u00A6siksika\u00A6germ\u00e2nicos (outros)\u00A6idiomas i\u00fapique\u00A6aramaico\u00A6franc\u00eas\u00A6fero\u00eas\u00A6c\u00e9lticos (outros)\u00A6fijiano\u00A6finland\u00eas\u00A6fula\u00A6tuvaluano\u00A6cebuano\u00A6persa\u00A6basco\u00A6escoc\u00eas\u00A6estoniano\u00A6espanhol\u00A6esperanto\u00A6ingl\u00eas\u00A6grego\u00A6altaicos (outros)\u00A6niueano\u00A6idiomas tupi\u00A6eve\u00A6tumbuka\u00A6mossi\u00A6dzonga\u00A6niger - kordofanian (other)\u00A6lushai\u00A6ugro-fin\u00eas (outros)\u00A6divehi\u00A6nias\u00A6mohawk\u00A6lunda\u00A6idiomas apache\u00A6luiseno\u00A6hupa\u00A6bini\u00A6alem\u00e3o\u00A6luba-Lulua\u00A6bikol\u00A6washo\u00A6indeterminado\u00A6waray\u00A6dinamarqu\u00eas\u00A6holand\u00eas, medieval (aprox. 1050-1350)\u00A6walamo\u00A6manobo languages\u00A6wakashan languages\u00A6santali\u00A6gal\u00eas\u00A6sasak\u00A6kabardian\u00A6chuvash\u00A6eslavo eclesi\u00e1stico\u00A6manipuri\u00A6tcheco\u00A6aramaico samaritano\u00A6cree\u00A6salishan languages\u00A6duala\u00A6c\u00f3rsico\u00A6ind\u00edgenas sul-americanos (outros)\u00A6manchu\u00A6iacuto\u00A6kawi\u00A6inguche\u00A6gbaia\u00A6sandawe\u00A6chamorro\u00A6indo-europeus (outros)\u00A6bhojpuri\u00A6ingl\u00eas, medieval (1100-1500)\u00A6karen\u00A6\u00edndicos (outros)\u00A6chechene\u00A6gayo\u00A6catal\u00e3o\u00A6umbundu\u00A6sir\u00edaco\u00A6kamba\u00A6tsimshian\u00A6ingl\u00eas, arcaico (aprox. 450-1100)\u00A6kachin\u00A6caucasianos (outros)\u00A6kabyle\u00A6kara-Kalpak\u00A6b\u00f3snio\u00A6caribe\u00A6bret\u00e3o\u00A6tibetano\u00A6bengali\u00A6bambara\u00A6ga\u00A6ind\u00edgenas centro-americanos (outros)\u00A6bislam\u00e1\u00A6biari\u00A6b\u00falgaro\u00A6bielo-russo\u00A6caddo\u00A6bashkir\u00A6zulu\u00A6zenaga\u00A6proven\u00e7al, arcaico (at\u00e9 1500)\u00A6upper sorbian\u00A6azerbaijano\u00A6aimara\u00A6avaric\u00A6assam\u00eas\u00A6Lower Sorbian\u00A6\u00e1rabe\u00A6ilocano\u00A6elamite\u00A6chin\u00eas\u00A6aragon\u00eas\u00A6idiomas pr\u00e1crito\u00A6am\u00e1rico\u00A6newari\u00A6Akan\u00A6zhuang\u00A6afric\u00e2ner\u00A6av\u00e9stico\u00A6abkhazian\u00A6afar\u00A6ioruba\u00A6idiomas algonquianos\u00A6ale\u00fate\u00A6mon-khmer (other)\u00A6i\u00eddiche\u00A6drav\u00eddicos (outros)\u00A6berbere\u00A6alto alem\u00e3o; baixo sax\u00e3o\u00A6bemba\u00A6beja\u00A6tok pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final String variantsKeys = "REVISED";

  private static final String variantsValues = "Revisado";

  private static final Hashtable variants;
  static
  {
    variants = new Hashtable();
    Enumeration keys = new StringTokenizer(variantsKeys, "\u00A6");
    Enumeration values = new StringTokenizer(variantsValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         variants.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "shortDateFormat", "dd-MM-yyyy" },
    { "mediumDateFormat", "d/MMM/yyyy" },
    { "longDateFormat", "d' de 'MMMM' de 'yyyy" },
    { "fullDateFormat", "EEEE, d' de 'MMMM' de 'yyyy" },
    { "fullTimeFormat", "HH'H'mm'm'ss's' z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
