/* LocaleInformation_hr.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML hr.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_hr extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "sij",
    "vel",
    "o\u017eu",
    "tra",
    "svi",
    "lip",
    "srp",
    "kol",
    "ruj",
    "lis",
    "stu",
    "pro",
    null,
  };

  private static final String[] months = {
    "sije\u010danj",
    "velja\u010da",
    "o\u017eujak",
    "travanj",
    "svibanj",
    "lipanj",
    "srpanj",
    "kolovoz",
    "rujan",
    "listopad",
    "studeni",
    "prosinac",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "ned",
    "pon",
    "uto",
    "sri",
    "\u010det",
    "pet",
    "sub",
  };

  private static final String[] weekdays = {
    null,
    "nedjelja",
    "ponedjeljak",
    "utorak",
    "srijeda",
    "\u010detvrtak",
    "petak",
    "subota",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Isto\u010dni Timor");
        put("TK", "Tokelau");
        put("TJ", "Tad\u017eikistan");
        put("TH", "Tajland");
        put("TG", "Togo");
        put("TF", "Francuske Ju\u017ene Teritorije");
        put("GY", "Gvajana");
        put("TD", "\u010cad");
        put("TC", "Turkski i Kaikos Otoci");
        put("GW", "Gvineja Bisau");
        put("GU", "Guam");
        put("GT", "Gvatemala");
        put("GS", "Ju\u017ena Gruzija i Ju\u017eni Sendvi\u010d Otoci");
        put("GR", "Gr\u010dka");
        put("GQ", "Ekvatorska Gvineja");
        put("GP", "Guadeloupe");
        put("SZ", "Svazi");
        put("SY", "Sirija");
        put("GN", "Gvineja");
        put("GM", "Gambija");
        put("GL", "Greenland");
        put("SV", "El Salvador");
        put("ST", "Sveti Toma i Prinsipe");
        put("GI", "Gibraltar");
        put("GH", "Gana");
        put("SR", "Surinam");
        put("GF", "Francuska Gvajana");
        put("SP", "Serbia");
        put("GE", "Gruzija");
        put("SO", "Somalija");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Ujedinjena Kraljevina");
        put("SL", "Sijera Leone");
        put("GA", "Gabon");
        put("SK", "Slova\u010dka");
        put("SJ", "Svalbard i Jan Mayen");
        put("SI", "Slovenija");
        put("SH", "Sveta Helena");
        put("SG", "Singapur");
        put("SE", "\u0160vedska");
        put("SD", "Sudan");
        put("SC", "Sej\u0161eli");
        put("SB", "Salamunovi Otoci");
        put("SA", "Saudijska Arabija");
        put("FR", "Francuska");
        put("FO", "Farski Otoci");
        put("FM", "Mikronezija, Federalne Dr\u017eave");
        put("RW", "Ruanda");
        put("FK", "Falklandski Otoci");
        put("RU", "Ruska Federacija");
        put("FJ", "Fid\u017ei");
        put("FI", "Finska");
        put("RO", "Rumunjska");
        put("RE", "Reunion");
        put("ET", "Etiopija");
        put("ES", "\u0160panjolska");
        put("ER", "Eritreja");
        put("EH", "Zapadna Sahara");
        put("EG", "Egipat");
        put("EE", "Estonija");
        put("EC", "Ekvador");
        put("DZ", "Al\u017eir");
        put("QA", "Katar");
        put("DO", "Dominikanska Republika");
        put("PY", "Paragvaj");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "Danska");
        put("DJ", "D\u017eibuti");
        put("PT", "Portugal");
        put("PS", "Palestinska Teritoija");
        put("PR", "Portoriko");
        put("DE", "Njema\u010dka");
        put("PN", "Pitcairn");
        put("PM", "Sveti Petar i Miguel");
        put("PL", "Poljska");
        put("PK", "Pakistan");
        put("PH", "Filipini");
        put("PG", "Papua Nova Gvineja");
        put("PF", "Francuska Polinezija");
        put("CZ", "\u010ce\u0161ka Republika");
        put("PE", "Peru");
        put("CY", "Cipar");
        put("CX", "Bo\u017ei\u0107ni Otoci");
        put("CV", "Zeleni Rt");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kostarika");
        put("CO", "Kolumbija");
        put("CN", "Kina");
        put("CM", "Kamerun");
        put("CL", "\u010cile");
        put("CK", "Kukovi Otoci");
        put("CI", "Obala Bjelokosti");
        put("CH", "\u0160vicarska");
        put("CG", "Kongo");
        put("CF", "Srednjoafri\u010dka Republika");
        put("CD", "Kongo, Demokratska Republika");
        put("CC", "Kokos (Keeling) Otoci");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Bjelorusija");
        put("BW", "Bocvana");
        put("BV", "Otok Bouvet");
        put("BT", "Butan");
        put("BS", "Bahami");
        put("BR", "Brazil");
        put("NZ", "Novi Zeland");
        put("BO", "Bolivija");
        put("BN", "Brunei Darussalam");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrein");
        put("NR", "Nauru");
        put("BG", "Bugarska");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgija");
        put("NO", "Norve\u0161ka");
        put("BD", "Banglade\u0161");
        put("BB", "Barbados");
        put("ZW", "Zimbabve");
        put("NL", "Nizozemska");
        put("BA", "Bosna i Hercegovina");
        put("NI", "Nikaragva");
        put("NG", "Nigerija");
        put("NF", "Norfol\u0161ki Otoci");
        put("AZ", "Azerbajd\u017ean");
        put("NE", "Niger");
        put("NC", "Nova Kaledonija");
        put("AW", "Aruba");
        put("ZM", "Zambija");
        put("NA", "Namibija");
        put("AU", "Australija");
        put("AT", "Austrija");
        put("AS", "Ameri\u010dka Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktik");
        put("MZ", "Mozambik");
        put("AO", "Angola");
        put("MY", "Malezija");
        put("AN", "Nizozemski Antili");
        put("MX", "Meksiko");
        put("AM", "Armenija");
        put("MW", "Malavi");
        put("AL", "Albanija");
        put("MV", "Maldivi");
        put("ZA", "Ju\u017ena Afrika");
        put("MU", "Mauricijus");
        put("MT", "Malta");
        put("AI", "Anguila");
        put("MS", "Montserat");
        put("MR", "Mauritanija");
        put("AG", "Antigua i Barbuda");
        put("MQ", "Martinik");
        put("AF", "Afganistan");
        put("MP", "Sjeverni Marianski Otoci");
        put("AE", "Ujedinjeni Arapski Emirati");
        put("MO", "Makao S.A.R. Kine");
        put("AD", "Andora");
        put("MN", "Mongolija");
        put("MM", "Mijanma");
        put("ML", "Mali");
        put("MK", "Makedonija, Republika");
        put("YU", "Jugoslavija");
        put("YT", "Majote");
        put("MH", "Mar\u0161alovi Otoci");
        put("MG", "Madagaskar");
        put("MD", "Moldavija, Republika");
        put("MC", "Monako");
        put("MA", "Maroko");
        put("YE", "Jemen");
        put("LY", "Libijska Arapska D\u017eamahirija");
        put("LV", "Latvija");
        put("LU", "Luksemburg");
        put("LT", "Litva");
        put("LS", "Lesoto");
        put("LR", "Liberija");
        put("LK", "\u0160ri Lanka");
        put("LI", "Lihten\u0161tajn");
        put("LC", "Sveta Lucija");
        put("LB", "Libanon");
        put("LA", "Laoska Narodna Demokratska Republika");
        put("KZ", "Kazakstan");
        put("KY", "Kajmanski Otoci");
        put("KW", "Kuvajt");
        put("KR", "Koreja, Ju\u017ena");
        put("KP", "Koreja, Sjeverna");
        put("KN", "Sveti Kristofor i Nevis");
        put("KM", "Komori");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambod\u017ea");
        put("KG", "Kirgistan");
        put("KE", "Kenija");
        put("WF", "Wallis i Futuna");
        put("JP", "Japan");
        put("JO", "Jordan");
        put("JM", "Jamajka");
        put("VU", "Vanuatu");
        put("VN", "Vijetnam");
        put("VI", "U.S. Djevi\u010danski Otoci");
        put("VG", "Britanski Djevi\u010danski Otoci");
        put("VE", "Venezuela");
        put("VC", "Sveti Vincent i Grenadini");
        put("VA", "Sveta Stolica (Dr\u017eava Vatikanskog Grada)");
        put("IT", "Italija");
        put("IS", "Island");
        put("IR", "Iran, Islamska Republika");
        put("IQ", "Irak");
        put("UZ", "Uzbekistan");
        put("IO", "Britanski Teritorij Indijskog Oceana");
        put("UY", "Urugvaj");
        put("IN", "Indija");
        put("IL", "Izrael");
        put("US", "Sjedinjene Dr\u017eave");
        put("IE", "Irska");
        put("ID", "Indonezija");
        put("UM", "Sjedinjene Dr\u017eave Manji Vanjski Otoci");
        put("UG", "Uganda");
        put("UA", "Ukrajina");
        put("HU", "Ma\u0111arska");
        put("HT", "Haiti");
        put("HR", "Hrvatska");
        put("TZ", "Tanzanija");
        put("HN", "Honduras");
        put("HM", "Heard Otok i McDonald Otoci");
        put("TW", "Tajvan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R. Kine");
        put("TT", "Trinidad i Tobago");
        put("TR", "Turska");
        put("TO", "Tonga");
        put("TN", "Tunis");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "shortDateFormat", "yyyy.MM.dd" },
    { "mediumDateFormat", "yyyy.MM.dd" },
    { "longDateFormat", "yyyy. MMMM dd" },
    { "fullDateFormat", "yyyy. MMMM dd" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
