/* LocaleInformation_fa.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML fa.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_fa extends ListResourceBundle
{
  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "\u062a\u06cc\u0645\u0648\u0631 \u0634\u0631\u0642\u06cc");
        put("TK", "\u062a\u0648\u06a9\u0644\u0627\u0626\u0648");
        put("TJ", "\u062a\u0627\u062c\u06cc\u06a9\u0633\u062a\u0627\u0646");
        put("TH", "\u062a\u0627\u06cc\u0644\u0646\u062f");
        put("TG", "\u062a\u0648\u06af\u0648");
        put("TF", "\u0645\u0633\u062a\u0639\u0645\u0631\u0647\u200c\u0647\u0627\u06cc \u062c\u0646\u0648\u0628\u06cc \u0641\u0631\u0627\u0646\u0633\u0647");
        put("GY", "\u06af\u0648\u06cc\u0627\u0646");
        put("TD", "\u0686\u0627\u062f");
        put("TC", "\u062c\u0632\u0627\u06cc\u0631 \u062a\u0631\u06a9 \u0648 \u06a9\u0627\u06cc\u06a9\u0648\u0633");
        put("GW", "\u06af\u06cc\u0646\u0647\u200c\u06cc \u0628\u06cc\u0633\u0627\u0626\u0648");
        put("GU", "\u06af\u0648\u0627\u0645");
        put("GT", "\u06af\u0648\u0627\u062a\u0645\u0627\u0644\u0627");
        put("GS", "\u062c\u0648\u0631\u062c\u06cc\u0627\u06cc \u062c\u0646\u0648\u0628\u06cc \u0648 \u062c\u0632\u0627\u06cc\u0631 \u0633\u0627\u0646\u062f\u0648\u06cc\u0686 \u062c\u0646\u0648\u0628\u06cc");
        put("GR", "\u06cc\u0648\u0646\u0627\u0646");
        put("GQ", "\u06af\u06cc\u0646\u0647\u200c\u06cc \u0627\u0633\u062a\u0648\u0627\u06cc\u06cc");
        put("GP", "\u06af\u0648\u0627\u062f\u0644\u0648\u067e");
        put("SZ", "\u0633\u0648\u0627\u0632\u06cc\u0644\u0646\u062f");
        put("SY", "\u0633\u0648\u0631\u06cc\u0647");
        put("GN", "\u06af\u06cc\u0646\u0647");
        put("GM", "\u06af\u0627\u0645\u0628\u06cc\u0627");
        put("GL", "\u06af\u0631\u0648\u0626\u0646\u0644\u0646\u062f");
        put("SV", "\u0627\u0644\u0633\u0627\u0644\u0648\u0627\u062f\u0648\u0631");
        put("ST", "\u0633\u0627\u0626\u0648 \u062a\u0648\u0645\u0647 \u0648 \u067e\u0631\u06cc\u0646\u0633\u06cc\u067e\u0647");
        put("GI", "\u06af\u06cc\u0628\u0631\u0627\u0644\u062a\u0627\u0631");
        put("GH", "\u063a\u0646\u0627");
        put("SR", "\u0633\u0648\u0631\u06cc\u0646\u0627\u0645");
        put("GF", "\u06af\u0648\u06cc\u0627\u0646 \u0641\u0631\u0627\u0646\u0633\u0647");
        put("SP", "\u0635\u0631\u0628\u0633\u062a\u0627\u0646");
        put("GE", "\u06af\u0631\u062c\u0633\u062a\u0627\u0646");
        put("SO", "\u0633\u0648\u0645\u0627\u0644\u06cc");
        put("GD", "\u06af\u0631\u0627\u0646\u0627\u062f\u0627");
        put("SN", "\u0633\u0646\u06af\u0627\u0644");
        put("SM", "\u0633\u0627\u0646 \u0645\u0627\u0631\u06cc\u0646\u0648");
        put("GB", "\u0627\u0646\u06af\u0644\u0633\u062a\u0627\u0646");
        put("SL", "\u0633\u06cc\u0631\u0627\u0644\u0626\u0648\u0646");
        put("GA", "\u06af\u0627\u0628\u0648\u0646");
        put("SK", "\u0627\u0633\u0644\u0648\u0627\u06a9\u06cc");
        put("SJ", "\u0627\u0633\u0648\u0627\u0644\u0628\u0627\u0631\u062f \u0648 \u062c\u0627\u0646 \u0645\u0627\u06cc\u0646");
        put("SI", "\u0627\u0633\u0644\u0648\u0648\u0646\u06cc");
        put("SH", "\u0633\u0646\u062a \u0647\u0644\u0646");
        put("SG", "\u0633\u0646\u06af\u0627\u067e\u0648\u0631");
        put("SE", "\u0633\u0648\u0626\u062f");
        put("SD", "\u0633\u0648\u062f\u0627\u0646");
        put("SC", "\u0633\u06cc\u0634\u0644");
        put("SB", "\u062c\u0632\u0627\u06cc\u0631 \u0633\u0644\u06cc\u0645\u0627\u0646");
        put("SA", "\u0639\u0631\u0628\u0633\u062a\u0627\u0646 \u0633\u0639\u0648\u062f\u06cc");
        put("FR", "\u0641\u0631\u0627\u0646\u0633\u0647");
        put("FO", "\u062c\u0632\u0627\u06cc\u0631 \u0641\u0627\u0631\u0648");
        put("FM", "\u0645\u06cc\u06a9\u0631\u0648\u0646\u0632\u06cc");
        put("RW", "\u0631\u0648\u0627\u0646\u062f\u0627");
        put("FK", "\u062c\u0632\u0627\u06cc\u0631 \u0641\u0627\u0644\u06a9\u0644\u0646\u062f");
        put("RU", "\u0631\u0648\u0633\u06cc\u0647");
        put("FJ", "\u0641\u06cc\u062c\u06cc");
        put("FI", "\u0641\u0646\u0644\u0627\u0646\u062f");
        put("RO", "\u0631\u0648\u0645\u0627\u0646\u06cc");
        put("RE", "\u0631\u06cc\u0648\u0646\u06cc\u0648\u0646");
        put("ET", "\u0627\u062a\u06cc\u0648\u067e\u06cc");
        put("ES", "\u0627\u0633\u067e\u0627\u0646\u06cc\u0627");
        put("ER", "\u0627\u0631\u06cc\u062a\u0631\u0647");
        put("EH", "\u0635\u062d\u0631\u0627\u06cc \u063a\u0631\u0628\u06cc");
        put("EG", "\u0645\u0635\u0631");
        put("EE", "\u0627\u0633\u062a\u0648\u0646\u06cc");
        put("EC", "\u0627\u06a9\u0648\u0627\u062f\u0631");
        put("DZ", "\u0627\u0644\u062c\u0632\u0627\u06cc\u0631");
        put("QA", "\u0642\u0637\u0631");
        put("DO", "\u062c\u0645\u0647\u0648\u0631\u06cc \u062f\u0648\u0645\u06cc\u0646\u06cc\u06a9\u0646");
        put("PY", "\u067e\u0627\u0631\u0627\u06af\u0648\u0626\u0647");
        put("DM", "\u062f\u0648\u0645\u06cc\u0646\u06cc\u06a9\u0627");
        put("PW", "\u067e\u0627\u0644\u0627\u0626\u0648");
        put("DK", "\u062f\u0627\u0646\u0645\u0627\u0631\u06a9");
        put("DJ", "\u062c\u06cc\u0628\u0648\u062a\u06cc");
        put("PT", "\u067e\u0631\u062a\u063a\u0627\u0644");
        put("PR", "\u067e\u0648\u0631\u062a\u0648 \u0631\u06cc\u06a9\u0648");
        put("DE", "\u0622\u0644\u0645\u0627\u0646");
        put("PN", "\u067e\u06cc\u062a\u06a9\u0627\u06cc\u0631\u0646");
        put("PM", "\u0633\u0646\u062a \u067e\u06cc\u0631 \u0648 \u0645\u06cc\u06a9\u0644\u0648\u0646");
        put("PL", "\u0644\u0647\u0633\u062a\u0627\u0646");
        put("PK", "\u067e\u0627\u06a9\u0633\u062a\u0627\u0646");
        put("PH", "\u0641\u06cc\u0644\u06cc\u067e\u06cc\u0646");
        put("PG", "\u067e\u0627\u067e\u0648\u0627 \u06af\u06cc\u0646\u0647\u200c\u06cc \u0646\u0648");
        put("PF", "\u067e\u0644\u06cc\u200c\u0646\u0632\u06cc \u0641\u0631\u0627\u0646\u0633\u0647");
        put("CZ", "\u062c\u0645\u0647\u0648\u0631\u06cc \u0686\u06a9");
        put("PE", "\u067e\u0631\u0648");
        put("CY", "\u0642\u0628\u0631\u0633");
        put("CX", "\u062c\u0632\u06cc\u0631\u0647\u200c\u06cc \u06a9\u0631\u06cc\u0633\u0645\u0633");
        put("CV", "\u06a9\u06cc\u067e \u0648\u0631\u062f");
        put("PA", "\u067e\u0627\u0646\u0627\u0645\u0627");
        put("CU", "\u06a9\u0648\u0628\u0627");
        put("CR", "\u06a9\u0627\u0633\u062a\u0627\u0631\u06cc\u06a9\u0627");
        put("CO", "\u06a9\u0644\u0645\u0628\u06cc\u0627");
        put("CN", "\u0686\u06cc\u0646");
        put("CM", "\u06a9\u0627\u0645\u0631\u0648\u0646");
        put("CL", "\u0634\u06cc\u0644\u06cc");
        put("CK", "\u062c\u0632\u0627\u06cc\u0631 \u06a9\u0648\u06a9");
        put("CI", "\u0633\u0627\u062d\u0644 \u0639\u0627\u062c");
        put("CH", "\u0633\u0648\u0626\u06cc\u0633");
        put("CG", "\u06a9\u0648\u0646\u06af\u0648");
        put("CF", "\u062c\u0645\u0647\u0648\u0631\u06cc \u0627\u0641\u0631\u06cc\u0642\u0627\u06cc \u0645\u0631\u06a9\u0632\u06cc");
        put("CD", "\u062c\u0645\u0647\u0648\u0631\u06cc \u062f\u0645\u0648\u06a9\u0631\u0627\u062a\u06cc\u06a9 \u06a9\u0646\u06af\u0648");
        put("CC", "\u062c\u0632\u0627\u06cc\u0631 \u06a9\u0648\u06a9\u0648\u0633");
        put("OM", "\u0639\u0645\u0627\u0646");
        put("CA", "\u06a9\u0627\u0646\u0627\u062f\u0627");
        put("BZ", "\u0628\u0644\u06cc\u0632");
        put("BY", "\u0628\u06cc\u0644\u0648\u0631\u0648\u0633\u06cc");
        put("BW", "\u0628\u0648\u062a\u0633\u0648\u0627\u0646\u0627");
        put("BV", "\u062c\u0632\u06cc\u0631\u0647\u200c\u06cc \u0628\u0648\u0648\u062a");
        put("BT", "\u0628\u0648\u062a\u0627\u0646");
        put("BS", "\u0628\u0627\u0647\u0627\u0645\u0627");
        put("BR", "\u0628\u0631\u0632\u06cc\u0644");
        put("NZ", "\u0632\u0644\u0627\u0646\u062f \u0646\u0648");
        put("BO", "\u0628\u0648\u0644\u06cc\u0648\u06cc");
        put("BN", "\u0628\u0631\u0648\u0646\u0626\u06cc");
        put("BM", "\u0628\u0631\u0645\u0648\u062f\u0627");
        put("NU", "\u0646\u06cc\u0648\u0626\u0647");
        put("BJ", "\u0628\u0646\u06cc\u0646");
        put("BI", "\u0628\u0648\u0631\u0648\u0646\u062f\u06cc");
        put("BH", "\u0628\u062d\u0631\u06cc\u0646");
        put("NR", "\u0646\u0627\u0626\u0648\u0631\u0648");
        put("BG", "\u0628\u0644\u063a\u0627\u0631\u0633\u062a\u0627\u0646");
        put("BF", "\u0628\u0648\u0631\u06a9\u06cc\u0646\u0627\u0641\u0627\u0633\u0648");
        put("NP", "\u0646\u067e\u0627\u0644");
        put("BE", "\u0628\u0644\u0698\u06cc\u06a9");
        put("NO", "\u0646\u0631\u0648\u0698");
        put("BD", "\u0628\u0646\u06af\u0644\u0627\u062f\u0634");
        put("BB", "\u0628\u0627\u0631\u0628\u0627\u062f\u0648\u0633");
        put("ZW", "\u0632\u06cc\u0645\u0628\u0627\u0628\u0648\u0647");
        put("NL", "\u0647\u0644\u0646\u062f");
        put("BA", "\u0628\u0648\u0633\u0646\u06cc \u0648 \u0647\u0631\u0632\u06af\u0648\u06cc\u0646");
        put("NI", "\u0646\u06cc\u06a9\u0627\u0631\u0627\u06af\u0648\u0626\u0647");
        put("NG", "\u0646\u06cc\u062c\u0631\u06cc\u0647");
        put("NF", "\u062c\u0632\u06cc\u0631\u0647\u200c\u06cc \u0646\u0648\u0631\u0641\u0648\u0644\u06a9");
        put("AZ", "\u0622\u0630\u0631\u0628\u0627\u06cc\u062c\u0627\u0646");
        put("NE", "\u0646\u06cc\u062c\u0631");
        put("NC", "\u06a9\u0627\u0644\u062f\u0648\u0646\u06cc\u0627\u06cc \u062c\u062f\u06cc\u062f");
        put("AW", "\u0622\u0631\u0648\u0628\u0627");
        put("ZM", "\u0632\u0627\u0645\u0628\u06cc\u0627");
        put("NA", "\u0646\u0627\u0645\u06cc\u0628\u06cc\u0627");
        put("AU", "\u0627\u0633\u062a\u0631\u0627\u0644\u06cc\u0627");
        put("AT", "\u0627\u062a\u0631\u06cc\u0634");
        put("AS", "\u0633\u0627\u0645\u0648\u0627\u06cc \u0627\u0645\u0631\u06cc\u06a9\u0627");
        put("AR", "\u0622\u0631\u0698\u0627\u0646\u062a\u06cc\u0646");
        put("AQ", "\u062c\u0646\u0648\u0628\u06af\u0627\u0646");
        put("MZ", "\u0645\u0648\u0632\u0627\u0645\u0628\u06cc\u06a9");
        put("AO", "\u0622\u0646\u06af\u0648\u0644\u0627");
        put("MY", "\u0645\u0627\u0644\u0632\u06cc");
        put("AN", "\u0622\u0646\u062a\u06cc\u0644 \u0647\u0644\u0646\u062f");
        put("MX", "\u0645\u06a9\u0632\u06cc\u06a9");
        put("AM", "\u0627\u0631\u0645\u0646\u0633\u062a\u0627\u0646");
        put("MW", "\u0645\u0627\u0644\u0627\u0648\u06cc");
        put("AL", "\u0622\u0644\u0628\u0627\u0646\u06cc");
        put("MV", "\u0645\u0627\u0644\u062f\u06cc\u0648");
        put("ZA", "\u0627\u0641\u0631\u06cc\u0642\u0627\u06cc \u062c\u0646\u0648\u0628\u06cc");
        put("MU", "\u0645\u0648\u0631\u06cc\u062a\u06cc\u0648\u0633");
        put("MT", "\u0645\u0627\u0644\u062a");
        put("AI", "\u0622\u0646\u06af\u06cc\u0644");
        put("MS", "\u0645\u0648\u0646\u062a\u200c\u0633\u0631\u0627\u062a");
        put("MR", "\u0645\u0648\u0631\u06cc\u062a\u0627\u0646\u06cc");
        put("AG", "\u0622\u0646\u062a\u06cc\u06af\u0648\u0627 \u0648 \u0628\u0627\u0631\u0628\u0648\u062f\u0627");
        put("MQ", "\u0645\u0627\u0631\u062a\u06cc\u0646\u06cc\u06a9");
        put("AF", "\u0627\u0641\u063a\u0627\u0646\u0633\u062a\u0627\u0646");
        put("MP", "\u062c\u0632\u0627\u06cc\u0631 \u0645\u0627\u0631\u06cc\u0627\u0646\u0627\u06cc \u0634\u0645\u0627\u0644\u06cc");
        put("AE", "\u0627\u0645\u0627\u0631\u0627\u062a \u0645\u062a\u062d\u062f\u0647\u200c\u06cc \u0639\u0631\u0628\u06cc");
        put("MO", "\u0645\u0627\u06a9\u0627\u0626\u0648");
        put("AD", "\u0622\u0646\u062f\u0648\u0631\u0627");
        put("MN", "\u0645\u063a\u0648\u0644\u0633\u062a\u0627\u0646");
        put("MM", "\u0645\u06cc\u0627\u0646\u0645\u0627\u0631");
        put("ML", "\u0645\u0627\u0644\u06cc");
        put("MK", "\u0645\u0642\u062f\u0648\u0646\u06cc\u0647");
        put("YU", "\u06cc\u0648\u06af\u0633\u0644\u0627\u0648\u06cc");
        put("YT", "\u0645\u0627\u06cc\u0648\u062a");
        put("MH", "\u062c\u0632\u0627\u06cc\u0631 \u0645\u0627\u0631\u0634\u0627\u0644");
        put("MG", "\u0645\u0627\u062f\u0627\u06af\u0627\u0633\u06a9\u0627\u0631");
        put("MD", "\u0645\u0648\u0644\u062f\u0648\u0648\u0627");
        put("MC", "\u0645\u0648\u0646\u0627\u06a9\u0648");
        put("MA", "\u0645\u0631\u0627\u06a9\u0634");
        put("YE", "\u06cc\u0645\u0646");
        put("LY", "\u0644\u06cc\u0628\u06cc");
        put("LV", "\u0644\u062a\u0648\u0646\u06cc");
        put("LU", "\u0644\u0648\u06a9\u0632\u0627\u0645\u0628\u0648\u0631\u06af");
        put("LT", "\u0644\u06cc\u062a\u0648\u0627\u0646\u06cc");
        put("LS", "\u0644\u0633\u0648\u062a\u0648");
        put("LR", "\u0644\u06cc\u0628\u0631\u06cc\u0627");
        put("LK", "\u0633\u0631\u06cc\u200c\u0644\u0627\u0646\u06a9\u0627");
        put("LI", "\u0644\u06cc\u062e\u062a\u0646\u200c\u0627\u0634\u062a\u0627\u06cc\u0646");
        put("LC", "\u0633\u0646\u062a \u0644\u0648\u0633\u06cc\u0627");
        put("LB", "\u0644\u0628\u0646\u0627\u0646");
        put("LA", "\u0644\u0627\u0626\u0648\u0633");
        put("KZ", "\u0642\u0632\u0627\u0642\u0633\u062a\u0627\u0646");
        put("KY", "\u062c\u0632\u0627\u06cc\u0631 \u06a9\u0650\u06cc\u0645\u0646");
        put("KW", "\u06a9\u0648\u06cc\u062a");
        put("KR", "\u06a9\u0631\u0647\u200c\u06cc \u062c\u0646\u0648\u0628\u06cc");
        put("KP", "\u06a9\u0631\u0647\u200c\u06cc \u0634\u0645\u0627\u0644\u06cc");
        put("KN", "\u0633\u0646\u062a \u06a9\u06cc\u062a\u0633 \u0648 \u0646\u0648\u06cc\u0633");
        put("KM", "\u06a9\u0648\u0645\u0648\u0631\u0648");
        put("KI", "\u06a9\u06cc\u0631\u06cc\u0628\u0627\u062a\u06cc");
        put("WS", "\u0633\u0627\u0645\u0648\u0627");
        put("KH", "\u06a9\u0627\u0645\u0628\u0648\u062c");
        put("KG", "\u0642\u0631\u0642\u06cc\u0632\u0633\u062a\u0627\u0646");
        put("KE", "\u06a9\u0646\u06cc\u0627");
        put("WF", "\u0648\u0627\u0644\u06cc\u0633 \u0648 \u0641\u06cc\u0648\u062a\u0648\u0646\u0627");
        put("JP", "\u0698\u0627\u067e\u0646");
        put("JO", "\u0627\u0631\u062f\u0646");
        put("JM", "\u062c\u0627\u0645\u0627\u0626\u06cc\u06a9\u0627");
        put("VU", "\u0648\u0627\u0646\u0648\u0627\u062a\u0648");
        put("VN", "\u0648\u06cc\u062a\u0646\u0627\u0645");
        put("VI", "\u062c\u0632\u0627\u06cc\u0631 \u0648\u06cc\u0631\u062c\u06cc\u0646 \u0627\u06cc\u0627\u0644\u0627\u062a \u0645\u062a\u062d\u062f\u0647");
        put("VG", "\u062c\u0632\u0627\u06cc\u0631 \u0648\u06cc\u0631\u062c\u06cc\u0646 \u0627\u0646\u06af\u0644\u0633\u062a\u0627\u0646");
        put("VE", "\u0648\u0646\u0632\u0648\u0626\u0644\u0627");
        put("VC", "\u0633\u0646\u062a \u0648\u06cc\u0646\u0633\u0646\u062a \u0648 \u06af\u0631\u0646\u0627\u062f\u06cc\u0646");
        put("VA", "\u0648\u0627\u062a\u06cc\u06a9\u0627\u0646");
        put("IT", "\u0627\u06cc\u062a\u0627\u0644\u06cc\u0627");
        put("IS", "\u0627\u06cc\u0633\u0644\u0646\u062f");
        put("IR", "\u0627\u06cc\u0631\u0627\u0646");
        put("IQ", "\u0639\u0631\u0627\u0642");
        put("UZ", "\u0627\u0632\u0628\u06a9\u0633\u062a\u0627\u0646");
        put("IO", "\u0645\u0633\u062a\u0639\u0645\u0631\u0647\u200c\u0647\u0627\u06cc \u0627\u0646\u06af\u0644\u0633\u062a\u0627\u0646 \u062f\u0631 \u0627\u0642\u06cc\u0627\u0646\u0648\u0633 \u0647\u0646\u062f");
        put("UY", "\u0627\u0648\u0631\u0648\u06af\u0648\u0626\u0647");
        put("IN", "\u0647\u0646\u062f");
        put("IL", "\u0627\u0633\u0631\u0627\u0626\u06cc\u0644");
        put("US", "\u0627\u06cc\u0627\u0644\u0627\u062a \u0645\u062a\u062d\u062f\u0647\u200c\u06cc \u0627\u0645\u0631\u06cc\u06a9\u0627");
        put("IE", "\u0627\u06cc\u0631\u0644\u0646\u062f");
        put("ID", "\u0627\u0646\u062f\u0648\u0646\u0632\u06cc");
        put("UM", "\u062c\u0632\u0627\u06cc\u0631 \u06a9\u0648\u0686\u06a9 \u062f\u0648\u0631\u0627\u0641\u062a\u0627\u062f\u0647\u200c\u06cc \u0627\u06cc\u0627\u0644\u0627\u062a \u0645\u062a\u062d\u062f\u0647");
        put("UG", "\u0627\u0648\u06af\u0627\u0646\u062f\u0627");
        put("UA", "\u0627\u0648\u06a9\u0631\u0627\u06cc\u0646");
        put("HU", "\u0645\u062c\u0627\u0631\u0633\u062a\u0627\u0646");
        put("HT", "\u0647\u0627\u06cc\u06cc\u062a\u06cc");
        put("HR", "\u06a9\u0631\u0648\u0627\u0633\u06cc");
        put("TZ", "\u062a\u0627\u0646\u0632\u0627\u0646\u06cc\u0627");
        put("HN", "\u0647\u0646\u062f\u0648\u0631\u0627\u0633");
        put("HM", "\u062c\u0632\u06cc\u0631\u0647\u200c\u06cc \u0647\u0631\u062f \u0648 \u062c\u0632\u0627\u06cc\u0631 \u0645\u06a9\u200c\u062f\u0648\u0646\u0627\u0644\u062f");
        put("TW", "\u062a\u0627\u06cc\u0648\u0627\u0646");
        put("TV", "\u062a\u0648\u0648\u0627\u0644\u0648");
        put("HK", "\u0647\u0646\u06af\u200c\u06a9\u0646\u06af");
        put("TT", "\u062a\u0631\u06cc\u0646\u06cc\u062f\u0627\u062f \u0648 \u062a\u0648\u0628\u0627\u06af\u0648");
        put("TR", "\u062a\u0631\u06a9\u06cc\u0647");
        put("TO", "\u062a\u0648\u0646\u06af\u0627");
        put("TN", "\u062a\u0648\u0646\u0633");
        put("TM", "\u062a\u0631\u06a9\u0645\u0646\u0633\u062a\u0627\u0646");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
