/* LocaleInformation_nl.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_nl extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "Jordaanse dinar\u00A6Boliviaanse mvdol\u00A6Goud\u00A6Faer\u00f6erse kroon\u00A6Libanees pond\u00A6Euro\u00A6Vietnamese dong\u00A6Tanzaniaanse shilling\u00A6Boliviaanse peso\u00A6Cambodjaanse riel\u00A6Aziatische monetaire eenheid\u00A6Boliviano (1863-1962)\u00A6Cambodjaanse oude riel\u00A6Zambiaans pond\u00A6Australisch pond\u00A6CFA-franc BEAC\u00A6Maltees pond\u00A6Ghanese hergewaardeerde cedi\u00A6Zambiaanse kwacha\u00A6Aziatische dinar-rekeneenheid\u00A6Ghanees pond\u00A6Boliviano\u00A6Ghanese oude cedi\u00A6Maltese lire\u00A6Australische dollar\u00A6Amerikaanse dollar (zelfde dag)\u00A6Italiaanse lire\u00A6Amerikaanse dollar (volgende dag)\u00A6Ghanese cedi\u00A6Singaporese dollar\u00A6Panamese balboa\u00A6Laotiaanse kip\u00A6Kirgizische som\u00A6Zwitserse franc\u00A6Oostenrijkse schilling\u00A6Amerikaanse dollar\u00A6Ethiopische dollar\u00A6Bruneise dollar\u00A6Jamaicaans pond\u00A6Ethiopische birr\u00A6Algerijnse franc germinal\u00A6Algerijnse nieuwe franc\u00A6Algerijnse dinar\u00A6Paraguayaanse guarani\u00A6Libisch pond\u00A6Jamaicaanse dollar\u00A6IJslandse kroon\u00A6Spaanse peseta\u00A6Bermuda-pond\u00A6Libische dinar\u00A6Libische Britse Militaire Autoriteit-lire\u00A6Bermuda-dollar\u00A6Nederlandse gulden\u00A6Mauritaanse ouguiya\u00A6Iraanse rial\u00A6Zweedse kroon\u00A6Eritrese nakfa\u00A6Kenyaanse shilling\u00A6Centraal-Afrikaanse CFA-franc\u00A6Argentijnse peso\u00A6Argentijnse peso (1983-1985)\u00A6Argentijnse peso moneda nacional\u00A6Nieuwe Taiwanese dollar\u00A6Soedanees pond\u00A6Georgische lari\u00A6Georgische kupon larit\u00A6Martinikaanse franc\u00A6Falklandeilands pond\u00A6Argentijnse austral\u00A6Soedanese dinar\u00A6Iraakse dinar\u00A6Tuvaluaanse dollar\u00A6Seychelse rupee\u00A6Letse roebel\u00A6Fijisch pond\u00A6Letse lats\u00A6Congolese za\u00efre\u00A6Congolese franc\u00A6Congolese franc congolais\u00A6Fijische dollar\u00A6Nicaraguaanse  c\u00f3rdoba oro\u00A6Macause pataca\u00A6Nicaraguaanse gouden c\u00f3rdoba\u00A6Nicaraguaanse c\u00f3rdoba\u00A6COMECON transferable roebel\u00A6Finse markka (1860-1962)\u00A6Finse markka\u00A6Salomonseilandse dollar\u00A6Luxemburgse frank\u00A6Trinidad en Tobago-oude dollar\u00A6Angolese escudo\u00A6Angolese kwanza reajustado (1995-1999)\u00A6Mongoolse tugrik\u00A6Hongaarse forint\u00A6Burundese franc\u00A6Angolese nieuwe kwanza (1990-2000)\u00A6Angolese kwanza (1977-1990)\u00A6Trinidad en Tobago-dollar\u00A6Swazische lilangeni\u00A6Nieuw-Hebridiaanse CFP-franc\u00A6Brits pond sterling\u00A6Saoedische souvereine rial\u00A6Saoedische rial\u00A6Litouwse talonas\u00A6Indiase rupee\u00A6Portugese escudo\u00A6Angolese kwanza\u00A6Portugese conto\u00A6Litouwse litas\u00A6Kazachstaanse tenge\u00A6Kazachstaanse roebel\u00A6Britse Maagdeneilandse dollar\u00A6Nigeriaans pond\u00A6Myanmarese dollarwisselcertificaten\u00A6Nigeriaanse naira\u00A6Ha\u00eftiaanse gourde\u00A6Syrisch pond\u00A6Palestijns pond\u00A6Bahreinse dinar\u00A6Myanmarese kyat\u00A6Nederlands-Antilliaanse gulden\u00A6Tsjechische koruna\u00A6Isle of Man pond sterling\u00A6Bulgaarse levwisselcertificaten\u00A6Lesothaanse loti\u00A6Gabonese CFA-franc\u00A6Bulgaarse lev (1879-1952)\u00A6Bulgaarse nieuwe lev\u00A6Bulgaarse socialistische lev\u00A6Canadese dollar\u00A6Bulgaarse harde lev\u00A6Turkse lire\u00A6Caymaneilandse dollar\u00A6Cyprisch pond\u00A6Isra\u00eblische nieuwe shekel\u00A6Guyaanse dollar\u00A6Armeense dram\u00A6Isra\u00eblisch pond\u00A6Malinese franc\u00A6Isra\u00eblische shekel\u00A6Venezolaanse bolivar\u00A6Albanese dollarwisselcertificaten\u00A6Liberiaanse dollar\u00A6Albanese lek valute\u00A6Kroatische kuna\u00A6R\u00e9unionse franc\u00A6Kroatische dinar\u00A6Albanese lek\u00A6Jersey pond sterling\u00A6Albanese lek (1946-1961)\u00A6Macedonische denar (1992-1993)\u00A6Noord-Vietnamese viet minh piastre dong viet\u00A6Noord-Vietnamese nieuwe dong\u00A6Macedonische denar\u00A6Noord-Vietnamese piastre dong viet\u00A6Timorese pataca\u00A6CFP-franc\u00A6Belgische frank (financieel)\u00A6Guinee-Bissause peso\u00A6Koeweitse dinar\u00A6Portuguees-Guinese mil reis\u00A6Belgische frank\u00A6Timorese escudo\u00A6Belgische frank (convertibel)\u00A6Portuguees-Guinese escudo\u00A6Salvadoraanse col\u00f3n\u00A6Cura\u00e7ao-gulden\u00A6Bengalese taka\u00A6Tongaans pond sterling\u00A6Tongaanse pa\u02bbanga\u00A6CFA-franc BCEAO\u00A6Sovjet-roebel\u00A6Nieuwe sovjet-roebel\u00A6Nieuw-Caledonische franc germinal\u00A6Kaapverdische escudo\u00A6Franse antillen CFA-franc\u00A6Zuid-Afrikaanse rand\u00A6Dominicaanse peso\u00A6Cubaanse wisselcertificaten\u00A6Zuid-Afrikaans pond\u00A6Zuid-Afrikaanse rand (financieel)\u00A6Tunesische dinar\u00A6Cubaanse peso\u00A6Frans-Guyaanse franc guiana\u00A6Oegandese shilling\u00A6Ceylon-rupee\u00A6Affars en Issas-franc\u00A6Vaticaanse lire\u00A6Santomese escudo\u00A6Oegandese shilling (1966-1987)\u00A6Santomese dobra\u00A6Marshalleilandse dollar\u00A6Nieuw-Zeelands pond\u00A6West-Samoaanse tala\u00A6West-Samoaans pond\u00A6Hodurese lempira\u00A6Franse metropolische nieuwe franc\u00A6Turkmeense manat\u00A6Guatemalteekse quetzal\u00A6Nieuw-Zeelandse dollar\u00A6Schotse pond\u00A6Barbadaanse dollar\u00A6Namibische dollar\u00A6Malagassische franc\u00A6Malagassische ariary\u00A6Egyptisch pond\u00A6Brits-Hondurese dollar\u00A6Poolse zloty (1950-1995)\u00A6Bosnische nieuwe dinar\u00A6Poolse Amerikaanse-dollarwisselcertificaten\u00A6Bosnische convertibele mark\u00A6Belizaanse dollar\u00A6Bosnische dinar\u00A6Poolse zloty\u00A6Jemenitische rial\u00A6Surinaamse gulden\u00A6Tsjechoslowaakse harde koruna\u00A6Zuid-Koreaanse won\u00A6Wit-Russische roebel\u00A6Jemenitische imadi rial\u00A6Wit-Russische roebel (1992-1994)\u00A6Tsjechoslowaakse koruna\u00A6Zuid-Koreaanse oude won\u00A6Zuid-Koreaanse hwan\u00A6Wit-Russische nieuwe roebel (1994-1999)\u00A6Somalilandse shilling\u00A6Griekse nieuwe drachme\u00A6Pakistaanse rupee\u00A6Afghani\u00A6Zimbabwaanse dollar\u00A6Srilankaanse rupee\u00A6Griekse drachme\u00A6Iers pond\u00A6Afghani (1927-2002)\u00A6Jemenitische dinar\u00A6Rwandese franc\u00A6Costaricaanse col\u00f3n\u00A6Tadzjikistaanse somoni\u00A6Tadzjikistaanse roebel\u00A6Estlandse kroon\u00A6Equatoriaal-Guinese peseta puineana\u00A6Moldavische roebel-cupon\u00A6Hongkongse dollar\u00A6Deense kroon\u00A6Moldavische leu\u00A6Equatoriaal-Guinese franco\u00A6Equatoriaal-Guinese ekwele guineana\u00A6Indonesische rupiah\u00A6Verenigde Arabische Emiraten-dirham\u00A6Noord-Koreaanse won\u00A6Indonesische nieuwe rupiah\u00A6Botswaanse pula\u00A6Monegaskische leu cupon\u00A6Indonesische Java-rupiah\u00A6Noord-Koreaanse Volksrepubliek-won\u00A6Indonesische nica-gulden\u00A6Vanuatuaanse vatu\u00A6Islamitische dinar\u00A6Somalische shilling\u00A6Andorrese peseta\u00A6Russische roebel (1991-1998)\u00A6Guadeloupse franc\u00A6Djiboutiaanse franc\u00A6Andorrese diner\u00A6Monegaskische franc germinal\u00A6Monegaskische nieuwe franc\u00A6Ecuadoraanse unidad de valor constante (UVC)\u00A6Ecuadoraanse sucre\u00A6Liechtensteinse frank\u00A6Russische roebel\u00A6Filipijnse peso\u00A6Oezbekistaanse sum\u00A6Colombiaanse peso\u00A6Thaise baht\u00A6Noord-Iers pond\u00A6Birmese rupee\u00A6Congolese CFA-franc\u00A6Birmese kyat\u00A6Colombiaanse papieren peso\u00A6Oezbekistaanse coupon-som\u00A6Oekra\u00efense karbovanetz\u00A6Qatarese rial\u00A6Oekra\u00efense hryvnia\u00A6Guinese syli\u00A6Chinese yuan renminbi\u00A6Mozambikaanse metical\u00A6Chinese Amerikaanse-dollarwisselcertificaten\u00A6Uruguayaanse peso uruguayo\u00A6Guinese franc (1960-1972)\u00A6Sanmarinese lire\u00A6Chinese jen min piao yuan\u00A6Mozambikaanse escudo\u00A6Guinese franc\u00A6Omaanse rial saidi\u00A6Papuaanse kina\u00A6Omaanse rial\u00A6Uruguayaanse peso (1975-1993)\u00A6Franse UIC-franc\u00A6Bhutaanse rupee\u00A6Za\u00efrese za\u00efre\u00A6Marokkaanse franc\u00A6Marokkaanse dirham\u00A6Bhutaanse ngultrum\u00A6Franse gouden franc\u00A6Uruguayaanse peso fuerte\u00A6Maleisische ringgit\u00A6Za\u00efrese nieuwe za\u00efre\u00A6Azerbeidzjaanse manat\u00A6Gambiaans pond\u00A6Comorese franc\u00A6Sierraleoonse leone\u00A6Gambiaanse dalasi\u00A6European Currency Unit\u00A6Bahamaans pond\u00A6Kameroense CFA-franc\u00A6Mexicaanse unidad de inversion (UDI)\u00A6CFA-franc BCEAEC\u00A6Bahamaanse dollar\u00A6Mexicaanse zilveren peso (1861-1992)\u00A6Mexicaanse peso\u00A6Peruaanse sol\u00A6Groenlandse kroon\u00A6Braziliaanse cruzeiro (1942-1967)\u00A6Peruaanse nieuwe sol\u00A6Chileense peso\u00A6Slowaakse koruna\u00A6Peruaanse inti\u00A6Braziliaanse cruzeiro\u00A6Special Drawing Rights\u00A6Franse franc germinal/franc poincare\u00A6Franse franc\u00A6Braziliaanse cruzado novo\u00A6Chileense unidades de fomento\u00A6Chileense escudo\u00A6Braziliaanse real\u00A6Chileense condor\u00A6Braziliaanse cruzeiro (1990-1993)\u00A6Duitse sperrmark\u00A6Malawisch pond\u00A6Braziliaanse cruzado\u00A6Braziliaanse cruzeiro novo (1967-1986)\u00A6Malawische kwacha\u00A6Trans-Djnestrische roebel\u00A6Duitse mark\u00A6Tsjaadse CFA-franc\u00A6Trans-Djnestrische nieuwe roebel\u00A6Trans-Djnestrische roebel-kupon\u00A6Nepalese rupee\u00A6Cookeilandse dollar\u00A6Japanse yen\u00A6Maldivische rufiyaa\u00A6CFA nieuwe franc\u00A6Maldivische rupee\u00A6Oost-Caribische dollar\u00A6Sloveense tolar\u00A6Joegoslavische  hervormde dinar\u00A6Arubaanse gulden\u00A6Joegoslavische oktober-dinar\u00A6Oost-Duitse ostmark\u00A6Joegoslavische convertibele dinar\u00A6Joegoslavische noviy-dinar\u00A6Turks en Caicos-kroon\u00A6Joegoslavische 1994-dinar\u00A6Joegoslavische federale dinar\u00A6Roemeense nieuwe leu\u00A6Joegoslavische harde dinar\u00A6Roemeense leu\u00A6Sloveense tolar bons\u00A6Noorse kroon\u00A6Mauritiaanse rupee\u00A6Europese rekeneenheid (XBD)\u00A6Gibraltarees pond\u00A6Vietnamese nationale dong\u00A6Europese rekeneenheid (XBC)\u00A6Vietnamese Republiek-dong\u00A6Europese monetaire eenheid\u00A6Europese samengestelde eenheid\u00A6Kiribatische dollar\u00A6Sint-Heleense pond\u00A6Vietnamese nieuwe dong";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LL\u00A6VND\u00A6T Sh\u00A6BOP\u00A6CR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6Bs\u00A6GHO\u00A6Lm\u00A6$A\u00A6USS\u00A6USN\u00A6GHC\u00A6S$\u00A6PAB\u00A6LAK\u00A6som\u00A6SwF\u00A6ATS\u00A6US$\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6LYB\u00A6Ber$\u00A6fl\u00A6UM\u00A6RI\u00A6SKr\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6Ft\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SRl\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6CZK\u00A6IMP\u00A6BGX\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6Can$\u00A6lev\u00A6TL\u00A6KYD\u00A6\u00a3C\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6T$\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6XNF\u00A6R\u00A6RD$\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6XMF\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Af\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6AFA\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HK$\u00A6DKr\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6Y\u00A6Mt\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GF\u00A6OMS\u00A6PGK\u00A6RO\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6Nu\u00A6XFO\u00A6UYF\u00A6RM\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6CF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6Ch$\u00A6Sk\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6leu\u00A6SIB\u00A6NKr\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mrt",
    "apr",
    "mei",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januari",
    "februari",
    "maart",
    "april",
    "mei",
    "juni",
    "juli",
    "augustus",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "zo",
    "ma",
    "di",
    "wo",
    "do",
    "vr",
    "za",
  };

  private static final String[] weekdays = {
    null,
    "zondag",
    "maandag",
    "dinsdag",
    "woensdag",
    "donderdag",
    "vrijdag",
    "zaterdag",
  };

  private static final String[] eras = {
    "v. Chr.",
    "n. Chr.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "Eastern-standaardtijd", "EST", "Eastern-standaardtijd"},
    {  "America/Halifax", "AST", "Atlantic-standaardtijd", "ADT", "Atlantic-zomertijd"},
    {  "Pacific/Honolulu", "HST", "Hawa\u00ef-standaardtijd", "HST", "Hawa\u00ef-standaardtijd"},
    {  "America/Denver", "MST", "Mountain-standaardtijd", "MDT", "Mountain-zomertijd"},
    {  "America/Anchorage", "AST", "Alaska-standaardtijd", "ADT", "Alaska-zomertijd"},
    {  "America/St_Johns", "CNT", "Newfoundland-standaardtijd", "CDT", "Newfoundland-zomertijd"},
    {  "Africa/Casablanca", "GMT", "Greenwich Mean Time", "GMT", "Greenwich Mean Time"},
    {  "America/Chicago", "CST", "Central-standaardtijd", "CDT", "Central-zomertijd"},
    {  "Asia/Shanghai", "CTT", "Chinese standaardtijd", "CDT", "Chinese standaardtijd"},
    {  "Asia/Tokyo", "JST", "Japanse standaardtijd", "JST", "Japanse standaardtijd"},
    {  "America/New_York", "EST", "Eastern-standaardtijd", "EDT", "Eastern-zomertijd"},
    {  "Europe/Bucharest", "EET", "Oost-Europese standaardtijd", "EEST", "Oost-Europese zomertijd"},
    {  "America/Los_Angeles", "PST", "Pacific-standaardtijd", "PDT", "Pacific-zomertijd"},
    {  "America/Phoenix", "MST", "Mountain-standaardtijd", "MST", "Mountain-standaardtijd"},
    {  "Etc/GMT", "GMT", "Greenwich Mean Time", "GMT", "Greenwich Mean Time"},
    {  "Asia/Jerusalem", "IST", "Isra\u00eblische standaardtijd", "IDT", "Isra\u00eblische zomertijd"},
    {  "Europe/Paris", "CET", "Midden-Europese standaardtijd", "CEST", "Midden-Europese zomertijd"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Oost-Timor\u00A6Tokelau\u00A6Tadzjikistan\u00A6Thailand\u00A6Togo\u00A6Franse Gebieden in de zuidelijke Indische Oceaan\u00A6Guyana\u00A6Tsjaad\u00A6Turks- en Caicoseilanden\u00A6Guinee-Bissau\u00A6Guam\u00A6Guatemala\u00A6Zuid-Georgi\u00eb en Zuidelijke Sandwicheilanden\u00A6Griekenland\u00A6Equatoriaal-Guinea\u00A6Guadeloupe\u00A6Swaziland\u00A6Syri\u00eb\u00A6Guinea\u00A6Gambia\u00A6Groenland\u00A6El Salvador\u00A6Sao Tom\u00e9 en Principe\u00A6Gibraltar\u00A6Ghana\u00A6Suriname\u00A6Frans-Guyana\u00A6Georgi\u00eb\u00A6Somali\u00eb\u00A6Grenada\u00A6Senegal\u00A6San Marino\u00A6Verenigd Koninkrijk\u00A6Sierra Leone\u00A6Gabon\u00A6Slowakije\u00A6Svalbard en Jan Mayen\u00A6Sloveni\u00eb\u00A6Saint Helena\u00A6Singapore\u00A6Zweden\u00A6Soedan\u00A6Seychellen\u00A6Salomonseilanden\u00A6Saoedi-Arabi\u00eb\u00A6Frankrijk\u00A6Faer\u00f6er\u00A6Micronesia, Federale Staten van\u00A6Rwanda\u00A6Falklandeilanden\u00A6Russische Federatie\u00A6Fiji\u00A6Finland\u00A6Roemeni\u00eb\u00A6R\u00e9union\u00A6Ethiopi\u00eb\u00A6Spanje\u00A6Eritrea\u00A6West-Sahara\u00A6Egypte\u00A6Estland\u00A6Ecuador\u00A6Algerije\u00A6Qatar\u00A6Dominicaanse Republiek\u00A6Paraguay\u00A6Dominica\u00A6Palau\u00A6Denemarken\u00A6Djibouti\u00A6Portugal\u00A6Palestijns Gebied\u00A6Puerto Rico\u00A6Duitsland\u00A6Pitcairn\u00A6Saint Pierre en Miquelon\u00A6Polen\u00A6Pakistan\u00A6Filipijnen\u00A6Papoea-Nieuw-Guinea\u00A6Frans-Polynesi\u00eb\u00A6Tsjechi\u00eb\u00A6Peru\u00A6Cyprus\u00A6Christmaseiland\u00A6Kaapverdi\u00eb\u00A6Panama\u00A6Cuba\u00A6Costa Rica\u00A6Colombia\u00A6China\u00A6Kameroen\u00A6Chili\u00A6Cookeilanden\u00A6Ivoorkust\u00A6Zwitserland\u00A6Congo\u00A6Centraal-Afrikaanse Republiek\u00A6Congo, Democratische Republiek\u00A6Cocoseilanden\u00A6Oman\u00A6Canada\u00A6Belize\u00A6Wit-Rusland\u00A6Botswana\u00A6Bouveteiland\u00A6Bhutan\u00A6Bahama\u2019s\u00A6Brazili\u00eb\u00A6Nieuw-Zeeland\u00A6Bolivia\u00A6Brunei Darussalam\u00A6Bermuda\u00A6Niue\u00A6Benin\u00A6Burundi\u00A6Bahrein\u00A6Nauru\u00A6Bulgarije\u00A6Burkina Faso\u00A6Nepal\u00A6Belgi\u00eb\u00A6Noorwegen\u00A6Bangladesh\u00A6Barbados\u00A6Zimbabwe\u00A6Nederland\u00A6Bosni\u00eb Herzegovina\u00A6Nicaragua\u00A6Nigeria\u00A6Norfolkeiland\u00A6Azerbeidzjan\u00A6Niger\u00A6Nieuw-Caledoni\u00eb\u00A6Aruba\u00A6Zambia\u00A6Namibi\u00eb\u00A6Australi\u00eb\u00A6Oostenrijk\u00A6Amerikaans Samoa\u00A6Argentini\u00eb\u00A6Antarctica\u00A6Mozambique\u00A6Angola\u00A6Maleisi\u00eb\u00A6Nederlandse Antillen\u00A6Mexico\u00A6Armeni\u00eb\u00A6Malawi\u00A6Albani\u00eb\u00A6Maldiven\u00A6Zuid-Afrika\u00A6Mauritius\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Mauritani\u00eb\u00A6Antigua en Barbuda\u00A6Martinique\u00A6Afghanistan\u00A6Noordelijke Marianeneilanden\u00A6Verenigde Arabische Emiraten\u00A6Macao S.A.R. van China\u00A6Andorra\u00A6Mongoli\u00eb\u00A6Myanmar\u00A6Mali\u00A6Macedoni\u00eb, Republiek\u00A6Joegoslavi\u00eb\u00A6Mayotte\u00A6Marshalleilanden\u00A6Madagaskar\u00A6Republiek Moldavi\u00eb\u00A6Monaco\u00A6Marokko\u00A6Jemen\u00A6Libi\u00eb\u00A6Letland\u00A6Luxemburg\u00A6Litouwen\u00A6Lesotho\u00A6Liberia\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Saint Lucia\u00A6Libanon\u00A6Laos\u00A6Kazachstan\u00A6Caymaneilanden\u00A6Koeweit\u00A6Zuid-Korea\u00A6Noord-Korea\u00A6Saint Kitts en Nevis\u00A6Comoren\u00A6Kiribati\u00A6Samoa\u00A6Cambodja\u00A6Kirgizstan\u00A6Kenia\u00A6Wallis en Futuna\u00A6Japan\u00A6Jordani\u00eb\u00A6Jamaica\u00A6Vanuatu\u00A6Vietnam\u00A6Amerikaanse Maagdeneilanden\u00A6Britse Maagdeneilanden\u00A6Venezuela\u00A6Saint Vincent en de Grenadines\u00A6Vaticaanstad\u00A6Itali\u00eb\u00A6IJsland\u00A6Iran\u00A6Irak\u00A6Oezbekistan\u00A6Brits Territorium in de Indische Oceaan\u00A6Uruguay\u00A6India\u00A6Isra\u00ebl\u00A6Verenigde Staten\u00A6Ierland\u00A6Indonesi\u00eb\u00A6Amerikaanse ondergeschikte afgelegen eilanden\u00A6Oeganda\u00A6Oekra\u00efne\u00A6Hongarije\u00A6Ha\u00efti\u00A6Kroati\u00eb\u00A6Tanzania\u00A6Honduras\u00A6Heardeiland en McDonaldeiland\u00A6Taiwan\u00A6Tuvalu\u00A6Hongkong S.A.R. van China\u00A6Trinidad en Tobago\u00A6Turkije\u00A6Tonga\u00A6Tunesi\u00eb\u00A6Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6ijo\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6kut\u00A6mic\u00A6wa\u00A6kum\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6vai\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6fan\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6bai\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tl\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sn\u00A6sm\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6tiv\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpf\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6snk\u00A6cop\u00A6yap\u00A6ach\u00A6yao\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6sms\u00A6bua\u00A6mas\u00A6smn\u00A6os\u00A6map\u00A6or\u00A6man\u00A6smj\u00A6smi\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6sma\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6ng\u00A6sla\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6kv\u00A6ku\u00A6sio\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6jv\u00A6gil\u00A6znd\u00A6shn\u00A6fon\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6ath\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6ypk\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6tup\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6nia\u00A6moh\u00A6luo\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6mno\u00A6wak\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6sal\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6pra\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "Gwich\u02bbin\u00A6Akkadisch\u00A6Ekajuk\u00A6Ijo\u00A6Xhosa\u00A6Soemerisch\u00A6Soesoe\u00A6Diverse talen\u00A6Lozi\u00A6Tonga (Nyasa)\u00A6Pohnpeiaans\u00A6Minangkabau\u00A6Sukuma\u00A6Wolof\u00A6Mongo\u00A6Kutenai\u00A6Micmac\u00A6Wallonisch\u00A6Kumyk\u00A6Zapotec\u00A6Koesjitisch (overige)\u00A6Lojban\u00A6Dogri\u00A6Volap\u00fck\u00A6Otomi-talen\u00A6Vietnamees\u00A6Vai\u00A6Rarotongan\u00A6Venda\u00A6Rapanui\u00A6Rajasthani\u00A6Turks, Ottomaans (1500-1928)\u00A6Nzima\u00A6Napolitaans\u00A6Oezbeeks\u00A6Oegaritisch\u00A6Tamashek\u00A6Noord-Amerikaans Indiaans (overige)\u00A6Nahuatl\u00A6Urdu\u00A6Fanti\u00A6Oekra\u00efens\u00A6Egyptisch (klassiek)\u00A6Uighur\u00A6Fang\u00A6Nilo-Saharam (overige)\u00A6Iers, middel- (900-1200)\u00A6Baltisch (overige)\u00A6Nyoro\u00A6Basa\u00A6Nyankole\u00A6Nyamwezi\u00A6Hmong\u00A6Balinees\u00A6Osage\u00A6Baloetsji\u00A6Tahitisch\u00A6Bamileke-talen\u00A6Twi\u00A6Serer\u00A6Tlingit\u00A6Tataars\u00A6Tsonga\u00A6Banda\u00A6Turks\u00A6Tonga (Tonga-eilanden)\u00A6Tswana\u00A6Tagalog\u00A6Turkmeens\u00A6Tigrinya\u00A6Thai\u00A6Kurukh\u00A6Tadzjik\u00A6Blin\u00A6Teloegoe\u00A6Kru\u00A6Kasjoebisch\u00A6Tamil\u00A6Tokelau\u00A6Efik\u00A6Swahili\u00A6Zweeds\u00A6Sundanees\u00A6Karachay-Balkar\u00A6Sotho, zuid\u00A6Swati\u00A6Servisch\u00A6Albanees\u00A6Mende\u00A6Creools en Pidgin (overige)\u00A6Somalisch\u00A6Afrihili\u00A6Shona\u00A6Samoaans\u00A6Sloveens\u00A6Grieks, klassiek (tot 1453)\u00A6Slowaaks\u00A6Gerbo\u00A6Singalees\u00A6Servokroatisch\u00A6Krim-Turks; Krim-Tataars\u00A6Afro-aziatisch (overige)\u00A6Sango\u00A6Noord-Samisch\u00A6Sindhi\u00A6Udmurt\u00A6Sardinisch\u00A6Sanskrit\u00A6Kinyarwanda\u00A6Russisch\u00A6Mandar\u00A6Roemeens\u00A6Rundi\u00A6Retoromaans\u00A6Moksha\u00A6Tiv\u00A6Adyghe\u00A6Zuni\u00A6Kpelle\u00A6Quechua\u00A6Tigre\u00A6Songhai\u00A6Creools en Pidgin, op Portugees gebaseerd (overige)\u00A6Sogdisch\u00A6Adangme\u00A6Kosreaans\u00A6Hittite\u00A6Creools en Pidgin, op Frans gebaseerd (overige)\u00A6Creools en Pidgin, op Engels gebaseerd (overige)\u00A6Himachali\u00A6Konkani\u00A6Hiligaynon\u00A6Gothisch\u00A6Gorontalo\u00A6Gondi\u00A6Dinka\u00A6Nubische talen\u00A6Portugees\u00A6Pashto\u00A6Friulisch\u00A6Foenicisch\u00A6Duits, oudhoog- (ca. 750-1050)\u00A6Soninke\u00A6Koptisch\u00A6Yapees\u00A6Akoli\u00A6Yao\u00A6Filipijns (overige)\u00A6Pools\u00A6Atjehs\u00A6Pali\u00A6Punjabi\u00A6Buginees\u00A6Iban\u00A6Skolt Sami\u00A6Buriat\u00A6Masai\u00A6Inari Sami\u00A6Ossetisch\u00A6Austronesisch\u00A6Oriya\u00A6Mandingo\u00A6Lule Sami\u00A6Sami-talen (overige)\u00A6Makassaars\u00A6Oromo\u00A6Maithili\u00A6Ojibwa\u00A6Magahi\u00A6Madurees\u00A6Zuid-Samisch\u00A6Langue d\u2019Oc (na 1500)\u00A6Sotho, noorderlijk\u00A6Batak\u00A6Erzya\u00A6Dogrib\u00A6Nyanja\u00A6Mayan\u00A6Navajo\u00A6Kimbundu\u00A6Ndebele, zuid-\u00A6Duits, middelhoog- (ca. 1050-1500)\u00A6Noors\u00A6Noors - Nynorsk\u00A6Nederlands\u00A6Ndonga\u00A6Slavisch (overige)\u00A6Nepalees\u00A6Ndebele, noord-\u00A6Chamische talen\u00A6Tetum\u00A6Noors - Bokm\u00e5l\u00A6Nauru\u00A6Tereno\u00A6Timne\u00A6Birmees\u00A6Lezgisch\u00A6Maltees\u00A6Perzisch, oud- (ca. 600-400 B.C.)\u00A6Maleis\u00A6Marathi\u00A6Frans, oud (842-ca. 1400)\u00A6Moldavisch\u00A6Frans, middel (ca. 1400-1600)\u00A6Mongools\u00A6Judeo-Arabisch\u00A6Malayalam\u00A6Macedonisch\u00A6Maori\u00A6Marshallees\u00A6Malagasisch\u00A6Marwari\u00A6Braj\u00A6Slave\u00A6Letlands\u00A6Luba-Katanga\u00A6Delaware\u00A6Litouws\u00A6Lao\u00A6Lingala\u00A6Limburgs\u00A6Ewondo\u00A6Ganda\u00A6Luxemburgs\u00A6Latijn\u00A6Judeo-Perzisch\u00A6Votisch\u00A6Sino-Tibetaans (overige)\u00A6Kirgizisch\u00A6Cornish\u00A6Komi\u00A6Koerdisch\u00A6Siouaanse talen\u00A6Kashmiri\u00A6Kanuri\u00A6Awadhi\u00A6Koreaans\u00A6Kannada\u00A6Khmer\u00A6Kalaallisut\u00A6Kazachs\u00A6Romani\u00A6Kuanyama\u00A6Sidamo\u00A6Kikuyu\u00A6Kongo\u00A6Noors, oud-\u00A6Georgisch\u00A6Creek\u00A6Romaans (overige)\u00A6Nogai\u00A6Munda-talen\u00A6Meerdere talen\u00A6Javaans\u00A6Gilbertees\u00A6Zande\u00A6Shan\u00A6Fon\u00A6Kalmyk\u00A6Australische talen\u00A6Khotanees\u00A6Japans\u00A6Khoisan (overige)\u00A6Palauaans\u00A6Cheyenne\u00A6Tai (overige)\u00A6Inuktitut\u00A6Papiamento\u00A6Italiaans\u00A6Gebarentalen\u00A6IJslands\u00A6Khasi\u00A6Cherokee\u00A6Pampanga\u00A6Pahlavi\u00A6Chipewyan\u00A6Ido\u00A6Choctaw\u00A6Chinook-jargon\u00A6Mari\u00A6Tuvinisch\u00A6Bantu\u00A6Pangasinan\u00A6Inupiaq\u00A6Chuukees\u00A6Sichuan Yi\u00A6Hawa\u00efaans\u00A6Lamba\u00A6Igbo\u00A6Chagatai\u00A6Iers, oud- (tot 900)\u00A6Papoea (overige)\u00A6Interlingue\u00A6Indonesisch\u00A6Lahnda\u00A6Dajak\u00A6Chibcha\u00A6Interlingua\u00A6Ladino\u00A6Herero\u00A6Haida\u00A6Dargwa\u00A6Armeens\u00A6Athapascaanse talen\u00A6Hongaars\u00A6Ha\u00eftiaans\u00A6Dakota\u00A6Kroatisch\u00A6Hiri Motu\u00A6Hindi\u00A6Dyula\u00A6Hebreeuws\u00A6Asturisch\u00A6Hausa\u00A6Sorbische talen\u00A6Manx\u00A6Gujarati\u00A6Semitisch (overige)\u00A6Selkup\u00A6Irokese talen\u00A6Guarani\u00A6Galicisch\u00A6Arawak\u00A6Geez\u00A6Kunsttalen (overige)\u00A6Schots Gaelic\u00A6Iraans\u00A6Iers\u00A6Arapaho\u00A6Araukaans\u00A6Fries\u00A6Siksika\u00A6Germaans (overige)\u00A6Yupik-talen\u00A6Aramees\u00A6Frans\u00A6Faer\u00f6ers\u00A6Keltisch (overige)\u00A6Fijisch\u00A6Fins\u00A6Fulah\u00A6Tuvalu\u00A6Cebuano\u00A6Perzisch\u00A6Baskisch\u00A6Schots\u00A6Estlands\u00A6Spaans\u00A6Esperanto\u00A6Engels\u00A6Grieks\u00A6Alta\u00efsch (overige)\u00A6Niueaans\u00A6Tupi-talen\u00A6Ewe\u00A6Toemboeka\u00A6Mossi\u00A6Dzongkha\u00A6Niger - Kordofanisch (overige)\u00A6Lushai\u00A6Fins-Oegrisch (overige)\u00A6Divehi\u00A6Nias\u00A6Mohawk\u00A6Luo\u00A6Lunda\u00A6Apache-talen\u00A6Luiseno\u00A6Hupa\u00A6Bini\u00A6Duits\u00A6Luba-Lulua\u00A6Bikol\u00A6Washo\u00A6Onbepaald\u00A6Waray\u00A6Deens\u00A6Nederlands, middel- (ca. 1050-1350)\u00A6Walamo\u00A6Manobo-talen\u00A6Wakashan-talen\u00A6Santali\u00A6Welsh\u00A6Sasak\u00A6Kabardisch\u00A6Tsjoevasjisch\u00A6Kerkslavisch\u00A6Manipoeri\u00A6Tsjechisch\u00A6Samaritaans Aramees\u00A6Cree\u00A6Salishan-talen\u00A6Duala\u00A6Corsicaans\u00A6Zuid-Amerikaans Indiaans (overige)\u00A6Mantsjoe\u00A6Yakut\u00A6Kawi\u00A6Ingoesj\u00A6Gbaya\u00A6Sandawe\u00A6Chamorro\u00A6Indo-Europees (overige)\u00A6Bhojpuri\u00A6Engels, middel- (1100-1500)\u00A6Karen\u00A6Indisch (overige)\u00A6Chechen\u00A6Gayo\u00A6Catalaans\u00A6Umbundu\u00A6Syriac\u00A6Kamba\u00A6Tsimshian\u00A6Engels, oud (ca. 450-1100)\u00A6Kachin\u00A6Kaukasisch (overige)\u00A6Kabyle\u00A6Kara-Kalpaks\u00A6Bosnisch\u00A6Caribisch\u00A6Bretons\u00A6Tibetaans\u00A6Bengalees\u00A6Bambara\u00A6Ga\u00A6Midden-Amerikaans Indiaans (overige)\u00A6Bislama\u00A6Bihari\u00A6Bulgaars\u00A6Wit-Russisch\u00A6Caddo\u00A6Basjkiers\u00A6Zulu\u00A6Zenaga\u00A6Proven\u00e7aals, oud- (tot 1500)\u00A6Oppersorbisch\u00A6Azerbeidzjaans\u00A6Aymara\u00A6Avarisch\u00A6Assamees\u00A6Nedersorbisch\u00A6Arabisch\u00A6Iloko\u00A6Elamitisch\u00A6Chinees\u00A6Aragonees\u00A6Prakrit-talen\u00A6Amhaars\u00A6Newari\u00A6Akan\u00A6Zhuang\u00A6Afrikaans\u00A6Avestisch\u00A6Abchazisch\u00A6Afar\u00A6Joruba\u00A6Algonkium-talen\u00A6Aleut\u00A6Mon-Khmer (overige)\u00A6Jiddisch\u00A6Dravidisch (overige)\u00A6Berber\u00A6Laagduits; Laagsaxon\u00A6Bemba\u00A6Beja\u00A6Tok Pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final String variantsKeys = "REVISED";

  private static final String variantsValues = "Gewijzigd";

  private static final Hashtable variants;
  static
  {
    variants = new Hashtable();
    Enumeration keys = new StringTokenizer(variantsKeys, "\u00A6");
    Enumeration values = new StringTokenizer(variantsValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         variants.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "d-M-yy" },
    { "mediumDateFormat", "d-MMM-yyyy" },
    { "longDateFormat", "d MMMM yyyy" },
    { "fullDateFormat", "EEEE d MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss' uur' z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
