/* LocaleInformation_et.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML et.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_et extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jaan",
    "veebr",
    "m\u00e4rts",
    "apr",
    "mai",
    "juuni",
    "juuli",
    "aug",
    "sept",
    "okt",
    "nov",
    "dets",
    null,
  };

  private static final String[] months = {
    "jaanuar",
    "veebruar",
    "m\u00e4rts",
    "aprill",
    "mai",
    "juuni",
    "juuli",
    "august",
    "september",
    "oktoober",
    "november",
    "detsember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "P",
    "E",
    "T",
    "K",
    "N",
    "R",
    "L",
  };

  private static final String[] weekdays = {
    null,
    "p\u00fchap\u00e4ev",
    "esmasp\u00e4ev",
    "teisip\u00e4ev",
    "kolmap\u00e4ev",
    "neljap\u00e4ev",
    "reede",
    "laup\u00e4ev",
  };

  private static final String[] eras = {
    "e.m.a.",
    "m.a.j.",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Ida-Timor");
        put("TK", "Tokelau");
        put("TJ", "Tad\u012aikistan");
        put("TH", "Tai");
        put("TG", "Togo");
        put("TF", "Prantsuse L\u00f5unaalad");
        put("GY", "Guyana");
        put("TD", "Tiaad");
        put("TC", "Turks ja Caicos");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "L\u00f5una-Georgia ja L\u00f5una-Sandwichi saared");
        put("GR", "Kreeka");
        put("GQ", "Ekvatoriaal-Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Svaasimaa");
        put("SY", "S\u00fc\u00fcria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f6\u00f6nimaa");
        put("SV", "El Salvador");
        put("ST", "Sao Tom\u00e9 ja Principe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Prantsuse Guajaana");
        put("SP", "Serbia");
        put("GE", "Gruusia");
        put("SO", "Somaalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "\u00dchendkuningriik");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakkia");
        put("SJ", "Svalbard ja Jan Mayen");
        put("SI", "Sloveenia");
        put("SH", "Saint Helena");
        put("SG", "Singapur");
        put("SE", "Rootsi");
        put("SD", "Sudaan");
        put("SC", "Seiiellid");
        put("SB", "Saalomoni Saared");
        put("SA", "Saudi Araabia");
        put("FR", "Prantsusmaa");
        put("FO", "F\u00e4\u00e4ri saared");
        put("FM", "Mikroneesia Liiduriigid");
        put("RW", "Rwanda");
        put("FK", "Falklandi saared");
        put("RU", "Venemaa");
        put("FJ", "Fid\u012ai");
        put("FI", "Soome");
        put("RO", "Rumeenia");
        put("RE", "R\u00e9union");
        put("ET", "Etioopia");
        put("ES", "Hispaania");
        put("ER", "Eritrea");
        put("EH", "L\u00e4\u00e4ne-Sahara");
        put("EG", "Egiptus");
        put("EE", "Eesti");
        put("EC", "Ecuador");
        put("DZ", "Al\u012aeeria");
        put("QA", "Katar");
        put("DO", "Dominikaani Vabariik");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Belau");
        put("DK", "Taani");
        put("DJ", "Djibouti");
        put("PT", "Portugal");
        put("PS", "Palestiina Omavalitsus");
        put("PR", "Puerto Rico");
        put("DE", "Saksamaa");
        put("PN", "Pitcairn");
        put("PM", "Saint-Pierre ja Miquelon");
        put("PL", "Poola");
        put("PK", "Pakistan");
        put("PH", "Filipiinid");
        put("PG", "Paapua Uus-Guinea");
        put("PF", "Prantsuse Pol\u00fcneesia");
        put("CZ", "Tiehhi Vabariik");
        put("PE", "Peruu");
        put("CY", "K\u00fcpros");
        put("CX", "J\u00f5ulusaar");
        put("CV", "Cabo Verde");
        put("PA", "Panama");
        put("CU", "Kuuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "Hiina");
        put("CM", "Kamerun");
        put("CL", "Tiiili");
        put("CK", "Cooki saared");
        put("CI", "Cote d\u2019Ivoire");
        put("CH", "\u0128veits");
        put("CG", "Kongo");
        put("CF", "Kesk-Aafrika Vabariik");
        put("CD", "Kongo DV");
        put("CC", "Kookossaared");
        put("OM", "Omaan");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Valgevene");
        put("BW", "Botswana");
        put("BV", "Bouvet\u2019 saar");
        put("BT", "Bhutan");
        put("BS", "Bahama saared");
        put("BR", "Brasiilia");
        put("NZ", "Uus-Meremaa");
        put("BO", "Boliivia");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrein");
        put("NR", "Nauru");
        put("BG", "Bulgaaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgia");
        put("NO", "Norra");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Holland");
        put("BA", "Bosnia ja Hertsegoviina");
        put("NI", "Nicaragua");
        put("NG", "Nigeeria");
        put("NF", "Norfolk");
        put("AZ", "Aserbaid\u012aaan");
        put("NE", "Niger");
        put("NC", "Uus-Kaledoonia");
        put("AW", "Aruba");
        put("ZM", "Sambia");
        put("NA", "Namiibia");
        put("AU", "Austraalia");
        put("AT", "Austria");
        put("AS", "Ameerika Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktika");
        put("MZ", "Mosambiik");
        put("AO", "Angola");
        put("MY", "Malaisia");
        put("AN", "Hollandi Antillid");
        put("MX", "Mehhiko");
        put("AM", "Armeenia");
        put("MW", "Malawi");
        put("AL", "Albaania");
        put("MV", "Maldiivid");
        put("ZA", "L\u00f5una-Aafrika Vabariik");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritaania");
        put("AG", "Antigua ja Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afganistan");
        put("MP", "P\u00f5hja-Mariaanid");
        put("AE", "Araabia \u00dchendemiraadid");
        put("MO", "Aomeni Hiina erihalduspiirkond");
        put("AD", "Andorra");
        put("MN", "Mongoolia");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Makedoonia Vabariik");
        put("YU", "Jugoslaavia");
        put("YT", "Mayotte");
        put("MH", "Marshalli Saared");
        put("MG", "Madagaskar");
        put("MD", "Moldova");
        put("MC", "Monaco");
        put("MA", "Maroko");
        put("YE", "Jeemen");
        put("LY", "Liib\u00fca");
        put("LV", "L\u00e4ti");
        put("LU", "Luksemburg");
        put("LT", "Leedu");
        put("LS", "Lesotho");
        put("LR", "Libeeria");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Liibanon");
        put("LA", "Laose DRV");
        put("KZ", "Kasahstan");
        put("KY", "Kaimani saared");
        put("KW", "Kuveit");
        put("KR", "L\u00f5una-Korea");
        put("KP", "P\u00f5hja-Korea");
        put("KN", "Saint Kitts ja Nevis");
        put("KM", "Komoorid");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambod\u012aa");
        put("KG", "K\u00f5rg\u00f5zstan");
        put("KE", "Kenya");
        put("WF", "Wallis ja Futuna");
        put("JP", "Jaapan");
        put("JO", "Jordaania");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "USA Neitsisaared");
        put("VG", "Briti Neitsisaared");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent ja Grenadiinid");
        put("VA", "P\u00fcha Tool (Vatikan)");
        put("IT", "Itaalia");
        put("IS", "Island");
        put("IR", "Iraan");
        put("IQ", "Iraak");
        put("UZ", "Usbekistan");
        put("IO", "Briti India ookeani ala");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Iisrael");
        put("US", "Ameerika \u00dchendriigid");
        put("IE", "Iirimaa");
        put("ID", "Indoneesia");
        put("UM", "\u00dchendriikide hajasaared");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Ungari");
        put("HT", "Haiti");
        put("HR", "Horvaatia");
        put("TZ", "Tansaania");
        put("HN", "Honduras");
        put("HM", "Heard ja McDonald");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hongkongi erihalduspiirkond");
        put("TT", "Trinidad ja Tobago");
        put("TR", "T\u00fcrgi");
        put("TO", "Tonga");
        put("TN", "Tuneesia");
        put("TM", "T\u00fcrkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd.MM.yy" },
    { "mediumDateFormat", "dd.MM.yyyy" },
    { "longDateFormat", "d MMMM yyyy" },
    { "fullDateFormat", "EEEE, d, MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss z" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
