/* LocaleInformation_hu.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML hu.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_hu extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan.",
    "febr.",
    "m\u00e1rc.",
    "\u00e1pr.",
    "m\u00e1j.",
    "j\u00fan.",
    "j\u00fal.",
    "aug.",
    "szept.",
    "okt.",
    "nov.",
    "dec.",
    null,
  };

  private static final String[] months = {
    "janu\u00e1r",
    "febru\u00e1r",
    "m\u00e1rcius",
    "\u00e1prilis",
    "m\u00e1jus",
    "j\u00fanius",
    "j\u00falius",
    "augusztus",
    "szeptember",
    "okt\u00f3ber",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "V",
    "H",
    "K",
    "Sze",
    "Cs",
    "P",
    "Szo",
  };

  private static final String[] weekdays = {
    null,
    "vas\u00e1rnap",
    "h\u00e9tf\u0151",
    "kedd",
    "szerda",
    "cs\u00fct\u00f6rt\u00f6k",
    "p\u00e9ntek",
    "szombat",
  };

  private static final String[] eras = {
    "i.e.",
    "i.u.",
  };

  private static final String[] ampms = {
    "DE",
    "DU",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Kelet-Timor");
        put("TK", "Tokelau");
        put("TJ", "Tadzsikiszt\u00e1n");
        put("TH", "Thaif\u00f6ld");
        put("TG", "Togo");
        put("TF", "Francia D\u00e9li Ter\u00fcletek");
        put("GY", "Guyana");
        put("TD", "Cs\u00e1d");
        put("TC", "T\u00f6r\u00f6k \u00e9s Caicos Szigetek");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "D\u00e9l-Georgia \u00e9s D\u00e9l-Sandwich Szigetek");
        put("GR", "G\u00f6r\u00f6gorsz\u00e1g");
        put("GQ", "Egyenl\u00edt\u010fi Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Szv\u00e1zif\u00f6ld");
        put("SY", "Sz\u00edriai Arab K\u00f6zt\u00e1rsas\u00e1g");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f6nland");
        put("SV", "El Salvador");
        put("ST", "Saint Tome \u00e9s Principe");
        put("GI", "Gibralt\u00e1r");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Francia Guyana");
        put("SP", "Serbia");
        put("GE", "Gr\u00fazia");
        put("SO", "Szom\u00e1lia");
        put("GD", "Grenada");
        put("SN", "Szeneg\u00e1l");
        put("SM", "San Marino");
        put("GB", "Egyes\u00fclt Kir\u00e1lys\u00e1g");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Szlov\u00e1kia");
        put("SJ", "Svalbard \u00e9s Jan Mayen");
        put("SI", "Szlov\u00e9nia");
        put("SH", "Saint Helena");
        put("SG", "Szingap\u00far");
        put("SE", "Sv\u00e9dorsz\u00e1g");
        put("SD", "Szud\u00e1n");
        put("SC", "Seychelles");
        put("SB", "Salamon-szigetek");
        put("SA", "Szaud-Ar\u00e1bia");
        put("FR", "Franciaorsz\u00e1g");
        put("FO", "Fer\u00f6er-szigetek");
        put("FM", "Mikron\u00e9zia, Sz\u00f6vets\u00e9gi \u00c1llamok");
        put("RW", "Ruanda");
        put("FK", "Falkland-szigetek");
        put("RU", "Orosz K\u00f6zt\u00e1rsas\u00e1g");
        put("FJ", "Fidzsi");
        put("FI", "Finnorsz\u00e1g");
        put("RO", "Rom\u00e1nia");
        put("RE", "Reunion (francia)");
        put("ET", "Eti\u00f3pia");
        put("ES", "Spanyolorsz\u00e1g");
        put("ER", "Eritrea");
        put("EH", "Nyugat Szahara");
        put("EG", "Egyiptom");
        put("EE", "\u00c9sztorsz\u00e1g");
        put("EC", "Ecuador");
        put("DZ", "Alg\u00e9ria");
        put("QA", "Katar");
        put("DO", "Dominikai K\u00f6zt\u00e1rsas\u00e1g");
        put("PY", "Paraguay");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "D\u00e1nia");
        put("DJ", "Dzsibuti");
        put("PT", "Portug\u00e1lia");
        put("PS", "Paleszt\u00edn Ter\u00fclet");
        put("PR", "Puerto Rico");
        put("DE", "N\u00e9metorsz\u00e1g");
        put("PN", "Pitcairn-sziget");
        put("PM", "Saint Pierre \u00e9s Miquelon");
        put("PL", "Lengyelorsz\u00e1g");
        put("PK", "Pakiszt\u00e1n");
        put("PH", "F\u00fcl\u00f6p-szigetek");
        put("PG", "P\u00e1pua \u00daj-Guinea");
        put("PF", "Polin\u00e9zia (francia)");
        put("CZ", "Cseh K\u00f6zt\u00e1rsas\u00e1g");
        put("PE", "Peru");
        put("CY", "Ciprus");
        put("CX", "Kar\u00e1csony-szigetek");
        put("CV", "Z\u00f6ld-foki K\u00f6zt\u00e1rsas\u00e1g");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Costa Rica");
        put("CO", "Kolumbia");
        put("CN", "K\u00edna");
        put("CM", "Kamerun");
        put("CL", "Chile");
        put("CK", "Cook-szigetek");
        put("CI", "Elef\u00e1ntcsontpart");
        put("CH", "Sv\u00e1jc");
        put("CG", "Kong\u00f3");
        put("CF", "K\u00f6z\u00e9p-afrikai K\u00f6zt\u00e1rsas\u00e1g");
        put("CD", "Kong\u00f3, Demokratikus k\u00f6zt\u00e1rsas\u00e1g");
        put("CC", "K\u00f3kusz (Keeling)-szigetek");
        put("OM", "Om\u00e1n");
        put("CA", "Kanada");
        put("BZ", "Beliz");
        put("BY", "Feh\u00e9roroszorsz\u00e1g");
        put("BW", "Botswana");
        put("BV", "Bouvet-sziget");
        put("BT", "Bhut\u00e1n");
        put("BS", "Baham\u00e1k");
        put("BR", "Braz\u00edlia");
        put("NZ", "\u00daj-Z\u00e9land");
        put("BO", "Bol\u00edvia");
        put("BN", "Brunei Darussalam");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulg\u00e1ria");
        put("BF", "Burkina Faso");
        put("NP", "Nep\u00e1l");
        put("BE", "Belgium");
        put("NO", "Norv\u00e9gia");
        put("BD", "Banglades");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Hollandia");
        put("BA", "Bosznia-Hercegovina");
        put("NI", "Nicaragua");
        put("NG", "Nig\u00e9ria");
        put("NF", "Norfolk-sziget");
        put("AZ", "Azerbajdzs\u00e1n");
        put("NE", "Niger");
        put("NC", "\u00daj Kaled\u00f3nia (francia)");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Nam\u00edbia");
        put("AU", "Ausztr\u00e1lia");
        put("AT", "Ausztria");
        put("AS", "Amerikai Szamoa");
        put("AR", "Argent\u00edna");
        put("AQ", "Antarktisz");
        put("MZ", "Mozambik");
        put("AO", "Angola");
        put("MY", "Malajzia");
        put("AN", "Holland Antill\u00e1k");
        put("MX", "Mexik\u00f3");
        put("AM", "\u00d6rm\u00e9nyorsz\u00e1g");
        put("MW", "Malawi");
        put("AL", "Alb\u00e1nia");
        put("MV", "Mald\u00edv-szigetek");
        put("ZA", "D\u00e9l-Afrika");
        put("MU", "Mauritius");
        put("MT", "M\u00e1lta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Maurit\u00e1nia");
        put("AG", "Antigua \u00e9s Barbuda");
        put("MQ", "Martinique (francia)");
        put("AF", "Afganiszt\u00e1n");
        put("MP", "\u00c9szaki Mariana-szigetek");
        put("AE", "Egyes\u00fclt Arab Emir\u00e1tus");
        put("MO", "Macao S.A.R., China");
        put("AD", "Andorra");
        put("MN", "Mong\u00f3lia");
        put("MM", "Mianmar");
        put("ML", "Mali");
        put("MK", "Maced\u00f3nia, K\u00f6zt\u00e1rsas\u00e1g");
        put("YU", "Jugoszl\u00e1via");
        put("YT", "Mayotte");
        put("MH", "Marshall-szigetek");
        put("MG", "Madagaszk\u00e1r");
        put("MD", "Mold\u00e1v K\u00f6zt\u00e1rsas\u00e1g");
        put("MC", "Monaco");
        put("MA", "Marokk\u00f3");
        put("YE", "Jemen");
        put("LY", "L\u00edbiai Arab Jamahiriya");
        put("LV", "Lettorsz\u00e1g");
        put("LU", "Luxemburg");
        put("LT", "Litv\u00e1nia");
        put("LS", "Lesotho");
        put("LR", "Lib\u00e9ria");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libanon");
        put("LA", "Laoszi N\u00e9pi Demokratikus K\u00f6zt\u00e1rsas\u00e1g");
        put("KZ", "Kazahszt\u00e1n");
        put("KY", "Kajm\u00e1n-szigetek");
        put("KW", "Kuwait");
        put("KR", "Korea, D\u00e9l");
        put("KP", "Korea, \u00c9szak");
        put("KN", "Saint Kitts \u00e9s Nevis");
        put("KM", "Comore-szigetek");
        put("KI", "Kiribati");
        put("WS", "Szamoa");
        put("KH", "Kambodzsa");
        put("KG", "Kirgiziszt\u00e1n");
        put("KE", "Kenya");
        put("WF", "Wallis \u00e9s Futuna Szigetek");
        put("JP", "Jap\u00e1n");
        put("JO", "Jord\u00e1nia");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietn\u00e1m");
        put("VI", "U.S. Virgin-szigetek");
        put("VG", "Brit Virgin-szigetek");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent \u00e9s Grenadines");
        put("VA", "Vatik\u00e1n");
        put("IT", "Olaszorsz\u00e1g");
        put("IS", "Izland");
        put("IR", "Ir\u00e1n");
        put("IQ", "Irak");
        put("UZ", "\u00dczbegiszt\u00e1n");
        put("IO", "Brit Indiai Oce\u00e1n");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Izrael");
        put("US", "Egyes\u00fclt \u00c1llamok");
        put("IE", "\u00cdrorsz\u00e1g");
        put("ID", "Indon\u00e9zia");
        put("UM", "United States Minor Outlying Islands");
        put("UG", "Uganda");
        put("UA", "Ukrajna");
        put("HU", "Magyarorsz\u00e1g");
        put("HT", "Haiti");
        put("HR", "Horv\u00e1torsz\u00e1g");
        put("TZ", "Tanz\u00e1nia");
        put("HN", "Honduras");
        put("HM", "Heard \u00e9s McDonald Szigetek");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R., China");
        put("TT", "Trinidad \u00e9s Tobago");
        put("TR", "T\u00f6r\u00f6korsz\u00e1g");
        put("TO", "Tonga");
        put("TN", "Tun\u00e9zia");
        put("TM", "T\u00fcrkmeniszt\u00e1n");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "yyyy.MM.dd." },
    { "mediumDateFormat", "yyyy.MM.dd." },
    { "longDateFormat", "yyyy. MMMM d." },
    { "fullDateFormat", "yyyy. MMMM d." },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss z" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
