/* LocaleInformation_lt.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML lt.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_lt extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "Sau",
    "Vas",
    "Kov",
    "Bal",
    "Geg",
    "Bir",
    "Lie",
    "Rgp",
    "Rgs",
    "Spa",
    "Lap",
    "Grd",
    null,
  };

  private static final String[] months = {
    "Sausio",
    "Vasario",
    "Kovo",
    "Baland\u017eio",
    "Gegu\u017e\u0117s",
    "Bir\u017eelio",
    "Liepos",
    "Rugpj\u016b\u010dio",
    "Rugs\u0117jo",
    "Spalio",
    "Lapkri\u010dio",
    "Gruod\u017eio",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Sk",
    "Pr",
    "An",
    "Tr",
    "Kt",
    "Pn",
    "\u0160t",
  };

  private static final String[] weekdays = {
    null,
    "Sekmadienis",
    "Pirmadienis",
    "Antradienis",
    "Tre\u010diadienis",
    "Ketvirtadienis",
    "Penktadienis",
    "\u0160e\u0161tadienis",
  };

  private static final String[] eras = {
    "pr.Kr.",
    "po.Kr.",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Ryt\u0173 Timoras");
        put("TK", "Tokelau");
        put("TJ", "Tad\u017eikija");
        put("TH", "Tailandas");
        put("TG", "Togas");
        put("TF", "Pranc\u016bz\u0173 pietin\u0117s teritorijos");
        put("GY", "Gviana");
        put("TD", "\u010cadas");
        put("TC", "Turks ir Kaikos salos");
        put("GW", "Gvin\u0117ja-Bisau");
        put("GU", "Guamas");
        put("GT", "Gvatemala");
        put("GS", "Ryt\u0173 D\u017eord\u017eija ir Ryt\u0173 Sandwich salos");
        put("GR", "Graikija");
        put("GQ", "Ekvatorin\u0117 Gvin\u0117ja");
        put("GP", "Gvadelup\u0117");
        put("SZ", "Svazilendas");
        put("SY", "Sirija");
        put("GN", "Gvin\u0117ja");
        put("GM", "Gambija");
        put("GL", "Grenlandija");
        put("SV", "El Salvadoras");
        put("ST", "San Tom\u0117 ir Princip\u0117");
        put("GI", "Gibraltaras");
        put("GH", "Gana");
        put("SR", "Surinamas");
        put("GF", "Pranc\u016bzijos Gviana");
        put("SP", "Serbia");
        put("GE", "Gruzija");
        put("SO", "Somalis");
        put("GD", "Grenada");
        put("SN", "Senegalas");
        put("SM", "San Marinas");
        put("GB", "Did\u017eioji Britanija");
        put("SL", "Siera Leon\u0117");
        put("GA", "Gabonas");
        put("SK", "Slovakia");
        put("SJ", "Svalbardo ir Jan Majen salos");
        put("SI", "Slov\u0117nija");
        put("SH", "\u0160ventoji Elena");
        put("SG", "Singap\u016bras");
        put("SE", "\u0160vedija");
        put("SD", "Sudanas");
        put("SC", "Sei\u0161eliai");
        put("SB", "Saliamono salos");
        put("SA", "Saudo Arabija");
        put("FR", "Pranc\u016bzija");
        put("FO", "Farer\u0173 salos");
        put("FM", "Mikronezijos Federacin\u0117s Valstijos");
        put("RW", "Ruanda");
        put("FK", "Folklendo salos (Malvinai)");
        put("RU", "Rusijos Federacija");
        put("FJ", "Fid\u017eis");
        put("FI", "Suomija");
        put("RO", "Rumunija");
        put("RE", "Rejunjonas");
        put("ET", "Etiopija");
        put("ES", "Ispanija");
        put("ER", "Eritr\u0117ja");
        put("EH", "Vakar\u0173 Sachara");
        put("EG", "Egiptas");
        put("EE", "Estija");
        put("EC", "Ekvadoras");
        put("DZ", "Al\u017eyras");
        put("QA", "Kataras");
        put("DO", "Dominikos Respublika");
        put("PY", "Paragvajus");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "Danija");
        put("DJ", "D\u017eibutis");
        put("PT", "Portugalija");
        put("PS", "Palestinos teritorija");
        put("PR", "Puerto Rikas");
        put("DE", "Vokietija");
        put("PN", "Pitkernas");
        put("PM", "Sen Pjeras ir Mikelonas");
        put("PL", "Lenkija");
        put("PK", "Pakistanas");
        put("PH", "Filipinai");
        put("PG", "Papua Naujoji Gvin\u0117ja");
        put("PF", "Pranc\u016bz\u0173 Polinezija");
        put("CZ", "\u010cekijos respublika");
        put("PE", "Peru");
        put("CY", "Kipras");
        put("CX", "Kal\u0117d\u0173 sala");
        put("CV", "\u017daliojo Ky\u0161ulio salos");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kosta Rika");
        put("CO", "Kolumbija");
        put("CN", "Kinija");
        put("CM", "Kamer\u016bnas");
        put("CL", "\u010cil\u0117");
        put("CK", "Kuko salos");
        put("CI", "Kot d\u2019Ivuar");
        put("CH", "\u0160veicarija");
        put("CG", "Kongas");
        put("CF", "Centrin\u0117s Afrikos Respublika");
        put("CD", "Kongo Demokratin\u0117 Respublika");
        put("CC", "Kokos\u0173 salos");
        put("OM", "Omanas");
        put("CA", "Kanada");
        put("BZ", "Belizas");
        put("BY", "Baltarusija");
        put("BW", "Botsvana");
        put("BV", "Bouvet sala");
        put("BT", "Butanas");
        put("BS", "Bahamai");
        put("BR", "Brazilija");
        put("NZ", "Naujoji Zelandija");
        put("BO", "Bolivija");
        put("BN", "Brun\u0117jus");
        put("BM", "Bermudai");
        put("NU", "Niuj\u0117");
        put("BJ", "Beninas");
        put("BI", "Burundis");
        put("BH", "Bahreinas");
        put("NR", "Nauru");
        put("BG", "Bulgarija");
        put("BF", "Burkina Fasas");
        put("NP", "Nepalas");
        put("BE", "Belgija");
        put("NO", "Norvegija");
        put("BD", "Banglade\u0161as");
        put("BB", "Barbadosas");
        put("ZW", "Zimbabv\u0117");
        put("NL", "Nyderlandai");
        put("BA", "Bosnija ir Hercegovina");
        put("NI", "Nikaragva");
        put("NG", "Nigerija");
        put("NF", "Norfolko sala");
        put("AZ", "Azerbaid\u017eanas");
        put("NE", "Nigeris");
        put("NC", "Naujoji Kaledonija");
        put("AW", "Aruba");
        put("ZM", "Zambija");
        put("NA", "Namibija");
        put("AU", "Australija");
        put("AT", "Austrija");
        put("AS", "Amerikos Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktika");
        put("MZ", "Mozambikas");
        put("AO", "Angola");
        put("MY", "Malaizija");
        put("AN", "Nyderland\u0173 Antilai");
        put("MX", "Meksika");
        put("AM", "Arm\u0117nija");
        put("MW", "Malavis");
        put("AL", "Albanija");
        put("MV", "Maldivai");
        put("ZA", "Piet\u0173 Afrika");
        put("MU", "Mauricijus");
        put("MT", "Malta");
        put("AI", "Angvila");
        put("MS", "Montserat");
        put("MR", "Mauritanija");
        put("AG", "Antigva ir Barbuda");
        put("MQ", "Martinika");
        put("AF", "Afganistanas");
        put("MP", "\u0160iaurin\u0117s Marianos salos");
        put("AE", "Jungtiniai Arab\u0173 Emyratai");
        put("MO", "Kinijos S.A.R. Makao");
        put("AD", "Andora");
        put("MN", "Mongolija");
        put("MM", "Mjanma");
        put("ML", "Malis");
        put("MK", "Makedonijos Respublika");
        put("YU", "Jugoslavija");
        put("YT", "Majot\u0117");
        put("MH", "Mar\u0161alo salos");
        put("MG", "Madagaskaras");
        put("MD", "Moldovos Respublika");
        put("MC", "Monakas");
        put("MA", "Marokas");
        put("YE", "Jemenas");
        put("LY", "Libijos Arab\u0173 D\u017eamahirija");
        put("LV", "Latvija");
        put("LU", "Liuksemburgas");
        put("LT", "Lietuva");
        put("LS", "Lesotas");
        put("LR", "Liberija");
        put("LK", "\u0160ri Lanka");
        put("LI", "Lichten\u0161teinas");
        put("LC", "\u0160ventoji Liucija");
        put("LB", "Libanas");
        put("LA", "Laoso Liaudies Demokratin\u0117 Respublika");
        put("KZ", "Kazachstanas");
        put("KY", "Kaiman\u0173 salos");
        put("KW", "Kuveitas");
        put("KR", "Piet\u0173 Kor\u0117ja");
        put("KP", "\u0160iaur\u0117s Kor\u0117ja");
        put("KN", "Sent Kitsas ir Nevis");
        put("KM", "Komorai");
        put("KI", "Kiribatis");
        put("WS", "Samoa");
        put("KH", "Kambod\u017ea");
        put("KG", "Kirgiztanas");
        put("KE", "Kenija");
        put("WF", "Valiso ir Futuna salos");
        put("JP", "Japonija");
        put("JO", "Jordanija");
        put("JM", "Jamaika");
        put("VU", "Vanuatu");
        put("VN", "Vietnamas");
        put("VI", "JAV Virginijos salos");
        put("VG", "Brit\u0173 Virginijos salos");
        put("VE", "Venesuela");
        put("VC", "\u0160ventasis Vincentas ir Grenadinai");
        put("VA", "Vatikano Miesto Valstija");
        put("IT", "Italija");
        put("IS", "Islandija");
        put("IR", "Irano");
        put("IQ", "Irakas");
        put("UZ", "Uzbekija");
        put("IO", "Brit\u0173 Indijos vandenyno teritorija");
        put("UY", "Urugvajus");
        put("IN", "Indija");
        put("IL", "Izraelis");
        put("US", "United States");
        put("IE", "Airija");
        put("ID", "Indonezija");
        put("UM", "JAV antraeil\u0117s teritorijos salos");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Vengrija");
        put("HT", "Haitis");
        put("HR", "Kroatija");
        put("TZ", "Tanzanija");
        put("HN", "Hond\u016bras");
        put("HM", "Heard ir McDonald salos");
        put("TW", "Taivanis");
        put("TV", "Tuvalu");
        put("HK", "Kinijos S.A.R.Honkongas");
        put("TT", "Trinidadas ir Tobagas");
        put("TR", "Turkija");
        put("TO", "Tonga");
        put("TN", "Tunisas");
        put("TM", "Turkm\u0117nistanas");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "yyyy.MM.dd" },
    { "mediumDateFormat", "yyyy.MM.dd" },
    { "longDateFormat", "yyyy 'm.' MMMM d 'd.'" },
    { "fullDateFormat", "yyyy 'm.' MMMM d 'd.',EEEE" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
