/* LocaleInformation_da.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_da extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6LRD\u00A6ALV\u00A6HRK\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6ZAR\u00A6DOP\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GNF\u00A6UYP\u00A6OMR\u00A6XFU\u00A6ZRZ\u00A6BTR\u00A6MAF\u00A6MAD\u00A6XFO\u00A6BTN\u00A6UYF\u00A6ZRN\u00A6MYR\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6BSP\u00A6CMF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6GIP\u00A6VNS\u00A6VNR\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "Jordansk dinar\u00A6Boliviansk mvdol\u00A6Guld\u00A6F\u00e6r\u00f8sk krone\u00A6Libanesisk pund\u00A6Euro\u00A6Vietnamesisk dong\u00A6Tanzanisk shilling\u00A6Boliviansk peso\u00A6Cambodjansk riel\u00A6Gammel cambodjansk riel\u00A6Zambisk pund\u00A6Australsk pund\u00A6Beninsk CFA-franc\u00A6Maltesisk pund\u00A6Ghanesisk revalueret cedi\u00A6Zambisk kwacha\u00A6Ghanesisk pund\u00A6Gammel ghanesisk cedi\u00A6Maltesisk lira\u00A6Australsk dollar\u00A6Amerikansk dollar (samme dag)\u00A6Italiensk lira\u00A6Amerikansk dollar (n\u00e6ste dag)\u00A6Ghanesisk cedi\u00A6Singaporeansk dollar\u00A6Panamansk balboa\u00A6Laotisk kip\u00A6Kirgisisk som\u00A6Schweizisk franc\u00A6\u00d8strigsk schilling\u00A6Amerikanske dollar\u00A6Etiopisk dollar\u00A6Bruneisk dollar\u00A6Jamaicansk pund\u00A6Etiopisk birr\u00A6Algerisk franc germinal\u00A6Ny algerisk franc\u00A6Algerisk dinar\u00A6Paraguaysk guarani\u00A6Libysk pund\u00A6Jamaicansk dollar\u00A6Islandsk krona\u00A6Spansk peseta\u00A6Bermudansk pund\u00A6Libysk dinar\u00A6Bermudansk dollar\u00A6Hollandsk guilder\u00A6Mauritansk ouguiya\u00A6Iransk rial\u00A6Svensk krona\u00A6Eritreisk nakfa\u00A6Kenyansk shilling\u00A6CFA-franc fra den Centralafrikanske republik\u00A6Argentinsk peso\u00A6Argentinsk peso (1983-1985)\u00A6Argentinsk peso moneda nacional\u00A6Ny taiwansk dollar\u00A6Sudansk pund\u00A6Georgisk lari\u00A6Georgisk kupon larit\u00A6Martiniquisk franc\u00A6Pund fra Falklands\u00f8erne\u00A6Argentinsk austral\u00A6Sudansk dinar\u00A6Irakisk dinar\u00A6Tuvaluansk dollar\u00A6Seychellisk rupee\u00A6Lettisk rubel\u00A6Fijiansk pund\u00A6Lettisk lats\u00A6Congolesisk Zaire\u00A6Congolesisk franc\u00A6Congolesisk franc congolais\u00A6Fijiansk dollar\u00A6Nicaraguansk cordoba oro\u00A6Macaosk pataca\u00A6Nicaraguansk gold cordoba\u00A6Nicaraguansk cordoba\u00A6Finsk mark (1860-1962)\u00A6Finsk mark\u00A6Salomonsk dollar\u00A6Luxembourgsk franc\u00A6Gammel dollar fra Trinidad og Tobago\u00A6Angolansk escudo\u00A6Angolansk kwanza reajustado (1995-1999)\u00A6Mongolsk tugrik\u00A6Ungarsk forint\u00A6Burundisk franc\u00A6Ny angolansk kwanza (1990-2000)\u00A6Angolansk kwanza (1977-1990)\u00A6Dollar fra Trinidad og Tobago\u00A6Swazilandsk lilangeni\u00A6CFP-franc fra Ny-Hebriderne\u00A6Britisk pund\u00A6Saudisk sovereign riyal\u00A6Saudisk riyal\u00A6Litauisk talonas\u00A6Indisk rupee\u00A6Portugisisk escudo\u00A6Angolansk kwanza\u00A6Portugisisk conto\u00A6Litauisk lita\u00A6Kasakhisk tenge\u00A6Kasakhisk rubel\u00A6Dollar fra De Britiske Jomfru\u00f8er\u00A6Nigeriansk pund\u00A6Nigeriansk naira\u00A6Haitisk gourde\u00A6Syrisk pund\u00A6Pal\u00e6stinensisk pund\u00A6Bahrainsk dinar\u00A6Myanmarsk kyat\u00A6Gylden fra De Nederlandske Antiller\u00A6Tjekkisk koruna\u00A6Lesothisk loti\u00A6Gabonesisk CFA-franc\u00A6Bulgarsk lev (1879-1952)\u00A6Ny Bulgarsk lev\u00A6Bulgarsk socialist lev\u00A6Canadisk dollar\u00A6Bulgarsk hard lev\u00A6Tyrkisk lira\u00A6Dollar fra Cayman\u00f8erne\u00A6Cypriotisk pund\u00A6Ny israelsk shekel\u00A6Guyansk dollar\u00A6Armensk dram\u00A6Israelsk pund\u00A6Malisk franc\u00A6Israelsk shekel\u00A6Venezuelansk bolivar\u00A6Liberisk dollar\u00A6Albansk lek\u00A6Kroatisk kuna\u00A6Kroatisk dinar\u00A6Albansk lek\u00A6Pund fra Jersey\u00A6Albansk lek (1946-1961)\u00A6Makedonsk denar (1992-1993)\u00A6Nordvietnamesisk viet minh piastre dong viet\u00A6Ny nordvietnamesisk dong\u00A6Makedonsk denar\u00A6Nordvietnamesisk piastre dong viet\u00A6Pataca fra Timor\u00A6CFP-franc\u00A6Belgisk franc (financial)\u00A6Guineansk peso\u00A6Kuwaitisk dinar\u00A6Portugisisk guinea mil reis\u00A6Belgisk franc\u00A6Escudo fra Timor\u00A6Belgisk franc (konvertibel)\u00A6Portugisisk guinea escudo\u00A6Salvadoransk colon\u00A6Curacaosk gylden\u00A6Bangladeshisk taka\u00A6Tongask pund\u00A6Tongask pa\u02bbanga\u00A6Sovjetisk rubel\u00A6Ny sovjetisk rubel\u00A6Nykaledonsk franc germinal\u00A6Kapverdisk escudo\u00A6Sydafrikansk rand\u00A6Dominikansk peso\u00A6Sydafrikansk pund\u00A6Sydafrikansk rand (financial)\u00A6Tunesisk dinar\u00A6Cubansk peso\u00A6Fransk-guyansk franc guiana\u00A6Ugandisk shilling\u00A6Ceylonesisk rupee\u00A6Affars og Issas franc\u00A6Vatikansk lira\u00A6Escudo fra Sao Tome og Principe\u00A6Ugandisk shilling (1966-1987)\u00A6Dobra fra Sao Tome og Principe\u00A6Dollar fra Marshall\u00f8erne\u00A6New Zealandsk pund\u00A6Samoansk tala\u00A6Samoansk pund\u00A6Honduransk lempira\u00A6Turkmensk manat\u00A6Guatemalansk quetzal\u00A6New Zealandsk dollar\u00A6Skotsk pund\u00A6Barbadisk dollar\u00A6Namibisk dollar\u00A6Madagaskisk franc\u00A6Madagaskisk ariary\u00A6Egyptisk pund\u00A6Britisk Honduras dollar\u00A6Polsk zloty (1950-1995)\u00A6Ny bosnien-hercegovinsk dinar\u00A6Bosnien-Hercegovinsk konvertibel mark\u00A6Belizisk dollar\u00A6Bosnien-Hercegovinsk dinar\u00A6Polsk zloty\u00A6Yemenitisk rial\u00A6Surinamsk guilder\u00A6Tjekkoslovakisk hard koruna\u00A6Sydkoreansk won\u00A6Hviderussisk rubel\u00A6Yemenitisk imadi riyal\u00A6Hviderussisk rubel (1992-1994)\u00A6Tjekkoslovakisk koruna\u00A6Gammel sydkoreansk won\u00A6Sydkoreansk hwan\u00A6Ny hviderussisk rubel (1994-1999)\u00A6Somalilands shilling\u00A6Ny gr\u00e6sk drachma\u00A6Pakistansk rupee\u00A6Zimbabwisk dollar\u00A6Srilankansk rupee\u00A6Gr\u00e6sk drachma\u00A6Irsk pund\u00A6Yemenitisk dinar\u00A6Rwandisk franc\u00A6Costaricansk colon\u00A6Tadsjikisk somoni\u00A6Tadsjikisk rubel\u00A6Estisk kroon\u00A6\u00c6kvatorialguineask peseta guineana\u00A6Moldovisk ruble cupon\u00A6Dansk krone\u00A6Moldovisk leu\u00A6\u00c6kvatorialguineask franco\u00A6\u00c6kvatorialguineask ekwele guineana\u00A6Indonesisk pupiah\u00A6Dirham fra de Forenede Arabiske Emirater\u00A6Nordkoreansk won\u00A6Ny indonesisk rupiah\u00A6Botswansk pula\u00A6Moldovisk leu cupon\u00A6Indonesisk java rupiah\u00A6Indonesisk nica guilder\u00A6Vanuaisk vatu\u00A6Islamisk dinar\u00A6Somalisk shilling\u00A6Andorransk peseta\u00A6Russisk rubel (1991-1998)\u00A6Guadeloupsk franc\u00A6Djiboutisk franc\u00A6Andorransk diner\u00A6Monegaskisk franc germinal\u00A6Ny monegaskisk franc\u00A6Ecuadoriansk sucre\u00A6Liechtensteinsk franc\u00A6Russisk rubel\u00A6Filippinsk peso\u00A6Usbekisk sum\u00A6Colombiansk peso\u00A6Thailandsk baht\u00A6Nordirsk pund\u00A6Burmesisk rupee\u00A6Congolesisk CFA-franc\u00A6Burmesisk kyat\u00A6Colombiansk papirpeso\u00A6Usbekisk coupon som\u00A6Ukrainsk karbovanetz\u00A6Qatarsk rial\u00A6Ukrainsk grynia\u00A6Guineansk syli\u00A6Kinesisk yuan renminbi\u00A6Mozambiquisk metical\u00A6Uruguaysk peso uruguayo\u00A6Guineansk franc (1960-1972)\u00A6Lira fra San Marino\u00A6Mozambiquisk escudo\u00A6Kinesisk jen min piao yuan\u00A6Papuansk kina\u00A6Omansk rial saidi\u00A6Guineansk franc\u00A6Uruguaysk peso (1975-1993)\u00A6Omansk rial\u00A6Fransk UIC-franc\u00A6Zairisk naire\u00A6Bhutansk rupee\u00A6Marokkansk franc\u00A6Marokkansk dirham\u00A6Fransk guldfranc\u00A6Bhutansk ngultrum\u00A6Uruguaysk peso fuerte\u00A6Ny zairisk zaire\u00A6Malaysisk ringgit\u00A6Aserbajdsjansk manat\u00A6Gambisk pund\u00A6Comorisk franc\u00A6Sierraleonsk leone\u00A6Gambisk dalasi\u00A6Bahamansk pund\u00A6Camerounsk CFA-franc\u00A6Bahamansk dollar\u00A6Mexicansk silver peso (1861-1992)\u00A6Mexicansk peso\u00A6Peruviansk sol\u00A6Gr\u00f8nlandsk krone\u00A6Brasiliansk cruzeiro (1942-1967)\u00A6Peruviansk sol nuevo\u00A6Chilensk peso\u00A6Slovakisk koruna\u00A6Peruviansk inti\u00A6Brasiliansk cruzeiro\u00A6Fransk franc\u00A6Brasiliansk cruzado novo\u00A6Chilensk unidades de fomento\u00A6Chilensk escudo\u00A6Brasiliansk real\u00A6Chilensk condor\u00A6Brasiliansk cruzeiro (1990-1993)\u00A6Tysk sperrmark\u00A6Malawisk pund\u00A6Brasiliansk cruzado\u00A6Brasiliansk cruzeiro novo (1967-1986)\u00A6Malawisk kwacha\u00A6Transdniestrisk rubel\u00A6Tysk mark\u00A6Tchadisk CFA-franc\u00A6Ny transdniestrisk rubel\u00A6Transdniestrisk rubelkupon\u00A6Nepalesisk rupee\u00A6Dollar fra Cook\u00f8erne\u00A6Japansk yen\u00A6Maldivisk rufiyaa\u00A6Maldivisk rupee\u00A6\u00d8st-karaibisk dollar\u00A6Slovensk tolar\u00A6Jugoslavisk reformed dinar\u00A6Arubansk gylden\u00A6Jugoslavisk october dinar\u00A6\u00d8sttysk mark\u00A6Jugoslavisk convertible dinar\u00A6Jugoslavisk noviy dinar\u00A6Jugoslavisk 1994 dinar\u00A6Jugoslavisk federation dinar\u00A6Ny rum\u00e6nsk leu\u00A6Jugoslavisk hard dinar\u00A6Rum\u00e6nsk leu\u00A6Slovensk tolar bons\u00A6Norsk krone\u00A6Mauritisk rupee\u00A6Gibraltarisk pund\u00A6Vietnamesisk national dong\u00A6Vietnamesisk republikansk dong\u00A6Pund fra Saint Helena\u00A6Ny vietnamesisk dong";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6LRD\u00A6ALV\u00A6HRK\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6ZAR\u00A6DOP\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GNF\u00A6UYP\u00A6OMR\u00A6XFU\u00A6ZRZ\u00A6BTR\u00A6MAF\u00A6MAD\u00A6XFO\u00A6BTN\u00A6UYF\u00A6ZRN\u00A6MYR\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6BSP\u00A6CMF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6GIP\u00A6VNS\u00A6VNR\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LL\u00A6VND\u00A6T Sh\u00A6BOP\u00A6CR\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6GHO\u00A6Lm\u00A6$A\u00A6USS\u00A6USN\u00A6GHC\u00A6S$\u00A6PAB\u00A6LAK\u00A6som\u00A6SwF\u00A6ATS\u00A6US$\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6Ber$\u00A6NLG\u00A6UM\u00A6RI\u00A6SKr\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6Ft\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SRl\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6CZK\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6Can$\u00A6lev\u00A6TL\u00A6KYD\u00A6\u00a3C\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6LRD\u00A6ALV\u00A6HRK\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6T$\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6R\u00A6RD$\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6kr\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6Y\u00A6Mt\u00A6Ur$\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GF\u00A6UYP\u00A6RO\u00A6XFU\u00A6ZRZ\u00A6BTR\u00A6MAF\u00A6MAD\u00A6XFO\u00A6Nu\u00A6UYF\u00A6ZRN\u00A6RM\u00A6AZM\u00A6GMP\u00A6CF\u00A6SLL\u00A6GMD\u00A6BSP\u00A6CMF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6Ch$\u00A6Sk\u00A6PEI\u00A6BRR\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6leu\u00A6SIB\u00A6NKr\u00A6MUR\u00A6GIP\u00A6VNS\u00A6VNR\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "maj",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januar",
    "februar",
    "marts",
    "april",
    "maj",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "s\u00f8n",
    "man",
    "tir",
    "ons",
    "tor",
    "fre",
    "l\u00f8r",
  };

  private static final String[] weekdays = {
    null,
    "s\u00f8ndag",
    "mandag",
    "tirsdag",
    "onsdag",
    "torsdag",
    "fredag",
    "l\u00f8rdag",
  };

  private static final String[] eras = {
    "f.Kr.",
    "e.Kr.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "Eastern-normaltid", "EST", "Eastern-normaltid"},
    {  "America/Halifax", "AST", "Atlantic-normaltid", "ADT", "Atlantic-sommertid"},
    {  "Pacific/Honolulu", "HST", "Hawaii-normaltid", "HST", "Hawaii-normaltid"},
    {  "America/Denver", "MST", "Mountain-normaltid", "MDT", "Mountain-sommertid"},
    {  "America/Anchorage", "AST", "Alaska-normaltid", "ADT", "Alaska-sommertid"},
    {  "America/St_Johns", "CNT", "Newfoundland-normaltid", "CDT", "Newfoundland-sommertid"},
    {  "Africa/Casablanca", "GMT", "Verdenstid", "GMT", "Verdenstid"},
    {  "America/Chicago", "CST", "Central-normaltid", "CDT", "Central-sommertid"},
    {  "Asia/Shanghai", "CTT", "Kinesisk normaltid", "CDT", "Kinesisk normaltid"},
    {  "Asia/Tokyo", "JST", "Japansk normaltid", "JST", "Japansk normaltid"},
    {  "America/New_York", "EST", "Eastern-normaltid", "EDT", "Eastern-sommertid"},
    {  "Europe/Bucharest", "EET", "\u00d8steurop\u00e6isk normaltid", "EEST", "\u00d8steurop\u00e6isk sommertid"},
    {  "America/Los_Angeles", "PST", "Pacific-normaltid", "PDT", "Pacific-sommertid"},
    {  "America/Phoenix", "MST", "Mountain-normaltid", "MST", "Mountain-normaltid"},
    {  "Etc/GMT", "GMT", "Verdenstid", "GMT", "Verdenstid"},
    {  "Asia/Jerusalem", "IST", "Israelsk normaltid", "IDT", "Israelsk sommertid"},
    {  "Europe/Paris", "CET", "Mellemeurop\u00e6isk normaltid", "CEST", "Mellemeurop\u00e6isk sommertid"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Timor-Leste\u00A6Tokelau\u00A6Tadsjikistan\u00A6Thailand\u00A6Togo\u00A6Franske Besiddelser i Det Sydlige Indiske Ocean\u00A6Guyana\u00A6Tchad\u00A6Turks- og Caicos\u00f8erne\u00A6Guinea-Bissau\u00A6Guam\u00A6Guatemala\u00A6South Georgia og De Sydlige Sandwich\u00f8er\u00A6Gr\u00e6kenland\u00A6\u00c6kvatorialguinea\u00A6Guadeloupe\u00A6Swaziland\u00A6Syrien\u00A6Guinea\u00A6Gambia\u00A6Gr\u00f8nland\u00A6El Salvador\u00A6S\u00e3o Tom\u00e9 og Pr\u00edncipe\u00A6Gibraltar\u00A6Ghana\u00A6Surinam\u00A6Fransk Guyana\u00A6Georgien\u00A6Somalia\u00A6Grenada\u00A6Senegal\u00A6San Marino\u00A6Storbritannien\u00A6Sierra Leone\u00A6Gabon\u00A6Slovakiet\u00A6Svalbard og Jan Mayen\u00A6Slovenien\u00A6St. Helena\u00A6Singapore\u00A6Sverige\u00A6Sudan\u00A6Seychellerne\u00A6Salomon\u00f8erne\u00A6Saudi-Arabien\u00A6Frankrig\u00A6F\u00e6r\u00f8erne\u00A6Mikronesiens Forenede Stater\u00A6Rwanda\u00A6Falklands\u00f8erne\u00A6Rusland\u00A6Fiji-\u00f8erne\u00A6Finland\u00A6Rum\u00e6nien\u00A6Reunion\u00A6Etiopien\u00A6Spanien\u00A6Eritrea\u00A6Vestsahara\u00A6Egypten\u00A6Estland\u00A6Ecuador\u00A6Algeriet\u00A6Qatar\u00A6Den Dominikanske Republik\u00A6Paraguay\u00A6Dominica\u00A6Palau\u00A6Danmark\u00A6Djibouti\u00A6Portugal\u00A6De pal\u00e6stinensiske omr\u00e5der\u00A6Puerto Rico\u00A6Tyskland\u00A6Pitcairn\u00A6Saint Pierre og Miquelon\u00A6Polen\u00A6Pakistan\u00A6Filippinerne\u00A6Papua Ny Guinea\u00A6Fransk Polynesien\u00A6Tjekkiet\u00A6Peru\u00A6Cypern\u00A6Jule\u00f8en\u00A6Kap Verde\u00A6Panama\u00A6Cuba\u00A6Costa Rica\u00A6Colombia\u00A6Kina\u00A6Cameroun\u00A6Chile\u00A6Cook-\u00f8erne\u00A6Elfenbenskysten\u00A6Schweiz\u00A6Congo\u00A6Centralafrikanske Republik\u00A6Den Demokratiske Republik Congo\u00A6Cocos-\u00f8erne (Keeling\u00f8erne)\u00A6Oman\u00A6Canada\u00A6Belize\u00A6Hviderusland\u00A6Botswana\u00A6Bouvet\u00f8\u00A6Bhutan\u00A6Bahamas\u00A6Brasilien\u00A6New Zealand\u00A6Bolivia\u00A6Brunei Darussalam\u00A6Bermuda\u00A6Niue\u00A6Benin\u00A6Burundi\u00A6Bahrain\u00A6Nauru\u00A6Bulgarien\u00A6Burkina Faso\u00A6Nepal\u00A6Belgien\u00A6Norge\u00A6Bangladesh\u00A6Barbados\u00A6Zimbabwe\u00A6Holland\u00A6Bosnien-Hercegovina\u00A6Nicaragua\u00A6Nigeria\u00A6Norfolk Island\u00A6Aserbajdsjan\u00A6Niger\u00A6Ny Caledonien\u00A6Aruba\u00A6Zambia\u00A6Namibia\u00A6Australien\u00A6\u00d8strig\u00A6Amerikansk Samoa\u00A6Argentina\u00A6Antarktis\u00A6Mozambique\u00A6Angola\u00A6Malaysia\u00A6Hollandske Antiller\u00A6Mexico\u00A6Armenien\u00A6Malawi\u00A6Albanien\u00A6Maldiverne\u00A6Sydafrika\u00A6Mauritius\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Mauretanien\u00A6Antigua og Barbuda\u00A6Martinique\u00A6Afghanistan\u00A6Nordmarianerne\u00A6Forenede Arabiske Emirater\u00A6SAR Macao\u00A6Andorra\u00A6Mongoliet\u00A6Myanmar\u00A6Mali\u00A6Republikken Makedonien\u00A6Jugoslavien\u00A6Mayotte\u00A6Marshall\u00f8erne\u00A6Madagaskar\u00A6Republikken Moldova\u00A6Monaco\u00A6Marokko\u00A6Yemen\u00A6Libyen\u00A6Letland\u00A6Luxembourg\u00A6Litauen\u00A6Lesotho\u00A6Liberia\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Saint Lucia\u00A6Libanon\u00A6Laos\u00A6Kasakhstan\u00A6Cayman\u00f8erne\u00A6Kuwait\u00A6Sydkorea\u00A6Nordkorea\u00A6Saint Kitts og Nevis\u00A6Comorerne\u00A6Kiribati\u00A6Samoa\u00A6Cambodja\u00A6Kirgisistan\u00A6Kenya\u00A6Wallis og Futuna\u00f8erne\u00A6Japan\u00A6Jordan\u00A6Jamaica\u00A6Vanuatu\u00A6Vietnam\u00A6De amerikanske jomfru\u00f8er\u00A6De britiske jomfru\u00f8er\u00A6Venezuela\u00A6St. Vincent og Grenadinerne\u00A6Vatikanstaten\u00A6Italien\u00A6Island\u00A6Iran\u00A6Irak\u00A6Usbekistan\u00A6Det Britiske Territorium i Det Indiske Ocean\u00A6Uruguay\u00A6Indien\u00A6Israel\u00A6USA\u00A6Irland\u00A6Indonesien\u00A6De Mindre Amerikanske Overs\u00f8iske \u00d8er\u00A6Uganda\u00A6Ukraine\u00A6Ungarn\u00A6Haiti\u00A6Kroatien\u00A6Tanzania\u00A6Honduras\u00A6Heard- og McDonald-\u00f8erne\u00A6Taiwan\u00A6Tuvalu\u00A6SAR Hongkong\u00A6Trinidad og Tobago\u00A6Tyrkiet\u00A6Tonga\u00A6Tunesien\u00A6Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6ijo\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6mic\u00A6wa\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6vai\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6fan\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tl\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sn\u00A6sm\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6tiv\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpf\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6snk\u00A6cop\u00A6yap\u00A6ach\u00A6yao\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6sms\u00A6bua\u00A6mas\u00A6smn\u00A6os\u00A6map\u00A6or\u00A6man\u00A6smj\u00A6smi\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6sma\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6ng\u00A6sla\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6ku\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6jv\u00A6gil\u00A6znd\u00A6shn\u00A6fon\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6nia\u00A6moh\u00A6luo\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "Gwich\u02bbin\u00A6Akkadisk\u00A6Ekajuk\u00A6Ijo\u00A6Xhosa\u00A6Sumerisk\u00A6Susu\u00A6Diverse sprog\u00A6Lozi\u00A6Tonga (Nyasa)\u00A6Ponape\u00A6Minangkabau\u00A6Sukuma\u00A6Wolof\u00A6Mongo\u00A6Micmac\u00A6Vallonsk\u00A6Zapotec\u00A6Kusjitiske sprog (\u00f8vrige)\u00A6Lojban\u00A6Dogri\u00A6Volap\u00fck\u00A6Otomi sprog\u00A6Vietnamesisk\u00A6Vai\u00A6Rarotongan\u00A6Venda\u00A6Rapanui\u00A6Rajasthani\u00A6Osmannisk (1500-1928)\u00A6Nzima\u00A6Neapolitansk\u00A6Usbekisk\u00A6Ugaristisk\u00A6Tamashek\u00A6Nordamerikanske indianske sprog (\u00f8vrige)\u00A6Nahuatl\u00A6Urdu\u00A6Fanti\u00A6Ukrainsk\u00A6Egyptisk (oldtid)\u00A6Uigurisk\u00A6Fang\u00A6Afrikanske sprog syd for Sahara (\u00f8vrige)\u00A6Irsk, Middel- (900-1200)\u00A6Baltiske sprog (\u00f8vrige)\u00A6Nyoro sprog\u00A6Basa\u00A6Nyankole\u00A6Nyamwezi\u00A6Hmong\u00A6Balinesisk\u00A6Osage\u00A6Baluchi\u00A6Tahitiansk\u00A6Twi\u00A6Serer\u00A6Tlingit\u00A6Tatarisk\u00A6Tsonga\u00A6Banda\u00A6Tyrkisk\u00A6Tonga (Tonga\u00f8erne)\u00A6Tswana\u00A6Tagalog\u00A6Turkmensk\u00A6Tigrinya\u00A6Thailandsk\u00A6Kurukh\u00A6Tajik\u00A6Blin\u00A6Telugu\u00A6Kru\u00A6Kashubian\u00A6Tamilsk\u00A6Tokelau\u00A6Efik\u00A6Swahili\u00A6Svensk\u00A6Sundanesisk\u00A6Karachay-Balkar\u00A6Sotho, Southern\u00A6Swati\u00A6Serbisk\u00A6Albansk\u00A6Mende\u00A6Kreolsk og pidgin (\u00f8vrige)\u00A6Somalisk\u00A6Afrihili\u00A6Shona\u00A6Samoansk\u00A6Slovensk\u00A6Gr\u00e6sk, Old- (til 1453)\u00A6Slovakisk\u00A6Grebo\u00A6Singalesisk\u00A6Serbokroatisk\u00A6Krim-tyrkisk; Krim-tatarisk\u00A6Afro-asiatisk (\u00f8vrige)\u00A6Sango\u00A6Nordsamisk\u00A6Sindhi\u00A6Udmurt\u00A6Sardinsk\u00A6Sanskrit\u00A6Kinyarwanda\u00A6Russisk\u00A6Mandar\u00A6Rum\u00e6nsk\u00A6Rundi\u00A6R\u00e6toromansk\u00A6Moksha\u00A6Tivi\u00A6Adyghe\u00A6Zuni\u00A6Kpelle\u00A6Quechua\u00A6Tigre\u00A6Songhai\u00A6Kreolsk og pidgin, baseret p\u00e5 portugisisk (\u00f8vrige)\u00A6Sogdiansk\u00A6Adangme\u00A6Kosraean\u00A6Hittitisk\u00A6Kreolsk og pidgin, baseret p\u00e5 fransk (\u00f8vrige)\u00A6Kreolsk og pidgin, baseret p\u00e5 engelsk (\u00f8vrige)\u00A6Himachali\u00A6Konkani\u00A6Hiligaynon\u00A6Gotisk\u00A6Gorontalo\u00A6Gondi\u00A6Dinka\u00A6Nubiske sprog\u00A6Portugisisk\u00A6Pashto (Pushto)\u00A6Friulian\u00A6F\u00f8nikisk\u00A6Tysk, Oldh\u00f8j- (ca.750-1050)\u00A6Soninke\u00A6Koptisk\u00A6Yap\u00A6Acoli\u00A6Yao\u00A6Filippinske sprog (\u00f8vrige)\u00A6Polsk\u00A6Achinesisk\u00A6Pali\u00A6Punjabi\u00A6Buginesisk\u00A6Iban\u00A6Skolt Sami\u00A6Buriat\u00A6Masai\u00A6Inari Sami\u00A6Ossetisk\u00A6Malajo-polynesiske sprog (\u00f8vrige)\u00A6Oriya\u00A6Mandingo\u00A6Lule Sami\u00A6Samiske sprog (\u00f8vrige)\u00A6Makasar\u00A6Oromo\u00A6Maithili\u00A6Ojibwa\u00A6Magahi\u00A6Madurese\u00A6Sydsamisk\u00A6Occitansk (efter 1500); Provencalsk\u00A6Sotho, Nord\u00A6Batak\u00A6Erzya\u00A6Dogrib\u00A6Nyanja; Chichewa; Chewa\u00A6Maya sprog\u00A6Navajo\u00A6Kimbundu\u00A6Ndebele, Syd\u00A6Tysk, Middelh\u00f8j- (ca.1050-1500)\u00A6Norsk\u00A6Nynorsk\u00A6Hollandsk\u00A6Ndonga\u00A6Slaviske sprog (\u00f8vrige)\u00A6Nepalesisk\u00A6Ndebele, Nord\u00A6Chamic sprog\u00A6Tetum\u00A6Norsk Bokm\u00e5l\u00A6Nauru\u00A6Tereno\u00A6Temne\u00A6Burmesisk\u00A6Lezghian\u00A6Maltesisk\u00A6Persisk, Old- (ca. 600-400 f. Kr.)\u00A6Malay\u00A6Marathisk\u00A6Fransk, Old- (842-ca.1400)\u00A6Moldovisk\u00A6Fransk, Middel- (ca.1400-1600)\u00A6Mongolsk\u00A6J\u00f8disk-arabisk\u00A6Malayalam\u00A6Makedonsk\u00A6Maori\u00A6Marshallese\u00A6Malagasy\u00A6Marwari\u00A6Braj\u00A6Slave (Athapascan)\u00A6Lettisk\u00A6Luba-Katanga\u00A6Delaware\u00A6Litauisk\u00A6Lao\u00A6Lingala\u00A6Limburgsk\u00A6Ewondo\u00A6Ganda\u00A6Luxembourgsk\u00A6Latin\u00A6J\u00f8disk-persisk\u00A6Votisk\u00A6Sino-tibetanske sprog (\u00f8vrige)\u00A6Kirgisisk\u00A6Cornisk\u00A6Kurdisk\u00A6Kashmiri\u00A6Kanuri\u00A6Awadhi\u00A6Koreansk\u00A6Kannaresisk\u00A6Khmer\u00A6Kalaallisut\u00A6Kasakhisk\u00A6Romani\u00A6Kuanyama\u00A6Sidamo\u00A6Kikuyu\u00A6Kongo\u00A6Islandsk, Old-\u00A6Georgisk\u00A6Creek\u00A6Romanske sprog (\u00f8vrige)\u00A6Nogai\u00A6Munda (\u00f8vrige)\u00A6Flere sprog\u00A6Javanesisk\u00A6Gilbertesisk\u00A6Zande\u00A6Shan\u00A6Fon\u00A6Kalmyk\u00A6Australske sprog\u00A6Khotanesisk\u00A6Japansk\u00A6Khoisan (\u00f8vrige)\u00A6Palauansk\u00A6Cheyenne\u00A6Tai (\u00f8vrige)\u00A6Inuktitut\u00A6Papiamento\u00A6Italiensk\u00A6Tegnsprog\u00A6Islandsk\u00A6Khasi\u00A6Cherokee\u00A6Pampanga\u00A6Pahlavi\u00A6Chipewyan\u00A6Ido\u00A6Choctaw\u00A6Chinook\u00A6Mari\u00A6Tuvinian\u00A6Bantu\u00A6Pangasinan\u00A6Inupiaq\u00A6Chuukese\u00A6Sichuan Yi\u00A6Hawaiiansk\u00A6Lamba\u00A6Igbo\u00A6Chagatai\u00A6Irsk, Old- (indtil 900)\u00A6Papua-australske sprog (\u00f8vrige)\u00A6Interlingue\u00A6Indonesisk\u00A6Lahnda\u00A6Dayak\u00A6Chibcha\u00A6Interlingua\u00A6Ladino\u00A6Herero\u00A6Haida\u00A6Dargwa\u00A6Armensk\u00A6Ungarsk\u00A6Haitisk\u00A6Dakota\u00A6Kroatisk\u00A6Hiri Motu\u00A6Hindi\u00A6Dyula\u00A6Hebraisk\u00A6Asturisk\u00A6Hausa\u00A6Vendiske sprog\u00A6Manx\u00A6Gujaratisk\u00A6Semitiske sprog (\u00f8vrige)\u00A6Selkupisk\u00A6Irokesiske sprog\u00A6Guarani\u00A6Galicisk\u00A6Arawak\u00A6Geez\u00A6Kunstsprog (\u00f8vrige)\u00A6G\u00e6lisk (skotsk)\u00A6Iranske sprog (\u00f8vrige)\u00A6Irsk\u00A6Arapaho\u00A6Araukansk\u00A6Frisisk\u00A6Siksika\u00A6Germanske sprog (\u00f8vrige)\u00A6Aram\u00e6isk\u00A6Fransk\u00A6F\u00e6r\u00f8sk\u00A6Keltiske sprog (\u00f8vrige)\u00A6Fijian\u00A6Finsk\u00A6Fulah\u00A6Tuvalu\u00A6Cebuano\u00A6Persisk\u00A6Baskisk\u00A6Skotsk\u00A6Estisk\u00A6Spansk\u00A6Esperanto\u00A6Engelsk\u00A6Gr\u00e6sk\u00A6Tyrkisk-tatariske sprog (\u00f8vrige)\u00A6Niuean\u00A6Ewe\u00A6Tumbuka\u00A6Mossi\u00A6Dzongkha\u00A6Niger-Congo sprog (\u00f8vrige)\u00A6Lushai\u00A6Finsk-ugriske sprog (\u00f8vrige)\u00A6Divehi\u00A6Nias\u00A6Mohawk\u00A6Luo\u00A6Lunda\u00A6Apache sprog\u00A6Luiseno\u00A6Hupa\u00A6Bini\u00A6Tysk\u00A6Luba-Lulua\u00A6Bikol\u00A6Washo\u00A6Sproget kan ikke bestemmes\u00A6Waray\u00A6Dansk\u00A6Hollandsk (ca. 1050-1350)\u00A6Walamo\u00A6Santali\u00A6Walisisk\u00A6Sasak\u00A6Kabardian\u00A6Chuvash\u00A6Kirkeslavisk\u00A6Manipuri\u00A6Tjekkisk\u00A6Samaritansk\u00A6Cree\u00A6Duala\u00A6Korsikansk\u00A6Sydamerikanske indianske sprog (\u00f8vrige)\u00A6Manchu\u00A6Yakut\u00A6Kawi\u00A6Ingush\u00A6Gbaya\u00A6Sandawe\u00A6Chamorro\u00A6Indoeurop\u00e6iske sprog (\u00f8vrige)\u00A6Bhojpuri\u00A6Engelsk, Middel- (1100-1500)\u00A6Karen\u00A6Indiske sprog (\u00f8vrige)\u00A6Tjetjensk\u00A6Gayo\u00A6Katalansk\u00A6Umbundu\u00A6Syrisk\u00A6Kamba\u00A6Tsimshisk\u00A6Angelsaksisk (ca.450-1100)\u00A6Kachin\u00A6Kaukasiske sprog (\u00f8vrige)\u00A6Kabyle\u00A6Karakalpakisk\u00A6Bosnisk\u00A6Caribisk\u00A6Bretonsk\u00A6Tibetansk\u00A6Bengalsk\u00A6Bambara\u00A6Ga\u00A6Mellemamerikanske indianske sprog (\u00f8vrige)\u00A6Bislama\u00A6Bihari\u00A6Bulgarsk\u00A6Hviderussisk\u00A6Caddo\u00A6Bashkir\u00A6Zulu\u00A6Zenaga\u00A6Provencalsk (f\u00f8r 1500)\u00A6\u00d8vre sorbisk\u00A6Aserbajdsjan\u00A6Aymara\u00A6Avarisk\u00A6Assamesisk\u00A6Nedre sorbisk\u00A6Arabisk\u00A6Iloko\u00A6Elamitisk\u00A6Kinesisk\u00A6Aragonesisk\u00A6Amharisk\u00A6Newari\u00A6Akan\u00A6Zhuang\u00A6Afrikaans\u00A6Avestan\u00A6Abkhasisk\u00A6Afar\u00A6Yoruba\u00A6Algonkiske sprog\u00A6Aleutiske sprog\u00A6Mon-khmer (\u00f8vrige)\u00A6Jiddisch\u00A6Dravidiske sprog (\u00f8vrige)\u00A6Berberiske sprog\u00A6Nedertysk; nedersachsisk\u00A6Bemba\u00A6Beja\u00A6Tok Pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "minNumberOfDaysInFirstWeek", "4" },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "shortDateFormat", "dd-MM-yy" },
    { "mediumDateFormat", "dd-MM-yyyy" },
    { "longDateFormat", "d. MMM yyyy" },
    { "fullDateFormat", "EEEE dd MMMM yyyy" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
