/* LocaleInformation_pt_PT.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML pt_PT.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_pt_PT extends ListResourceBundle
{
  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("PS", "Territ\u00f3rio Palestiniano");
        put("MP", "Ilhas Mariana do Norte");
        put("GL", "Gronel\u00e2ndia");
        put("MO", "Macau - Regi\u00e3o Administrativa Especial da China");
        put("YU", "Jugosl\u00e1via");
        put("AE", "Emiratos \u00c1rabes Unidos");
        put("MK", "Maced\u00f3nia, Rep\u00fablica da");
        put("PL", "Pol\u00f3nia");
        put("SM", "S\u00e3o Marino");
        put("VN", "Vietname");
        put("MG", "Madag\u00e1scar");
        put("SI", "Eslov\u00e9nia");
        put("PG", "Papua Nova Guin\u00e9");
        put("MD", "Mold\u00e1via, Rep\u00fablica da");
        put("VI", "Ilhas Virgin E.U.A.");
        put("SG", "Singapura");
        put("MC", "M\u00f3naco");
        put("VG", "Ilhas Virgin Brit\u00e2nicas");
        put("CZ", "Rep\u00fablica Checa");
        put("SC", "Seicheles");
        put("CX", "Ilha do Natal");
        put("YE", "I\u00e9men");
        put("VC", "Saint Vincent e Grenadines");
        put("VA", "Santa S\u00e9 (Estado da Cidade do Vaticano)");
        put("LV", "Let\u00f3nia");
        put("UZ", "Uzbaquist\u00e3o");
        put("CM", "Camar\u00f5es");
        put("FK", "Ilhas Falkland");
        put("RO", "Rom\u00e9nia");
        put("UM", "Ilhas Minor Outlying (E.U.A)");
        put("RE", "Reunion");
        put("LA", "Lao, Rep\u00fablica Popular Democr\u00e1tica");
        put("BY", "Bielorr\u00fassia");
        put("KZ", "Cazaquist\u00e3o");
        put("KY", "Ilhas Caim\u00e3o");
        put("ER", "Eritreia");
        put("KR", "Coreia do Sul");
        put("KP", "Coreia do Norte");
        put("BJ", "Benim");
        put("KN", "Saint Kitts e Nevis");
        put("HK", "Hong Kong - Regi\u00e3o Administrativa Especial da China");
        put("EH", "Sahara Ocidental");
        put("EG", "Egipto");
        put("EE", "Est\u00f3nia");
        put("TM", "Turquemenist\u00e3o");
        put("KG", "Quirguizist\u00e3o");
        put("BA", "B\u00f3snia-Herzegovina");
        put("KE", "Qu\u00e9nia");
        put("TJ", "Tajiquist\u00e3o");
        put("NC", "Nova Caled\u00f3nia");
        put("AZ", "Azerbeij\u00e3o");
        put("TF", "Territ\u00f3rios Franceses a Sul");
        put("TD", "Tchade");
        put("TC", "Ilhas Turcas e Caicos");
        put("GW", "Guin\u00e9-Bissau");
        put("AQ", "Ant\u00e1rctica");
        put("GS", "Ilhas South Georgia e South Sandwich");
        put("MU", "Maur\u00edcias");
        put("AM", "Arm\u00e9nia");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "currencyFormat", "#,##0.00 \u00a4;-#,##0.00 \u00a4" },
    { "shortDateFormat", "yy/MM/dd" },
    { "mediumDateFormat", "yyyy/MM/dd" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
