/* LocaleInformation_ms.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_ms extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "MYR";

  private static final String currenciesDisplayNameValues = "Ringgit Malaysia";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "|");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "MYR";

  private static final String currenciesSymbolValues = "RM";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "|");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "Jan",
    "Feb",
    "Mac",
    "Apr",
    "Mei",
    "Jun",
    "Jul",
    "Ogos",
    "Sep",
    "Okt",
    "Nov",
    "Dis",
    null,
  };

  private static final String[] months = {
    "Januari",
    "Februari",
    "Mac",
    "April",
    "Mei",
    "Jun",
    "Julai",
    "Ogos",
    "September",
    "Oktober",
    "November",
    "Disember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Ahd",
    "Isn",
    "Sel",
    "Rab",
    "Kha",
    "Jum",
    "Sab",
  };

  private static final String[] weekdays = {
    null,
    "Ahad",
    "Isnin",
    "Selasa",
    "Rabu",
    "Khamis",
    "Jumaat",
    "Sabtu",
  };

  private static final String territoriesKeys = "TL|TK|TJ|TH|TG|TF|GY|TD|TC|GW|GU|GT|GS|GR|GQ|GP|SZ|SY|GN|GM|GL|SV|ST|GI|GH|SR|GF|SP|GE|SO|GD|SN|SM|GB|SL|GA|SK|SJ|SI|SH|SG|SE|SD|SC|SB|SA|FR|FO|FM|RW|FK|RU|FJ|FI|RO|RE|ET|ES|ER|EH|EG|EE|EC|DZ|QA|DO|PY|DM|PW|DK|DJ|PT|PS|PR|DE|PN|PM|PL|PK|PH|PG|PF|CZ|PE|CY|CX|CV|PA|CU|CR|CO|CN|CM|CL|CK|CI|CH|CG|CF|CD|CC|OM|CA|BZ|BY|BW|BV|BT|BS|BR|NZ|BO|BN|BM|NU|BJ|BI|BH|NR|BG|BF|NP|BE|NO|BD|BB|ZW|NL|BA|NI|NG|NF|AZ|NE|NC|AW|ZM|NA|AU|AT|AS|AR|AQ|MZ|AO|MY|AN|MX|AM|MW|AL|MV|ZA|MU|MT|AI|MS|MR|AG|MQ|AF|MP|AE|MO|AD|MN|MM|ML|MK|YU|YT|MH|MG|MD|MC|MA|YE|LY|LV|LU|LT|LS|LR|LK|LI|LC|LB|LA|KZ|KY|KW|KR|KP|KN|KM|KI|WS|KH|KG|KE|WF|JP|JO|JM|VU|VN|VI|VG|VE|VC|VA|IT|IS|IR|IQ|UZ|IO|UY|IN|IL|US|IE|ID|UM|UG|UA|HU|HT|HR|TZ|HN|HM|TW|TV|HK|TT|TR|TO|TN|TM";

  private static final String territoriesValues = "Timor-Leste|Tokelau|Tadjikistan|Thailand|Togo|French Southern Territories|Guyana|Cad|Turks and Caicos Islands|Guinea Bissau|Guam|Guatemala|South Georgia and the South Sandwich Islands|Yunani|Equatorial Guinea|Guadeloupe|Swaziland|Syria|Guinea|Gambia|Greenland|El Salvador|Sao Tome dan Principe|Gibraltar|Ghana|Surinam|French Guiana|Serbia|Georgia|Somalia|Grenada|Senegal|San Marino|United Kingdom|Siera Leon|Gabon|Slovakia|Svalbard and Jan Mayen|Slovenia|Saint Helena|Singapura|Sweden|Sudan|Seychelles|Kepulauan Solomon|Arab Saudi|Perancis|Faroe Islands|Micronesia|Rwanda|Falkland Islands|Russia|Fiji|Finland|Romania|R\u00e9union|Ethiopia|Sepanyol|Eritrea|Sahara Barat|Mesir|Estonia|Ecuador|Aljazair|Qatar|Republik Dominican|Paraguay|Dominica|Palau|Denmark|Jibouti|Feringgi|Palestinian Territory|Puerto Rico|Jerman|Pitcairn|Saint Pierre and Miquelon|Poland|Pakistan|Filipina|Papua New Guinea|French Polynesia|Republik Czech|Peru|Kibris|Christmas Island|Cape Verde|Panama|Cuba|Kosta Rika|Colombia|Cina|Kamerun|Cile|Cook Islands|Pantai Gading|Switzerland|Congo|Republik Afrika Tengah|Democratic Republic of the Congo|Cocos (Keeling) Islands|Oman|Kanada|Belize|Belarus|Botswana|Bouvet Island|Bhutan|Bahamas|Brazil|New Zealand|Bolivia|Brunei|Bermuda|Niue|Benin|Burundi|Bahrain|Nauru|Bulgaria|Burkina Faso|Nepal|Belgium|Norway|Bangladesh|Barbados|Zimbabwe|Belanda|Bosnia dan Herzegovina|Nicaragua|Nigeria|Norfolk Island|Azerbaijan|Niger|New Caledonia|Aruba|Zambia|Namibia|Australia|Austria|American Samoa|Argentina|Antarctica|Mozambik|Angola|Malaysia|Netherlands Antilles|Meksiko|Armenia|Malawi|Albania|Maldiv|Afrika Selatan|Mauritius|Malta|Anguilla|Montserrat|Mauritania|Antigua dan Barbuda|Martinique|Afghanistan|Northern Mariana Islands|Emiriah Arab Bersatu|Macao S.A.R., China|Andorra|Mongolia|Myanmar|Mali|Macedonia|Yugoslavia|Mayotte|Kepulauan Marshall|Madagaskar|Moldova|Monaco|Maghribi|Yaman|Libya|Latvia|Luksembourg|Lithuania|Lesotho|Liberia|Sri Lanka|Liechtenstein|Saint Lucia|Lubnan|Laos|Kazakhstan|Cayman Islands|Kuwait|Selatan Korea|Utara Korea|Saint Kitts dan Nevis|Comoros|Kiribati|Samoa|Kemboja|Kyrgyzstan|Kenya|Wallis and Futuna|Jepun|Jordan|Jamaika|Vanuatu|Vietnam|U.S. Virgin Islands|British Virgin Islands|Venezuela|Saint Vincent dan Grenadines|Vatican|Itali|Iceland|Iran|Iraq|Uzbekistan|British Indian Ocean Territory|Uruguay|Hindia|Israel|Amerika Syarikat|Ireland|Indonesia|United States Minor Outlying Islands|Uganda|Ukraine|Hungari|Haiti|Croatia|Tanzania|Honduras|Heard Island and McDonald Islands|Taiwan|Tuvalu|Hong Kong S.A.R., China|Trinidad dan Tobago|Turki|Tonga|Tunisia|Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "|");
    Enumeration values = new StringTokenizer(territoriesValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "ms";

  private static final String languagesValues = "Bahasa Melayu";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "|");
    Enumeration values = new StringTokenizer(languagesValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
