/* LocaleInformation_es.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML es.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_es extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "ene",
    "feb",
    "mar",
    "abr",
    "may",
    "jun",
    "jul",
    "ago",
    "sep",
    "oct",
    "nov",
    "dic",
    null,
  };

  private static final String[] months = {
    "enero",
    "febrero",
    "marzo",
    "abril",
    "mayo",
    "junio",
    "julio",
    "agosto",
    "septiembre",
    "octubre",
    "noviembre",
    "diciembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dom",
    "lun",
    "mar",
    "mi\u00e9",
    "jue",
    "vie",
    "s\u00e1b",
  };

  private static final String[] weekdays = {
    null,
    "domingo",
    "lunes",
    "martes",
    "mi\u00e9rcoles",
    "jueves",
    "viernes",
    "s\u00e1bado",
  };

  private static final String[] eras = {
    "a.C.",
    "d.C.",
  };

  private static final String[][] zoneStrings =
  {
    { "America/Los_Angeles", "Hora est\u00e1ndar del Pac\u00edfico", "PST", "Hora de verano del Pac\u00edfico", "PDT" },
    { "Africa/Casablanca", "Hora media de Greenwich", "GMT", "Hora media de Greenwich", "GMT" },
    { "America/New_York", "Hora est\u00e1ndar oriental", "EST", "Hora de verano oriental", "EDT" },
    { "America/Anchorage", "Hora est\u00e1ndar de Alaska", "AST", "Hora de verano de Alaska", "ADT" },
    { "Etc/GMT", "Hora media de Greenwich", "GMT", "Hora media de Greenwich", "GMT" },
    { "Asia/Shanghai", "Hora est\u00e1ndar de China", "CTT", "Hora est\u00e1ndar de China", "CDT" },
    { "America/Halifax", "Hora est\u00e1ndar del Atl\u00e1ntico", "AST", "Hora de verano del Atl\u00e1ntico", "ADT" },
    { "Europe/Paris", "Hora est\u00e1ndar de Europa Central", "CET", "Hora de verano de Europa Central", "CEST" },
    { "America/Denver", "Hora est\u00e1ndar de Monta\u00f1a", "MST", "Hora de verano de Monta\u00f1a", "MDT" },
    { "Asia/Jerusalem", "Hora est\u00e1ndar de Israel", "IST", "Hora de verano de Israel", "IDT" },
    { "America/St_Johns", "Hora est\u00e1ndar de Newfoundland", "CNT", "Hora de verano de Newfoundland", "CDT" },
    { "Pacific/Honolulu", "Hora est\u00e1ndar de Hawai", "HST", "Hora est\u00e1ndar de Hawai", "HST" },
    { "America/Indianapolis", "Hora est\u00e1ndar oriental", "EST", "Hora est\u00e1ndar oriental", "EST" },
    { "America/Chicago", "Hora est\u00e1ndar central", "CST", "Hora de verano central", "CDT" },
    { "Europe/Bucharest", "Hora est\u00e1ndar de Europa del Este", "EET", "Hora de verano de Europa del Este", "EEST" },
    { "Asia/Tokyo", "Hora est\u00e1ndar de Jap\u00f3n", "JST", "Hora est\u00e1ndar de Jap\u00f3n", "JST" },
    { "America/Phoenix", "Hora est\u00e1ndar de Monta\u00f1a", "MST", "Hora est\u00e1ndar de Monta\u00f1a", "MST" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor Oriental");
        put("TK", "Islas Tokelau");
        put("TJ", "Tayikist\u00e1n");
        put("TH", "Tailandia");
        put("TG", "Togo");
        put("TF", "Territorios Australes Franceses");
        put("GY", "Guyana");
        put("TD", "Chad");
        put("TC", "Islas Turcas y Caicos");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Islas Georgia del Sur y Sandwich del Sur");
        put("GR", "Grecia");
        put("GQ", "Guinea Ecuatorial");
        put("GP", "Guadalupe");
        put("SZ", "Suazilandia");
        put("SY", "Siria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Groenlandia");
        put("SV", "El Salvador");
        put("ST", "Santo Tom\u00e9 y Pr\u00edncipe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Guayana Francesa");
        put("SP", "Serbia");
        put("GE", "Georgia");
        put("SO", "Somalia");
        put("GD", "Granada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Reino Unido");
        put("SL", "Sierra Leona");
        put("GA", "Gab\u00f3n");
        put("SK", "Eslovaquia");
        put("SJ", "Svalbard y Jan Mayen");
        put("SI", "Eslovenia");
        put("SH", "Santa Elena");
        put("SG", "Singapur");
        put("SE", "Suecia");
        put("SD", "Sud\u00e1n");
        put("SC", "Seychelles");
        put("SB", "Islas Salom\u00f3n");
        put("SA", "Arabia Saud\u00ed");
        put("FR", "Francia");
        put("FO", "Islas Feroe");
        put("FM", "Micronesia");
        put("RW", "Ruanda");
        put("FK", "Islas Falkland (Malvinas)");
        put("RU", "Rusia");
        put("FJ", "Fiyi");
        put("FI", "Finlandia");
        put("RO", "Ruman\u00eda");
        put("RE", "R\u00e9union");
        put("ET", "Etiop\u00eda");
        put("ES", "Espa\u00f1a");
        put("ER", "Eritrea");
        put("EH", "S\u00e1hara Occidental");
        put("EG", "Egipto");
        put("EE", "Estonia");
        put("EC", "Ecuador");
        put("DZ", "Argelia");
        put("QA", "Qatar");
        put("DO", "Rep\u00fablica Dominicana");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Dinamarca");
        put("DJ", "Yibuti");
        put("PT", "Portugal");
        put("PS", "Territorios Palestinos");
        put("PR", "Puerto Rico");
        put("DE", "Alemania");
        put("PN", "Pitcairn");
        put("PM", "San Pedro y Miquel\u00f3n");
        put("PL", "Polonia");
        put("PK", "Pakist\u00e1n");
        put("PH", "Filipinas");
        put("PG", "Pap\u00faa Nueva Guinea");
        put("PF", "Polinesia Francesa");
        put("CZ", "Rep\u00fablica Checa");
        put("PE", "Per\u00fa");
        put("CY", "Chipre");
        put("CX", "Isla Navidad");
        put("CV", "Cabo Verde");
        put("PA", "Panam\u00e1");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "China");
        put("CM", "Camer\u00fan");
        put("CL", "Chile");
        put("CK", "Islas Cook");
        put("CI", "Costa de Marfil");
        put("CH", "Suiza");
        put("CG", "Congo");
        put("CF", "Rep\u00fablica Centroafricana");
        put("CD", "Rep\u00fablica Democr\u00e1tica del Congo");
        put("CC", "Islas Cocos (Keeling)");
        put("OM", "Om\u00e1n");
        put("CA", "Canad\u00e1");
        put("BZ", "Belice");
        put("BY", "Bielorrusia");
        put("BW", "Botsuana");
        put("BV", "Isla Bouvet");
        put("BT", "But\u00e1n");
        put("BS", "Bahamas");
        put("BR", "Brasil");
        put("NZ", "Nueva Zelanda");
        put("BO", "Bolivia");
        put("BN", "Brun\u00e9i");
        put("BM", "Bermudas");
        put("NU", "Isla Niue");
        put("BJ", "Ben\u00edn");
        put("BI", "Burundi");
        put("BH", "Bahr\u00e1in");
        put("NR", "Nauru");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "B\u00e9lgica");
        put("NO", "Noruega");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabue");
        put("NL", "Pa\u00edses Bajos");
        put("BA", "Bosnia-Herzegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Isla Norfolk");
        put("AZ", "Azerbaiy\u00e1n");
        put("NE", "N\u00edger");
        put("NC", "Nueva Caledonia");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australia");
        put("AT", "Austria");
        put("AS", "Samoa Americana");
        put("AR", "Argentina");
        put("AQ", "Ant\u00e1rtida");
        put("MZ", "Mozambique");
        put("AO", "Angola");
        put("MY", "Malasia");
        put("AN", "Antillas Neerlandesas");
        put("MX", "M\u00e9xico");
        put("AM", "Armenia");
        put("MW", "Malawi");
        put("AL", "Albania");
        put("MV", "Maldivas");
        put("ZA", "Sud\u00e1frica");
        put("MU", "Mauricio");
        put("MT", "Malta");
        put("AI", "Anguila");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("AG", "Antigua y Barbuda");
        put("MQ", "Martinica");
        put("AF", "Afganist\u00e1n");
        put("MP", "Islas Marianas del Norte");
        put("AE", "Emiratos \u00c1rabes Unidos");
        put("MO", "Macao, Regi\u00f3n administrativa especial de China");
        put("AD", "Andorra");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mal\u00ed");
        put("MK", "Macedonia");
        put("YU", "Yugoslavia");
        put("YT", "Mayotte");
        put("MH", "Islas Marshall");
        put("MG", "Madagascar");
        put("MD", "Moldova");
        put("MC", "M\u00f3naco");
        put("MA", "Marruecos");
        put("YE", "Yemen");
        put("LY", "Libia");
        put("LV", "Letonia");
        put("LU", "Luxemburgo");
        put("LT", "Lituania");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "L\u00edbano");
        put("LA", "Laos");
        put("KZ", "Kazajst\u00e1n");
        put("KY", "Islas Caim\u00e1n");
        put("KW", "Kuwait");
        put("KR", "Corea del Sur");
        put("KP", "Corea del Norte");
        put("KN", "San Crist\u00f3bal y Nieves");
        put("KM", "Comoras");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Camboya");
        put("KG", "Kirguizist\u00e1n");
        put("KE", "Kenia");
        put("WF", "Wallis y Futuna");
        put("JP", "Jap\u00f3n");
        put("JO", "Jordania");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Islas V\u00edrgenes de los Estados Unidos");
        put("VG", "Islas V\u00edrgenes Brit\u00e1nicas");
        put("VE", "Venezuela");
        put("VC", "San Vicente y las Granadinas");
        put("VA", "Ciudad del Vaticano");
        put("IT", "Italia");
        put("IS", "Islandia");
        put("IR", "Ir\u00e1n");
        put("IQ", "Iraq");
        put("UZ", "Uzbekist\u00e1n");
        put("IO", "Territorios Brit\u00e1nico del Oc\u00e9ano \u00cdndico");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Israel");
        put("US", "Estados Unidos");
        put("IE", "Irlanda");
        put("ID", "Indonesia");
        put("UM", "Islas menores alejadas de los Estados Unidos");
        put("UG", "Uganda");
        put("UA", "Ucrania");
        put("HU", "Hungr\u00eda");
        put("HT", "Hait\u00ed");
        put("HR", "Croacia");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Islas Heard y McDonald");
        put("TW", "Taiw\u00e1n");
        put("TV", "Tuvalu");
        put("HK", "Hong-Kong, Regi\u00f3n administrativa especial de China");
        put("TT", "Trinidad y Tabago");
        put("TR", "Turqu\u00eda");
        put("TO", "Tonga");
        put("TN", "T\u00fanez");
        put("TM", "Turkmenist\u00e1n");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "currencyFormat", "\u00a4#,##0.00;(\u00a4#,##0.00)" },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "d/MM/yy" },
    { "mediumDateFormat", "dd-MMM-yy" },
    { "longDateFormat", "d' de 'MMMM' de 'yyyy" },
    { "fullDateFormat", "EEEE d' de 'MMMM' de 'yyyy" },
    { "fullTimeFormat", "HH'H'mm''ss\" z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
