/* LocaleInformation_fr.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_fr extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "dinar jordanien\u00A6Bolivian Mvdol\u00A6Or\u00A6Faeroe Islands Kronur\u00A6livre libanaise\u00A6euro\u00A6dong\u00A6shilling de Tanzanie\u00A6peso bolivien\u00A6riel\u00A6unit\u00e9 mon\u00e9taire asiatique\u00A6boliviano (1863-1962)\u00A6vieux riel\u00A6livre zambienne\u00A6livre australienne\u00A6franc CFA (BEAC)\u00A6livre maltaise\u00A6cedi revaloris\u00e9\u00A6kwacha\u00A6dinar asiatique (unit\u00e9 de compte)\u00A6livre ghan\u00e9enne\u00A6boliviano\u00A6ancien cedi\u00A6lire maltaise\u00A6dollar australien\u00A6dollar des Etats-Unis (jour m\u00eame)\u00A6lire italienne\u00A6dollar des Etats-Unis (jour suivant)\u00A6c\u00e9di\u00A6dollar de Singapour\u00A6balboa\u00A6kip\u00A6som du Kyrgystan\u00A6franc suisse\u00A6schilling autrichien\u00A6dollar des \u00c9tats-Unis\u00A6dollar \u00e9thiopien\u00A6dollar de Brunei\u00A6livre jama\u00efcaine\u00A6birr\u00A6franc germinal alg\u00e9rien\u00A6nouveau franc alg\u00e9rien\u00A6dinar alg\u00e9rien\u00A6guarani\u00A6livre libyenne\u00A6dollar jama\u00efcain\u00A6couronne islandaise\u00A6peseta espagnole\u00A6livre des Bermudes\u00A6dinar Iibyen\u00A6lire de l\u2019autori\u00e9 militaire britannique de Libye\u00A6dollar des Bermudes\u00A6florin n\u00e9erlandais\u00A6ouguija\u00A6rial iranien\u00A6couronne su\u00e9doise\u00A6Eritrean Nakfa\u00A6shilling du Kenya\u00A6franc CFA de la R\u00e9publique du Centre Afrique\u00A6peso argentin\u00A6peso argentin (1983-1985)\u00A6Argentine Peso Moneda Nacional\u00A6dollar ta\u00efwanais\u00A6livre soudanaise\u00A6lari\u00A6Georgian Kupon Larit\u00A6franc martiniquais\u00A6livre des Falkland (Malvinas)\u00A6austral\u00A6dinar soudanais\u00A6dinar irakien\u00A6dollar du Tuvalu\u00A6roupie des Seychelles\u00A6rouble letton\u00A6livre de Fiji\u00A6lats letton\u00A6Congolese Zaire\u00A6franc de la R\u00e9publique Congolaise\u00A6franc congolais\u00A6dollar de Fidji\u00A6cordoba d\u2019or\u00A6pataca\u00A6cordoba d\u2019or\u00A6cordoba\u00A6rouble transf\u00e9rable du COMECON\u00A6mark finlandais (1860-1962)\u00A6mark finlandais\u00A6dollar de Salomon\u00A6franc luxembourgeois\u00A6vieux dollar de la Trinit\u00e9\u00A6escudo angolais\u00A6kwanza angolais r\u00e9ajust\u00e9 (1995-1999)\u00A6tugrik\u00A6forint\u00A6franc du Burundi\u00A6nouveau kwanza angolais (1990-2000)\u00A6kwanza angolais (1977-1990)\u00A6dollar de la Trinit\u00e9\u00A6lilangeni\u00A6franc CFP des Nouvelles H\u00e9brides\u00A6livre sterling\u00A6riyal saoudien\u00A6riyal s\u00e9oudien\u00A6Talonas de Lithuanie\u00A6roupie indienne\u00A6escudo portugais\u00A6kwanza angolais\u00A6conto portugais\u00A6Lita de Lithuanian\u00A6tenge du Kazakhstan\u00A6rouble du Kazakhstan\u00A6dollar des \u00eeles Vierges britanniques\u00A6livre nig\u00e9riane\u00A6dollar de Myanmar (certificat de devises \u00e9trang\u00e8res)\u00A6naira\u00A6gourde\u00A6livre syrienne\u00A6livre palestinienne\u00A6dinar de Bahrein\u00A6Myanmar Kyat\u00A6florin des Antilles n\u00e9erl.\u00A6couronne tch\u00e8que\u00A6livre sterling de l\u2019Ile de Man\u00A6lev (certificat de devises \u00e9trang\u00e8res)\u00A6Lesotho Loti\u00A6franc CFA gabonnais\u00A6lev (1879-1952)\u00A6nouveau lef\u00A6lev de Bulgarie socialiste\u00A6dollar canadien\u00A6lev\u00A6livre turque\u00A6dollar des \u00eeles Ca\u00efmans\u00A6livre cypriote\u00A6sh\u00e9kel\u00A6dollar de Guyane\u00A6dram arm\u00e9nien\u00A6livre isra\u00e9lienne\u00A6franc malien\u00A6sh\u00e9kel\u00A6bolivar\u00A6dollar albanais (certificat de devises \u00e9trang\u00e8res)\u00A6dollar lib\u00e9rien\u00A6Albanian Lek Valute\u00A6kuna\u00A6franc de la R\u00e9union\u00A6dinar croate\u00A6lek albanais\u00A6livre sterling de Jersey\u00A6lek albanais (1946-1961)\u00A6dinar mac\u00e9donien (1992-1993)\u00A6North Vietnam Viet Minh Piastre Dong Viet\u00A6nouveau dong nord-vietnamien\u00A6dinar mac\u00e9donien\u00A6North Vietnam Piastre Dong Viet\u00A6pataca de Timor\u00A6franc CFP\u00A6franc belge (financier)\u00A6peso de Guin\u00e9e-Bissau\u00A6dinar koweitien\u00A6Portuguese Guinea Mil Reis\u00A6franc belge\u00A6escudo de Timor\u00A6franc belge (convertible)\u00A6Escudo de Guin\u00e9e Portugaise\u00A6colon\u00A6florin de Curacao\u00A6taka\u00A6livre sterling du Tonga\u00A6pa\u02bbanga\u00A6franc CFA (BCEAO)\u00A6rouble de C.E.I.\u00A6nouveau rouble sovi\u00e9tique\u00A6franc Germinal de Nouvelle Cal\u00e9donie\u00A6escudo du Cap-Vert\u00A6franc CFA antillais\u00A6rand\u00A6peso dominicain\u00A6certificat de devises \u00e9trang\u00e8res de Cuba\u00A6livre sud-africaine\u00A6rand sud-africain (financier)\u00A6dinar tunisien\u00A6peso cubain\u00A6franc guyanais\u00A6shilling ougandais\u00A6roupie de Ceylan\u00A6franc Affars et Issas\u00A6lire du Vatican\u00A6escudo de Sao Tom\u00e9 et Principe\u00A6shilling ougandais (1966-1987)\u00A6dobra\u00A6dollar des  \u00eeles Marshall\u00A6livre n\u00e9o-z\u00e9landaise\u00A6tala\u00A6livre du Samoa\u00A6lempira\u00A6nouveau franc m\u00e9tropolitain\u00A6Turkmenistan Manat\u00A6quetzal\u00A6dollar n\u00e9o-z\u00e9landais\u00A6livre \u00e9cossaise\u00A6dollar de Barbade\u00A6dollar de Namibie\u00A6franc malgache\u00A6ariary malgache\u00A6livre \u00e9gyptienne\u00A6dollar du Honduras britannique\u00A6zloty (1950-1995)\u00A6nouveau dinar de Bosnie-Herzegovine\u00A6dollar US polonais (certificat de devises \u00e9trang\u00e8res)\u00A6mark convertible de Bosnie-Herzegovine\u00A6dollar de B\u00e9lize\u00A6dinar de Bosnie-Herzegovine\u00A6riyal du Y\u00e9men\u00A6florin du Surinam\u00A6couronne tch\u00e8que\u00A6won sud-cor\u00e9en\u00A6rouble bi\u00e9lorusse\u00A6riyal du Y\u00e9men\u00A6rouble bi\u00e9lorusse (1992-1994)\u00A6couronne tch\u00e8que\u00A6vieux won\u00A6hwan\u00A6nouveau rouble bi\u00e9lorusse (1994-1999)\u00A6shilling de Somalie\u00A6nouveau drachme\u00A6roupie du Pakistan\u00A6afghani\u00A6dollar du Zimbabwe\u00A6roupie de Sri Lanka\u00A6drachme\u00A6livre irlandaise\u00A6afghani\u00A6dinar du Y\u00e9men\u00A6franc du Rwanda\u00A6colon\u00A6somoni du Tadjikistan\u00A6rouble du Tadjikistan\u00A6couronne estonienne\u00A6peseta de Guin\u00e9e Equatoriale\u00A6rouble moldave\u00A6dollar de Hong Kong\u00A6couronne danoise\u00A6leu moldave\u00A6franco de Guin\u00e9e Equatoriale\u00A6ekw\u00e9l\u00e9\u00A6rupiah\u00A6dirham des \u00c9mirats arabes unis\u00A6won nord-cor\u00e9en\u00A6nouvelle roupie indon\u00e9sienne\u00A6pula\u00A6Moldovan Leu Cupon\u00A6roupie de Java\u00A6won du peuple nord-cor\u00e9en\u00A6florin de Nica\u00A6vatu\u00A6dinar musulman\u00A6shilling de Somalie\u00A6peseta andorrane\u00A6rouble de Russie (1991-1998)\u00A6franc guadeloup\u00e9en\u00A6franc de Djibouti\u00A6diner andorran\u00A6franc Germinal mon\u00e9gasque\u00A6nouveau franc marocain\u00A6unit\u00e9 de valeur constante \u00e9quatoriale (UVC)\u00A6sucre\u00A6franc du Liechtenstein\u00A6peso philippin\u00A6sum\u00A6peso colombien\u00A6baht\u00A6livre d\u2019Irlande du Nord\u00A6roupie de Birmanie\u00A6franc CFA congolais\u00A6kyat\u00A6Colombian Paper Peso\u00A6Uzbekistan Coupon Som\u00A6karbovanetz\u00A6rial du Qatar\u00A6hryvnia\u00A6syli\u00A6Yuan Ren-min-bi\u00A6m\u00e9tical\u00A6dollar US chinois (certificat de devises \u00e9trang\u00e8res)\u00A6peso uruguayen\u00A6franc guin\u00e9en (1960-1972)\u00A6lire de Saint-Marin\u00A6Chinese Jen Min Piao Yuan\u00A6escudo du Mozambique\u00A6franc guin\u00e9en\u00A6Oman Rial Saidi\u00A6kina\u00A6rial omani\u00A6peso uruguayen (1975-1993)\u00A6franc UIC\u00A6roupie de Bhoutan\u00A6za\u00efre\u00A6franc marocain\u00A6dirham marocain\u00A6ngultrum\u00A6franc or\u00A6peso fort uruguayen\u00A6ringgit\u00A6nouveau za\u00efre\u00A6Azerbaijanian Manat\u00A6livre de Gambie\u00A6franc des Comores\u00A6l\u00e9one\u00A6dalasie\u00A6unit\u00e9 de compte europ\u00e9enne (ECU)\u00A6livre des Bahamas\u00A6franc CFA camerounais\u00A6unit\u00e9 de conversion mexicaine (UDI)\u00A6franc CFA (BCEAEC)\u00A6dollar des Bahamas\u00A6peso d\u2019argent mexicain (1861-1992)\u00A6sol p\u00e9ruvien\u00A6couronne du Groenland\u00A6cruzeiro (1942-1967)\u00A6nouveau sol p\u00e9ruvien\u00A6peso chilien\u00A6couronne slovaque\u00A6Inti p\u00e9ruvien\u00A6cruzeiro\u00A6franc germinal/franc Poincar\u00e9\u00A6franc fran\u00e7ais\u00A6nouveau cruzado\u00A6Chilean Unidades de Fomento\u00A6escudo chilien\u00A6r\u00e9al\u00A6condor chilien\u00A6cruzeiro (1990-1993)\u00A6sperrmark allemand\u00A6livre de Malawi\u00A6cruzeiro\u00A6nouveau cruzeiro (1967-1986)\u00A6kwacha\u00A6rouble moldave\u00A6deutsche mark\u00A6franc CFA du Tchad\u00A6nouveau rouble moldave\u00A6Transdniestria Ruble Kupon\u00A6roupie du N\u00e9pal\u00A6dollar des \u00eeles Cook\u00A6yen\u00A6roupie des Maldives\u00A6nouveau franc CFA\u00A6roupie des Maldives\u00A6dollar des Cara\u00efbes\u00A6tolar slov\u00e8ne\u00A6dinar yougoslave r\u00e9form\u00e9\u00A6florin d\u2019Aruba\u00A6dinar yougoslave d\u2019Octobre\u00A6mark est-allemand\u00A6dinar yougoslave convertible\u00A6dinar yougoslave Noviy\u00A6couronne des \u00eeles Turks et Ca\u00efques\u00A6dinar yougoslave 1994\u00A6dinar de la F\u00e9d\u00e9ration Yougoslave\u00A6nouveau leu\u00A6nouveau dinar yougoslave\u00A6leu\u00A6bons de tolar slov\u00e8ne\u00A6couronne norv\u00e9gienne\u00A6roupie de l\u2019\u00eele Maurice\u00A6unit\u00e9 de compte europ\u00e9enne (XBD)\u00A6livre de Gibraltar\u00A6dong national du Vietnam\u00A6unit\u00e9 de compte europ\u00e9enne (XBC)\u00A6dong de la R\u00e9publique Vietnamienne\u00A6unit\u00e9 mon\u00e9taire europ\u00e9enne\u00A6unit\u00e9 composite europ\u00e9enne\u00A6dollar de Kiribati\u00A6livre de Sainte-H\u00e9l\u00e8ne\u00A6nouveau dong vietnamien";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6GNF\u00A6PGK\u00A6OMS\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6Bs\u00A6GHO\u00A6Lm\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6som\u00A6sFr.\u00A6ATS\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6FB\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6KM\u00A6BZD\u00A6BAD\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6Af\u00A6Z$\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6GF\u00A6PGK\u00A6OMS\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6Nu\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRG\u00A6F\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "janv.",
    "f\u00e9vr.",
    "mars",
    "avr.",
    "mai",
    "juin",
    "juil.",
    "ao\u00fbt",
    "sept.",
    "oct.",
    "nov.",
    "d\u00e9c.",
    null,
  };

  private static final String[] months = {
    "janvier",
    "f\u00e9vrier",
    "mars",
    "avril",
    "mai",
    "juin",
    "juillet",
    "ao\u00fbt",
    "septembre",
    "octobre",
    "novembre",
    "d\u00e9cembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dim.",
    "lun.",
    "mar.",
    "mer.",
    "jeu.",
    "ven.",
    "sam.",
  };

  private static final String[] weekdays = {
    null,
    "dimanche",
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
  };

  private static final String[] eras = {
    "av. J.-C.",
    "ap. J.-C.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "HNE (\u00c9UA)", "Heure normale de l\u2019Est (\u00c9UA)", "HAE (\u00c9UA)", "Heure avanc\u00e9e de l\u2019Est (\u00c9UA)"},
    {  "America/Halifax", "HNA", "Heure normale de l\u2019Atlantique", "HAA", "Heure avanc\u00e9e de l\u2019Atlantique"},
    {  "Pacific/Honolulu", "HST", "Heure normale d\u2019Hawa\u00ef", "HDT", "Heure avanc\u00e9e d\u2019Hawa\u00ef"},
    {  "America/Denver", "HNR (\u00c9UA)", "Heure normale des Rocheuses (\u00c9UA)", "HAR (\u00c9UA)", "Heure avanc\u00e9e des Rocheuses (\u00c9UA)"},
    {  "America/Winnipeg", "HNC", "Heure normale du Centre", "HAC", "Heure avanc\u00e9e du Centre"},
    {  "America/Anchorage", "HNAK", "Heure normale de l\u2019Alaska", "HAAK", "Heure avanc\u00e9e de l\u2019Alaska"},
    {  "America/Montreal", "HNE", "Heure normale de l\u2019Est", "HAE", "Heure avanc\u00e9e de l\u2019Est"},
    {  "America/St_Johns", "HNT", "Heure normale de Terre-Neuve", "HAT", "Heure avanc\u00e9e de Terre-Neuve"},
    {  "America/Edmonton", "HNR", "Heure normale des Rocheuses", "HAR", "Heure avanc\u00e9e des Rocheuses"},
    {  "America/Chicago", "HNC (\u00c9UA)", "Heure normale du Centre (\u00c9UA)", "HAC (\u00c9UA)", "Heure avanc\u00e9e du Centre (\u00c9UA)"},
    {  "Asia/Shanghai", "HNC", "Heure normale de Chine", "HAC", "Heure avanc\u00e9e de Chine"},
    {  "America/Vancouver", "HNP", "Heure normale du Pacifique", "HAP", "Heure avanc\u00e9e du Pacifique"},
    {  "Asia/Tokyo", "HNJ", "Heure normale du Japon", "HAJ", "Heure avanc\u00e9e du Japon"},
    {  "America/New_York", "HNE (\u00c9UA)", "Heure normale de l\u2019Est (\u00c9UA)", "HAE (\u00c9UA)", "Heure avanc\u00e9e de l\u2019Est (\u00c9UA)"},
    {  "Europe/Bucharest", "HEE", "Heure normale de l\u2019Europe de l\u2019Est", "HAEE", "Heure avanc\u00e9e de l\u2019Europe de l\u2019Est"},
    {  "America/Los_Angeles", "HNP (\u00c9UA)", "Heure normale du Pacifique (\u00c9UA)", "HAP (\u00c9UA)", "Heure avanc\u00e9e du Pacifique (\u00c9UA)"},
    {  "America/Phoenix", "HNR (\u00c9UA)", "Heure normale des Rocheuses (\u00c9UA)", "HAR (\u00c9UA)", "Heure avanc\u00e9e des Rocheuses (\u00c9UA)"},
    {  "Etc/GMT", "GMT", "Temps Moyen de Greenwich", "GMT", "Temps Moyen de Greenwich"},
    {  "Asia/Jerusalem", "HNI", "Heure normale d\u2019Isra\u00ebl", "HAI", "Heure avanc\u00e9e d\u2019Isra\u00ebl"},
    {  "Europe/Paris", "HNEC", "Heure normale de l\u2019Europe centrale", "HAEC", "Heure avanc\u00e9e de l\u2019Europe centrale"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6062\u00A6ST\u00A6GI\u00A6061\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6057\u00A6FM\u00A6RW\u00A6054\u00A6FK\u00A6053\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6833\u00A6EG\u00A6EE\u00A6830\u00A6EC\u00A6DZ\u00A6QA\u00A6039\u00A6DO\u00A6PY\u00A6DM\u00A6035\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6030\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6029\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6021\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6419\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6019\u00A6018\u00A6NZ\u00A6017\u00A6BO\u00A6BN\u00A6015\u00A6BM\u00A6014\u00A6013\u00A6NU\u00A6BJ\u00A6011\u00A6BI\u00A6172\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6ZZ\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6AX\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6009\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6005\u00A6MW\u00A6AL\u00A6MV\u00A6003\u00A6ZA\u00A6MU\u00A6002\u00A6MT\u00A6AI\u00A6001\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6155\u00A6LU\u00A6154\u00A6LT\u00A6LS\u00A6LR\u00A6151\u00A6150\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6145\u00A6142\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Timor-Leste\u00A6Tokelau\u00A6Tadjikistan\u00A6Tha\u00eflande\u00A6Togo\u00A6Terres australes fran\u00e7aises\u00A6Guyana\u00A6Tchad\u00A6\u00celes Turks et Ca\u00efques\u00A6Guin\u00e9e-Bissau\u00A6Guam\u00A6Guatemala\u00A6G\u00e9orgie du Sud, \u00celes Sandwich du Sud\u00A6Gr\u00e8ce\u00A6Guin\u00e9e \u00e9quatoriale\u00A6Guadeloupe\u00A6Swaziland\u00A6Syrie\u00A6Guin\u00e9e\u00A6Gambie\u00A6Groenland\u00A6El Salvador\u00A6Asie centrale et du Sud\u00A6Sao Tom\u00e9-et-Principe\u00A6Gibraltar\u00A6Polyn\u00e9sie\u00A6Ghana\u00A6Suriname\u00A6Guyane fran\u00e7aise\u00A6G\u00e9orgie\u00A6Somalie\u00A6Grenade\u00A6S\u00e9n\u00e9gal\u00A6Saint-Marin\u00A6Royaume-Uni\u00A6Sierra Leone\u00A6Gabon\u00A6Slovaquie\u00A6Svalbard et \u00cele Jan Mayen\u00A6Slov\u00e9nie\u00A6Sainte-H\u00e9l\u00e8ne\u00A6Singapour\u00A6Su\u00e8de\u00A6Soudan\u00A6Seychelles\u00A6\u00celes Salomon\u00A6Arabie saoudite\u00A6France\u00A6\u00celes F\u00e9ro\u00e9\u00A6Micron\u00e9sie\u00A6Micron\u00e9sie\u00A6Rwanda\u00A6M\u00e9lan\u00e9sie\u00A6\u00celes Falkland (Malvinas)\u00A6Australie et Nouvelle-Z\u00e9lande\u00A6Russie\u00A6Fidji\u00A6Finlande\u00A6Roumanie\u00A6R\u00e9union\u00A6\u00c9thiopie\u00A6Espagne\u00A6\u00c9rythr\u00e9e\u00A6Sahara occidental\u00A6\u00cele de Man\u00A6\u00c9gypte\u00A6Estonie\u00A6\u00celes Anglo-Normandes\u00A6\u00c9quateur\u00A6Alg\u00e9rie\u00A6Qatar\u00A6Europe m\u00e9ridionale\u00A6R\u00e9publique dominicaine\u00A6Paraguay\u00A6Dominique\u00A6Asie du Sud-Est\u00A6Palaos\u00A6Danemark\u00A6Djibouti\u00A6Portugal\u00A6Territoire palestinien\u00A6Asie orientale\u00A6Porto Rico\u00A6Allemagne\u00A6Pitcairn\u00A6Saint-Pierre-et-Miquelon\u00A6Pologne\u00A6Pakistan\u00A6Philippines\u00A6Papouasie-Nouvelle-Guin\u00e9e\u00A6Polyn\u00e9sie fran\u00e7aise\u00A6R\u00e9publique tch\u00e8que\u00A6P\u00e9rou\u00A6Chypre\u00A6\u00cele Christmas\u00A6Cap Vert\u00A6Panama\u00A6Cuba\u00A6Costa Rica\u00A6Cara\u00efbes\u00A6Colombie\u00A6Chine\u00A6Cameroun\u00A6Chili\u00A6\u00celes Cook\u00A6Am\u00e9rique du Nord\u00A6C\u00f4te d\u2019Ivoire\u00A6Suisse\u00A6Congo\u00A6R\u00e9publique centrafricaine\u00A6R\u00e9publique d\u00e9mocratique du Congo\u00A6\u00celes Cocos\u00A6Oman\u00A6Canada\u00A6Am\u00e9rique latine et Cara\u00efbes\u00A6Belize\u00A6B\u00e9larus\u00A6Botswana\u00A6\u00cele Bouvet\u00A6Bhoutan\u00A6Bahamas\u00A6Br\u00e9sil\u00A6Am\u00e9riques\u00A6Afrique australe\u00A6Nouvelle-Z\u00e9lande\u00A6Afrique centrale\u00A6Bolivie\u00A6Brunei\u00A6Afrique septentrionale\u00A6Bermudes\u00A6Afrique orientale\u00A6Am\u00e9rique centrale\u00A6Niu\u00e9\u00A6Benin\u00A6Afrique occidentale\u00A6Burundi\u00A6Commonwealth of Independent States\u00A6Bahre\u00efn\u00A6Nauru\u00A6Bulgarie\u00A6Burkina Faso\u00A6N\u00e9pal\u00A6Belgique\u00A6Autre Oc\u00e9anie\u00A6Norv\u00e8ge\u00A6Bangladesh\u00A6Barbade\u00A6Zimbabwe\u00A6Pays-Bas\u00A6Bosnie-Herz\u00e9govine\u00A6Nicaragua\u00A6Nig\u00e9ria\u00A6\u00cele Norfolk\u00A6Azerba\u00efdjan\u00A6Niger\u00A6Iles d\u2019\u00c5land\u00A6Nouvelle-Cal\u00e9donie\u00A6Aruba\u00A6Zambie\u00A6Namibie\u00A6Australie\u00A6Autriche\u00A6Samoa am\u00e9ricaines\u00A6Argentine\u00A6Antarctique\u00A6Oc\u00e9anie\u00A6Mozambique\u00A6Angola\u00A6Malaisie\u00A6Antilles n\u00e9erlandaises\u00A6Mexique\u00A6Arm\u00e9nie\u00A6Am\u00e9rique du Sud\u00A6Malawi\u00A6Albanie\u00A6Maldives\u00A6Le continent de l'Am\u00e9rique du Nord\u00A6Afrique du Sud\u00A6Maurice\u00A6Afrique\u00A6Malte\u00A6Anguilla\u00A6Monde\u00A6Montserrat\u00A6Mauritanie\u00A6Antigua-et-Barbuda\u00A6Martinique\u00A6Afghanistan\u00A6\u00celes Mariannes du Nord\u00A6\u00c9mirats arabes unis\u00A6Macao R.A.S. de Chine\u00A6Andorre\u00A6Mongolie\u00A6Myanmar\u00A6Mali\u00A6Mac\u00e9doine\u00A6Yougoslavie\u00A6Mayotte\u00A6\u00celes Marshall\u00A6Madagascar\u00A6Moldova\u00A6Monaco\u00A6Maroc\u00A6Y\u00e9men\u00A6Libye\u00A6Lettonie\u00A6Europe occidentale\u00A6Luxembourg\u00A6Europe septentrionale\u00A6Lithuanie\u00A6Lesotho\u00A6Lib\u00e9ria\u00A6Europe orientale\u00A6Europe\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Sainte-Lucie\u00A6Liban\u00A6Laos\u00A6Kazakhstan\u00A6\u00celes Ca\u00efmanes\u00A6Kowe\u00eft\u00A6Asie occidentale\u00A6Asie\u00A6Cor\u00e9e du Sud\u00A6Cor\u00e9e du Nord\u00A6Saint Kitts et Nevis\u00A6Comores\u00A6Kiribati\u00A6Samoa\u00A6Cambodge\u00A6Kirghizistan\u00A6Kenya\u00A6Wallis et Futuna\u00A6Japon\u00A6Jordanie\u00A6Jama\u00efque\u00A6Vanuatu\u00A6Viet Nam\u00A6\u00celes Vierges des \u00c9tats-Unis\u00A6\u00celes Vierges Britanniques\u00A6V\u00e9n\u00e9zuela\u00A6Saint-Vincent-et-les Grenadines\u00A6Saint-Si\u00e8ge (Etat de la Cit\u00e9 du Vatican)\u00A6Italie\u00A6Islande\u00A6Iran\u00A6Iraq\u00A6Ouzb\u00e9kistan\u00A6Territoire britannique de l\u2019oc\u00e9an indien\u00A6Uruguay\u00A6Inde\u00A6Isra\u00ebl\u00A6\u00c9tats-Unis\u00A6Irlande\u00A6Indon\u00e9sie\u00A6\u00celes Mineures \u00c9loign\u00e9es des \u00c9tats-Unis\u00A6Ouganda\u00A6Ukraine\u00A6Hongrie\u00A6Ha\u00efti\u00A6Croatie\u00A6Tanzanie\u00A6Honduras\u00A6\u00celes Heard et MacDonald\u00A6Ta\u00efwan\u00A6Tuvalu\u00A6Hong-Kong R.A.S. de Chine\u00A6Trinit\u00e9-et-Tobago\u00A6Turquie\u00A6Tonga\u00A6Tunisie\u00A6Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6ijo\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6kut\u00A6mic\u00A6wa\u00A6kum\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6vai\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6fan\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6bai\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tl\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sn\u00A6sm\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6tiv\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpf\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6snk\u00A6cop\u00A6yap\u00A6ach\u00A6yao\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6sms\u00A6bua\u00A6mas\u00A6smn\u00A6os\u00A6map\u00A6or\u00A6man\u00A6smj\u00A6smi\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6sma\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6root\u00A6ng\u00A6sla\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6kv\u00A6ku\u00A6sio\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6jv\u00A6gil\u00A6znd\u00A6shn\u00A6fon\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6ath\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6ypk\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6tup\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6nia\u00A6moh\u00A6luo\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6mno\u00A6wak\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6sal\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6pra\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "gwich\u02bbin\u00A6akkadien\u00A6ekajuk\u00A6ijo\u00A6xhosa\u00A6sum\u00e9rien\u00A6soussou\u00A6langues diverses\u00A6lozi\u00A6tonga (Nyasa)\u00A6pohnpei\u00A6minangkabau\u00A6sukuma\u00A6wolof\u00A6mongo\u00A6kutenai\u00A6micmac\u00A6wallon\u00A6koumyk\u00A6zapot\u00e8que\u00A6couchitiques (autre)\u00A6lojban\u00A6dogra\u00A6volap\u00fck\u00A6langues otomangues\u00A6vietnamien\u00A6va\u00ef\u00A6rarotongan\u00A6venda\u00A6rapanui\u00A6rajasthani\u00A6turc ottoman (1500-1928)\u00A6nzema\u00A6napolitain\u00A6ouzbek\u00A6ougaritique\u00A6tamacheq\u00A6indiennes d\u2019Am\u00e9rique du Nord (autre)\u00A6nahuatl\u00A6ourdou\u00A6fanti\u00A6ukrainien\u00A6\u00e9gyptien (ancien)\u00A6ou\u00efgour\u00A6fang\u00A6nilo-sahariennes (autre)\u00A6irlandais moyen (900-1200)\u00A6baltique (autre)\u00A6nyoro\u00A6bassa\u00A6nyankol\u00e9\u00A6nyamwezi\u00A6hmong\u00A6Balinais\u00A6osage\u00A6baloutchi\u00A6tahitien\u00A6langues bamilekes\u00A6twi\u00A6s\u00e9r\u00e8re\u00A6tlingit\u00A6tatar\u00A6tsonga\u00A6banda\u00A6turc\u00A6tongan (\u00celes Tonga)\u00A6setswana\u00A6tagalog\u00A6turkm\u00e8ne\u00A6tigrigna\u00A6tha\u00ef\u00A6kurukh\u00A6tadjik\u00A6blin\u00A6t\u00e9lougou\u00A6kru\u00A6cashubian\u00A6tamoul\u00A6tokelau\u00A6efik\u00A6swahili\u00A6su\u00e9dois\u00A6soundanais\u00A6karacay-balkar\u00A6sotho du Sud\u00A6swati\u00A6serbe\u00A6albanais\u00A6mend\u00e9\u00A6pidgins et langues cr\u00e9oles (autre)\u00A6somali\u00A6afrihili\u00A6shona\u00A6samoan\u00A6slov\u00e8ne\u00A6vieux grec (avant 1453)\u00A6slovaque\u00A6grebo\u00A6singhalais\u00A6serbo-croate\u00A6turc de Crim\u00e9e; tatar de Crim\u00e9e\u00A6afro-asiatique (autre)\u00A6sango\u00A6sami du Nord\u00A6sindhi\u00A6oudmourte\u00A6sarde\u00A6sanskrit\u00A6rwanda\u00A6russe\u00A6mandar\u00A6roumain\u00A6roundi\u00A6rh\u00e9to-roman\u00A6moksa\u00A6tiv\u00A6adygu\u00e9\u00A6zuni\u00A6kpell\u00e9\u00A6quechua\u00A6tigr\u00e9\u00A6songhai\u00A6pidgin portugais (autre)\u00A6sogdien\u00A6adangme\u00A6kusaien\u00A6hittite\u00A6pidgin fran\u00e7ais (autre)\u00A6pidgin anglais (autre)\u00A6himachali\u00A6konkani\u00A6hiligaynon\u00A6gotique\u00A6gorontalo\u00A6gondi\u00A6dinka\u00A6langues nubiennes\u00A6portugais\u00A6pachto\u00A6frioulan\u00A6ph\u00e9nicien\u00A6allemand, vieux haut (ca. 750-1050)\u00A6sonink\u00e9\u00A6copte\u00A6yapois\u00A6acoli\u00A6yao\u00A6philippines (autre)\u00A6polonais\u00A6aceh\u00A6pali\u00A6pendjabi\u00A6bugi\u00A6iban\u00A6sami skolt\u00A6buriat\u00A6masai\u00A6sami d\u2019Inari\u00A6oss\u00e8te\u00A6malayo-polyn\u00e9sien\u00A6oriya\u00A6meninka\u00A6sami de Lule\u00A6sami (autre)\u00A6makasar\u00A6galla\u00A6maithili\u00A6ojibwa\u00A6magahi\u00A6madurais\u00A6sami du Sud\u00A6occitan (apr\u00e8s 1500)\u00A6sotho du Sud	\u00A6batak\u00A6erzya\u00A6dogrib\u00A6nyanja\u00A6langue maya\u00A6navaho\u00A6kiMboundou\u00A6nd\u00e9b\u00e9l\u00e9 du Sud\u00A6allemand, moyen haut (ca. 1050-1500)\u00A6norv\u00e9gien\u00A6nynorsk norv\u00e9gien\u00A6n\u00e9erlandais\u00A6racine\u00A6ndonga\u00A6slaves (autre)\u00A6n\u00e9palais\u00A6nd\u00e9b\u00e9l\u00e9 du Nord\u00A6chames, langues\u00A6tetum\u00A6bokm\u00e5l norv\u00e9gien\u00A6nauruan\u00A6tereno\u00A6temne\u00A6birman\u00A6lezghien\u00A6maltais\u00A6perse, vieux (ca. 600-400 av. J.-C.)\u00A6malais\u00A6marathe\u00A6vieux fran\u00e7ais (842-ca.1400)\u00A6moldave\u00A6fran\u00e7ais moyen (ca.1400-1600)\u00A6mongol\u00A6jud\u00e9o-arabe\u00A6malayalam\u00A6mac\u00e9donien\u00A6maori\u00A6marshall\u00A6malgache\u00A6marwari\u00A6braj\u00A6slave\u00A6letton\u00A6luba-katanga\u00A6delaware\u00A6lituanien\u00A6lao\u00A6lingala\u00A6limbourgeois\u00A6ewondo\u00A6ganda\u00A6luxembourgeois\u00A6latin\u00A6jud\u00e9o-persan\u00A6vote\u00A6sino-tib\u00e9taines (autre)\u00A6kirghize\u00A6cornique\u00A6komi\u00A6kurde\u00A6sioux, langues\u00A6kashmiri\u00A6kanouri\u00A6awadhi\u00A6cor\u00e9en\u00A6kannada\u00A6khmer\u00A6groenlandais\u00A6kazakh\u00A6tsigane\u00A6kuanyama\u00A6sidamo\u00A6kikuyu\u00A6kongo\u00A6norrois, vieux\u00A6g\u00e9orgien\u00A6creek\u00A6romanes (autre)\u00A6noga\u00ef, nogay\u00A6mounda, langues\u00A6langues multiples\u00A6javanais\u00A6gilbertais\u00A6zande\u00A6chan\u00A6fon\u00A6kalmouk\u00A6langues australiennes\u00A6khotanais\u00A6japonais\u00A6khoisan (autre)\u00A6palau\u00A6cheyenne\u00A6tha\u00ef (autre)\u00A6inuktitut\u00A6papiamento\u00A6italien\u00A6langues des signes\u00A6islandais\u00A6khasi\u00A6cherokee\u00A6pampanga\u00A6pahlavi\u00A6chippewyan\u00A6ido\u00A6choctaw\u00A6jargon chinook\u00A6mari\u00A6touva\u00A6bantou\u00A6pangasinan\u00A6inupiaq\u00A6chuuk\u00A6yi de Sichuan\u00A6hawa\u00efen\u00A6lamba\u00A6igbo\u00A6jagataic\u00A6irlandais ancien (jusqu\u2019\u00e0 900)\u00A6papoues (autre)\u00A6interlingue\u00A6indon\u00e9sien\u00A6lahnda\u00A6dayak\u00A6chibcha\u00A6interlingua\u00A6ladino\u00A6h\u00e9r\u00e9ro\u00A6haida\u00A6dargwa\u00A6arm\u00e9nien\u00A6langues athapascanes\u00A6hongrois\u00A6ha\u00eftien\u00A6dakota\u00A6croate\u00A6hiri motu\u00A6hindi\u00A6dyula\u00A6h\u00e9breu\u00A6asturien\u00A6haoussa\u00A6sorabes, langues\u00A6manx\u00A6goudjrati\u00A6s\u00e9mitiques (autre)\u00A6selkoupe\u00A6langues iroquoiennes\u00A6guarani\u00A6galicien\u00A6arawak\u00A6gu\u00e8ze\u00A6artificielle (autre)\u00A6ga\u00e9lique \u00e9cossais\u00A6iranien\u00A6irlandais\u00A6arapaho\u00A6araukan\u00A6frison\u00A6pieds-noirs\u00A6germanique (autre)\u00A6yupik, langues\u00A6aram\u00e9en\u00A6fran\u00e7ais\u00A6f\u00e9ro\u00efen\u00A6langue celtique (autre)\u00A6fidjien\u00A6finnois\u00A6peul\u00A6tuvalu\u00A6cebuano\u00A6persan\u00A6basque\u00A6\u00e9cossais\u00A6estonien\u00A6espagnol\u00A6esp\u00e9ranto\u00A6anglais\u00A6grec\u00A6alta\u00efques (autre)\u00A6niu\u00e9\u00A6tupi, langues\u00A6\u00e9w\u00e9\u00A6tumbuka\u00A6mossi\u00A6dzongkha\u00A6nig\u00e9ro-congolaise (autre)\u00A6lushai\u00A6langue finno-ougrienne (autre)\u00A6maldivien\u00A6nias\u00A6mohawk\u00A6luo\u00A6lunda\u00A6langues apaches\u00A6luiseno\u00A6hupa\u00A6bini\u00A6allemand\u00A6luba-lulua\u00A6bikol\u00A6washo\u00A6ind\u00e9termin\u00e9e\u00A6waray\u00A6danois\u00A6n\u00e9erlandais moyen (ca. 1050-1350)\u00A6walamo\u00A6manobo, langues\u00A6wakashennes, langues\u00A6santal\u00A6gallois\u00A6sasak\u00A6kabardine\u00A6tchouvache\u00A6slavon d\u2019\u00e9glise\u00A6manipuri\u00A6tch\u00e8que\u00A6samaritain\u00A6cree\u00A6salisha, langues\u00A6douala\u00A6corse\u00A6indiennes d\u2019Am\u00e9rique du Sud (autre)\u00A6mandchou\u00A6iakoute\u00A6kawi\u00A6ingouche\u00A6gbaya\u00A6sandawe\u00A6chamorro\u00A6langue indo-europ\u00e9enne (autre)\u00A6bhojpuri\u00A6anglais moyen (1100-1500)\u00A6karen\u00A6langue indo-aryenne (autre)\u00A6tch\u00e9tch\u00e8ne\u00A6gayo\u00A6catalan\u00A6umbundu\u00A6syriaque\u00A6kamba\u00A6tsimshian\u00A6vieil anglais (ca.450-1100)\u00A6kachin\u00A6langue caucasienne (autre)\u00A6kabyle\u00A6kara-kalpak\u00A6bosniaque\u00A6caribe\u00A6breton\u00A6tib\u00e9tain\u00A6bengali\u00A6bambara\u00A6ga\u00A6indien d\u2019Am\u00e9rique Centrale (autre)\u00A6bichlamar\u00A6bihari\u00A6bulgare\u00A6bi\u00e9lorusse\u00A6caddo\u00A6bachkir\u00A6zoulou\u00A6zenaga\u00A6proven\u00e7al ancien (jusqu\u2019\u00e0 1500)\u00A6haut-sorabe\u00A6az\u00e9ri\u00A6aymara\u00A6avar\u00A6assamais\u00A6bas-sorabe\u00A6arabe\u00A6iloko\u00A6\u00e9lamite\u00A6chinois\u00A6aragonais\u00A6pr\u00e2krit\u00A6amharique\u00A6newari\u00A6akan\u00A6zhuang\u00A6afrikaans\u00A6avestique\u00A6abkhaze\u00A6afar\u00A6yoruba\u00A6langues algiques\u00A6al\u00e9oute\u00A6mon-khmer (autre)\u00A6yiddish\u00A6langue dravidienne (autre)\u00A6berb\u00e8re\u00A6bas allemand, bas saxon\u00A6bemba\u00A6bedja\u00A6tok pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final String variantsKeys = "REVISED";

  private static final String variantsValues = "R\u00e9vis\u00e9";

  private static final Hashtable variants;
  static
  {
    variants = new Hashtable();
    Enumeration keys = new StringTokenizer(variantsKeys, "\u00A6");
    Enumeration values = new StringTokenizer(variantsValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         variants.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "currencyFormat", "#,##0.00 \u00a4;-#,##0.00 \u00a4" },
    { "localPatternChars", "GaMjkHmsSEDFwWxhKzAeugXZ" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "minNumberOfDaysInFirstWeek", "4" },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "shortDateFormat", "dd/MM/yy" },
    { "mediumDateFormat", "d MMM yy" },
    { "longDateFormat", "d MMMM yyyy" },
    { "fullDateFormat", "EEEE d MMMM yyyy" },
    { "fullTimeFormat", "HH' h 'mm z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
