/* LocaleInformation_sq.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML sq.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_sq extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "Jan",
    "Shk",
    "Mar",
    "Pri",
    "Maj",
    "Qer",
    "Kor",
    "Gsh",
    "Sht",
    "Tet",
    "N\u00ebn",
    "Dhj",
    null,
  };

  private static final String[] months = {
    "janar",
    "shkurt",
    "mars",
    "prill",
    "maj",
    "qershor",
    "korrik",
    "gusht",
    "shtator",
    "tetor",
    "n\u00ebntor",
    "dhjetor",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Die",
    "H\u00ebn",
    "Mar",
    "M\u00ebr",
    "Enj",
    "Pre",
    "Sht",
  };

  private static final String[] weekdays = {
    null,
    "e diel",
    "e h\u00ebn\u00eb",
    "e mart\u00eb",
    "e m\u00ebrkur\u00eb",
    "e enjte",
    "e premte",
    "e shtun\u00eb",
  };

  private static final String[] eras = {
    "p.e.r.",
    "n.e.r.",
  };

  private static final String[] ampms = {
    "PD",
    "MD",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TJ", "Taxhikistan");
        put("TH", "Tajland\u00eb");
        put("TG", "Togo");
        put("GY", "Guajana");
        put("TD", "\u00c7ad");
        put("GW", "Guine Bisau");
        put("GT", "Guatemal\u00eb");
        put("GR", "Greqi");
        put("GQ", "Guineja Ekuatoriale");
        put("SZ", "Svaziland\u00eb");
        put("SY", "Siri");
        put("GN", "Guine");
        put("GM", "Gambi");
        put("ST", "Sao Tome e Prinsipe");
        put("GH", "Gan\u00eb");
        put("SP", "Serbi\u00eb");
        put("GE", "Gjeorgji");
        put("SO", "Somali");
        put("SL", "Siera Leone");
        put("GA", "Gjabon");
        put("SK", "Sllovaki");
        put("SI", "Slloveni");
        put("SG", "Singapor");
        put("SE", "Suedi");
        put("SC", "Sishel");
        put("SB", "Ishujt Solomon");
        put("SA", "Arabia Saudite");
        put("FR", "Franc\u00eb");
        put("FM", "Mikronezi");
        put("RW", "Ruanda");
        put("RU", "Rusi");
        put("FJ", "Fixhi");
        put("FI", "Finland\u00eb");
        put("RO", "Rumani");
        put("ET", "Etiopi");
        put("ES", "Spanj\u00eb");
        put("ER", "Eritre");
        put("EH", "Saharaja Per\u00ebndimore");
        put("EG", "Egjipt");
        put("EE", "Estoni");
        put("EC", "Ekuator");
        put("DZ", "Algjeri");
        put("QA", "Katar");
        put("DO", "Republika Dominikan\u00eb");
        put("PY", "Paraguaj");
        put("DM", "Dominik\u00eb");
        put("DK", "Danimark\u00eb");
        put("DJ", "Xhibuti");
        put("PT", "Portugali");
        put("DE", "Gjermani");
        put("PL", "Poloni");
        put("PH", "Filipine");
        put("PG", "Papua Guineja e Re");
        put("CZ", "Republika e \u00c7ekis\u00eb");
        put("CY", "Qipro");
        put("CV", "Kap Verde");
        put("CU", "Kub\u00eb");
        put("CR", "Kosta Rika");
        put("CO", "Kolumbi");
        put("CN", "Kin\u00eb");
        put("CM", "Kamerun");
        put("CL", "Kili");
        put("CI", "Bregu i Fildisht\u00eb");
        put("CH", "Zvic\u00ebr");
        put("CG", "Kongo");
        put("CF", "Republika Qendrore e Afrik\u00ebs");
        put("CA", "Kanada");
        put("BY", "Bjellorusi");
        put("BW", "Botsvana");
        put("BT", "Butan");
        put("NZ", "Zelanda e Re");
        put("BO", "Bolivi");
        put("BN", "Brunej");
        put("BH", "Bahrein");
        put("BG", "Bullgari");
        put("BE", "Belgjik\u00eb");
        put("NO", "Norvegji");
        put("ZW", "Zimbabve");
        put("NL", "Vendet e Ul\u00ebta");
        put("BA", "Bosnja dhe Hercegovina");
        put("NI", "Nikaragua");
        put("NG", "Nigeri");
        put("AZ", "Azerbajxhan");
        put("ZM", "Zambi");
        put("AU", "Australi");
        put("NA", "Namibi");
        put("AT", "Austri");
        put("AR", "Argjentin\u00eb");
        put("MZ", "Mozambik");
        put("AO", "Angol\u00eb");
        put("MY", "Malajzi");
        put("MX", "Meksik\u00eb");
        put("AM", "Armeni");
        put("MW", "Malavi");
        put("AL", "Shqip\u00ebria");
        put("MV", "Maldivit");
        put("ZA", "Afrika e Jugut");
        put("MT", "Malt\u00eb");
        put("MR", "Mauritani");
        put("AG", "Antigua e Barbuda");
        put("AF", "Afganistan");
        put("AE", "Emiratet Arabe te Bashkuara");
        put("AD", "Andorr\u00eb");
        put("MN", "Mongoli");
        put("MK", "Maqedoni");
        put("MH", "Ishujt Marshall");
        put("MG", "Madagaskar");
        put("MD", "Moldavi");
        put("MC", "Monako");
        put("MA", "Maroko");
        put("YE", "Jemen");
        put("LY", "Libi");
        put("LV", "Letoni");
        put("LU", "Luksemburg");
        put("LT", "Lituani");
        put("LS", "Lesoto");
        put("LR", "Liberi");
        put("LI", "Liht\u00ebnshtajn");
        put("LB", "Liban");
        put("KZ", "Kazakistan");
        put("KW", "Kuvajt");
        put("KR", "Koreja e Jugut");
        put("KP", "Koreja e Veriut");
        put("KN", "Saint Kitts e Nevis");
        put("KM", "Komore");
        put("KI", "Qiribati");
        put("KH", "Kamboxhi");
        put("KG", "Kirgistan");
        put("KE", "Kenia");
        put("JP", "Japoni");
        put("JO", "Jordani");
        put("JM", "Xhamajk\u00eb");
        put("VE", "Venezuel\u00eb");
        put("VC", "Saint Vincent e Grenadinet");
        put("VA", "Vatikan");
        put("IT", "Itali");
        put("IS", "Island\u00eb");
        put("IQ", "Irak");
        put("UY", "Uruguaj");
        put("IN", "Indi");
        put("IL", "Izrael");
        put("US", "Shtetet e Bashkuara t\u00eb Amerik\u00ebs");
        put("IE", "Irland\u00eb");
        put("ID", "Indonezi");
        put("UA", "Ukrain\u00eb");
        put("HU", "Hungari");
        put("HR", "Kroaci");
        put("TZ", "Tanzani");
        put("TW", "Tajvan");
        put("TT", "Trinidad e Tobago");
        put("TR", "Turqi");
        put("TN", "Tunisi");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "yy-MM-dd" },
    { "mediumDateFormat", "yyyy-MM-dd" },
    { "longDateFormat", "dd MMMM yyyy" },
    { "fullDateFormat", "EEEE, dd MMMM yyyy" },
    { "shortTimeFormat", "h.mm.a" },
    { "mediumTimeFormat", "h:mm:ss.a" },
    { "longTimeFormat", "h.mm.ss.a z" },
    { "fullTimeFormat", "h.mm.ss.a z" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
