/* LocaleInformation_bn.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_bn extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "BDT";

  private static final String currenciesDisplayNameValues = "BDT";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "|");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "INR|BDT";

  private static final String currenciesSymbolValues = "\u099f\u09be\u0995\u09be|\u09f3";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "|");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "\u099c\u09be\u09a8\u09c1\u09df\u09be\u09b0\u09c0",
    "\u09ab\u09c7\u09ac\u09cd\u09b0\u09c1\u09df\u09be\u09b0\u09c0",
    "\u09ae\u09be\u09b0\u09cd\u099a",
    "\u098f\u09aa\u09cd\u09b0\u09bf\u09b2",
    "\u09ae\u09c7",
    "\u099c\u09c1\u09a8",
    "\u099c\u09c1\u09b2\u09be\u0987",
    "\u0986\u0997\u09b8\u09cd\u099f",
    "\u09b8\u09c7\u09aa\u09cd\u099f\u09c7\u09ae\u09cd\u09ac\u09b0",
    "\u0985\u0995\u09cd\u099f\u09cb\u09ac\u09b0",
    "\u09a8\u09ad\u09c7\u09ae\u09cd\u09ac\u09b0",
    "\u09a1\u09bf\u09b8\u09c7\u09ae\u09cd\u09ac\u09b0",
    null,
  };

  private static final String[] months = {
    "\u099c\u09be\u09a8\u09c1\u09df\u09be\u09b0\u09c0",
    "\u09ab\u09c7\u09ac\u09cd\u09b0\u09c1\u09df\u09be\u09b0\u09c0",
    "\u09ae\u09be\u09b0\u09cd\u099a",
    "\u098f\u09aa\u09cd\u09b0\u09bf\u09b2",
    "\u09ae\u09c7",
    "\u099c\u09c1\u09a8",
    "\u099c\u09c1\u09b2\u09be\u0987",
    "\u0986\u0997\u09b8\u09cd\u099f",
    "\u09b8\u09c7\u09aa\u09cd\u099f\u09c7\u09ae\u09cd\u09ac\u09b0",
    "\u0985\u0995\u09cd\u099f\u09cb\u09ac\u09b0",
    "\u09a8\u09ad\u09c7\u09ae\u09cd\u09ac\u09b0",
    "\u09a1\u09bf\u09b8\u09c7\u09ae\u09cd\u09ac\u09b0",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "\u09b0\u09ac\u09bf",
    "\u09b8\u09cb\u09ae",
    "\u09ae\u0999\u09cd\u0997\u09b2",
    "\u09ac\u09c1\u09a7",
    "\u09ac\u09c3\u09b9\u09b8\u09cd\u09aa\u09a4\u09bf",
    "\u09b6\u09c1\u0995\u09cd\u09b0",
    "\u09b6\u09a8\u09bf",
  };

  private static final String[] weekdays = {
    null,
    "\u09b0\u09ac\u09bf\u09ac\u09be\u09b0",
    "\u09b8\u09cb\u09ae\u09ac\u09be\u09b0",
    "\u09ae\u0999\u09cd\u0997\u09b2\u09ac\u09be\u09b0",
    "\u09ac\u09c1\u09a7\u09ac\u09be\u09b0",
    "\u09ac\u09c3\u09b9\u09b7\u09cd\u09aa\u09a4\u09bf\u09ac\u09be\u09b0",
    "\u09b6\u09c1\u0995\u09cd\u09b0\u09ac\u09be\u09b0",
    "\u09b6\u09a8\u09bf\u09ac\u09be\u09b0",
  };

  private static final String[] ampms = {
    "\u09aa\u09c2\u09b0\u09cd\u09ac\u09be\u09b9\u09cd\u09a3",
    "\u0985\u09aa\u09b0\u09be\u09b9\u09cd\u09a3",
  };

  private static final String territoriesKeys = "AU|GY|AT|AR|MY|GT|MX|GR|AM|ZA|AL|SY|SV|AF|MN|GH|SO|GE|MG|GB|SK|MD|SG|MA|SE|SD|SA|YE|LY|FR|LV|LU|LT|LR|RU|FI|LK|RO|LB|LA|KZ|ET|ES|KR|EH|EG|EE|KH|EC|KG|KE|DZ|PY|JP|DK|PT|JO|JM|DE|PL|PK|VN|PH|PE|CZ|PA|VE|CU|CR|IT|CO|IS|CN|IR|IQ|CL|UZ|UY|IN|CH|IL|CG|US|IE|ID|BY|BT|BR|UA|NZ|HU|BO|HN|TW|BG|NP|NO|BE|BD|TR|NL|TN|NI|TM|TJ|AZ|TH";

  private static final String territoriesValues = "\u0985\u09b8\u09cd\u099f\u09cd\u09b0\u09c7\u09b2\u09bf\u09df\u09be|\u0997\u09bf\u09df\u09be\u09a8\u09be|\u0985\u09b8\u09cd\u099f\u09cd\u09b0\u09bf\u09df\u09be|\u0986\u09b0\u09cd\u099c\u09c7\u09a3\u09cd\u099f\u09be\u0987\u09a8\u09be|\u09ae\u09be\u09b2\u09cd\u09af\u09be\u09b6\u09bf\u09df\u09be|\u0997\u09cb\u09df\u09be\u099f\u09bf\u09ae\u09be\u09b2\u09be|\u09ae\u0995\u09cd\u09b8\u09bf\u0995\u09cb|\u0997\u09cd\u09b0\u09c0\u09b8\u09cd|\u0986\u09b0\u09cd\u09ae\u09c7\u09a8\u09bf\u09df\u09be|\u09a6\u0995\u09cd\u09b7\u09bf\u09a3 \u0986\u09ab\u09cd\u09b0\u09bf\u0995\u09be|\u0986\u09b2\u09ac\u09cd\u09af\u09be\u09a8\u09bf\u09df\u09be|\u09b8\u09bf\u09b0\u09bf\u09df\u09be|\u09b8\u09be\u09b2\u09ad\u09c7\u09a1\u09b0|\u0986\u09ab\u0997\u09be\u09a8\u09bf\u09b8\u09cd\u09a4\u09be\u09a8|\u09ae\u0999\u09cd\u0997\u09cb\u09b2\u09bf\u09df\u09be|\u0997\u09be\u09a8\u09be|\u09b8\u09cb\u09ae\u09be\u09b2\u09bf|\u099c\u09b0\u09cd\u099c\u09bf\u09df\u09be|\u09ae\u09be\u09a6\u09be\u0997\u09be\u09b8\u09cd\u0995\u09be\u09b0|\u0997\u09cd\u09b0\u09c7\u099f\u09ac\u09c3\u099f\u09c7\u09a8|\u09b6\u09cd\u09b2\u09cb\u09ad\u09be\u0995\u09bf\u09df\u09be|\u09ae\u09cb\u09b2\u09cd\u09a6\u09be\u09ad\u09bf\u09df\u09be|\u09b8\u09bf\u0999\u09cd\u0997\u09be\u09aa\u09c1\u09b0|\u09ae\u09cb\u09b0\u0995\u09cd\u0995\u09cb|\u09b8\u09c1\u0987\u09a1\u09c7\u09a8|\u09b8\u09c1\u09a6\u09be\u09a8|\u09b8\u09be\u0989\u09a6\u09bf \u0986\u09b0\u09ac|\u0987\u09ae\u09c7\u09a8|\u09b2\u09bf\u09ac\u09bf\u09df\u09be|\u09ab\u09cd\u09b0\u09be\u09a8\u09cd\u09b8|\u09b2\u09be\u09a4\u09cd\u09ad\u09bf\u09df\u09be|\u09b2\u09be\u0995\u09cd\u09b8\u09c7\u09ae\u09ac\u09be\u09b0\u09cd\u0997|\u09b2\u09bf\u09a4\u09cd\u09ad\u09be|\u09b2\u09be\u0987\u09ac\u09bf\u09b0\u09bf\u09df\u09be|\u09b0\u09be\u09b6\u09bf\u09df\u09be|\u09ab\u09bf\u09a8\u09cd\u09b2\u09cd\u09af\u09be\u09a3\u09cd\u09a1|\u09b6\u09cd\u09b0\u09c0\u09b2\u0999\u09cd\u0995\u09be|\u09b0\u09c1\u09ae\u09be\u09a8\u09bf\u09df\u09be|\u09b2\u09c7\u09ac\u09be\u09a8\u09a8|\u09b2\u09be\u0993\u09b8|\u0995\u09be\u099c\u09be\u0995\u09b8\u09cd\u09a5\u09be\u09a8|\u0987\u09ab\u09bf\u0993\u09aa\u09bf\u09df\u09be|\u09b8\u09cd\u09aa\u09c7\u09a8|\u09a6\u0995\u09cd\u09b7\u09bf\u09a3 \u0995\u09cb\u09b0\u09bf\u09df\u09be|\u09aa\u09b6\u09cd\u099a\u09bf\u09ae\u09c0 \u09b8\u09be\u09b9\u09be\u09b0\u09be|\u09ae\u09bf\u09b6\u09b0|\u098f\u09b8\u09cd\u09a4\u09cb\u09a8\u09bf\u09df\u09be|\u0995\u09be\u09ae\u09cd\u09ac\u09cb\u099c|\u0987\u0995\u09cb\u09df\u09be\u09a1\u09b0|\u0995\u09bf\u09b0\u09cd\u0997\u09bf\u099c\u09bf\u09df\u09be|\u0995\u09c7\u09a8\u09bf\u09df\u09be|\u098f\u09b2\u099c\u09bf\u09b0\u09bf\u09df\u09be|\u09aa\u09cd\u09af\u09be\u09b0\u09be\u0997\u09cb\u09df\u09c7|\u099c\u09be\u09aa\u09be\u09a8|\u09a1\u09c7\u09a8\u09cd\u09ae\u09be\u09b0\u09cd\u0995|\u09aa\u09b0\u09cd\u09a4\u09c1\u0997\u09be\u09b2|\u099c\u09b0\u09cd\u09a1\u09a8|\u099c\u09cd\u09af\u09be\u09ae\u09c7\u0995\u09be|\u099c\u09be\u09b0\u09cd\u09ae\u09be\u09a8\u09bf|\u09aa\u09cb\u09b2\u09cd\u09af\u09be\u09a3\u09cd\u09a1|\u09aa\u09be\u0995\u09bf\u09b8\u09cd\u09a4\u09be\u09a8|\u09ad\u09bf\u09df\u09c7\u09a4\u09a8\u09be\u09ae|\u09ab\u09bf\u09b2\u09bf\u09aa\u09be\u0987\u09a8|\u09aa\u09bf\u09b0\u09c1|\u099a\u09c7\u0995\u09bf\u09df\u09be|\u09aa\u09be\u09a8\u09be\u09ae\u09be|\u09ad\u09c7\u09a8\u09c7\u099c\u09c1\u09df\u09c7\u09b2\u09be|\u0995\u09bf\u0989\u09ac\u09be|\u0995\u09cb\u09b8\u09cd\u099f\u09be\u09b0\u09bf\u0995\u09be|\u0987\u09a4\u09be\u09b2\u09c0|\u0995\u09cb\u09b2\u09cb\u09ae\u09cd\u09ac\u09bf\u09df\u09be|\u0986\u0987\u09b8\u09b2\u09a3\u09cd\u09a1|\u099a\u09c0\u09a8|\u0987\u09b0\u09be\u09a8|\u0987\u09b0\u09be\u0995|\u099a\u09bf\u09b2\u09bf|\u0989\u099c\u09cd\u09ac\u09c7\u0995\u09bf\u09b8\u09cd\u09a5\u09be\u09a8|\u0989\u09b0\u09c1\u0997\u09cb\u09df\u09c7|\u09ad\u09be\u09b0\u09a4|\u09b8\u09c1\u0987\u099c\u09b0\u09cd\u09b2\u09a3\u09cd\u09a1|\u0987\u09b8\u09cd\u09b0\u09be\u09df\u09c7\u09b2|\u0995\u0999\u09cd\u0997\u09cb|\u09ae\u09be\u09b0\u09cd\u0995\u09bf\u09a8 \u09af\u09c1\u0995\u09cd\u09a4\u09b0\u09be\u09b7\u09cd\u099f\u09cd\u09b0|\u0986\u09df\u09be\u09b0\u09cd\u09b2\u09a3\u09cd\u09a1|\u0987\u09a8\u09cd\u09a6\u09cb\u09a8\u09c7\u09b6\u09bf\u09df\u09be|\u09ac\u09c7\u09b2\u09cb\u09b0\u09c1\u09b6\u09bf\u09df\u09be|\u09ad\u09c1\u099f\u09be\u09a8|\u09ac\u09cd\u09b0\u09be\u099c\u09bf\u09b2|\u0987\u0989\u0995\u09cd\u09b0\u09c7\u0987\u09a8|\u09a8\u09bf\u0989 \u099c\u09bf\u09b2\u09a3\u09cd\u09a1|\u09b9\u09be\u0999\u09cd\u0997\u09c7\u09b0\u09bf|\u09ac\u09cb\u09b2\u09bf\u09ad\u09bf\u09df\u09be|\u09b9\u09a3\u09cd\u09a1\u09c1\u09b0\u09be\u09b8|\u09a4\u09be\u0987\u0993\u09df\u09be\u09a8|\u09ac\u09c1\u09b2\u0997\u09c7\u09b0\u09bf\u09df\u09be|\u09a8\u09c7\u09aa\u09be\u09b2|\u09a8\u09b0\u0993\u09df\u09c7|\u09ac\u09c7\u09b2\u09cd\u099c\u09bf\u09df\u09ae|\u09ac\u09be\u0982\u09b2\u09be\u09a6\u09c7\u09b6|\u09a4\u09c1\u09b0\u09b8\u09cd\u0995|\u09b9\u09b2\u09a3\u09cd\u09a1|\u099f\u09bf\u0989\u09a8\u09bf\u09b8\u09cd|\u09a8\u09bf\u0995\u09be\u09b0\u09be\u0997\u09cb\u09df\u09be|\u09a4\u09c1\u09b0\u09cd\u0995\u09ae\u09c7\u09a8\u09bf\u09df\u09be|\u09a4\u09be\u099c\u09bf\u0995\u09b8\u09cd\u09a5\u09be\u09a8|\u0986\u099c\u09be\u09b0\u09ac\u09be\u0987\u099c\u09be\u09a8|\u09a5\u09be\u0987";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "|");
    Enumeration values = new StringTokenizer(territoriesValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "bn";

  private static final String languagesValues = "\u09ac\u09be\u0982\u09b2\u09be";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "|");
    Enumeration values = new StringTokenizer(languagesValues, "|");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "ampms", ampms },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
