/* LocaleInformation_es.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_es extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "dinar jordano\u00A6MVDOL boliviano\u00A6oro\u00A6corona de las Islas Feroe\u00A6libra libanesa\u00A6euro\u00A6dong vietnamita\u00A6chel\u00edn tanzano\u00A6peso boliviano\u00A6riel camboyano\u00A6unidad monetaria asi\u00e1tica\u00A6boliviano (1863-1962)\u00A6antiguo riel camboyano\u00A6libra zambiana\u00A6libra australiana\u00A6franco CFA BEAC\u00A6libra maltesa\u00A6cedi revaluado ghan\u00e9s\u00A6kwacha zambiano\u00A6unidad de cuenta asi\u00e1tica en dinares\u00A6libra ghanesa\u00A6boliviano\u00A6antiguo cedi ghan\u00e9s\u00A6lira maltesa\u00A6d\u00f3lar australiano\u00A6d\u00f3lar estadounidense (mismo d\u00eda)\u00A6lira italiana\u00A6d\u00f3lar estadounidense (d\u00eda siguiente)\u00A6cedi ghan\u00e9s\u00A6d\u00f3lar singapurense\u00A6balboa paname\u00f1o\u00A6kip laosiano\u00A6som kirgu\u00eds\u00A6franco suizo\u00A6chel\u00edn austriaco\u00A6d\u00f3lar estadounidense\u00A6d\u00f3lar et\u00edope\u00A6d\u00f3lar de Brun\u00e9i\u00A6libra jamaicana\u00A6birr et\u00edope\u00A6franco germinal argelino\u00A6nuevo franco argelino\u00A6dinar argelino\u00A6guaran\u00ed paraguayo\u00A6libra libia\u00A6d\u00f3lar de Jamaica\u00A6corona islandesa\u00A6peseta espa\u00f1ola\u00A6libra de Bermudas\u00A6dinar libio\u00A6lira libia de la Autoridad Militar Brit\u00e1nica\u00A6d\u00f3lar de Bermudas\u00A6flor\u00edn neerland\u00e9s\u00A6ouguiya mauritano\u00A6rial iran\u00ed\u00A6corona sueca\u00A6nakfa eritreo\u00A6chel\u00edn keniata\u00A6franco CFA de la Rep\u00fablica Centroafricana\u00A6peso argentino\u00A6peso argentino (1983-1985)\u00A6peso moneda nacional argentino\u00A6nuevo d\u00f3lar taiwan\u00e9s\u00A6libra sudanesa\u00A6lari georgiano\u00A6kupon larit georgiano\u00A6franco de Martinica\u00A6libra de las Islas Malvinas\u00A6austral argentino\u00A6dinar sudan\u00e9s\u00A6dinar iraqu\u00ed\u00A6d\u00f3lar de Tuvalu\u00A6rupia de Seychelles\u00A6rublo let\u00f3n\u00A6libra de las Islas Fiyi\u00A6lats let\u00f3n\u00A6zaire congole\u00f1o\u00A6franco de la Rep\u00fablica del Congo\u00A6franco congole\u00f1o\u00A6d\u00f3lar de las Islas Fiyi\u00A6c\u00f3rdoba oro nicarag\u00fcense\u00A6pataca de Macao\u00A6c\u00f3rdoba oro nicarag\u00fcense\u00A6c\u00f3rdoba nicarag\u00fcense\u00A6rublo transferible del COMECON\u00A6marco finland\u00e9s (1860-1962)\u00A6marco finland\u00e9s\u00A6d\u00f3lar de las Islas Salom\u00f3n\u00A6franco luxemburgu\u00e9s\u00A6antiguo d\u00f3lar de Trinidad y Tobago\u00A6escudo angole\u00f1o\u00A6kwanza reajustado angole\u00f1o (1995-1999)\u00A6tugrik mongol\u00A6forinto h\u00fangaro\u00A6franco de Burundi\u00A6nuevo kwanza angole\u00f1o (1990-2000)\u00A6kwanza angole\u00f1o (1977-1990)\u00A6d\u00f3lar de Trinidad y Tobago\u00A6lilangeni suazi\u00A6franco CFP de las Nuevas H\u00e9bridas\u00A6libra esterlina brit\u00e1nica\u00A6riyal soberano saud\u00ed\u00A6riyal saud\u00ed\u00A6talonas lituano\u00A6rupia india\u00A6escudo portugu\u00e9s\u00A6kwanza angole\u00f1o\u00A6conto portugu\u00e9s\u00A6litas lituano\u00A6tenge kazako\u00A6rublo kazako\u00A6d\u00f3lar de las Islas V\u00edrgenes Brit\u00e1nicas\u00A6libra nigeriana\u00A6certificados de cambio birmanos en d\u00f3lares\u00A6naira nigeriano\u00A6gourde haitiano\u00A6libra siria\u00A6libra palestina\u00A6dinar bahrein\u00ed\u00A6kyat de Myanmar\u00A6flor\u00edn de las Antillas Neerlandesas\u00A6corona checa\u00A6libra esterlina de la Isla de Man\u00A6certificados de cambio b\u00falgaros en leva\u00A6loti lesothense\u00A6franco CFA de Gab\u00f3n\u00A6lev b\u00falgaro (1879-1952)\u00A6nuevo lev b\u00falgaro\u00A6lev socialista b\u00falgaro\u00A6d\u00f3lar canadiense\u00A6lev fuerte b\u00falgaro\u00A6lira turca\u00A6d\u00f3lar de las Islas Caim\u00e1n\u00A6libra chipriota\u00A6nuevo sheqel israel\u00ed\u00A6d\u00f3lar guyan\u00e9s\u00A6dram armenio\u00A6libra israel\u00ed\u00A6franco mal\u00ed\u00A6sheqel israel\u00ed\u00A6bol\u00edvar venezolano\u00A6certificados de cambio albaneses en d\u00f3lares\u00A6d\u00f3lar liberiano\u00A6lek valute alban\u00e9s\u00A6kuna croata\u00A6franco de Reuni\u00f3n\u00A6dinar croata\u00A6lek alban\u00e9s\u00A6libra esterlina de Jersey\u00A6lek alban\u00e9s (1946-1961)\u00A6dinar macedonio (1992-1993)\u00A6viet minh piastre dong viet de Vietnam del Norte\u00A6nuevo dong de Vietnam del Norte\u00A6dinar macedonio\u00A6piastre dong viet de Vietnam del Norte\u00A6pataca timorense\u00A6franco CFP\u00A6franco belga (financiero)\u00A6peso de Guinea-Biss\u00e1u\u00A6dinar kuwait\u00ed\u00A6mil reis de Guinea Portuguesa\u00A6franco belga\u00A6escudo timorense\u00A6franco belga (convertible)\u00A6escudo de Guinea Portuguesa\u00A6col\u00f3n salvadore\u00f1o\u00A6flor\u00edn de Curazao\u00A6taka de Bangladesh\u00A6libra esterlina tongana\u00A6pa\u02bbanga tongano\u00A6franco CFA BCEAO\u00A6rublo sovi\u00e9tico\u00A6nuevo rublo sovi\u00e9tico\u00A6franco germinal de Nueva Caledonia\u00A6escudo de Cabo Verde\u00A6franco CFA de las Antillas Francesas\u00A6rand sudafricano\u00A6peso dominicano\u00A6certificados de cambio cubanos\u00A6libra sudafricana\u00A6rand sudafricano (financiero)\u00A6dinar tunecino\u00A6peso cubano\u00A6franco guayan\u00e9s de la Guayana Francesa\u00A6chel\u00edn ugand\u00e9s\u00A6rupia cingalesa\u00A6franco de Affars e Issas\u00A6lira de la Ciudad del Vaticano\u00A6escudo de Santo Tom\u00e9 y Pr\u00edncipe\u00A6chel\u00edn ugand\u00e9s (1966-1987)\u00A6dobra de Santo Tom\u00e9 y Pr\u00edncipe\u00A6d\u00f3lar de las Islas Marshall\u00A6libra neozelandesa\u00A6tala samoano\u00A6libra samoana\u00A6lempira hondure\u00f1o\u00A6nuevo franco metropolitano franc\u00e9s\u00A6manat turcomano\u00A6quetzal guatemalteco\u00A6d\u00f3lar neozeland\u00e9s\u00A6libra escocesa\u00A6d\u00f3lar de Barbados\u00A6d\u00f3lar de Namibia\u00A6franco malgache\u00A6ariary malgache\u00A6libra egipcia\u00A6d\u00f3lar de Honduras Brit\u00e1nica\u00A6zloty polaco (1950-1995)\u00A6nuevo dinar bosnio\u00A6certificados de cambio polacos en d\u00f3lares estadounidenses\u00A6marco bosnio convertible\u00A6d\u00f3lar de Belice\u00A6dinar bosnio\u00A6zloty polaco\u00A6rial yemen\u00ed\u00A6flor\u00edn surinam\u00e9s\u00A6corona fuerte checoslovaca\u00A6won surcoreano\u00A6rublo bielorruso\u00A6riyal Imadi yemen\u00ed\u00A6rublo bielorruso (1992-1994)\u00A6corona checoslovaca\u00A6antiguo won surcoreano\u00A6hwan surcoreano\u00A6nuevo rublo bielorruso (1994-1999)\u00A6chel\u00edn de Somalilandia\u00A6nuevo dracma griego\u00A6rupia pakistan\u00ed\u00A6afgani\u00A6d\u00f3lar de Zimbabue\u00A6rupia de Sri Lanka\u00A6dracma griego\u00A6libra irlandesa\u00A6afgani (1927-2002)\u00A6dinar yemen\u00ed\u00A6franco ruand\u00e9s\u00A6col\u00f3n costarricense\u00A6somoni tayiko\u00A6rublo tayiko\u00A6corona estonia\u00A6peseta guineana de Guinea Ecuatorial\u00A6cup\u00f3n rublo moldavo\u00A6d\u00f3lar de Hong Kong\u00A6corona danesa\u00A6leu moldavo\u00A6franco de Guinea Ecuatorial\u00A6ekuele de Guinea Ecuatorial\u00A6rupia indonesia\u00A6dirham de los Emiratos \u00c1rabes Unidos\u00A6won norcoreano\u00A6nueva rupia indonesia\u00A6pula botsuano\u00A6cup\u00f3n leu moldavo\u00A6rupia Java indonesia\u00A6won del pueblo norcoreano\u00A6flor\u00edn Nica indonesio\u00A6vatu vanuatuense\u00A6dinar isl\u00e1mico\u00A6chel\u00edn somal\u00ed\u00A6peseta andorrana\u00A6rublo ruso (1991-1998)\u00A6franco de Guadalupe\u00A6franco de Yibuti\u00A6diner andorrano\u00A6franco germinal monegasco\u00A6nuevo franco monegasco\u00A6unidad de valor constante (UVC) ecuatoriana\u00A6sucre ecuatoriano\u00A6franco de Liechtenstein\u00A6rublo ruso\u00A6peso filipino\u00A6sum uzbeko\u00A6peso colombiano\u00A6baht tailand\u00e9s\u00A6libra de Irlanda del Norte\u00A6rupia birmana\u00A6franco CFA del Congo\u00A6kyat birmano\u00A6peso de papel colombiano\u00A6cup\u00f3n som uzbeko\u00A6karbovanet ucraniano\u00A6riyal de Qatar\u00A6grivna ucraniana\u00A6syli guineano\u00A6yuan renminbi chino\u00A6metical mozambique\u00f1o\u00A6certificados de cambio chinos en d\u00f3lares estadounidenses\u00A6peso uruguayo\u00A6franco guineo (1960-1972)\u00A6lira de San Marino\u00A6jen min piao yuan chino\u00A6escudo mozambique\u00f1o\u00A6franco guineo\u00A6rial saidi oman\u00ed\u00A6kina de Pap\u00faa Nueva Guinea\u00A6rial oman\u00ed\u00A6peso uruguayo (1975-1993)\u00A6franco UIC franc\u00e9s\u00A6rupia butanesa\u00A6zaire zaire\u00f1o\u00A6franco marroqu\u00ed\u00A6dirham marroqu\u00ed\u00A6ngultrum butan\u00e9s\u00A6franco oro franc\u00e9s\u00A6peso fuerte uruguayo\u00A6ringgit malasio\u00A6nuevo zaire zaire\u00f1o\u00A6manat azer\u00ed\u00A6libra gambiana\u00A6franco comorense\u00A6leone de Sierra Leona\u00A6dalasi gambiano\u00A6unidad de moneda europea\u00A6libra de las Bahamas\u00A6franco CFA de Camer\u00fan\u00A6unidad de inversi\u00f3n (UDI) mexicana\u00A6franco CFA BCEAEC\u00A6d\u00f3lar de las Bahamas\u00A6peso de plata mexicano (1861-1992)\u00A6peso mexicano\u00A6sol peruano\u00A6corona de Groenlandia\u00A6cruceiro brasile\u00f1o (1942-1967)\u00A6nuevo sol peruano\u00A6peso chileno\u00A6corona eslovaca\u00A6inti peruano\u00A6cruceiro brasile\u00f1o\u00A6derechos especiales de giro\u00A6franco germinal/franco Poincar\u00e9 franc\u00e9s\u00A6franco franc\u00e9s\u00A6nuevo cruzado brasile\u00f1o\u00A6unidad de fomento chilena\u00A6escudo chileno\u00A6real brasile\u00f1o\u00A6c\u00f3ndor chileno\u00A6cruceiro brasile\u00f1o (1990-1993)\u00A6sperrmark alem\u00e1n\u00A6libra de Malawi\u00A6cruzado brasile\u00f1o\u00A6nuevo cruceiro brasile\u00f1o (1967-1986)\u00A6kwacha de Malawi\u00A6rublo de Transdniestria\u00A6marco alem\u00e1n\u00A6franco CFA del Chad\u00A6nuevo rublo de Transdniestria\u00A6cup\u00f3n rublo de Transdniestria\u00A6rupia nepalesa\u00A6d\u00f3lar de las Islas Cook\u00A6yen japon\u00e9s\u00A6rufiyaa de Maldivas\u00A6nuevo franco CFA\u00A6rupia de Maldivas\u00A6d\u00f3lar del Caribe Oriental\u00A6t\u00f3lar esloveno\u00A6dinar reformado yugoslavo\u00A6flor\u00edn de Aruba\u00A6dinar de octubre yugoslavo\u00A6ostmark de Alemania del Este\u00A6dinar convertible yugoslavo\u00A6super dinar yugoslavo\u00A6corona de las Islas Turcas y Caicos\u00A6dinar 1994 yugoslavo\u00A6dinar de la Federaci\u00f3n Yugoslava\u00A6nuevo leu rumano\u00A6dinar fuerte yugoslavo\u00A6leu rumano\u00A6t\u00f3lar bons esloveno\u00A6corona noruega\u00A6rupia mauriciana\u00A6unidad de cuenta europea (XBD)\u00A6libra de Gibraltar\u00A6dong nacional vietnamita\u00A6unidad de cuenta europea (XBC)\u00A6dong de la Rep\u00fablica del vietnamita\u00A6unidad monetaria europea\u00A6unidad compuesta europea\u00A6d\u00f3lar de Kiribati\u00A6libra de Santa Elena\u00A6nuevo dong vietnamita";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6BOB\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6AFN\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6AFA\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GNF\u00A6OMS\u00A6PGK\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JD\u00A6BOV\u00A6XAU\u00A6FOK\u00A6LL\u00A6VND\u00A6T Sh\u00A6BOP\u00A6CR\u00A6XAM\u00A6BOL\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6XAD\u00A6GHP\u00A6Bs\u00A6GHO\u00A6Lm\u00A6$A\u00A6USS\u00A6USN\u00A6GHC\u00A6S$\u00A6PAB\u00A6LAK\u00A6som\u00A6SwF\u00A6ATS\u00A6US$\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6\u20a7\u00A6BMP\u00A6LD\u00A6LYB\u00A6Ber$\u00A6NLG\u00A6UM\u00A6RI\u00A6SKr\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6XTR\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6Ft\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SRl\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6CZK\u00A6IMP\u00A6BGX\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6Can$\u00A6lev\u00A6TL\u00A6KYD\u00A6\u00a3C\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6T$\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6XNF\u00A6R\u00A6RD$\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6XMF\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Af\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6AFA\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HK$\u00A6DKr\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6Y\u00A6Mt\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6CNP\u00A6MZE\u00A6GF\u00A6OMS\u00A6PGK\u00A6RO\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6Nu\u00A6XFO\u00A6UYF\u00A6RM\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6CF\u00A6SLL\u00A6GMD\u00A6XEU\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6Ch$\u00A6Sk\u00A6PEI\u00A6BRR\u00A6XDR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6leu\u00A6SIB\u00A6NKr\u00A6MUR\u00A6XBD\u00A6GIP\u00A6VNS\u00A6XBC\u00A6VNR\u00A6XBB\u00A6XBA\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "ene",
    "feb",
    "mar",
    "abr",
    "may",
    "jun",
    "jul",
    "ago",
    "sep",
    "oct",
    "nov",
    "dic",
    null,
  };

  private static final String[] months = {
    "enero",
    "febrero",
    "marzo",
    "abril",
    "mayo",
    "junio",
    "julio",
    "agosto",
    "septiembre",
    "octubre",
    "noviembre",
    "diciembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dom",
    "lun",
    "mar",
    "mi\u00e9",
    "jue",
    "vie",
    "s\u00e1b",
  };

  private static final String[] weekdays = {
    null,
    "domingo",
    "lunes",
    "martes",
    "mi\u00e9rcoles",
    "jueves",
    "viernes",
    "s\u00e1bado",
  };

  private static final String[] eras = {
    "a.C.",
    "d.C.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "Hora est\u00e1ndar oriental", "EST", "Hora est\u00e1ndar oriental"},
    {  "America/Halifax", "AST", "Hora est\u00e1ndar del Atl\u00e1ntico", "ADT", "Hora de verano del Atl\u00e1ntico"},
    {  "Pacific/Honolulu", "HST", "Hora est\u00e1ndar de Hawai", "HST", "Hora est\u00e1ndar de Hawai"},
    {  "America/Denver", "MST", "Hora est\u00e1ndar de Monta\u00f1a", "MDT", "Hora de verano de Monta\u00f1a"},
    {  "America/Anchorage", "AST", "Hora est\u00e1ndar de Alaska", "ADT", "Hora de verano de Alaska"},
    {  "America/St_Johns", "CNT", "Hora est\u00e1ndar de Newfoundland", "CDT", "Hora de verano de Newfoundland"},
    {  "Africa/Casablanca", "GMT", "Hora media de Greenwich", "GMT", "Hora media de Greenwich"},
    {  "America/Chicago", "CST", "Hora est\u00e1ndar central", "CDT", "Hora de verano central"},
    {  "Asia/Shanghai", "CTT", "Hora est\u00e1ndar de China", "CDT", "Hora est\u00e1ndar de China"},
    {  "Asia/Tokyo", "JST", "Hora est\u00e1ndar de Jap\u00f3n", "JST", "Hora est\u00e1ndar de Jap\u00f3n"},
    {  "America/New_York", "EST", "Hora est\u00e1ndar oriental", "EDT", "Hora de verano oriental"},
    {  "Europe/Bucharest", "EET", "Hora est\u00e1ndar de Europa del Este", "EEST", "Hora de verano de Europa del Este"},
    {  "America/Los_Angeles", "PST", "Hora est\u00e1ndar del Pac\u00edfico", "PDT", "Hora de verano del Pac\u00edfico"},
    {  "America/Phoenix", "MST", "Hora est\u00e1ndar de Monta\u00f1a", "MST", "Hora est\u00e1ndar de Monta\u00f1a"},
    {  "Etc/GMT", "GMT", "Hora media de Greenwich", "GMT", "Hora media de Greenwich"},
    {  "Asia/Jerusalem", "IST", "Hora est\u00e1ndar de Israel", "IDT", "Hora de verano de Israel"},
    {  "Europe/Paris", "CET", "Hora est\u00e1ndar de Europa Central", "CEST", "Hora de verano de Europa Central"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Timor Oriental\u00A6Islas Tokelau\u00A6Tayikist\u00e1n\u00A6Tailandia\u00A6Togo\u00A6Territorios Australes Franceses\u00A6Guyana\u00A6Chad\u00A6Islas Turcas y Caicos\u00A6Guinea-Bissau\u00A6Guam\u00A6Guatemala\u00A6Islas Georgia del Sur y Sandwich del Sur\u00A6Grecia\u00A6Guinea Ecuatorial\u00A6Guadalupe\u00A6Suazilandia\u00A6Siria\u00A6Guinea\u00A6Gambia\u00A6Groenlandia\u00A6El Salvador\u00A6Santo Tom\u00e9 y Pr\u00edncipe\u00A6Gibraltar\u00A6Ghana\u00A6Suriname\u00A6Guayana Francesa\u00A6Georgia\u00A6Somalia\u00A6Granada\u00A6Senegal\u00A6San Marino\u00A6Reino Unido\u00A6Sierra Leona\u00A6Gab\u00f3n\u00A6Eslovaquia\u00A6Svalbard y Jan Mayen\u00A6Eslovenia\u00A6Santa Elena\u00A6Singapur\u00A6Suecia\u00A6Sud\u00e1n\u00A6Seychelles\u00A6Islas Salom\u00f3n\u00A6Arabia Saud\u00ed\u00A6Francia\u00A6Islas Feroe\u00A6Micronesia\u00A6Ruanda\u00A6Islas Falkland (Malvinas)\u00A6Rusia\u00A6Fiyi\u00A6Finlandia\u00A6Ruman\u00eda\u00A6R\u00e9union\u00A6Etiop\u00eda\u00A6Espa\u00f1a\u00A6Eritrea\u00A6S\u00e1hara Occidental\u00A6Egipto\u00A6Estonia\u00A6Ecuador\u00A6Argelia\u00A6Qatar\u00A6Rep\u00fablica Dominicana\u00A6Paraguay\u00A6Dominica\u00A6Palau\u00A6Dinamarca\u00A6Yibuti\u00A6Portugal\u00A6Territorios Palestinos\u00A6Puerto Rico\u00A6Alemania\u00A6Pitcairn\u00A6San Pedro y Miquel\u00f3n\u00A6Polonia\u00A6Pakist\u00e1n\u00A6Filipinas\u00A6Pap\u00faa Nueva Guinea\u00A6Polinesia Francesa\u00A6Rep\u00fablica Checa\u00A6Per\u00fa\u00A6Chipre\u00A6Isla Navidad\u00A6Cabo Verde\u00A6Panam\u00e1\u00A6Cuba\u00A6Costa Rica\u00A6Colombia\u00A6China\u00A6Camer\u00fan\u00A6Chile\u00A6Islas Cook\u00A6Costa de Marfil\u00A6Suiza\u00A6Congo\u00A6Rep\u00fablica Centroafricana\u00A6Rep\u00fablica Democr\u00e1tica del Congo\u00A6Islas Cocos (Keeling)\u00A6Om\u00e1n\u00A6Canad\u00e1\u00A6Belice\u00A6Bielorrusia\u00A6Botsuana\u00A6Isla Bouvet\u00A6But\u00e1n\u00A6Bahamas\u00A6Brasil\u00A6Nueva Zelanda\u00A6Bolivia\u00A6Brun\u00e9i\u00A6Bermudas\u00A6Isla Niue\u00A6Ben\u00edn\u00A6Burundi\u00A6Bahr\u00e1in\u00A6Nauru\u00A6Bulgaria\u00A6Burkina Faso\u00A6Nepal\u00A6B\u00e9lgica\u00A6Noruega\u00A6Bangladesh\u00A6Barbados\u00A6Zimbabue\u00A6Pa\u00edses Bajos\u00A6Bosnia-Herzegovina\u00A6Nicaragua\u00A6Nigeria\u00A6Isla Norfolk\u00A6Azerbaiy\u00e1n\u00A6N\u00edger\u00A6Nueva Caledonia\u00A6Aruba\u00A6Zambia\u00A6Namibia\u00A6Australia\u00A6Austria\u00A6Samoa Americana\u00A6Argentina\u00A6Ant\u00e1rtida\u00A6Mozambique\u00A6Angola\u00A6Malasia\u00A6Antillas Neerlandesas\u00A6M\u00e9xico\u00A6Armenia\u00A6Malawi\u00A6Albania\u00A6Maldivas\u00A6Sud\u00e1frica\u00A6Mauricio\u00A6Malta\u00A6Anguila\u00A6Montserrat\u00A6Mauritania\u00A6Antigua y Barbuda\u00A6Martinica\u00A6Afganist\u00e1n\u00A6Islas Marianas del Norte\u00A6Emiratos \u00c1rabes Unidos\u00A6Macao, Regi\u00f3n administrativa especial de China\u00A6Andorra\u00A6Mongolia\u00A6Myanmar\u00A6Mal\u00ed\u00A6Macedonia\u00A6Yugoslavia\u00A6Mayotte\u00A6Islas Marshall\u00A6Madagascar\u00A6Moldova\u00A6M\u00f3naco\u00A6Marruecos\u00A6Yemen\u00A6Libia\u00A6Letonia\u00A6Luxemburgo\u00A6Lituania\u00A6Lesotho\u00A6Liberia\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Saint Lucia\u00A6L\u00edbano\u00A6Laos\u00A6Kazajst\u00e1n\u00A6Islas Caim\u00e1n\u00A6Kuwait\u00A6Corea del Sur\u00A6Corea del Norte\u00A6San Crist\u00f3bal y Nieves\u00A6Comoras\u00A6Kiribati\u00A6Samoa\u00A6Camboya\u00A6Kirguizist\u00e1n\u00A6Kenia\u00A6Wallis y Futuna\u00A6Jap\u00f3n\u00A6Jordania\u00A6Jamaica\u00A6Vanuatu\u00A6Vietnam\u00A6Islas V\u00edrgenes de los Estados Unidos\u00A6Islas V\u00edrgenes Brit\u00e1nicas\u00A6Venezuela\u00A6San Vicente y las Granadinas\u00A6Ciudad del Vaticano\u00A6Italia\u00A6Islandia\u00A6Ir\u00e1n\u00A6Iraq\u00A6Uzbekist\u00e1n\u00A6Territorios Brit\u00e1nico del Oc\u00e9ano \u00cdndico\u00A6Uruguay\u00A6India\u00A6Israel\u00A6Estados Unidos\u00A6Irlanda\u00A6Indonesia\u00A6Islas menores alejadas de los Estados Unidos\u00A6Uganda\u00A6Ucrania\u00A6Hungr\u00eda\u00A6Hait\u00ed\u00A6Croacia\u00A6Tanzania\u00A6Honduras\u00A6Islas Heard y McDonald\u00A6Taiw\u00e1n\u00A6Tuvalu\u00A6Hong-Kong, Regi\u00f3n administrativa especial de China\u00A6Trinidad y Tabago\u00A6Turqu\u00eda\u00A6Tonga\u00A6T\u00fanez\u00A6Turkmenist\u00e1n";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6ijo\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6kut\u00A6mic\u00A6wa\u00A6kum\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6vai\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6fan\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6bai\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tl\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sn\u00A6sm\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6tiv\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6snk\u00A6cop\u00A6yap\u00A6ach\u00A6yao\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6sms\u00A6bua\u00A6mas\u00A6smn\u00A6os\u00A6map\u00A6or\u00A6man\u00A6smj\u00A6smi\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6sma\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6root\u00A6ng\u00A6sla\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6kv\u00A6ku\u00A6sio\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6jv\u00A6gil\u00A6znd\u00A6shn\u00A6fon\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6ath\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6ypk\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6tup\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6nia\u00A6moh\u00A6luo\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6mno\u00A6wak\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6sal\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6pra\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "kutchin\u00A6acadio\u00A6ekajuk\u00A6ijo\u00A6xhosa\u00A6sumerio\u00A6susu\u00A6lenguas varias\u00A6lozi\u00A6tonga (Niasa)\u00A6pohnpeiano\u00A6minangkabau\u00A6sukuma\u00A6uolof\u00A6mongo\u00A6kutenai\u00A6micmac\u00A6val\u00f3n\u00A6kumyk\u00A6zapoteco\u00A6cusitas (otras)\u00A6lojban\u00A6dogri\u00A6volapuk\u00A6lenguas otomanas\u00A6vietnamita\u00A6vai\u00A6rarotongano\u00A6venda\u00A6rapanui\u00A6rajasthani\u00A6turco otomano (1500-1928)\u00A6nzima\u00A6napolitano\u00A6uzbeko\u00A6ugar\u00edtico\u00A6tamashek\u00A6indias norteamericanas (otras)\u00A6n\u00e1huatl\u00A6urdu\u00A6fanti\u00A6ucraniano\u00A6egipcio (antiguo)\u00A6uigur\u00A6fang\u00A6nilosaharianas (otras)\u00A6irland\u00e9s medieval (900-1200)\u00A6b\u00e1lticas (otras)\u00A6nyoro\u00A6basa\u00A6nyankole\u00A6nyamwezi\u00A6hmong\u00A6balin\u00e9s\u00A6osage\u00A6baluchi\u00A6tahitiano\u00A6lenguas bamileke\u00A6twi\u00A6serer\u00A6tlingit\u00A6tatar\u00A6tsonga\u00A6banda\u00A6turco\u00A6tonga (Islas Tonga)\u00A6setchwana\u00A6tagalo\u00A6turkmeno\u00A6tigrinya\u00A6tailand\u00e9s\u00A6kurukh\u00A6tayiko\u00A6blin\u00A6telugu\u00A6kru\u00A6casubio\u00A6tamil\u00A6tokelauano\u00A6efik\u00A6swahili\u00A6sueco\u00A6sundan\u00e9s\u00A6karachay-balkar\u00A6sesotho\u00A6siswati\u00A6serbio\u00A6alban\u00e9s\u00A6mende\u00A6criollas y pidgins (otras)\u00A6somal\u00ed\u00A6afrihili\u00A6shona\u00A6samoano\u00A6esloveno\u00A6griego antiguo (hasta el 1453)\u00A6eslovaco\u00A6gerbo\u00A6singal\u00e9s\u00A6serbo-croata\u00A6turco de Crimea; t\u00e1rtaro de Crimea\u00A6afroasi\u00e1tica (otra)\u00A6sango\u00A6sami septentrional\u00A6sindhi\u00A6udmurt\u00A6sardo\u00A6s\u00e1nscrito\u00A6kinyarwanda\u00A6ruso\u00A6mandar\u00A6rumano\u00A6kiroundi\u00A6reto-romance\u00A6moksha\u00A6tiv\u00A6adigeo\u00A6zuni\u00A6kpelle\u00A6quechua\u00A6tigr\u00e9\u00A6songhai\u00A6criollas y pidgins, basadas en el portugu\u00e9s (otras)\u00A6sogdiano\u00A6adangme\u00A6kosraeano\u00A6hitita\u00A6criollas y pidgins, basadas en el ingl\u00e9s (otras)\u00A6himachali\u00A6konkani\u00A6hiligaynon\u00A6g\u00f3tico\u00A6gorontalo\u00A6gondi\u00A6dinka\u00A6lenguas nubias\u00A6portugu\u00e9s\u00A6pashto\u00A6friulano\u00A6fenicio\u00A6alem\u00e1n de la alta edad antigua (750-1050 aprox.)\u00A6sonink\u00e9\u00A6copto\u00A6yap\u00e9s\u00A6acoli\u00A6yao\u00A6filipinas (otras)\u00A6polaco\u00A6acehn\u00e9s\u00A6pali\u00A6punjab\u00ed\u00A6bugin\u00e9s\u00A6iban\u00A6sami sklot\u00A6buriat\u00A6masai\u00A6sami inari\u00A6os\u00e9tico\u00A6austronesio\u00A6oriya\u00A6mandingo\u00A6sami lule\u00A6lenguas sami (otras)\u00A6macasar\u00A6oromo\u00A6maithili\u00A6ojibwa\u00A6magahi\u00A6madur\u00e9s\u00A6sami meridional\u00A6occitano (despu\u00e9s del 1500)\u00A6sesotho septentrional\u00A6batak\u00A6erzya\u00A6dogrib\u00A6nyanja\u00A6maya\u00A6navajo\u00A6kimbundu\u00A6ndebele meridional\u00A6alem\u00e1n de la alta edad media (1050-1500 aprox.)\u00A6noruego\u00A6nynorsk noruego\u00A6holand\u00e9s\u00A6ra\u00edz\u00A6ndonga\u00A6eslavas (otras)\u00A6nepal\u00ed\u00A6ndebele septentrional\u00A6lenguas ch\u00e1micas\u00A6tet\u00fan\u00A6bokmal noruego\u00A6nauruano\u00A6tereno\u00A6temne\u00A6birmano\u00A6lezgiano\u00A6malt\u00e9s\u00A6persa antiguo (600-400 a.C. aprox.)\u00A6malayo\u00A6marathi\u00A6franc\u00e9s antiguo (842-1400 aprox.)\u00A6moldavo\u00A6franc\u00e9s medieval (1400-1600 aprox.)\u00A6mongol\u00A6judeo-\u00e1rabe\u00A6malayalam\u00A6macedonio\u00A6maor\u00ed\u00A6marshal\u00e9s\u00A6malgache\u00A6marwari\u00A6braj\u00A6slave\u00A6let\u00f3n\u00A6luba-katanga\u00A6delaware\u00A6lituano\u00A6laosiano\u00A6lingala\u00A6limburgu\u00e9s\u00A6ewondo\u00A6ganda\u00A6luxemburgu\u00e9s\u00A6lat\u00edn\u00A6judeo-persa\u00A6v\u00f3tico\u00A6sino-tibetanas (otras)\u00A6kirghiz\u00A6c\u00f3rnico\u00A6komi\u00A6kurdo\u00A6lenguas siouan\u00A6cachemiro\u00A6kanuri\u00A6avadhi\u00A6coreano\u00A6canar\u00e9s\u00A6jemer\u00A6groenland\u00e9s\u00A6kazajo\u00A6roman\u00ed\u00A6kuanyama\u00A6sidamo\u00A6kikuyu\u00A6kongo\u00A6norse antiguo\u00A6georgiano\u00A6creek\u00A6rom\u00e1nicas (otras)\u00A6nogai\u00A6lenguas munda\u00A6lenguas m\u00faltiples\u00A6javan\u00e9s\u00A6gilbert\u00e9s\u00A6zande\u00A6shan\u00A6fon\u00A6kalmyk\u00A6lenguas australianas\u00A6kotan\u00e9s\u00A6japon\u00e9s\u00A6khoisan (otras)\u00A6palavano\u00A6cheyene\u00A6tai (otras)\u00A6inuktitut\u00A6papiamento\u00A6italiano\u00A6lenguajes de signos\u00A6island\u00e9s\u00A6khasi\u00A6cherokee\u00A6pampanga\u00A6pahlavi\u00A6chipewyan\u00A6ido\u00A6choctaw\u00A6jerga chinuk\u00A6mar\u00ed\u00A6tuviniano\u00A6bant\u00fa\u00A6pangasin\u00e1n\u00A6inupiak\u00A6truk\u00e9s\u00A6sichuan yi\u00A6hawaiano\u00A6lamba\u00A6igbo\u00A6chagat\u00e1i\u00A6irland\u00e9s antiguo (hasta 900)\u00A6pap\u00faes (otras)\u00A6interlingue\u00A6indonesio\u00A6lahnda\u00A6dayak\u00A6chibcha\u00A6interlingua\u00A6ladino\u00A6herero\u00A6haida\u00A6dargva\u00A6armenio\u00A6lenguas atabascas\u00A6h\u00fangaro\u00A6haitiano\u00A6dakota\u00A6croata\u00A6hiri motu\u00A6hindi\u00A6diula\u00A6hebreo\u00A6asturiano\u00A6hausa\u00A6lenguas sorbias\u00A6ga\u00e9lico man\u00e9s\u00A6gujarati\u00A6sem\u00edticas (otras)\u00A6selkup\u00A6lenguas iroquesas\u00A6guaran\u00ed\u00A6gallego\u00A6arahuaco\u00A6geez\u00A6artificiales (otras)\u00A6ga\u00e9lico escoc\u00e9s\u00A6iranio\u00A6irland\u00e9s\u00A6arapaho\u00A6araucano\u00A6fris\u00f3n\u00A6siksika\u00A6germ\u00e1nicas (otras)\u00A6lenguas yupik\u00A6arameo\u00A6franc\u00e9s\u00A6fero\u00e9s\u00A6celtas (otras)\u00A6fidji\u00A6finland\u00e9s\u00A6fula\u00A6tuvaluano\u00A6cebuano\u00A6farsi\u00A6vasco\u00A6escoc\u00e9s\u00A6estonio\u00A6espa\u00f1ol\u00A6esperanto\u00A6ingl\u00e9s\u00A6griego\u00A6altaicas (otras)\u00A6niueano\u00A6lenguas tup\u00ed\u00A6ewe\u00A6tumbuka\u00A6mossi\u00A6bhutan\u00ed\u00A6n\u00edger-kordofanianas (otras)\u00A6lushai\u00A6finougrias (otras)\u00A6divehi\u00A6nias\u00A6mohawk\u00A6luo\u00A6lunda\u00A6lenguas apache\u00A6luise\u00f1o\u00A6hupa\u00A6bini\u00A6alem\u00e1n\u00A6luba-lulua\u00A6bicol\u00A6washo\u00A6indeterminada\u00A6waray\u00A6dan\u00e9s\u00A6neerland\u00e9s medio (1050-1350 aprox.)\u00A6walamo\u00A6lenguas manobo\u00A6lenguas wakasha\u00A6santali\u00A6gal\u00e9s\u00A6sasak\u00A6kabardiana\u00A6chuvash\u00A6eslavo eclesi\u00e1stico\u00A6manipuri\u00A6checo\u00A6arameo samaritano\u00A6cree\u00A6lenguas salishan\u00A6duala\u00A6corso\u00A6indias sudamericanas (otras)\u00A6manch\u00fa\u00A6yakut\u00A6kawi\u00A6ingush\u00A6gbaya\u00A6sandawe\u00A6chamorro\u00A6indoeuropeas (otras)\u00A6bhojpuri\u00A6ingl\u00e9s medieval (1100-1500)\u00A6karen\u00A6\u00edndicas (otras)\u00A6checheno\u00A6gayo\u00A6catal\u00e1n\u00A6umbundu\u00A6siriaco\u00A6kamba\u00A6tsimshiano\u00A6ingl\u00e9s antiguo (450-1100 aprox.)\u00A6kachin\u00A6cauc\u00e1sicas (otras)\u00A6cabila\u00A6karakalpako\u00A6bosnio\u00A6caribe\u00A6bret\u00f3n\u00A6tibetano\u00A6bengal\u00ed\u00A6bambara\u00A6ga\u00A6indias centroamericanas (otras)\u00A6bislama\u00A6bihari\u00A6b\u00falgaro\u00A6bielorruso\u00A6caddo\u00A6bashkir\u00A6zul\u00fa\u00A6zenaga\u00A6provenzal antiguo (hasta el 1500)\u00A6sorbio superior\u00A6azer\u00ed\u00A6aymara\u00A6avar\u00A6asam\u00e9s\u00A6sorbio inferior\u00A6\u00e1rabe\u00A6ilocano\u00A6elamita\u00A6chino\u00A6aragon\u00e9s\u00A6lenguas prakrit\u00A6am\u00e1rico\u00A6newari\u00A6akan\u00A6zhuang\u00A6afrikaans\u00A6av\u00e9stico\u00A6abkhaziano\u00A6afar\u00A6yoruba\u00A6lenguas algonquinas\u00A6aleutiano\u00A6mon-jemer (otras)\u00A6yidish\u00A6drav\u00eddicas (otras)\u00A6bereber\u00A6bajo alem\u00e1n; bajo saj\u00f3n\u00A6bemba\u00A6beja\u00A6tok pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final String variantsKeys = "REVISED";

  private static final String variantsValues = "Revisado";

  private static final Hashtable variants;
  static
  {
    variants = new Hashtable();
    Enumeration keys = new StringTokenizer(variantsKeys, "\u00A6");
    Enumeration values = new StringTokenizer(variantsValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         variants.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "currencyFormat", "\u00a4#,##0.00;(\u00a4#,##0.00)" },
    { "localPatternChars", "GuMtkHmsSEDFwWahKzUeygAZ" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "shortDateFormat", "d/MM/yy" },
    { "mediumDateFormat", "dd-MMM-yy" },
    { "longDateFormat", "d' de 'MMMM' de 'yyyy" },
    { "fullDateFormat", "EEEE d' de 'MMMM' de 'yyyy" },
    { "fullTimeFormat", "HH'H'mm''ss\" z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
