/* LocaleInformation_ga.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML ga.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_ga extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "Ean",
    "Feabh",
    "M\u00e1rta",
    "Aib",
    "Beal",
    "Meith",
    "I\u00fail",
    "L\u00fan",
    "MF\u00f3mh",
    "DF\u00f3mh",
    "Samh",
    "Noll",
    null,
  };

  private static final String[] months = {
    "Ean\u00e1ir",
    "Feabhra",
    "M\u00e1rta",
    "Aibre\u00e1n",
    "Bealtaine",
    "Meitheamh",
    "I\u00fail",
    "L\u00fanasa",
    "Me\u00e1n F\u00f3mhair",
    "Deireadh F\u00f3mhair",
    "Samhain",
    "Nollaig",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Domh",
    "Luan",
    "M\u00e1irt",
    "C\u00e9ad",
    "D\u00e9ar",
    "Aoine",
    "Sath",
  };

  private static final String[] weekdays = {
    null,
    "D\u00e9 Domhnaigh",
    "D\u00e9 Luain",
    "D\u00e9 M\u00e1irt",
    "D\u00e9 C\u00e9adaoin",
    "D\u00e9ardaoin",
    "D\u00e9 hAoine",
    "D\u00e9 Sathairn",
  };

  private static final String[] eras = {
    "RC",
    "AD",
  };

  private static final String[] ampms = {
    "a.m.",
    "p.m.",
  };

  private static final String[][] zoneStrings =
  {
    { "Etc/GMT", "Me\u00e1n-Am Greenwich", "MAG", "Me\u00e1n-Am Greenwich", "MAG" },
    { "Europe/Dublin", "Me\u00e1n-Am Greenwich", "MAG", "Am Samhraidh na h\u00c9ireann", "AS\u00c9" },
    { "Europe/Belfast", "Me\u00e1n-Am Greenwich", "MAG", "Am Samhraidh na Breataine", "ASB" },
    { "Europe/London", "Me\u00e1n-Am Greenwich", "MAG", "Am Samhraidh na Breataine", "ASB" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "T\u00edom\u00f3r-Leste");
        put("TK", "T\u00f3cal\u00e1");
        put("TJ", "An T\u00e1ids\u00edceast\u00e1in");
        put("TH", "An T\u00e9alainn");
        put("TG", "T\u00f3ga");
        put("TF", "Cr\u00edocha Francacha Theas");
        put("GY", "An Ghu\u00e1in");
        put("TD", "Sead");
        put("TC", "Oile\u00e1in Turks agus Caicos");
        put("GW", "An Ghuine-Bhissau");
        put("GU", "Guam");
        put("GT", "Guatamala");
        put("GS", "An tSeoirsia Theas agus Oile\u00e1in Sandwich Theas");
        put("GR", "An Ghr\u00e9ig");
        put("GQ", "An Ghuine Mhe\u00e1nchriosach");
        put("GP", "Guadal\u00faip");
        put("SZ", "An tSuasalainn");
        put("SY", "An tSiria");
        put("GN", "An Ghuine");
        put("GM", "An Ghaimbia");
        put("GL", "An Ghraonlainn");
        put("SV", "An tSalvad\u00f3ir");
        put("ST", "Sao Tome agus Principe");
        put("GI", "Giobr\u00e1ltar");
        put("GH", "G\u00e1na");
        put("SR", "Suranam");
        put("GF", "An Ghu\u00e1in Fhrancach");
        put("SP", "An tSeirbia");
        put("GE", "An tSeoirsia");
        put("SO", "An tSom\u00e1il");
        put("GD", "Grenada");
        put("SN", "An tSeineag\u00e1il");
        put("SM", "San Mair\u00edne");
        put("GB", "An R\u00edocht Aontaithe");
        put("SL", "Siarra Leon");
        put("GA", "An Ghab\u00fain");
        put("SK", "An tSl\u00f3vaic");
        put("SJ", "Svalbard agus Jan Mayen");
        put("SI", "An tSl\u00f3v\u00e9in");
        put("SH", "San H\u00e9ilin");
        put("SG", "Singeap\u00f3r");
        put("SE", "An tSualainn");
        put("SD", "An tS\u00fad\u00e1in");
        put("SC", "Na S\u00e9is\u00e9il");
        put("SB", "Oile\u00e1in Solomon");
        put("SA", "An Araib Sh\u00e1dach");
        put("FR", "An Fhrainc");
        put("FO", "Oile\u00e1in Fhar\u00f3");
        put("FM", "An Mhicrin\u00e9is");
        put("RW", "Ruanda");
        put("FK", "Oile\u00e1in Fh\u00e1clainne");
        put("RU", "C\u00f3naidhm na R\u00faise");
        put("FJ", "Fids\u00ed");
        put("FI", "An Fhionlainn");
        put("RO", "An R\u00f3m\u00e1in");
        put("RE", "R\u00e9union");
        put("ET", "An Aet\u00f3ip");
        put("ES", "An Sp\u00e1inn");
        put("ER", "Eritrea");
        put("EH", "An Sah\u00e1ra Thiar");
        put("EG", "An \u00c9igipt");
        put("EE", "An East\u00f3in");
        put("EC", "Eacuad\u00f3r");
        put("DZ", "An Ailg\u00e9ir");
        put("QA", "Catar");
        put("DO", "An Phoblacht Dhoiminiceach");
        put("PY", "Paragua");
        put("DM", "Doiminice");
        put("PW", "Palau");
        put("DK", "An Danmhairg");
        put("DJ", "Djibouti");
        put("PT", "An Phortaing\u00e9il");
        put("PS", "Na Cr\u00edocha Pailist\u00edneacha");
        put("PR", "Port\u00f3 R\u00edce");
        put("DE", "An Ghearm\u00e1in");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre agus Miquelon");
        put("PL", "An Pholainn");
        put("PK", "An Phacast\u00e1in");
        put("PH", "Na hOile\u00e1in Fhilip\u00edneacha");
        put("PG", "Nua-Ghuine Phapua");
        put("PF", "An Pholain\u00e9is Fhrancach");
        put("CZ", "Poblacht na Seice");
        put("PE", "Peiri\u00fa");
        put("CY", "An Chipir");
        put("CX", "Oile\u00e1n na Nollag");
        put("CV", "Rinn Verde");
        put("PA", "Panama");
        put("CU", "C\u00faba");
        put("CR", "C\u00f3sta R\u00edce");
        put("CO", "An Chol\u00f3im");
        put("CN", "An tS\u00edn");
        put("CM", "Camar\u00fan");
        put("CL", "An tSile");
        put("CK", "Oile\u00e1in Cook");
        put("CI", "An C\u00f3sta Eabhair");
        put("CH", "An Eilv\u00e9is");
        put("CG", "An Cong\u00f3");
        put("CF", "Poblacht na hAfraice L\u00e1ir");
        put("CD", "Poblacht Dhaonlathach an Chong\u00f3");
        put("CC", "Oile\u00e1in Cocos (Keeling)");
        put("OM", "Oman");
        put("CA", "Ceanada");
        put("BZ", "An Bheil\u00eds");
        put("BY", "An Bhealar\u00fais");
        put("BW", "An Bhotsu\u00e1in");
        put("BV", "Oile\u00e1in Bouvet");
        put("BT", "An Bh\u00fat\u00e1in");
        put("BS", "Na Bah\u00e1ma\u00ed");
        put("BR", "An Bhrasa\u00edl");
        put("NZ", "An Nua-Sh\u00e9alainn");
        put("BO", "An Bholaiv");
        put("BN", "Br\u00fain\u00e9");
        put("BM", "Beirmi\u00fada");
        put("NU", "Niue");
        put("BJ", "Beinin");
        put("BI", "An Bhur\u00fain");
        put("BH", "Bair\u00e9in");
        put("NR", "N\u00e1r\u00fa");
        put("BG", "An Bhulg\u00e1ir");
        put("BF", "Buirc\u00edne Fas\u00f3");
        put("NP", "Neipeal");
        put("BE", "An Bheilg");
        put("NO", "An Iorua");
        put("BD", "An Bhanglaid\u00e9is");
        put("BB", "Barbad\u00f3s");
        put("ZW", "An tSiomb\u00e1ib");
        put("NL", "An \u00cdsilt\u00edr");
        put("BA", "An Bhoisnia-Heirseagaiv\u00e9in");
        put("NI", "Nicearagua");
        put("NG", "An Nig\u00e9ir");
        put("NF", "Oile\u00e1n Norfolk");
        put("AZ", "An Asarbaise\u00e1in");
        put("NE", "An N\u00edgir");
        put("NC", "An Nua-Chalad\u00f3in");
        put("AW", "Aruba");
        put("ZM", "An tSaimbia");
        put("NA", "An Namaib");
        put("AU", "An Astr\u00e1il");
        put("AT", "An Ostair");
        put("AS", "Sam\u00f3 Meirice\u00e1nach");
        put("AR", "An Airgint\u00edn");
        put("AQ", "An Antartaice");
        put("MZ", "M\u00f3saimb\u00edc");
        put("AO", "Ang\u00f3la");
        put("MY", "An Mhalaeisia");
        put("AN", "Antill\u00ed na h\u00cdsilt\u00edre");
        put("MX", "Meicsiceo");
        put("AM", "An Airm\u00e9in");
        put("MW", "An Mhal\u00e1iv");
        put("AL", "An Alb\u00e1in");
        put("MV", "Mhaildiv\u00ed");
        put("ZA", "An Afraic Theas");
        put("MU", "Oile\u00e1n Mhuir\u00eds");
        put("MT", "M\u00e1lta");
        put("AI", "Anguilla");
        put("MS", "Montsarat");
        put("MR", "An Mharat\u00e1in");
        put("AG", "Antigua agus Barbuda");
        put("MQ", "Martinique");
        put("AF", "An Afganast\u00e1in");
        put("MP", "Oile\u00e1in Mariana Thuaidh");
        put("AE", "Aontas na n\u00c9im\u00edr\u00edochta\u00ed Arabacha");
        put("MO", "Mac\u00e1\u00f3 (R.R.S. na S\u00edne)");
        put("AD", "And\u00f3ra");
        put("MN", "An Mhong\u00f3il");
        put("MM", "Maenmar");
        put("ML", "Mail\u00ed");
        put("MK", "An Mhacad\u00f3in");
        put("YU", "An I\u00fagslaiv");
        put("YT", "Mayotte");
        put("MH", "Oile\u00e1in Marshall");
        put("MG", "Madagascar");
        put("MD", "An Mhold\u00f3iv");
        put("MC", "Monac\u00f3");
        put("MA", "Marac\u00f3");
        put("YE", "\u00c9imin");
        put("LY", "An Libia");
        put("LV", "An Laitvia");
        put("LU", "Lucsamburg");
        put("LT", "An Liotu\u00e1in");
        put("LS", "Leos\u00f3ta");
        put("LR", "An Lib\u00e9ir");
        put("LK", "Sr\u00ed Lanca");
        put("LI", "Lichtinst\u00e9in");
        put("LC", "Saint Lucia");
        put("LB", "An Liob\u00e1in");
        put("LA", "Laos");
        put("KZ", "An Chasacst\u00e1in");
        put("KY", "Oile\u00e1in Cayman");
        put("KW", "Cu\u00e1it");
        put("KR", "An Ch\u00f3ir\u00e9 Theas");
        put("KP", "An Ch\u00f3ir\u00e9 Thuaidh");
        put("KN", "Saint Kitts agus Nevis");
        put("KM", "Oile\u00e1in Chom\u00f3ra");
        put("KI", "Cireabait\u00ed");
        put("WS", "Sam\u00f3");
        put("KH", "An Chamb\u00f3id");
        put("KG", "An Chirgeast\u00e1in");
        put("KE", "An Ch\u00e9inia");
        put("WF", "Oile\u00e1in Vail\u00eds agus Fut\u00fana");
        put("JP", "An tSeap\u00e1in");
        put("JO", "An Iord\u00e1in");
        put("JM", "Iam\u00e1ice");
        put("VU", "Vanuat\u00fa");
        put("VN", "V\u00edtneam");
        put("VI", "Oile\u00e1in na Maighdean S.A.M.");
        put("VG", "Oile\u00e1in Bhriotanacha na Maighdean");
        put("VE", "Veinis\u00e9ala");
        put("VC", "Saint Vincent agus na Grenadines");
        put("VA", "An Chathaoir Naofa (St\u00e1t Chathair na Vatac\u00e1ine)");
        put("IT", "An Iod\u00e1il");
        put("IS", "An \u00cdoslainn");
        put("IR", "An Iar\u00e1in");
        put("IQ", "An Iar\u00e1ic");
        put("UZ", "\u00daisb\u00e9iceast\u00e1in");
        put("IO", "Cr\u00edocha Briotanacha an Aig\u00e9in Indiagh");
        put("UY", "Urugua");
        put("IN", "An India");
        put("IL", "Iosrael");
        put("US", "St\u00e1it Aontaithe Mheirice\u00e1");
        put("IE", "\u00c9ire");
        put("ID", "An Indin\u00e9is");
        put("UM", "Mion-Oile\u00e1in Imeallacha S.A.M.");
        put("UG", "Uganda");
        put("UA", "An \u00dacr\u00e1in");
        put("HU", "An Ung\u00e1ir");
        put("HT", "H\u00e1it\u00ed");
        put("HR", "An Chr\u00f3it");
        put("TZ", "An Tans\u00e1in");
        put("HN", "Hond\u00faras");
        put("HM", "Oile\u00e1n Heard agus Oile\u00e1in McDonald");
        put("TW", "An T\u00e9av\u00e1in");
        put("TV", "Tuval\u00fa");
        put("HK", "Hong Cong (R.R.S. na S\u00edne)");
        put("TT", "Oile\u00e1in na Tr\u00edon\u00f3ide agus Tob\u00e1ga");
        put("TR", "An Tuirc");
        put("TO", "Tonga");
        put("TN", "An T\u00fain\u00e9is");
        put("TM", "An Tuircm\u00e9anast\u00e1in");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "localPatternChars", "RbMLkUnsSElFtTauKcBeyrAC" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "ampms", ampms },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
