/* LocaleInformation_sl.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML sl.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_sl extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "maj",
    "jun",
    "jul",
    "avg",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januar",
    "februar",
    "marec",
    "april",
    "maj",
    "junij",
    "julij",
    "avgust",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "ned",
    "pon",
    "tor",
    "sre",
    "\u010det",
    "pet",
    "sob",
  };

  private static final String[] weekdays = {
    null,
    "nedelja",
    "ponedeljek",
    "torek",
    "sreda",
    "\u010detrtek",
    "petek",
    "sobota",
  };

  private static final String[] eras = {
    "pr.n.\u0161.",
    "po Kr.",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Vzhodni Timor");
        put("TK", "Tokelau");
        put("TJ", "Tad\u017eikistan");
        put("TH", "Tajska");
        put("TG", "Togo");
        put("TF", "Francoski ju\u017eni teritorij");
        put("GY", "Gvajana");
        put("TD", "\u010cad");
        put("TC", "Oto\u010dji Turks in Caicos");
        put("GW", "Gvineja Bissau");
        put("GU", "Guam");
        put("GT", "Gvatemala");
        put("GS", "Ju\u017ena Georgija in Ju\u017eni Sandwich Islands");
        put("GR", "Gr\u010dija");
        put("GQ", "Ekvatorialna Gvineja");
        put("GP", "Guadeloupe");
        put("SZ", "Svazi");
        put("SY", "Sirija");
        put("GN", "Gvineja");
        put("GM", "Gambija");
        put("GL", "Grenlandija");
        put("SV", "Salvador");
        put("ST", "Sao Tome in Principe");
        put("GI", "Gibraltar");
        put("GH", "Gana");
        put("SR", "Surinam");
        put("GF", "Francoska Gvajana");
        put("SP", "Serbia");
        put("GE", "Gruzija");
        put("SO", "Somalija");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Velika Britanija");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slova\u0161ka");
        put("SJ", "Svalbard in Jan Mayen");
        put("SI", "Slovenija");
        put("SH", "Sveta Helena");
        put("SG", "Singapur");
        put("SE", "\u0160vedska");
        put("SD", "Sudan");
        put("SC", "Sej\u0161eli");
        put("SB", "Salomonovo oto\u010dje");
        put("SA", "Saudova Arabija");
        put("FR", "Francija");
        put("FO", "Fererski otoki");
        put("FM", "Mikronezija");
        put("RW", "Ruanda");
        put("FK", "Falklandski (Malvinski) otoki");
        put("RU", "Ruska federacija");
        put("FJ", "Fid\u017ei");
        put("FI", "Finska");
        put("RO", "Romunija");
        put("RE", "Reunion");
        put("ET", "Etiopija");
        put("ES", "\u0160panija");
        put("ER", "Eritreja");
        put("EH", "Zahodna Sahara");
        put("EG", "Egipt");
        put("EE", "Estonija");
        put("EC", "Ekvador");
        put("DZ", "Al\u017eirija");
        put("QA", "Katar");
        put("DO", "Dominikanska republika");
        put("PY", "Paragvaj");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "Danska");
        put("DJ", "D\u017eibuti");
        put("PT", "Portugalska");
        put("PS", "Palestinsko ozemlje");
        put("PR", "Portoriko");
        put("DE", "Nem\u010dija");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre in Miquelon");
        put("PL", "Poljska");
        put("PK", "Pakistan");
        put("PH", "Filipini");
        put("PG", "Papua Nova Gvineja");
        put("PF", "Francoska Polinezija");
        put("CZ", "\u010ce\u0161ka");
        put("PE", "Peru");
        put("CY", "Ciper");
        put("CX", "Bo\u017ei\u010dni otok");
        put("CV", "Kapverdski otoki");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kostarika");
        put("CO", "Kolumbija");
        put("CN", "Kitajska");
        put("CM", "Kamerun");
        put("CL", "\u010cile");
        put("CK", "Cookovi otoki");
        put("CI", "Slonoko\u0161\u010dena obala");
        put("CH", "\u0160vica");
        put("CG", "Kongo");
        put("CF", "Centralnoafri\u0161ka republika");
        put("CD", "Demokrati\u010dna republika Kongo");
        put("CC", "Kokosovi otoki");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Belorusija");
        put("BW", "Bocvana");
        put("BV", "Otok Bouvet");
        put("BT", "Butan");
        put("BS", "Bahami");
        put("BR", "Brazilija");
        put("NZ", "Nova Zelandija");
        put("BO", "Bolivija");
        put("BN", "Brunej");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrajn");
        put("NR", "Nauru");
        put("BG", "Bolgarija");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgija");
        put("NO", "Norve\u0161ka");
        put("BD", "Banglade\u0161");
        put("BB", "Barbados");
        put("ZW", "Zimbabve");
        put("NL", "Nizozemska");
        put("BA", "Bosna in Hercegovina");
        put("NI", "Nikaragva");
        put("NG", "Nigerija");
        put("NF", "Otok Norfolk");
        put("AZ", "Azerbajd\u017ean");
        put("NE", "Niger");
        put("NC", "Nova Kaledonija");
        put("AW", "Aruba");
        put("ZM", "Zambija");
        put("NA", "Namibija");
        put("AU", "Avstralija");
        put("AT", "Avstrija");
        put("AS", "Ameri\u0161ka Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktika");
        put("MZ", "Mozambik");
        put("AO", "Angola");
        put("MY", "Malezija");
        put("AN", "Nizozemski Antili");
        put("MX", "Mehika");
        put("AM", "Armenija");
        put("MW", "Malavi");
        put("AL", "Albanija");
        put("MV", "Maldivi");
        put("ZA", "Ju\u017ena Afrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Angvila");
        put("MS", "Montserrat");
        put("MR", "Mavretanija");
        put("AG", "Antigva in Barbuda");
        put("MQ", "Martinik");
        put("AF", "Afganistan");
        put("MP", "Severni Marianski otoki");
        put("AE", "Zdru\u017eeni arabski emirati");
        put("MO", "Makao S.A.R. Kitajske");
        put("AD", "Andora");
        put("MN", "Mongolija");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Republika Makedonija");
        put("YU", "Jugoslavija");
        put("YT", "Mayotte");
        put("MH", "Marshallovi otoki");
        put("MG", "Madagaskar");
        put("MD", "Republika Moldova");
        put("MC", "Monako");
        put("MA", "Maroko");
        put("YE", "Jemen");
        put("LY", "Libija");
        put("LV", "Latvija");
        put("LU", "Luxemburg");
        put("LT", "Litva");
        put("LS", "Lesoto");
        put("LR", "Liberija");
        put("LK", "\u0160rilanka");
        put("LI", "Liechtenstein");
        put("LC", "Saint Lucia");
        put("LB", "Libanon");
        put("LA", "Ljudska demokrati\u010dna republika Laos");
        put("KZ", "Kazahstan");
        put("KY", "Kajmanski otoki");
        put("KW", "Kuvajt");
        put("KR", "Ju\u017ena Koreja");
        put("KP", "Severna Koreja");
        put("KN", "Saint Kitts in Nevis");
        put("KM", "Komori");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambod\u017ea");
        put("KG", "Kirgizistan");
        put("KE", "Kenija");
        put("WF", "Wallis in Futuna");
        put("JP", "Japonska");
        put("JO", "Jordan");
        put("JM", "Jamajka");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Ameri\u0161ki Devi\u0161ki otoki");
        put("VG", "Britanski Devi\u0161ki otoki");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent in Grenadine");
        put("VA", "Vatikan");
        put("IT", "Italija");
        put("IS", "Islandija");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Uzbekistan");
        put("IO", "Britanska Indija");
        put("UY", "Urugvaj");
        put("IN", "Indija");
        put("IL", "Izrael");
        put("US", "Zdru\u017eene dr\u017eave Amerike");
        put("IE", "Irska");
        put("ID", "Indonezija");
        put("UM", "Ameri\u0161ki manj\u0161i oddaljeni otoki");
        put("UG", "Uganda");
        put("UA", "Ukrajina");
        put("HU", "Mad\u017earska");
        put("HT", "Haiti");
        put("HR", "Hrva\u0161ka");
        put("TZ", "Tanzanija");
        put("HN", "Honduras");
        put("HM", "Heardov otok in McDonaldovi otoki");
        put("TW", "Tajvan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R. Kitajske");
        put("TT", "Trinidad in Tobago");
        put("TR", "Tur\u010dija");
        put("TO", "Tonga");
        put("TN", "Tunizija");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "yy.M.d" },
    { "mediumDateFormat", "yyyy.M.d" },
    { "longDateFormat", "dd. MMMM yyyy" },
    { "fullDateFormat", "EEEE, dd. MMMM yyyy" },
    { "shortTimeFormat", "H:mm" },
    { "mediumTimeFormat", "H:mm:ss" },
    { "longTimeFormat", "H:mm:ss z" },
    { "fullTimeFormat", "H:mm:ss z" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
