/* LocaleInformation_is.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML is.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_is extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "ma\u00ed",
    "j\u00fan",
    "j\u00fal",
    "\u00e1g\u00fa",
    "sep",
    "okt",
    "n\u00f3v",
    "des",
    null,
  };

  private static final String[] months = {
    "jan\u00faar",
    "febr\u00faar",
    "mars",
    "apr\u00edl",
    "ma\u00ed",
    "j\u00fan\u00ed",
    "j\u00fal\u00ed",
    "\u00e1g\u00fast",
    "september",
    "okt\u00f3ber",
    "n\u00f3vember",
    "desember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "sun",
    "m\u00e1n",
    "\u00feri",
    "mi\u00f0",
    "fim",
    "f\u00f6s",
    "lau",
  };

  private static final String[] weekdays = {
    null,
    "sunnudagur",
    "m\u00e1nudagur",
    "\u00feri\u00f0judagur",
    "mi\u00f0vikudagur",
    "fimmtudagur",
    "f\u00f6studagur",
    "laugardagur",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Austur-T\u00edmor");
        put("TK", "T\u00f3kel\u00e1");
        put("TJ", "Tadsjikistan");
        put("TH", "Ta\u00edland");
        put("TG", "T\u00f3g\u00f3");
        put("TF", "Fr\u00f6nsku su\u00f0l\u00e6gu landsv\u00e6\u00f0in");
        put("GY", "Gv\u00e6jana");
        put("TD", "Tsjad");
        put("TC", "Turks- og Caicoseyjar");
        put("GW", "G\u00ednea-Biss\u00e1");
        put("GU", "Gvam");
        put("GT", "Gvatemala");
        put("GS", "Su\u00f0ur-Georg\u00eda og Su\u00f0ur-Sandv\u00edkureyjar");
        put("GR", "Grikkland");
        put("GQ", "Mi\u00f0baugs-G\u00ednea");
        put("GP", "Gvadel\u00fapeyjar");
        put("SZ", "Svas\u00edland");
        put("SY", "S\u00fdrland");
        put("GN", "G\u00ednea");
        put("GM", "Gamb\u00eda");
        put("GL", "Gr\u00e6nland");
        put("SV", "El Salvador");
        put("ST", "Sa\u00f3 T\u00f3me og Prins\u00edpe");
        put("GI", "G\u00edbraltar");
        put("GH", "Gana");
        put("SR", "S\u00far\u00ednam");
        put("GF", "Franska Gv\u00e6jana");
        put("SP", "Serb\u00eda");
        put("GE", "Georg\u00eda");
        put("SO", "S\u00f3mal\u00eda");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Mar\u00edn\u00f3");
        put("GB", "Bretland");
        put("SL", "S\u00ederra Le\u00f3ne");
        put("GA", "Gabon");
        put("SK", "Sl\u00f3vak\u00eda");
        put("SJ", "Svalbar\u00f0i og Jan Mayen");
        put("SI", "Sl\u00f3ven\u00eda");
        put("SH", "Sankti Helena");
        put("SG", "Singap\u00far");
        put("SE", "Sv\u00ed\u00fej\u00f3\u00f0");
        put("SD", "S\u00fadan");
        put("SC", "Seychelleseyjar");
        put("SB", "Sal\u00f3monseyjar");
        put("SA", "S\u00e1di-Arab\u00eda");
        put("FR", "Frakkland");
        put("FO", "F\u00e6reyjar");
        put("FM", "Mikr\u00f3nes\u00eda");
        put("RW", "R\u00faanda");
        put("FK", "Falklandseyjar");
        put("RU", "R\u00fassland");
        put("FJ", "F\u00eddjieyjar");
        put("FI", "Finnland");
        put("RO", "R\u00famen\u00eda");
        put("RE", "R\u00e9union");
        put("ET", "E\u00fe\u00ed\u00f3p\u00eda");
        put("ES", "Sp\u00e1nn");
        put("ER", "Er\u00edtrea");
        put("EH", "Vestur-Sahara");
        put("EG", "Egyptaland");
        put("EE", "Eistland");
        put("EC", "Ekvador");
        put("DZ", "Als\u00edr");
        put("QA", "Katar");
        put("DO", "D\u00f3min\u00edska l\u00fd\u00f0veldi\u00f0");
        put("PY", "Paragv\u00e6");
        put("DM", "D\u00f3min\u00edka");
        put("PW", "Pal\u00e1");
        put("DK", "Danm\u00f6rk");
        put("DJ", "Dj\u00edb\u00fat\u00ed");
        put("PT", "Port\u00fagal");
        put("PS", "Palest\u00edna");
        put("PR", "P\u00faert\u00f3 R\u00edk\u00f3");
        put("DE", "\u00de\u00fdskaland");
        put("PN", "Pitcairn");
        put("PM", "Sankti Pierre og Miquelon");
        put("PL", "P\u00f3lland");
        put("PK", "Pakistan");
        put("PH", "Filippseyjar");
        put("PG", "Pap\u00faa N\u00fdja-G\u00ednea");
        put("PF", "Franska P\u00f3l\u00fdnes\u00eda");
        put("CZ", "T\u00e9kkland");
        put("PE", "Per\u00fa");
        put("CY", "K\u00fdpur");
        put("CX", "J\u00f3laey");
        put("CV", "Gr\u00e6nh\u00f6f\u00f0aeyjar");
        put("CU", "K\u00faba");
        put("CR", "Kostar\u00edka");
        put("CO", "K\u00f3lumb\u00eda");
        put("CN", "K\u00edna");
        put("CM", "Kamer\u00fan");
        put("CK", "Cookseyjar");
        put("CI", "F\u00edlabeinsstr\u00f6ndin");
        put("CH", "Sviss");
        put("CG", "Vestur-Kong\u00f3");
        put("CF", "Mi\u00f0-Afr\u00edkul\u00fd\u00f0veldi\u00f0");
        put("CD", "Austur-Kong\u00f3");
        put("CC", "K\u00f3koseyjar");
        put("OM", "\u00d3man");
        put("CA", "Kanada");
        put("BZ", "Bel\u00eds");
        put("BY", "Hv\u00edta-R\u00fassland");
        put("BW", "Botsvana");
        put("BV", "Bouveteyja");
        put("BT", "B\u00fatan");
        put("BS", "Bahamaeyjar");
        put("BR", "Brasil\u00eda");
        put("NZ", "N\u00fdja-Sj\u00e1land");
        put("BO", "B\u00f3liv\u00eda");
        put("BN", "Br\u00fanei");
        put("BM", "Berm\u00fadaeyjar");
        put("NU", "Niue");
        put("BJ", "Ben\u00edn");
        put("BI", "B\u00far\u00fand\u00ed");
        put("BH", "Barein");
        put("NR", "N\u00e1r\u00fa");
        put("BG", "B\u00falgar\u00eda");
        put("BF", "B\u00fark\u00edna Fas\u00f3");
        put("NP", "Nepal");
        put("BE", "Belg\u00eda");
        put("NO", "Noregur");
        put("BD", "Bangladess");
        put("BB", "Barbados");
        put("NL", "Ni\u00f0url\u00f6nd");
        put("BA", "Bosn\u00eda og Herseg\u00f3v\u00edna");
        put("NI", "N\u00edkaragva");
        put("NG", "N\u00edger\u00eda");
        put("NF", "Norfolkeyja");
        put("AZ", "Aserba\u00eddsjan");
        put("NE", "N\u00edger");
        put("NC", "N\u00fdja-Kaled\u00f3n\u00eda");
        put("AW", "Ar\u00faba");
        put("ZM", "Samb\u00eda");
        put("NA", "Namib\u00eda");
        put("AU", "\u00c1stral\u00eda");
        put("AT", "Austurr\u00edki");
        put("AS", "Bandar\u00edska Sam\u00f3a");
        put("AR", "Argent\u00edna");
        put("AQ", "Su\u00f0urskautslandi\u00f0");
        put("MZ", "M\u00f3samb\u00edk");
        put("AO", "Ang\u00f3la");
        put("MY", "Malas\u00eda");
        put("AN", "Hollensku Antillur");
        put("MX", "Mex\u00edk\u00f3");
        put("AM", "Armen\u00eda");
        put("MW", "Malav\u00ed");
        put("AL", "Alban\u00eda");
        put("MV", "Mald\u00edveyjar");
        put("ZA", "Su\u00f0ur-Afr\u00edka");
        put("MU", "M\u00e1rit\u00edus");
        put("MT", "Malta");
        put("AI", "Angvilla");
        put("MS", "Montserrat");
        put("MR", "M\u00e1ritan\u00eda");
        put("AG", "Ant\u00edgva og Barb\u00fada");
        put("MQ", "Martin\u00edk");
        put("AF", "Afganistan");
        put("MP", "Nor\u00f0ur-Mar\u00edanaeyjar");
        put("AE", "Sameinu\u00f0u arab\u00edsku furstad\u00e6min");
        put("MO", "Maka\u00f3");
        put("AD", "Andorra");
        put("MN", "Mong\u00f3l\u00eda");
        put("MM", "Mjanmar");
        put("ML", "Mal\u00ed");
        put("MK", "Maked\u00f3n\u00eda");
        put("YU", "J\u00fag\u00f3slav\u00eda");
        put("YT", "Mayotte");
        put("MH", "Marshalleyjar");
        put("MG", "Madagaskar");
        put("MD", "Mold\u00f3va");
        put("MC", "M\u00f3nak\u00f3");
        put("MA", "Marokk\u00f3");
        put("YE", "Jemen");
        put("LY", "L\u00edb\u00eda");
        put("LV", "Lettland");
        put("LU", "L\u00faxemborg");
        put("LT", "Lith\u00e1en");
        put("LS", "Les\u00f3t\u00f3");
        put("LR", "L\u00edber\u00eda");
        put("LK", "Sr\u00ed Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Sankti L\u00fas\u00eda");
        put("LB", "L\u00edbanon");
        put("LA", "Laos");
        put("KZ", "Kasakstan");
        put("KY", "Caymaneyjar");
        put("KW", "K\u00faveit");
        put("KR", "Su\u00f0ur-K\u00f3rea");
        put("KP", "Nor\u00f0ur-K\u00f3rea");
        put("KN", "Sankti Krist\u00f3fer og Nevis");
        put("KM", "K\u00f3moreyjar");
        put("KI", "K\u00edribat\u00ed");
        put("WS", "Sam\u00f3a");
        put("KH", "Kamb\u00f3d\u00eda");
        put("KG", "Kirgisistan");
        put("KE", "Ken\u00eda");
        put("WF", "Wallis- og F\u00fat\u00fanaeyjar");
        put("JP", "Japan");
        put("JO", "J\u00f3rdan\u00eda");
        put("JM", "Jama\u00edka");
        put("VU", "Van\u00faat\u00fa");
        put("VN", "V\u00edetnam");
        put("VI", "J\u00f3mfr\u00faaeyjar (bandar\u00edsku)");
        put("VG", "J\u00f3mfr\u00faaeyjar (bresku)");
        put("VE", "Venes\u00faela");
        put("VC", "Sankti Vinsent og Grenad\u00edneyjar");
        put("VA", "P\u00e1fagar\u00f0ur");
        put("IT", "\u00cdtal\u00eda");
        put("IS", "\u00cdsland");
        put("IR", "\u00cdran");
        put("IQ", "\u00cdrak");
        put("UZ", "\u00dasbekistan");
        put("IO", "Bresku Indlandshafseyjar");
        put("UY", "\u00dar\u00fagv\u00e6");
        put("IN", "Indland");
        put("IL", "\u00cdsrael");
        put("US", "Bandar\u00edkin");
        put("IE", "\u00cdrland");
        put("ID", "Ind\u00f3nes\u00eda");
        put("UM", "Sm\u00e1eyjar Bandar\u00edkjanna");
        put("UG", "\u00daganda");
        put("UA", "\u00dakra\u00edna");
        put("HU", "Ungverjaland");
        put("HT", "Ha\u00edt\u00ed");
        put("HR", "Kr\u00f3at\u00eda");
        put("TZ", "Tansan\u00eda");
        put("HN", "Hond\u00faras");
        put("HM", "Heard og McDonaldseyjar");
        put("TW", "Ta\u00edvan");
        put("TV", "T\u00faval\u00fa");
        put("HK", "Hong Kong");
        put("TT", "Tr\u00ednidad og T\u00f3bag\u00f3");
        put("TR", "Tyrkland");
        put("TO", "Tonga");
        put("TN", "T\u00fanis");
        put("TM", "T\u00farkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "shortDateFormat", "d.M.yyyy" },
    { "mediumDateFormat", "d.M.yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE, d. MMMM yyyy" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
