/* LocaleInformation_ro.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_ro extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "ROL";

  private static final String currenciesDisplayNameValues = "ROL";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "ROL";

  private static final String currenciesSymbolValues = "lei";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "Ian",
    "Feb",
    "Mar",
    "Apr",
    "Mai",
    "Iun",
    "Iul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
    null,
  };

  private static final String[] months = {
    "ianuarie",
    "februarie",
    "martie",
    "aprilie",
    "mai",
    "iunie",
    "iulie",
    "august",
    "septembrie",
    "octombrie",
    "noiembrie",
    "decembrie",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "D",
    "L",
    "Ma",
    "Mi",
    "J",
    "V",
    "S",
  };

  private static final String[] weekdays = {
    null,
    "duminic\u0103",
    "luni",
    "mar\u0163i",
    "miercuri",
    "joi",
    "vineri",
    "s\u00eemb\u0103t\u0103",
  };

  private static final String[] eras = {
    "d.C.",
    "\u00ee.d.C.",
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6SP\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "Timorul de Est\u00A6Tokelau\u00A6Tadjikistan\u00A6Tailanda\u00A6Togo\u00A6Teritoriile Franceze de Sud\u00A6Guyana\u00A6Ciad\u00A6Insulele Turks \u015fi Caicos\u00A6Guineea-Bissau\u00A6Guam\u00A6Guatemala\u00A6Insulele South Georgia \u015fi South Sandwich\u00A6Grecia\u00A6Guineea Ecuatorial\u0103\u00A6Guadeloupe\u00A6Swaziland\u00A6Siria\u00A6Guineea\u00A6Gambia\u00A6Groenlanda\u00A6El Salvador\u00A6Sao Tome \u015fi Principe\u00A6Gibraltar\u00A6Ghana\u00A6Surinam\u00A6Guyana Francez\u0103\u00A6Serbia\u00A6Georgia\u00A6Somalia\u00A6Grenada\u00A6Senegal\u00A6San Marino\u00A6Marea Britanie\u00A6Sierra Leone\u00A6Gabon\u00A6Slovacia\u00A6Svalbard \u015fi Jan Mayen\u00A6Slovenia\u00A6Saint Helena\u00A6Singapore\u00A6Suedia\u00A6Sudan\u00A6Seychelles\u00A6Insulele Solomon\u00A6Arabia Saudit\u0103\u00A6Fran\u0163a\u00A6Insulele Feroe\u00A6Micronezia, Statele Federate\u00A6Rwanda\u00A6Insulele Falkland\u00A6Rusia\u00A6Fiji\u00A6Finlanda\u00A6Rom\u00e2nia\u00A6Reunion\u00A6Etiopia\u00A6Spania\u00A6Eritrea\u00A6Sahara de Vest\u00A6Egipt\u00A6Estonia\u00A6Ecuador\u00A6Algeria\u00A6Qatar\u00A6Republica Dominican\u0103\u00A6Paraguay\u00A6Dominica\u00A6Palau\u00A6Danemarca\u00A6Djibouti\u00A6Portugalia\u00A6Teritoriul Palestinian\u00A6Porto Rico\u00A6Germania\u00A6Pitcairn\u00A6Saint Pierre \u015fi Miquelon\u00A6Polonia\u00A6Pakistan\u00A6Filipine\u00A6Papua Noua Guinee\u00A6Polinezia Francez\u0103\u00A6Republica Ceh\u0103\u00A6Peru\u00A6Cipru\u00A6Insula Christmas\u00A6Capul Verde\u00A6Panama\u00A6Cuba\u00A6Costa Rica\u00A6Columbia\u00A6China\u00A6Camerun\u00A6Chile\u00A6Insulele Cook\u00A6Coasta de Filde\u015f\u00A6Eleve\u0163ia\u00A6Congo\u00A6Republica Central African\u0103\u00A6Congo, Republica Democratic\u0103\u00A6Insulele Cocos (Keeling)\u00A6Oman\u00A6Canada\u00A6Belize\u00A6Bielorusia\u00A6Botswana\u00A6Insula Bouvet\u00A6Bhutan\u00A6Bahamas\u00A6Brazilia\u00A6Noua Zeeland\u0103\u00A6Bolivia\u00A6Brunei\u00A6Bermuda\u00A6Niue\u00A6Benin\u00A6Burundi\u00A6Bahrain\u00A6Nauru\u00A6Bulgaria\u00A6Burkina Faso\u00A6Nepal\u00A6Belgia\u00A6Norvegia\u00A6Bangladesh\u00A6Barbados\u00A6Zimbabwe\u00A6Olanda\u00A6Bosnia \u015fi Herzegovina\u00A6Nicaragua\u00A6Nigeria\u00A6Insulele Norfolk\u00A6Azerbaidjan\u00A6Niger\u00A6Noua Caledonie\u00A6Aruba\u00A6Zambia\u00A6Namibia\u00A6Australia\u00A6Austria\u00A6Samoa American\u0103\u00A6Argentina\u00A6Antarctica\u00A6Mozambic\u00A6Angola\u00A6Malaezia\u00A6Antilele Olandeze\u00A6Mexic\u00A6Armenia\u00A6Malawi\u00A6Albania\u00A6Maldive\u00A6Africa de Sud\u00A6Mauritius\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Mauritania\u00A6Antigua \u015fi Barbuda\u00A6Martinica\u00A6Afganistan\u00A6Insulele Northern Mariana\u00A6Emiratele Arabe Unite\u00A6R.A.S. Macao a Chinei\u00A6Andora\u00A6Mongolia\u00A6Myanmar\u00A6Mali\u00A6Macedonia\u00A6Iugoslavia\u00A6Mayotte\u00A6Insulele Marshall\u00A6Madagascar\u00A6Moldova, Republica\u00A6Monaco\u00A6Maroc\u00A6Yemen\u00A6Libia, Jamahiriya Arab\u0103\u00A6Letonia\u00A6Luxemburg\u00A6Lituania\u00A6Lesotho\u00A6Liberia\u00A6Sri Lanka\u00A6Liechtenstein\u00A6Saint Lucia\u00A6Liban\u00A6Lao, Republica Democratic\u0103 Popular\u0103\u00A6Kazahstan\u00A6Insulele Cayman\u00A6Kuweit\u00A6Coreea de Sud\u00A6Coreea de Nord\u00A6Saint Kitts \u015fi Nevis\u00A6Comoros\u00A6Kiribati\u00A6Samoa\u00A6Cambodgia\u00A6Kirghizia\u00A6Kenya\u00A6Wallis \u015fi Futuna\u00A6Japonia\u00A6Iordania\u00A6Jamaica\u00A6Vanuatu\u00A6Vietnam\u00A6Insulele Virgine S.U.A.\u00A6Insulele Virgine Britanice\u00A6Venezuela\u00A6Saint Vincent \u015fi Grenadines\u00A6Sf\u00e2ntul Scaun (Statul Vatican)\u00A6Italia\u00A6Islanda\u00A6Iran\u00A6Iraq\u00A6Uzbekistan\u00A6Teritoriile Britanice din Oceanul Indian\u00A6Uruguay\u00A6India\u00A6Israel\u00A6Statele Unite\u00A6Irlanda\u00A6Indonezia\u00A6United States Minor Outlying Islands\u00A6Uganda\u00A6Ucraina\u00A6Ungaria\u00A6Haiti\u00A6Croa\u0163ia\u00A6Tanzania\u00A6Honduras\u00A6Insula Heard \u015fi Insulele McDonald\u00A6Taiwan\u00A6Tuvalu\u00A6R.A.S. Hong Kong a Chinei\u00A6Trinidad \u015fi Tobago\u00A6Turcia\u00A6Tonga\u00A6Tunisia\u00A6Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "ja\u00A6en\u00A6tr\u00A6ko\u00A6no\u00A6el\u00A6nl\u00A6bg\u00A6lv\u00A6he\u00A6cs\u00A6it\u00A6lt\u00A6fr\u00A6zh\u00A6ru\u00A6ro\u00A6fi\u00A6ar\u00A6sv\u00A6pt\u00A6pl\u00A6sl\u00A6sk\u00A6de\u00A6hu\u00A6et\u00A6es\u00A6hr\u00A6da";

  private static final String languagesValues = "Japonez\u0103\u00A6Englez\u0103\u00A6Turc\u0103\u00A6Coreean\u0103\u00A6Norvegian\u0103\u00A6Greac\u0103\u00A6Olandez\u0103\u00A6Bulgar\u0103\u00A6Leton\u0103\u00A6Ebraic\u0103\u00A6Ceh\u0103\u00A6Italian\u0103\u00A6Lituanian\u0103\u00A6Francez\u0103\u00A6Chinez\u0103\u00A6Rus\u0103\u00A6Rom\u00e2n\u0103\u00A6Finlandez\u0103\u00A6Arab\u0103\u00A6Suedez\u0103\u00A6Portughez\u0103\u00A6Polonez\u0103\u00A6Sloven\u0103\u00A6Slovac\u0103\u00A6German\u0103\u00A6Maghiar\u0103\u00A6Estonian\u0103\u00A6Spaniol\u0103\u00A6Croat\u0103\u00A6Danez\u0103";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "localPatternChars", "GanjkHmsSEDFwWxhKzAeugXZ" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd.MM.yyyy" },
    { "mediumDateFormat", "dd.MM.yyyy" },
    { "longDateFormat", "d MMMM yyyy" },
    { "fullDateFormat", "d MMMM yyyy" },
    { "territories", territories },
    { "languages", languages },
  };

  public Object[][] getContents() { return contents; }
}
