/* LocaleInformation_id.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML id.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_id extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "Mei",
    "Jun",
    "Jul",
    "Agu",
    "Sep",
    "Okt",
    "Nov",
    "Des",
    null,
  };

  private static final String[] months = {
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "Min",
    "Sen",
    "Sel",
    "Rab",
    "Kam",
    "Jum",
    "Sab",
  };

  private static final String[] weekdays = {
    null,
    "Minggu",
    "Senin",
    "Selasa",
    "Rabu",
    "Kamis",
    "Jumat",
    "Sabtu",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TK", "Tokelau");
        put("TJ", "Tajikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("GY", "Guyana");
        put("TD", "Chad");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "Georgia Selatan dan Kepulauan Sandwich Selatan");
        put("GR", "Yunani");
        put("GQ", "Guinea Khatulistiwa");
        put("GP", "Guadeloupe");
        put("SZ", "Swaziland");
        put("SY", "Syria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Greenland");
        put("SV", "El Salvador");
        put("ST", "Sao Tome dan Principe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Guyana Perancis");
        put("SP", "Serbia");
        put("GE", "Georgia");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Inggris Raya");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakia");
        put("SJ", "Svalbard dan Jan Mayen");
        put("SI", "Slovenia");
        put("SH", "Saint Helena");
        put("SG", "Singapura");
        put("SE", "Sweden");
        put("SD", "Sudan");
        put("SC", "Seychelles");
        put("SB", "Kepulauan Solomon");
        put("SA", "Arab Saudi");
        put("FR", "Perancis");
        put("FO", "Kepulauan Faroe");
        put("FM", "Mikronesia");
        put("RW", "Rwanda");
        put("FK", "Kepulauan Falkland");
        put("RU", "Rusia");
        put("FJ", "Fiji");
        put("FI", "Finlandia");
        put("RO", "Romania");
        put("RE", "R\u00e9union");
        put("ET", "Ethiopia");
        put("ES", "Spanyol");
        put("ER", "Eritrea");
        put("EH", "Sahara Barat");
        put("EG", "Mesir");
        put("EE", "Estonia");
        put("EC", "Ekuador");
        put("DZ", "Algeria");
        put("QA", "Qatar");
        put("DO", "Republik Dominika");
        put("PY", "Paraguay");
        put("DM", "Dominika");
        put("PW", "Palau");
        put("DK", "Denmark");
        put("DJ", "Jibouti");
        put("PT", "Portugis");
        put("PS", "Otoritas Palestina");
        put("PR", "Puerto Riko");
        put("DE", "Jerman");
        put("PN", "Pitcairn");
        put("PM", "Saint Pierre dan Miquelon");
        put("PL", "Polandia");
        put("PK", "Pakistan");
        put("PH", "Filipina");
        put("PG", "Papua Nugini");
        put("PF", "Polynesia Perancis");
        put("CZ", "Republik Ceko");
        put("PE", "Peru");
        put("CY", "Siprus");
        put("CX", "Pulau Christmas");
        put("CV", "Tanjung Verde");
        put("PA", "Panama");
        put("CU", "Kuba");
        put("CR", "Kosta Rika");
        put("CO", "Kolombia");
        put("CN", "Cina");
        put("CM", "Kamerun");
        put("CL", "Chili");
        put("CK", "Kepulauan Cook");
        put("CI", "Pantai Gading");
        put("CH", "Swiss");
        put("CG", "Kongo");
        put("CF", "Republik Afrika Tengah");
        put("CD", "Republik Demokratik Kongo");
        put("CC", "Kepulauan Cocos");
        put("OM", "Oman");
        put("CA", "Kanada");
        put("BZ", "Belize");
        put("BY", "Belarusia");
        put("BW", "Botswana");
        put("BV", "Kepulauan Bouvet");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brazil");
        put("NZ", "Selandia Baru");
        put("BO", "Bolivia");
        put("BN", "Brunei");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgia");
        put("NO", "Norwegia");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Netherlands");
        put("BA", "Bosnia dan Herzegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Kepulauan Norfolk");
        put("AZ", "Azerbaijan");
        put("NE", "Niger");
        put("NC", "Kaledonia Baru");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australia");
        put("AT", "Austria");
        put("AS", "Samoa Amerika");
        put("AR", "Argentina");
        put("AQ", "Antarktika");
        put("MZ", "Mozambique");
        put("AO", "Angola");
        put("MY", "Malaysia");
        put("AN", "Antilles Belanda");
        put("MX", "Mexico");
        put("AM", "Armenia");
        put("MW", "Malawi");
        put("AL", "Albania");
        put("MV", "Maldives");
        put("ZA", "Afrika Selatan");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("AG", "Antigua dan Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "Kepualuan Mariana Utara");
        put("AE", "Uni Emirat Arab");
        put("MO", "Makao S.A.R. Cina");
        put("AD", "Andora");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Macedonia");
        put("YU", "Yugoslavia");
        put("YT", "Mayotte");
        put("MH", "Kepulauan Marshall");
        put("MG", "Madagaskar");
        put("MD", "Moldova");
        put("MC", "Monaco");
        put("MA", "Maroko");
        put("YE", "Yaman");
        put("LY", "Libya");
        put("LV", "Latvia");
        put("LU", "Luxembourg");
        put("LT", "Lithuania");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Santa Lusia");
        put("LB", "Lebanon");
        put("LA", "Laos");
        put("KZ", "Kazakhstan");
        put("KY", "Kepulauan Kayman");
        put("KW", "Kuwait");
        put("KR", "Korea Selatan");
        put("KP", "Korea Utara");
        put("KN", "Saint Kitts dan Nevis");
        put("KM", "Komoros");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kamboja");
        put("KG", "Kyrgyzstan");
        put("KE", "Kenya");
        put("WF", "Wallis dan Futuna");
        put("JP", "Jepang");
        put("JO", "Yordania");
        put("JM", "Jamaika");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Kepulauan U.S. Virgin");
        put("VG", "Kepulauan British Virgin");
        put("VE", "Venezuela");
        put("VC", "Saint Vincent dan Grenadines");
        put("VA", "Vatikan");
        put("IT", "Itali");
        put("IS", "Islandia");
        put("IR", "Iran");
        put("IQ", "Iraq");
        put("UZ", "Uzbekistan");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Israel");
        put("US", "Amerika Serikat");
        put("IE", "Irlandia");
        put("ID", "Indonesia");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Hungaria");
        put("HT", "Haiti");
        put("HR", "Kroasia");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Pulau Heard dan Kepulauan McDonald");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R., Cina");
        put("TT", "Trinidad dan Tobago");
        put("TR", "Turkey");
        put("TO", "Tonga");
        put("TN", "Tunisia");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "." },
    { "currencyFormat", "\u00a4#,##0.00;-\u00a4#,##0.00" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
