/* LocaleInformation_fr.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML fr.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_fr extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "janv.",
    "f\u00e9vr.",
    "mars",
    "avr.",
    "mai",
    "juin",
    "juil.",
    "ao\u00fbt",
    "sept.",
    "oct.",
    "nov.",
    "d\u00e9c.",
    null,
  };

  private static final String[] months = {
    "janvier",
    "f\u00e9vrier",
    "mars",
    "avril",
    "mai",
    "juin",
    "juillet",
    "ao\u00fbt",
    "septembre",
    "octobre",
    "novembre",
    "d\u00e9cembre",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "dim.",
    "lun.",
    "mar.",
    "mer.",
    "jeu.",
    "ven.",
    "sam.",
  };

  private static final String[] weekdays = {
    null,
    "dimanche",
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
  };

  private static final String[] eras = {
    "av. J.-C.",
    "ap. J.-C.",
  };

  private static final String[][] zoneStrings =
  {
    { "America/Los_Angeles", "Heure normale du Pacifique (\u00c9UA)", "HNP (\u00c9UA)", "Heure avanc\u00e9e du Pacifique (\u00c9UA)", "HAP (\u00c9UA)" },
    { "Pacific/Honolulu", "Heure normale d\u2019Hawa\u00ef", "HST", "Heure avanc\u00e9e d\u2019Hawa\u00ef", "HDT" },
    { "Etc/GMT", "Temps Moyen de Greenwich", "GMT", "Temps Moyen de Greenwich", "GMT" },
    { "America/Phoenix", "Heure normale des Rocheuses (\u00c9UA)", "HNR (\u00c9UA)", "Heure avanc\u00e9e des Rocheuses (\u00c9UA)", "HAR (\u00c9UA)" },
    { "America/Denver", "Heure normale des Rocheuses (\u00c9UA)", "HNR (\u00c9UA)", "Heure avanc\u00e9e des Rocheuses (\u00c9UA)", "HAR (\u00c9UA)" },
    { "Asia/Jerusalem", "Heure normale d\u2019Isra\u00ebl", "HNI", "Heure avanc\u00e9e d\u2019Isra\u00ebl", "HAI" },
    { "America/Edmonton", "Heure normale des Rocheuses", "HNR", "Heure avanc\u00e9e des Rocheuses", "HAR" },
    { "America/Anchorage", "Heure normale de l\u2019Alaska", "HNAK", "Heure avanc\u00e9e de l\u2019Alaska", "HAAK" },
    { "Europe/Paris", "Heure normale de l\u2019Europe centrale", "HNEC", "Heure avanc\u00e9e de l\u2019Europe centrale", "HAEC" },
    { "America/Indianapolis", "Heure normale de l\u2019Est (\u00c9UA)", "HNE (\u00c9UA)", "Heure avanc\u00e9e de l\u2019Est (\u00c9UA)", "HAE (\u00c9UA)" },
    { "Europe/Bucharest", "Heure normale de l\u2019Europe de l\u2019Est", "HEE", "Heure avanc\u00e9e de l\u2019Europe de l\u2019Est", "HAEE" },
    { "Asia/Tokyo", "Heure normale du Japon", "HNJ", "Heure avanc\u00e9e du Japon", "HAJ" },
    { "America/Winnipeg", "Heure normale du Centre", "HNC", "Heure avanc\u00e9e du Centre", "HAC" },
    { "Asia/Shanghai", "Heure normale de Chine", "HNC", "Heure avanc\u00e9e de Chine", "HAC" },
    { "America/Vancouver", "Heure normale du Pacifique", "HNP", "Heure avanc\u00e9e du Pacifique", "HAP" },
    { "America/New_York", "Heure normale de l\u2019Est (\u00c9UA)", "HNE (\u00c9UA)", "Heure avanc\u00e9e de l\u2019Est (\u00c9UA)", "HAE (\u00c9UA)" },
    { "America/Montreal", "Heure normale de l\u2019Est", "HNE", "Heure avanc\u00e9e de l\u2019Est", "HAE" },
    { "America/Halifax", "Heure normale de l\u2019Atlantique", "HNA", "Heure avanc\u00e9e de l\u2019Atlantique", "HAA" },
    { "America/St_Johns", "Heure normale de Terre-Neuve", "HNT", "Heure avanc\u00e9e de Terre-Neuve", "HAT" },
    { "America/Chicago", "Heure normale du Centre (\u00c9UA)", "HNC (\u00c9UA)", "Heure avanc\u00e9e du Centre (\u00c9UA)", "HAC (\u00c9UA)" },
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "Timor-Leste");
        put("TK", "Tokelau");
        put("TJ", "Tadjikistan");
        put("TH", "Tha\u00eflande");
        put("TG", "Togo");
        put("TF", "Terres australes fran\u00e7aises");
        put("GY", "Guyana");
        put("TD", "Tchad");
        put("TC", "\u00celes Turks et Ca\u00efques");
        put("GW", "Guin\u00e9e-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "G\u00e9orgie du Sud, \u00celes Sandwich du Sud");
        put("GR", "Gr\u00e8ce");
        put("GQ", "Guin\u00e9e \u00e9quatoriale");
        put("GP", "Guadeloupe");
        put("SZ", "Swaziland");
        put("SY", "Syrie");
        put("GN", "Guin\u00e9e");
        put("GM", "Gambie");
        put("GL", "Groenland");
        put("SV", "El Salvador");
        put("ST", "Sao Tom\u00e9-et-Principe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Suriname");
        put("GF", "Guyane fran\u00e7aise");
        put("SP", "Serbie");
        put("GE", "G\u00e9orgie");
        put("SO", "Somalie");
        put("GD", "Grenade");
        put("SN", "S\u00e9n\u00e9gal");
        put("SM", "Saint-Marin");
        put("GB", "Royaume-Uni");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovaquie");
        put("SJ", "Svalbard et \u00cele Jan Mayen");
        put("SI", "Slov\u00e9nie");
        put("SH", "Sainte-H\u00e9l\u00e8ne");
        put("SG", "Singapour");
        put("SE", "Su\u00e8de");
        put("SD", "Soudan");
        put("SC", "Seychelles");
        put("SB", "\u00celes Salomon");
        put("SA", "Arabie saoudite");
        put("FR", "France");
        put("FO", "\u00celes F\u00e9ro\u00e9");
        put("FM", "Micron\u00e9sie");
        put("RW", "Rwanda");
        put("FK", "\u00celes Falkland (Malvinas)");
        put("RU", "Russie");
        put("FJ", "Fidji");
        put("FI", "Finlande");
        put("RO", "Roumanie");
        put("RE", "R\u00e9union");
        put("ET", "\u00c9thiopie");
        put("ES", "Espagne");
        put("ER", "\u00c9rythr\u00e9e");
        put("EH", "Sahara occidental");
        put("EG", "\u00c9gypte");
        put("EE", "Estonie");
        put("EC", "\u00c9quateur");
        put("DZ", "Alg\u00e9rie");
        put("QA", "Qatar");
        put("DO", "R\u00e9publique dominicaine");
        put("PY", "Paraguay");
        put("DM", "Dominique");
        put("PW", "Palaos");
        put("DK", "Danemark");
        put("DJ", "Djibouti");
        put("PT", "Portugal");
        put("PS", "Territoire palestinien");
        put("PR", "Porto Rico");
        put("DE", "Allemagne");
        put("PN", "Pitcairn");
        put("PM", "Saint-Pierre-et-Miquelon");
        put("PL", "Pologne");
        put("PK", "Pakistan");
        put("PH", "Philippines");
        put("PG", "Papouasie-Nouvelle-Guin\u00e9e");
        put("PF", "Polyn\u00e9sie fran\u00e7aise");
        put("CZ", "R\u00e9publique tch\u00e8que");
        put("PE", "P\u00e9rou");
        put("CY", "Chypre");
        put("CX", "\u00cele Christmas");
        put("CV", "Cap Vert");
        put("PA", "Panama");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombie");
        put("CN", "Chine");
        put("CM", "Cameroun");
        put("CL", "Chili");
        put("CK", "\u00celes Cook");
        put("CI", "C\u00f4te d\u2019Ivoire");
        put("CH", "Suisse");
        put("CG", "Congo");
        put("CF", "R\u00e9publique centrafricaine");
        put("CD", "R\u00e9publique d\u00e9mocratique du Congo");
        put("CC", "\u00celes Cocos");
        put("OM", "Oman");
        put("CA", "Canada");
        put("BZ", "Belize");
        put("BY", "B\u00e9larus");
        put("BW", "Botswana");
        put("BV", "\u00cele Bouvet");
        put("BT", "Bhoutan");
        put("BS", "Bahamas");
        put("BR", "Br\u00e9sil");
        put("NZ", "Nouvelle-Z\u00e9lande");
        put("BO", "Bolivie");
        put("BN", "Brunei");
        put("BM", "Bermudes");
        put("NU", "Niu\u00e9");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahre\u00efn");
        put("NR", "Nauru");
        put("BG", "Bulgarie");
        put("BF", "Burkina Faso");
        put("NP", "N\u00e9pal");
        put("BE", "Belgique");
        put("NO", "Norv\u00e8ge");
        put("BD", "Bangladesh");
        put("BB", "Barbade");
        put("ZW", "Zimbabwe");
        put("NL", "Pays-Bas");
        put("BA", "Bosnie-Herz\u00e9govine");
        put("NI", "Nicaragua");
        put("NG", "Nig\u00e9ria");
        put("NF", "\u00cele Norfolk");
        put("AZ", "Azerba\u00efdjan");
        put("NE", "Niger");
        put("NC", "Nouvelle-Cal\u00e9donie");
        put("AW", "Aruba");
        put("ZM", "Zambie");
        put("NA", "Namibie");
        put("AU", "Australie");
        put("AT", "Autriche");
        put("AS", "Samoa am\u00e9ricaines");
        put("AR", "Argentine");
        put("AQ", "Antarctique");
        put("MZ", "Mozambique");
        put("AO", "Angola");
        put("MY", "Malaisie");
        put("AN", "Antilles n\u00e9erlandaises");
        put("MX", "Mexique");
        put("AM", "Arm\u00e9nie");
        put("MW", "Malawi");
        put("AL", "Albanie");
        put("MV", "Maldives");
        put("ZA", "Afrique du Sud");
        put("MU", "Maurice");
        put("MT", "Malte");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritanie");
        put("AG", "Antigua-et-Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "\u00celes Mariannes du Nord");
        put("AE", "\u00c9mirats arabes unis");
        put("MO", "Macao R.A.S. de Chine");
        put("AD", "Andorre");
        put("MN", "Mongolie");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Mac\u00e9doine");
        put("YU", "Yougoslavie");
        put("YT", "Mayotte");
        put("MH", "\u00celes Marshall");
        put("MG", "Madagascar");
        put("MD", "Moldova");
        put("MC", "Monaco");
        put("MA", "Maroc");
        put("YE", "Y\u00e9men");
        put("LY", "Libye");
        put("LV", "Lettonie");
        put("LU", "Luxembourg");
        put("LT", "Lithuanie");
        put("LS", "Lesotho");
        put("LR", "Lib\u00e9ria");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "Sainte-Lucie");
        put("LB", "Liban");
        put("LA", "Laos");
        put("KZ", "Kazakhstan");
        put("KY", "\u00celes Ca\u00efmanes");
        put("KW", "Kowe\u00eft");
        put("KR", "Cor\u00e9e du Sud");
        put("KP", "Cor\u00e9e du Nord");
        put("KN", "Saint Kitts et Nevis");
        put("KM", "Comores");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Cambodge");
        put("KG", "Kirghizistan");
        put("KE", "Kenya");
        put("WF", "Wallis et Futuna");
        put("JP", "Japon");
        put("JO", "Jordanie");
        put("JM", "Jama\u00efque");
        put("VU", "Vanuatu");
        put("VN", "Viet Nam");
        put("VI", "\u00celes Vierges des \u00c9tats-Unis");
        put("VG", "\u00celes Vierges Britanniques");
        put("VE", "V\u00e9n\u00e9zuela");
        put("VC", "Saint-Vincent-et-les Grenadines");
        put("VA", "Saint-Si\u00e8ge (Etat de la Cit\u00e9 du Vatican)");
        put("IT", "Italie");
        put("IS", "Islande");
        put("IR", "Iran");
        put("IQ", "Iraq");
        put("UZ", "Ouzb\u00e9kistan");
        put("IO", "Territoire britannique de l\u2019oc\u00e9an indien");
        put("UY", "Uruguay");
        put("IN", "Inde");
        put("IL", "Isra\u00ebl");
        put("US", "\u00c9tats-Unis");
        put("IE", "Irlande");
        put("ID", "Indon\u00e9sie");
        put("UM", "\u00celes Mineures \u00c9loign\u00e9es des \u00c9tats-Unis");
        put("UG", "Ouganda");
        put("UA", "Ukraine");
        put("HU", "Hongrie");
        put("HT", "Ha\u00efti");
        put("HR", "Croatie");
        put("TZ", "Tanzanie");
        put("HN", "Honduras");
        put("HM", "\u00celes Heard et MacDonald");
        put("TW", "Ta\u00efwan");
        put("TV", "Tuvalu");
        put("HK", "Hong-Kong R.A.S. de Chine");
        put("TT", "Trinit\u00e9-et-Tobago");
        put("TR", "Turquie");
        put("TO", "Tonga");
        put("TN", "Tunisie");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "currencyFormat", "#,##0.00 \u00a4;-#,##0.00 \u00a4" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd/MM/yy" },
    { "mediumDateFormat", "d MMM yy" },
    { "longDateFormat", "d MMMM yyyy" },
    { "fullDateFormat", "EEEE d MMMM yyyy" },
    { "fullTimeFormat", "HH' h 'mm z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
