/* LocaleInformation_sv.java --
   Copyright (C) 2005  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML

package gnu.java.locale;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.StringTokenizer;
import java.util.ListResourceBundle;

public class LocaleInformation_sv extends ListResourceBundle
{
  private static final String currenciesDisplayNameKeys = "JOD\u00A6BOV\u00A6FOK\u00A6LBP\u00A6EUR\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6ITL\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6GBP\u00A6SAS\u00A6SAR\u00A6LTT\u00A6INR\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GNF\u00A6OMR\u00A6UYP\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6JPY\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6GIP\u00A6VNS\u00A6VNR\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesDisplayNameValues = "Jordansk dinar\u00A6Boliviansk mvdol\u00A6F\u00e4r\u00f6isk krona\u00A6Libanesiskt pund\u00A6Euro\u00A6Vietnamesisk dong\u00A6Tanzanisk shilling\u00A6Boliviansk peso\u00A6Kambodjansk riel\u00A6Kambodjansk gammal riel\u00A6Zambiskt pund\u00A6Australiskt pund\u00A6CFA Franc BEAC\u00A6Maltesiskt pund\u00A6Ghanansk omv\u00e4rderad cedi\u00A6Zambisk kwacha\u00A6Ghananskt pund\u00A6Ghanansk gammal cedi\u00A6Maltesisk lira\u00A6Australisk dollar\u00A6US-dollar (samma dag)\u00A6Italiensk lira\u00A6US-dollar (n\u00e4sta dag)\u00A6Ghanansk cedi\u00A6Singaporiansk dollar\u00A6Panamansk balboa\u00A6Laotisk kip\u00A6Kirgizistansk som\u00A6Schweizisk franc\u00A6\u00d6sterrikisk schilling\u00A6US-dollar\u00A6Etiopisk dollar\u00A6Bruneisk dollar\u00A6Jamaicanskt pund\u00A6Etiopisk birr\u00A6Algerisk franc germinal\u00A6Algerisk ny franc\u00A6Algerisk dinar\u00A6Paraguaysk guarani\u00A6Libyskt pund\u00A6Jamaicansk dollar\u00A6Isl\u00e4ndsk krona\u00A6Spansk peseta\u00A6Bermuda-pund\u00A6Libysk dinar\u00A6Libyska brittiska milit\u00e4rmyndighetens lira\u00A6Bermuda-dollar\u00A6Nederl\u00e4ndsk gulden\u00A6Mauretansk ouguiya\u00A6Iransk rial\u00A6Svensk krona\u00A6Eritreansk nakfa\u00A6Kenyansk shilling\u00A6Centralafrikansk CFA-franc\u00A6Argentinsk peso\u00A6Argentinsk peso (1983-1985)\u00A6Argentinsk peso \u2013 Moneda nacional\u00A6Taiwanesisk ny dollar\u00A6Sudanesiskt pund\u00A6Georgisk lari\u00A6Georgisk kupon larit\u00A6Martiniqueisk franc\u00A6Falklands\u00f6arnas pund\u00A6Argentinsk austral\u00A6Sudanesisk dinar\u00A6Irakisk dinar\u00A6Tuvaluansk dollar\u00A6Seychellisk rupie\u00A6Lettisk rubel\u00A6Fijianskt pund\u00A6Lettisk lats\u00A6Kongolesisk zaire\u00A6Kongolesisk franc\u00A6Kongolesisk franc congolais\u00A6Fijiansk dollar\u00A6Nicaraguansk c\u00f3rdoba oro\u00A6Macaoisk pataca\u00A6Nicaraguansk guldc\u00f3rdoba\u00A6Nicaraguansk c\u00f3rdoba\u00A6Finsk mark (1860-1962)\u00A6Finsk mark\u00A6Salomon-dollar\u00A6Luxemburgsk franc\u00A6Trinidadisk gammal dollar\u00A6Angolansk escudo\u00A6Angolansk kwanza \u2013 Reajustado (1995-1999)\u00A6Mongolisk tugrik\u00A6Ungersk forint\u00A6Burundisk franc\u00A6Angolansk ny kwanza (1990-2000)\u00A6Angolansk kwanza (1977-1990)\u00A6Trinidadisk dollar\u00A6Swazil\u00e4ndsk lilangeni\u00A6Nyhebridisk CFP-franc\u00A6Brittiskt pund sterling\u00A6Saudisk sovereign riyal\u00A6Saudisk riyal\u00A6Lettisk talonas\u00A6Indisk rupie\u00A6Portugisisk escudo\u00A6Angolansk kwanza\u00A6Portugisisk conto\u00A6Lettisk lita\u00A6Kazakisk tenge\u00A6Kazakisk rubel\u00A6Jungfru\u00f6isk dollar\u00A6Nigerianskt pund\u00A6Myanmarisk dollar \u2013 Foreign Exchange Certificates\u00A6Nigeriansk naira\u00A6Haitisk gourde\u00A6Syriskt pund\u00A6Palestinskt pund\u00A6Bahrainsk dinar\u00A6Myanmarisk kyat\u00A6Nederl\u00e4ndsk antillisk gulden\u00A6Tjeckisk koruna\u00A6Isle of Man-pund sterling\u00A6Bulgarisk lev \u2013 Foreign Exchange Certificates\u00A6Lesothisk loti\u00A6Gabonesisk CFA-franc\u00A6Bulgarisk lev (1879-1952)\u00A6Bulgarisk ny lev\u00A6Bulgarisk socialistisk lev\u00A6Kanadensisk dollar\u00A6Bulgarisk h\u00e5rd lev\u00A6Turkisk lira\u00A6Cayman-dollar\u00A6Cypriotiskt pund\u00A6Israelisk ny shekel\u00A6Guyanansk dollar\u00A6Armenisk dram\u00A6Israeliskt pund\u00A6Malisk franc\u00A6Israelisk shekel\u00A6Venezuelansk bolivar\u00A6Albansk dollar \u2013 Foreign Exchange Certificates)\u00A6Liberisk dollar\u00A6Albansk lek \u2013 Valute)\u00A6Kroatisk kuna\u00A6R\u00e9union-franc\u00A6Kroatisk dinar\u00A6Albansk lek\u00A6Jersey-pund sterling\u00A6Albansk lek (1946-1961)\u00A6Makedonisk denar (1992-1993)\u00A6Nordvietnamesisk viet minh piastre dong viet\u00A6Nordvietnamesisk ny dong\u00A6Makedonisk denar\u00A6Nordvietnamesisk piastre dong viet\u00A6Timoriansk pataca\u00A6CFP-franc\u00A6Belgisk franc (finansiell)\u00A6Guinea-Bissau-peso\u00A6Kuwaitisk dinar\u00A6Portugisiska Guinea-mil reis\u00A6Belgisk franc\u00A6Timoriansk escudo\u00A6Belgisk franc (konvertibel)\u00A6Portugisiska Guinea-escudo\u00A6Salvadoransk col\u00f3n\u00A6Cura\u00e7ao-gulden\u00A6Bangladeshisk taka\u00A6Tonganskt pund sterling\u00A6Tongansk pa\u02bbanga\u00A6CFA Franc BCEAO\u00A6Sovjetisk rubel\u00A6Sovjetisk ny rubel\u00A6Nykaledonsk franc germinal\u00A6Kapverdisk escudo\u00A6Fransk Antillisk CFA-franc\u00A6Sydafrikansk rand\u00A6Dominikansk peso\u00A6Kubansk Foreign Exchange Certificates\u00A6Sydafrikansk rand\u00A6Sydafrikansk rand (finansiell)\u00A6Tunisisk dinar\u00A6Kubansk peso\u00A6Franska Guyanas Franc Guiana\u00A6Ugandisk shilling\u00A6Ceylonesisk rupie\u00A6Affars och Issas-franc\u00A6Vatikansk lira\u00A6S\u00e3o Tom\u00e9 och Pr\u00edncipe-escudo\u00A6Ugandisk shilling (1966-1987)\u00A6S\u00e3o Tom\u00e9 och Pr\u00edncipe-dobra\u00A6Marshall\u00f6isk dollar\u00A6Nyzeel\u00e4ndskt pund\u00A6V\u00e4stsamoansk tala\u00A6V\u00e4stsamoanskt pund\u00A6Hoduransk lempira\u00A6French Metropolitan Nouveau Franc\u00A6Turkmensk manat\u00A6Guatemalansk quetzal\u00A6Nyzeel\u00e4ndsk dollar\u00A6Skotskt pund\u00A6Barbadisk dollar\u00A6Namibisk dollar\u00A6Madagaskisk franc\u00A6Madagaskisk ariary\u00A6Egyptiskt pund\u00A6Brittiska Honduras-dollar\u00A6Polsk zloty (1950-1995)\u00A6Bosnisk-hercegovinsk ny dinar\u00A6Polsk US-dollar Foreign Exchange Certificates\u00A6Konvertibel bosnisk-hercegovinsk mark\u00A6Belizisk dollar\u00A6Bosnisk-hercegovinsk dinar\u00A6Polsk zloty\u00A6Jemenitisk rial\u00A6Surinamesisk gulden\u00A6Tjeckisk h\u00e5rd koruna\u00A6Sydkoreansk won\u00A6Vitrysk rubel\u00A6Jemenitisk imadi riyal\u00A6Vitrysk rubel (1992-1994)\u00A6Tjeckisk koruna\u00A6Sydkoreansk gammal won\u00A6Sydkoreansk hwan\u00A6Vitrysk ny rubel (1994-1999)\u00A6Somalil\u00e4ndsk shilling\u00A6Grekisk ny drachma\u00A6Pakistansk rupie\u00A6Zimbabwisk dollar\u00A6Srilankesisk rupie\u00A6Grekisk drachma\u00A6Irl\u00e4ndskt pund\u00A6Jemenitisk dinar\u00A6Rwandisk franc\u00A6Costarikansk col\u00f3n\u00A6Tadzjikisk somoni\u00A6Tadzjikisk rubel\u00A6Estnisk krona\u00A6Ekvatorialguineansk peseta guineana\u00A6Moldavisk rubelkupong\u00A6Hongkong-dollar\u00A6Dansk krona\u00A6Moldavisk leu\u00A6Ekvatorialguineansk franco\u00A6Ekvatorialguineansk ekwele guineana\u00A6Indonesisk rupiah\u00A6F\u00f6renade arabemiratens dirham\u00A6Nordkoreansk won\u00A6Indonesisk ny rupiah\u00A6Botswansk pula\u00A6Moldavisk leu-kupong\u00A6Indonesisk java rupiah\u00A6Nordkoreansk won\u00A6Indonesisk nica gulden\u00A6Vanuatisk vatu\u00A6Islamisk dinar\u00A6Somalisk shilling\u00A6Andorransk peseta\u00A6Rysk rubel (1991-1998)\u00A6Guadeloupisk franc\u00A6Djiboutisk franc\u00A6Andorransk diner\u00A6Monegaskisk franc germinal\u00A6Monegaskisk franc nouveau\u00A6Ecuadoriansk Unidad de Valor Constante (UVC)\u00A6Ecuadoriansk sucre\u00A6Liechtensteinsk franc\u00A6Rysk rubel\u00A6Filippinsk peso\u00A6Uzbekisk sum\u00A6Colombiansk peso\u00A6Thail\u00e4ndsk baht\u00A6Nordirl\u00e4ndskt pund\u00A6Burmesisk rupee\u00A6Kongolesisk CFA-franc\u00A6Burmesisk kyat\u00A6Colombiansk papperspeso\u00A6Uzbekisk coupon som\u00A6Ukrainsk karbovanetz\u00A6Qatarisk rial\u00A6Ukrainsk hryvnia\u00A6Guineansk syli\u00A6Kinesisk yuan renminbi\u00A6Mo\u00e7ambikisk metical\u00A6Kinesisk USA-dollar Foreign Exchange Certificates\u00A6Uruguayansk peso uruguayo\u00A6Guineansk franc (1960-1972)\u00A6Sanmarinsk lira\u00A6Mo\u00e7ambikisk escudo\u00A6Kinesisk jen min piao yuan\u00A6Papuansk kina\u00A6Omansk rial saidi\u00A6Guineansk franc\u00A6Omansk rial\u00A6Uruguayansk peso (1975-1993)\u00A6French UIC-Franc\u00A6Bhutanesisk rupie\u00A6Zairisk zaire\u00A6Marockansk franc\u00A6Marockansk dirham\u00A6Bhutanesisk ngultrum\u00A6Fransk guldfranc\u00A6Uruguayansk peso fuerte\u00A6Malaysisk ringgit\u00A6Zairisk ny zaire\u00A6Azerbajdzjansk manat\u00A6Gambiskt pund\u00A6Komorisk franc\u00A6Sierraleonsk leone\u00A6Gambisk dalasi\u00A6Bahamanskt pund\u00A6Kamerunsk CFA-franc\u00A6Mexikansk Unidad de Inversion (UDI)\u00A6CFA Franc BCEAEC\u00A6Bahamansk dollar\u00A6Mexikansk silverpeso (1861-1992)\u00A6Mexikansk peso\u00A6Peruansk sol\u00A6Gr\u00f6nl\u00e4ndsk krona\u00A6Brasiliansk cruzeiro (1942-1967)\u00A6Peruansk sol nuevo\u00A6Chilensk peso\u00A6Slovakisk koruna\u00A6Peruansk inti\u00A6Brasiliansk cruzeiro\u00A6Fransk Franc Germinal/Franc Poincare\u00A6Fransk franc\u00A6Brasiliansk cruzado novo\u00A6Chilensk unidad de fomento\u00A6Chilensk escudo\u00A6Brasiliansk real\u00A6Chilensk condor\u00A6Brasiliansk cruzeiro (1990-1993)\u00A6Tysk sperrmark\u00A6Malawiskt pund\u00A6Brasiliansk cruzado\u00A6Brasiliansk cruzeiro novo (1967-1986)\u00A6Malawisk kwacha\u00A6Transdniestrisk rubel\u00A6Tysk mark\u00A6Tchadisk CFA-franc\u00A6Transdniestrisk ny rubel\u00A6Transdniestrisk rubelkupong\u00A6Nepalesisk rupie\u00A6Cook-dollar\u00A6Japansk yen\u00A6Maldivisk rufiyaa\u00A6CFA Nouveau Franc\u00A6Maldivisk rupie\u00A6\u00d6stkaribisk dollar\u00A6Slovensk tolar\u00A6Jugoslavisk reformerad dinar\u00A6Aruba-florin\u00A6Jugoslavisk oktoberdinar\u00A6\u00d6sttysk mark\u00A6Jugoslavisk konvertibel dinar\u00A6Dinar (Serbien och Montenegro)\u00A6Turks and Caicos-crown\u00A6Jugoslavisk dinar (1994)\u00A6Jugoslavisk federationsdinar\u00A6Rum\u00e4nsk ny leu\u00A6Jugoslavisk h\u00e5rd dinar\u00A6Rum\u00e4nsk leu\u00A6Slovensk tolar bons\u00A6Norsk krona\u00A6Mauritisk rupie\u00A6Gibraltiskt pund\u00A6Vietnamesisk nationell dong\u00A6Vietnamesisk dong\u00A6Kiribatisk dollar\u00A6S:t Helena-pund\u00A6Vietnamesisk ny dong";

  private static final Hashtable currenciesDisplayName;
  static
  {
    currenciesDisplayName = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesDisplayNameKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesDisplayNameValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesDisplayName.put(key, value);
      }
  }

  private static final String currenciesSymbolKeys = "JOD\u00A6BOV\u00A6FOK\u00A6LBP\u00A6VND\u00A6TZS\u00A6BOP\u00A6KHR\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6GHO\u00A6MTL\u00A6AUD\u00A6USS\u00A6USN\u00A6GHC\u00A6SGD\u00A6PAB\u00A6LAK\u00A6KGS\u00A6CHF\u00A6ATS\u00A6USD\u00A6ETD\u00A6BND\u00A6JMP\u00A6ETB\u00A6DZG\u00A6DZF\u00A6DZD\u00A6PYG\u00A6LYP\u00A6JMD\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LYD\u00A6LYB\u00A6BMD\u00A6NLG\u00A6MRO\u00A6IRR\u00A6SEK\u00A6ERN\u00A6KES\u00A6CFF\u00A6ARS\u00A6ARP\u00A6ARM\u00A6TWD\u00A6SDP\u00A6GEL\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6IQD\u00A6TVD\u00A6SCR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6FJD\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SBD\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6MNT\u00A6HUF\u00A6BIF\u00A6AON\u00A6AOK\u00A6TTD\u00A6SZL\u00A6NHF\u00A6SAS\u00A6SAR\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6KZT\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6SYP\u00A6PSP\u00A6BHD\u00A6MMK\u00A6ANG\u00A6CZK\u00A6IMP\u00A6BGX\u00A6LSL\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6CAD\u00A6BGL\u00A6TRL\u00A6KYD\u00A6CYP\u00A6ILS\u00A6GYD\u00A6AMD\u00A6ILP\u00A6MLF\u00A6ILL\u00A6VEB\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6ALL\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MKD\u00A6VDD\u00A6TPP\u00A6XPF\u00A6BEL\u00A6GWP\u00A6KWD\u00A6GWM\u00A6BEF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6BDT\u00A6TOS\u00A6TOP\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVE\u00A6XNF\u00A6ZAR\u00A6DOP\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6UGX\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6STD\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6HNL\u00A6XMF\u00A6TMM\u00A6GTQ\u00A6NZD\u00A6SSP\u00A6BBD\u00A6NAD\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6BAM\u00A6BZD\u00A6BAD\u00A6PLN\u00A6YER\u00A6SRG\u00A6CSK\u00A6KRW\u00A6BYR\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6PKR\u00A6ZWD\u00A6LKR\u00A6GRD\u00A6IEP\u00A6YDD\u00A6RWF\u00A6CRC\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HKD\u00A6DKK\u00A6MDL\u00A6GQF\u00A6GQE\u00A6IDR\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VUV\u00A6XID\u00A6SOS\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DJF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6COP\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QAR\u00A6UAH\u00A6GNS\u00A6CNY\u00A6MZM\u00A6CNX\u00A6UYU\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GNF\u00A6UYP\u00A6OMR\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6BTN\u00A6XFO\u00A6UYF\u00A6MYR\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6KMF\u00A6SLL\u00A6GMD\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MXN\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6CLP\u00A6SKK\u00A6PEI\u00A6BRR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6BRL\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MWK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6NPR\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6XCD\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6ROL\u00A6SIB\u00A6NOK\u00A6MUR\u00A6GIP\u00A6VNS\u00A6VNR\u00A6KID\u00A6SHP\u00A6VNN";

  private static final String currenciesSymbolValues = "JD\u00A6BOV\u00A6FOK\u00A6LL\u00A6VND\u00A6T Sh\u00A6BOP\u00A6CR\u00A6KHO\u00A6ZMP\u00A6AUP\u00A6XAF\u00A6MTP\u00A6GHR\u00A6ZMK\u00A6GHP\u00A6GHO\u00A6Lm\u00A6$A\u00A6USS\u00A6USN\u00A6GHC\u00A6S$\u00A6PAB\u00A6LAK\u00A6som\u00A6SwF\u00A6ATS\u00A6US$\u00A6ETD\u00A6BND\u00A6JMP\u00A6Br\u00A6DZG\u00A6DZF\u00A6DA\u00A6PYG\u00A6LYP\u00A6J$\u00A6ISK\u00A6ESP\u00A6BMP\u00A6LD\u00A6LYB\u00A6Ber$\u00A6NLG\u00A6UM\u00A6RI\u00A6kr\u00A6ERN\u00A6K Sh\u00A6CFF\u00A6Arg$\u00A6ARP\u00A6ARM\u00A6NT$\u00A6SDP\u00A6lari\u00A6GEK\u00A6MQF\u00A6FKP\u00A6ARA\u00A6SDD\u00A6ID\u00A6TVD\u00A6SR\u00A6LVR\u00A6FJP\u00A6LVL\u00A6CDL\u00A6CDG\u00A6CDF\u00A6F$\u00A6NIO\u00A6MOP\u00A6NIG\u00A6NIC\u00A6FIN\u00A6FIM\u00A6SI$\u00A6LUF\u00A6TTO\u00A6AOS\u00A6AOR\u00A6Tug\u00A6Ft\u00A6Fbu\u00A6AON\u00A6AOK\u00A6TT$\u00A6E\u00A6NHF\u00A6SAS\u00A6SRl\u00A6LTT\u00A6PTE\u00A6AOA\u00A6PTC\u00A6LTL\u00A6T\u00A6KZR\u00A6VGD\u00A6NGP\u00A6MMX\u00A6NGN\u00A6HTG\u00A6LS\u00A6PSP\u00A6BD\u00A6MMK\u00A6NA f.\u00A6CZK\u00A6IMP\u00A6BGX\u00A6M\u00A6GAF\u00A6BGO\u00A6BGN\u00A6BGM\u00A6Can$\u00A6lev\u00A6TL\u00A6KYD\u00A6\u00a3C\u00A6ILS\u00A6G$\u00A6dram\u00A6ILP\u00A6MLF\u00A6ILL\u00A6Be\u00A6ALX\u00A6LRD\u00A6ALV\u00A6HRK\u00A6REF\u00A6HRD\u00A6lek\u00A6JEP\u00A6ALK\u00A6MKN\u00A6VDP\u00A6VDN\u00A6MDen\u00A6VDD\u00A6TPP\u00A6CFPF\u00A6BEL\u00A6GWP\u00A6KD\u00A6GWM\u00A6BF\u00A6TPE\u00A6BEC\u00A6GWE\u00A6SVC\u00A6CWG\u00A6Tk\u00A6TOS\u00A6T$\u00A6XOF\u00A6SUR\u00A6SUN\u00A6NCF\u00A6CVEsc\u00A6XNF\u00A6R\u00A6RD$\u00A6CUX\u00A6ZAP\u00A6ZAL\u00A6TND\u00A6CUP\u00A6GUF\u00A6U Sh\u00A6LNR\u00A6AIF\u00A6VAL\u00A6STE\u00A6UGS\u00A6Db\u00A6MHD\u00A6NZP\u00A6WST\u00A6WSP\u00A6L\u00A6XMF\u00A6TMM\u00A6Q\u00A6$NZ\u00A6SSP\u00A6BDS$\u00A6N$\u00A6MGF\u00A6MGA\u00A6EGP\u00A6BZH\u00A6PLZ\u00A6BAN\u00A6PLX\u00A6KM\u00A6BZ$\u00A6BAD\u00A6Zl\u00A6YRl\u00A6Sf\u00A6CSK\u00A6KRW\u00A6Rbl\u00A6YEI\u00A6BYL\u00A6CSC\u00A6KRO\u00A6KRH\u00A6BYB\u00A6SQS\u00A6GRN\u00A6Pra\u00A6Z$\u00A6SL Re\u00A6GRD\u00A6IR\u00a3\u00A6YDD\u00A6RWF\u00A6C\u00A6TJS\u00A6TJR\u00A6EEK\u00A6GQP\u00A6MDR\u00A6HK$\u00A6DKr\u00A6MDL\u00A6GQF\u00A6GQE\u00A6Rp\u00A6AED\u00A6KPW\u00A6IDN\u00A6BWP\u00A6MDC\u00A6IDJ\u00A6KPP\u00A6IDG\u00A6VT\u00A6XID\u00A6So. Sh.\u00A6ADP\u00A6RUR\u00A6GPF\u00A6DF\u00A6ADD\u00A6MCG\u00A6MCF\u00A6ECV\u00A6ECS\u00A6LIF\u00A6RUB\u00A6PHP\u00A6UZS\u00A6Col$\u00A6THB\u00A6IBP\u00A6BUR\u00A6COF\u00A6BUK\u00A6COB\u00A6UZC\u00A6UAK\u00A6QR\u00A6UAH\u00A6GNS\u00A6Y\u00A6Mt\u00A6CNX\u00A6Ur$\u00A6GNI\u00A6SML\u00A6MZE\u00A6CNP\u00A6PGK\u00A6OMS\u00A6GF\u00A6UYP\u00A6RO\u00A6XFU\u00A6BTR\u00A6ZRZ\u00A6MAF\u00A6MAD\u00A6Nu\u00A6XFO\u00A6UYF\u00A6RM\u00A6ZRN\u00A6AZM\u00A6GMP\u00A6CF\u00A6SLL\u00A6GMD\u00A6BSP\u00A6CMF\u00A6MXV\u00A6XEF\u00A6BSD\u00A6MXP\u00A6MEX$\u00A6PES\u00A6GLK\u00A6BRZ\u00A6PEN\u00A6Ch$\u00A6Sk\u00A6PEI\u00A6BRR\u00A6FRG\u00A6FRF\u00A6BRN\u00A6CLF\u00A6CLE\u00A6R$\u00A6CLC\u00A6BRE\u00A6DES\u00A6MWP\u00A6BRC\u00A6BRB\u00A6MK\u00A6PDR\u00A6DEM\u00A6TDF\u00A6PDN\u00A6PDK\u00A6Nrs\u00A6CKD\u00A6MVR\u00A6XCF\u00A6MVP\u00A6EC$\u00A6SIT\u00A6YUR\u00A6AWG\u00A6YUO\u00A6DDM\u00A6YUN\u00A6YUM\u00A6TCC\u00A6YUG\u00A6YUF\u00A6RON\u00A6YUD\u00A6leu\u00A6SIB\u00A6NKr\u00A6MUR\u00A6GIP\u00A6VNS\u00A6VNR\u00A6KID\u00A6SHP\u00A6VNN";

  private static final Hashtable currenciesSymbol;
  static
  {
    currenciesSymbol = new Hashtable();
    Enumeration keys = new StringTokenizer(currenciesSymbolKeys, "\u00A6");
    Enumeration values = new StringTokenizer(currenciesSymbolValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         currenciesSymbol.put(key, value);
      }
  }

  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "maj",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "dec",
    null,
  };

  private static final String[] months = {
    "januari",
    "februari",
    "mars",
    "april",
    "maj",
    "juni",
    "juli",
    "augusti",
    "september",
    "oktober",
    "november",
    "december",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "s\u00f6",
    "m\u00e5",
    "ti",
    "on",
    "to",
    "fr",
    "l\u00f6",
  };

  private static final String[] weekdays = {
    null,
    "s\u00f6ndag",
    "m\u00e5ndag",
    "tisdag",
    "onsdag",
    "torsdag",
    "fredag",
    "l\u00f6rdag",
  };

  private static final String[] eras = {
    "f.Kr.",
    "e.Kr.",
  };

  private static final String[] ampms = {
    "f.m.",
    "e.m.",
  };

  private static final String[][] zoneStrings =
  {
    {  "America/Indianapolis", "EST", "Eastern, normaltid", "EST", "Eastern, normaltid"},
    {  "America/Halifax", "AST", "Atlantic, normaltid", "ADT", "Atlantic, sommartid"},
    {  "Pacific/Honolulu", "HST", "Hawaii, normaltid", "HST", "Hawaii, normaltid"},
    {  "America/Denver", "MST", "Mountain, normaltid", "MDT", "Mountain, sommartid"},
    {  "America/Anchorage", "AST", "Alaska, normaltid", "ADT", "Alaska, sommartid"},
    {  "America/St_Johns", "CNT", "Newfoundland, normaltid", "CDT", "Newfoundland, sommartid"},
    {  "Africa/Casablanca", "GMT", "Greenwichtid", "GMT", "Greenwichtid"},
    {  "America/Chicago", "CST", "Central, normaltid", "CDT", "Central, sommartid"},
    {  "Asia/Shanghai", "CTT", "Kina, normaltid", "CDT", "Kina, normaltid"},
    {  "Asia/Tokyo", "JST", "Japan, normaltid", "JST", "Japan, normaltid"},
    {  "America/New_York", "EST", "Eastern, normaltid", "EDT", "Eastern, sommartid"},
    {  "Europe/Bucharest", "EET", "\u00d6steuropa, normaltid", "EEST", "\u00d6steuropa, sommartid"},
    {  "America/Los_Angeles", "PST", "Pacific, normaltid", "PDT", "Pacific, sommartid"},
    {  "America/Phoenix", "MST", "Mountain, normaltid", "MST", "Mountain, sommartid"},
    {  "Etc/GMT", "GMT", "Greenwichtid", "GMT", "Greenwichtid"},
    {  "Asia/Jerusalem", "IST", "Israel, normaltid", "IDT", "Israel, sommartid"},
    {  "Europe/Paris", "CET", "Centraleuropa, normaltid", "CEST", "Centraleuropa, sommartid"},
  };

  private static final String territoriesKeys = "TL\u00A6TK\u00A6TJ\u00A6TH\u00A6TG\u00A6TF\u00A6GY\u00A6TD\u00A6TC\u00A6GW\u00A6GU\u00A6GT\u00A6GS\u00A6GR\u00A6GQ\u00A6GP\u00A6SZ\u00A6SY\u00A6GN\u00A6GM\u00A6GL\u00A6SV\u00A6ST\u00A6GI\u00A6GH\u00A6SR\u00A6GF\u00A6GE\u00A6SO\u00A6GD\u00A6SN\u00A6SM\u00A6GB\u00A6SL\u00A6GA\u00A6SK\u00A6SJ\u00A6SI\u00A6SH\u00A6SG\u00A6SE\u00A6SD\u00A6SC\u00A6SB\u00A6SA\u00A6FR\u00A6FO\u00A6FM\u00A6RW\u00A6FK\u00A6RU\u00A6FJ\u00A6FI\u00A6RO\u00A6RE\u00A6ET\u00A6ES\u00A6ER\u00A6EH\u00A6EG\u00A6EE\u00A6EC\u00A6DZ\u00A6QA\u00A6DO\u00A6PY\u00A6DM\u00A6PW\u00A6DK\u00A6DJ\u00A6PT\u00A6PS\u00A6PR\u00A6DE\u00A6PN\u00A6PM\u00A6PL\u00A6PK\u00A6PH\u00A6PG\u00A6PF\u00A6CZ\u00A6PE\u00A6CY\u00A6CX\u00A6CV\u00A6PA\u00A6CU\u00A6CR\u00A6CO\u00A6CN\u00A6CM\u00A6CL\u00A6CK\u00A6CI\u00A6CH\u00A6CG\u00A6CF\u00A6CD\u00A6CC\u00A6OM\u00A6CA\u00A6BZ\u00A6BY\u00A6BW\u00A6BV\u00A6BT\u00A6BS\u00A6BR\u00A6NZ\u00A6BO\u00A6BN\u00A6BM\u00A6NU\u00A6BJ\u00A6BI\u00A6BH\u00A6NR\u00A6BG\u00A6BF\u00A6NP\u00A6BE\u00A6NO\u00A6BD\u00A6BB\u00A6ZW\u00A6NL\u00A6BA\u00A6NI\u00A6NG\u00A6NF\u00A6AZ\u00A6NE\u00A6NC\u00A6AW\u00A6ZM\u00A6NA\u00A6AU\u00A6AT\u00A6AS\u00A6AR\u00A6AQ\u00A6MZ\u00A6AO\u00A6MY\u00A6AN\u00A6MX\u00A6AM\u00A6MW\u00A6AL\u00A6MV\u00A6ZA\u00A6MU\u00A6MT\u00A6AI\u00A6MS\u00A6MR\u00A6AG\u00A6MQ\u00A6AF\u00A6MP\u00A6AE\u00A6MO\u00A6AD\u00A6MN\u00A6MM\u00A6ML\u00A6MK\u00A6YU\u00A6YT\u00A6MH\u00A6MG\u00A6MD\u00A6MC\u00A6MA\u00A6YE\u00A6LY\u00A6LV\u00A6LU\u00A6LT\u00A6LS\u00A6LR\u00A6LK\u00A6LI\u00A6LC\u00A6LB\u00A6LA\u00A6KZ\u00A6KY\u00A6KW\u00A6KR\u00A6KP\u00A6KN\u00A6KM\u00A6KI\u00A6WS\u00A6KH\u00A6KG\u00A6KE\u00A6WF\u00A6JP\u00A6JO\u00A6JM\u00A6VU\u00A6VN\u00A6VI\u00A6VG\u00A6VE\u00A6VC\u00A6VA\u00A6IT\u00A6IS\u00A6IR\u00A6IQ\u00A6UZ\u00A6IO\u00A6UY\u00A6IN\u00A6IL\u00A6US\u00A6IE\u00A6ID\u00A6UM\u00A6UG\u00A6UA\u00A6HU\u00A6HT\u00A6HR\u00A6TZ\u00A6HN\u00A6HM\u00A6TW\u00A6TV\u00A6HK\u00A6TT\u00A6TR\u00A6TO\u00A6TN\u00A6TM";

  private static final String territoriesValues = "\u00d6sttimor\u00A6Tokelau\u00f6arna\u00A6Tadzjikistan\u00A6Thailand\u00A6Togo\u00A6Franska Sydterritorierna\u00A6Guyana\u00A6Tchad\u00A6Turks- och Caicos\u00f6arna\u00A6Guinea-Bissau\u00A6Guam\u00A6Guatemala\u00A6Sydgeorgien och S\u00f6dra Sandwich\u00f6arna\u00A6Grekland\u00A6Ekvatorialguinea\u00A6Guadeloupe\u00A6Swaziland\u00A6Syrien\u00A6Guinea\u00A6Gambia\u00A6Gr\u00f6nland\u00A6El Salvador\u00A6S\u00e3o Tom\u00e9 och Pr\u00edncipe\u00A6Gibraltar\u00A6Ghana\u00A6Surinam\u00A6Franska Guyana\u00A6Georgien\u00A6Somalia\u00A6Grenada\u00A6Senegal\u00A6San Marino\u00A6Storbritannien\u00A6Sierra Leone\u00A6Gabon\u00A6Slovakien\u00A6Svalbard och Jan Mayen\u00A6Slovenien\u00A6S:t Helena\u00A6Singapore\u00A6Sverige\u00A6Sudan\u00A6Seychellerna\u00A6Salomon\u00f6arna\u00A6Saudiarabien\u00A6Frankrike\u00A6F\u00e4r\u00f6arna\u00A6Mikronesien\u00A6Rwanda\u00A6Falklands\u00f6arna\u00A6Ryssland\u00A6Fiji\u00A6Finland\u00A6Rum\u00e4nien\u00A6R\u00e9union\u00A6Etiopien\u00A6Spanien\u00A6Eritrea\u00A6V\u00e4stra Sahara\u00A6Egypten\u00A6Estland\u00A6Ecuador\u00A6Algeriet\u00A6Qatar\u00A6Dominikanska republiken\u00A6Paraguay\u00A6Dominica\u00A6Palau\u00A6Danmark\u00A6Djibouti\u00A6Portugal\u00A6Palestinska territoriet\u00A6Puerto Rico\u00A6Tyskland\u00A6Pitcairn\u00A6S:t Pierre och Miquelon\u00A6Polen\u00A6Pakistan\u00A6Filippinerna\u00A6Papua Nya Guinea\u00A6Franska Polynesien\u00A6Tjeckien\u00A6Peru\u00A6Cypern\u00A6Jul\u00f6n\u00A6Kap Verde\u00A6Panama\u00A6Kuba\u00A6Costa Rica\u00A6Colombia\u00A6Kina\u00A6Kamerun\u00A6Chile\u00A6Cook\u00f6arna\u00A6Elfenbenskusten\u00A6Schweiz\u00A6Kongo-Brazzaville\u00A6Centralafrikanska republiken\u00A6Kongo-Kinshasa\u00A6Kokos\u00f6arna (Keeling\u00f6arna)\u00A6Oman\u00A6Kanada\u00A6Belize\u00A6Vitryssland\u00A6Botswana\u00A6Bouvet\u00f6n\u00A6Bhutan\u00A6Bahamas\u00A6Brasilien\u00A6Nya Zeeland\u00A6Bolivia\u00A6Brunei\u00A6Bermuda\u00A6Niue\u00f6n\u00A6Benin\u00A6Burundi\u00A6Bahrain\u00A6Nauru\u00A6Bulgarien\u00A6Burkina Faso\u00A6Nepal\u00A6Belgien\u00A6Norge\u00A6Bangladesh\u00A6Barbados\u00A6Zimbabwe\u00A6Nederl\u00e4nderna\u00A6Bosnien och Hercegovina\u00A6Nicaragua\u00A6Nigeria\u00A6Norfolk\u00f6n\u00A6Azerbajdzjan\u00A6Niger\u00A6Nya Kaledonien\u00A6Aruba\u00A6Zambia\u00A6Namibia\u00A6Australien\u00A6\u00d6sterrike\u00A6Amerikanska Samoa\u00A6Argentina\u00A6Antarktis\u00A6Mo\u00e7ambique\u00A6Angola\u00A6Malaysia\u00A6Nederl\u00e4ndska Antillerna\u00A6Mexiko\u00A6Armenien\u00A6Malawi\u00A6Albanien\u00A6Maldiverna\u00A6Sydafrika\u00A6Mauritius\u00A6Malta\u00A6Anguilla\u00A6Montserrat\u00A6Mauretanien\u00A6Antigua och Barbuda\u00A6Martinique\u00A6Afghanistan\u00A6Nordmarianerna\u00A6F\u00f6renade Arabemiraten\u00A6Macao (S.A.R. Kina)\u00A6Andorra\u00A6Mongoliet\u00A6Myanmar\u00A6Mali\u00A6Makedonien\u00A6Jugoslavien\u00A6Mayotte\u00A6Marshall\u00f6arna\u00A6Madagaskar\u00A6Moldavien\u00A6Monaco\u00A6Marocko\u00A6Jemen\u00A6Libyen\u00A6Lettland\u00A6Luxemburg\u00A6Litauen\u00A6Lesotho\u00A6Liberia\u00A6Sri Lanka\u00A6Liechtenstein\u00A6S:t Lucia\u00A6Libanon\u00A6Laos\u00A6Kazakstan\u00A6Cayman\u00f6arna\u00A6Kuwait\u00A6Sydkorea\u00A6Nordkorea\u00A6S:t Kitts och Nevis\u00A6Komorerna\u00A6Kiribati\u00A6Samoa\u00A6Kambodja\u00A6Kirgizistan\u00A6Kenya\u00A6Wallis- och Futuna\u00f6arna\u00A6Japan\u00A6Jordanien\u00A6Jamaica\u00A6Vanuatu\u00A6Vietnam\u00A6Amerikanska Jungfru\u00f6arna\u00A6Brittiska Jungfru\u00f6arna\u00A6Venezuela\u00A6S:t Vincent och Grenadinerna\u00A6Vatikanstaten\u00A6Italien\u00A6Island\u00A6Iran\u00A6Irak\u00A6Uzbekistan\u00A6Brittiska Indiska ocean\u00f6arna\u00A6Uruguay\u00A6Indien\u00A6Israel\u00A6USA\u00A6Irland\u00A6Indonesien\u00A6USAs yttre \u00f6ar\u00A6Uganda\u00A6Ukraina\u00A6Ungern\u00A6Haiti\u00A6Kroatien\u00A6Tanzania\u00A6Honduras\u00A6Heard- och McDonald\u00f6arna\u00A6Taiwan\u00A6Tuvalu\u00A6Hongkong (S.A.R. Kina)\u00A6Trinidad och Tobago\u00A6Turkiet\u00A6Tonga\u00A6Tunisien\u00A6Turkmenistan";

  private static final Hashtable territories;
  static
  {
    territories = new Hashtable();
    Enumeration keys = new StringTokenizer(territoriesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(territoriesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         territories.put(key, value);
      }
  }

  private static final String languagesKeys = "gwi\u00A6akk\u00A6eka\u00A6xh\u00A6sux\u00A6sus\u00A6mis\u00A6loz\u00A6tog\u00A6pon\u00A6min\u00A6suk\u00A6wo\u00A6lol\u00A6kut\u00A6mic\u00A6wa\u00A6kum\u00A6zap\u00A6cus\u00A6jbo\u00A6doi\u00A6vo\u00A6oto\u00A6vi\u00A6rar\u00A6ve\u00A6rap\u00A6raj\u00A6ota\u00A6nzi\u00A6nap\u00A6uz\u00A6uga\u00A6tmh\u00A6nai\u00A6nah\u00A6ur\u00A6fat\u00A6uk\u00A6egy\u00A6ug\u00A6fan\u00A6ssa\u00A6mga\u00A6bat\u00A6nyo\u00A6bas\u00A6nyn\u00A6nym\u00A6hmn\u00A6ban\u00A6osa\u00A6bal\u00A6ty\u00A6bai\u00A6tw\u00A6srr\u00A6tli\u00A6tt\u00A6ts\u00A6bad\u00A6tr\u00A6to\u00A6tn\u00A6tl\u00A6tk\u00A6ti\u00A6th\u00A6kru\u00A6tg\u00A6byn\u00A6te\u00A6kro\u00A6csb\u00A6ta\u00A6tkl\u00A6efi\u00A6sw\u00A6sv\u00A6su\u00A6krc\u00A6st\u00A6ss\u00A6sr\u00A6sq\u00A6men\u00A6crp\u00A6so\u00A6afh\u00A6sn\u00A6sm\u00A6sl\u00A6grc\u00A6sk\u00A6grb\u00A6si\u00A6sh\u00A6crh\u00A6afa\u00A6sg\u00A6se\u00A6sd\u00A6udm\u00A6sc\u00A6sa\u00A6rw\u00A6ru\u00A6mdr\u00A6ro\u00A6rn\u00A6rm\u00A6mdf\u00A6tiv\u00A6ady\u00A6zun\u00A6kpe\u00A6qu\u00A6tig\u00A6son\u00A6cpp\u00A6sog\u00A6ada\u00A6kos\u00A6hit\u00A6cpf\u00A6cpe\u00A6him\u00A6kok\u00A6hil\u00A6got\u00A6gor\u00A6gon\u00A6din\u00A6nub\u00A6pt\u00A6ps\u00A6fur\u00A6phn\u00A6goh\u00A6snk\u00A6cop\u00A6ach\u00A6phi\u00A6pl\u00A6ace\u00A6pi\u00A6pa\u00A6bug\u00A6iba\u00A6sms\u00A6bua\u00A6mas\u00A6smn\u00A6os\u00A6map\u00A6or\u00A6man\u00A6smj\u00A6smi\u00A6mak\u00A6om\u00A6mai\u00A6oj\u00A6mag\u00A6mad\u00A6sma\u00A6oc\u00A6nso\u00A6btk\u00A6myv\u00A6dgr\u00A6ny\u00A6myn\u00A6nv\u00A6kmb\u00A6nr\u00A6gmh\u00A6no\u00A6nn\u00A6nl\u00A6ng\u00A6sla\u00A6ne\u00A6nd\u00A6cmc\u00A6tet\u00A6nb\u00A6na\u00A6ter\u00A6tem\u00A6my\u00A6lez\u00A6mt\u00A6peo\u00A6ms\u00A6mr\u00A6fro\u00A6mo\u00A6frm\u00A6mn\u00A6jrb\u00A6ml\u00A6mk\u00A6mi\u00A6mh\u00A6mg\u00A6mwr\u00A6bra\u00A6den\u00A6lv\u00A6lu\u00A6del\u00A6lt\u00A6lo\u00A6ln\u00A6li\u00A6ewo\u00A6lg\u00A6lb\u00A6la\u00A6jpr\u00A6vot\u00A6sit\u00A6ky\u00A6kw\u00A6kv\u00A6ku\u00A6sio\u00A6ks\u00A6kr\u00A6awa\u00A6ko\u00A6kn\u00A6km\u00A6kl\u00A6kk\u00A6rom\u00A6kj\u00A6sid\u00A6ki\u00A6kg\u00A6non\u00A6ka\u00A6mus\u00A6roa\u00A6nog\u00A6mun\u00A6mul\u00A6jv\u00A6gil\u00A6znd\u00A6shn\u00A6xal\u00A6aus\u00A6kho\u00A6ja\u00A6khi\u00A6pau\u00A6chy\u00A6tai\u00A6iu\u00A6pap\u00A6it\u00A6sgn\u00A6is\u00A6kha\u00A6chr\u00A6pam\u00A6pal\u00A6chp\u00A6io\u00A6cho\u00A6chn\u00A6chm\u00A6tyv\u00A6bnt\u00A6pag\u00A6ik\u00A6chk\u00A6ii\u00A6haw\u00A6lam\u00A6ig\u00A6chg\u00A6sga\u00A6paa\u00A6ie\u00A6id\u00A6lah\u00A6day\u00A6chb\u00A6ia\u00A6lad\u00A6hz\u00A6hai\u00A6dar\u00A6hy\u00A6ath\u00A6hu\u00A6ht\u00A6dak\u00A6hr\u00A6ho\u00A6hi\u00A6dyu\u00A6he\u00A6ast\u00A6ha\u00A6wen\u00A6gv\u00A6gu\u00A6sem\u00A6sel\u00A6iro\u00A6gn\u00A6gl\u00A6arw\u00A6gez\u00A6art\u00A6gd\u00A6ira\u00A6ga\u00A6arp\u00A6arn\u00A6fy\u00A6bla\u00A6gem\u00A6ypk\u00A6arc\u00A6fr\u00A6fo\u00A6cel\u00A6fj\u00A6fi\u00A6ff\u00A6tvl\u00A6ceb\u00A6fa\u00A6eu\u00A6sco\u00A6et\u00A6es\u00A6eo\u00A6en\u00A6el\u00A6tut\u00A6niu\u00A6tup\u00A6ee\u00A6tum\u00A6mos\u00A6dz\u00A6nic\u00A6lus\u00A6fiu\u00A6dv\u00A6nia\u00A6moh\u00A6lun\u00A6apa\u00A6lui\u00A6hup\u00A6bin\u00A6de\u00A6lua\u00A6bik\u00A6was\u00A6und\u00A6war\u00A6da\u00A6dum\u00A6wal\u00A6mno\u00A6wak\u00A6sat\u00A6cy\u00A6sas\u00A6kbd\u00A6cv\u00A6cu\u00A6mni\u00A6cs\u00A6sam\u00A6cr\u00A6sal\u00A6dua\u00A6co\u00A6sai\u00A6mnc\u00A6sah\u00A6kaw\u00A6inh\u00A6gba\u00A6sad\u00A6ch\u00A6ine\u00A6bho\u00A6enm\u00A6kar\u00A6inc\u00A6ce\u00A6gay\u00A6ca\u00A6umb\u00A6syr\u00A6kam\u00A6tsi\u00A6ang\u00A6kac\u00A6cau\u00A6kab\u00A6kaa\u00A6bs\u00A6car\u00A6br\u00A6bo\u00A6bn\u00A6bm\u00A6gaa\u00A6cai\u00A6bi\u00A6bh\u00A6bg\u00A6be\u00A6cad\u00A6ba\u00A6zu\u00A6zen\u00A6pro\u00A6hsb\u00A6az\u00A6ay\u00A6av\u00A6as\u00A6dsb\u00A6ar\u00A6ilo\u00A6elx\u00A6zh\u00A6an\u00A6pra\u00A6am\u00A6new\u00A6ak\u00A6za\u00A6af\u00A6ae\u00A6ab\u00A6aa\u00A6yo\u00A6alg\u00A6ale\u00A6mkh\u00A6yi\u00A6dra\u00A6ber\u00A6nds\u00A6bem\u00A6bej\u00A6tpi";

  private static final String languagesValues = "gwich\u02bbin\u00A6akkadiska\u00A6ekajuk\u00A6xhosa\u00A6sumeriska\u00A6susu\u00A6blandade spr\u00e5k\u00A6lozi\u00A6tonganska (Nyasa)\u00A6ponape\u00A6minangkabau\u00A6sukuma\u00A6wolof\u00A6lolo; mongo\u00A6kutenai\u00A6mic-mac\u00A6walloon\u00A6kumyk\u00A6zapotek\u00A6kushitiska (annat)\u00A6lojban\u00A6dogri\u00A6volap\u00fck\u00A6otomanguespr\u00e5k\u00A6vietnamesiska\u00A6rarotongan\u00A6venda\u00A6rapanui\u00A6rajasthani\u00A6ottomanturkiska (1500-1928)\u00A6nzima\u00A6napolitanska\u00A6uzbekiska\u00A6ugaritiska\u00A6tamashek\u00A6nordamerikanskt indianspr\u00e5k (annat)\u00A6nahuatl; aztekiska\u00A6urdu\u00A6fanti\u00A6ukrainska\u00A6fornegyptiska\u00A6uiguriska\u00A6fang\u00A6nilosahariskt (annat)\u00A6medeliriska (900-1200)\u00A6baltiskt (annat)\u00A6nyoro\u00A6basa\u00A6nyankole\u00A6nyamwezi\u00A6hmong\u00A6balinesiska\u00A6osage\u00A6baluchi\u00A6tahitiska\u00A6bamilekiska spr\u00e5k\u00A6twi\u00A6serer\u00A6tlingit\u00A6tatariska\u00A6tsonga\u00A6banda\u00A6turkiska\u00A6tonganska\u00A6tswana\u00A6tagalog\u00A6turkmeniska\u00A6tigrinja\u00A6thail\u00e4ndska\u00A6kurukh\u00A6tadzjikiska\u00A6blin\u00A6telugu\u00A6kru\u00A6kasjubiska\u00A6tamil\u00A6tokelauiska\u00A6efik\u00A6swahili\u00A6svenska\u00A6sundanesiska\u00A6karachay-balkar\u00A6syd\u00adsotho\u00A6swati\u00A6serbiska\u00A6albanska\u00A6mende\u00A6kreolska och pidgin (annat)\u00A6somaliska\u00A6afrihili\u00A6shona; manshona\u00A6samoanska\u00A6slovenska\u00A6forngrekiska (till 1453)\u00A6slovakiska\u00A6grebo\u00A6singalesiska\u00A6serbokroatiska\u00A6krimturkiska; krimtatar\u00A6afro-asiatiskt (andra)\u00A6sango\u00A6nord\u00adsamiska\u00A6sindhi\u00A6udmurtiska\u00A6sardiska\u00A6sanskrit\u00A6rwanda; kinjarwanda\u00A6ryska\u00A6mandar\u00A6rum\u00e4nska\u00A6rundi\u00A6r\u00e4to\u00adromanska\u00A6moksja\u00A6tivi\u00A6adygeiska\u00A6zu\u00f1i\u00A6kpelle\u00A6quechua\u00A6tigr\u00e9\u00A6songhai\u00A6kreolska och pidgin, portugisiskbaserade (\u00f6vriga)\u00A6sogdiska\u00A6adangme\u00A6kosreanska\u00A6hettitiska\u00A6kreolska och pidgin, franskbaserade (\u00f6vriga)\u00A6kreolska och pidgin, engelskbaserade (\u00f6vriga)\u00A6himachali\u00A6konkani\u00A6hiligaynon\u00A6gotiska\u00A6gorontalo\u00A6gondi\u00A6dinka\u00A6nubiska spr\u00e5k\u00A6portugisiska\u00A6pashto; afghanska\u00A6friulianska\u00A6kananeiska; feniciska\u00A6fornh\u00f6gtyska (ca.750-1050)\u00A6soninke\u00A6koptiska\u00A6acholi\u00A6filippinskt spr\u00e5k (annat)\u00A6polska\u00A6achinese\u00A6pali\u00A6panjabi\u00A6buginesiska\u00A6iban\u00A6skoltsamiska\u00A6buriat\u00A6massajiska\u00A6enaresamiska\u00A6ossetiska\u00A6austronesiska\u00A6oriya\u00A6mande\u00A6lulesamiska\u00A6samiskt spr\u00e5k (annat)\u00A6makasar\u00A6oromo\u00A6maithili\u00A6odjibwa; chippewa\u00A6magahi\u00A6madurese\u00A6sydsamiska\u00A6provensalska (efter 1500); occitanska\u00A6sotho, nord\u00A6batak\u00A6erjya\u00A6dogrib\u00A6nyanja\u00A6maya\u00A6navaho\u00A6kinbundu\u00A6syd\u00adndebele\u00A6medelh\u00f6gtyska (ca.1050-1500)\u00A6norska\u00A6ny\u00adnorsk\u00A6nederl\u00e4ndska\u00A6ndonga\u00A6slaviskt (annat)\u00A6nepalesisika\u00A6nord\u00adndebele\u00A6chamispr\u00e5k\u00A6tetum\u00A6norskt bokm\u00e5l\u00A6nauru\u00A6tereno\u00A6temne\u00A6burmanska\u00A6lezghien\u00A6maltesiska\u00A6fornpersiska (ca 600-400 f.Kr.)\u00A6malajiska\u00A6marathi\u00A6fornfranska (842- ca 1400)\u00A6moldaviska\u00A6medelfranska (ca 1400-1600)\u00A6mongoliska\u00A6judisk arabiska\u00A6malayalam\u00A6makedonska\u00A6maori\u00A6marshalliska\u00A6malagassiska\u00A6marwari\u00A6braj\u00A6slave\u00A6lettiska\u00A6luba-katanga\u00A6delaware\u00A6litauiska\u00A6laotiska\u00A6lingala\u00A6limburgiska\u00A6ewondo\u00A6luganda\u00A6luxemburgiska\u00A6latin\u00A6judisk farsi\u00A6votiska\u00A6sinotibetanska spr\u00e5k\u00A6kirgisiska\u00A6korniska\u00A6kome\u00A6kurdiska\u00A6siouxspr\u00e5k\u00A6kashmiriska\u00A6kanuri\u00A6awadhi\u00A6koreanska\u00A6kanaresiska; kannada\u00A6kambodjanska; khmeriska\u00A6gr\u00f6nl\u00e4ndska\u00A6kazakstanska\u00A6romani\u00A6kuanyama\u00A6sidamo\u00A6kikuyu\u00A6kikongo\u00A6fornnordiska\u00A6georgiska\u00A6muskogee\u00A6romanskt (annat)\u00A6nogai\u00A6mundaspr\u00e5k\u00A6flera spr\u00e5k\u00A6javanesiska\u00A6gilbertesiska; kiribati\u00A6zand\u00e9\u00A6shan\u00A6kalmuckiska\u00A6australiska spr\u00e5k\u00A6khotanesiska\u00A6japanska\u00A6khoisan (annat)\u00A6palau\u00A6cheyenne\u00A6tai (annat)\u00A6inuktitut\u00A6papiamento\u00A6italienska\u00A6teckenspr\u00e5k\u00A6isl\u00e4ndska\u00A6khasi\u00A6cherokesiska\u00A6pampanga\u00A6pahlavi\u00A6chipewyan\u00A6ido\u00A6choctaw\u00A6chinook\u00A6mari\u00A6tuviniska\u00A6bantuspr\u00e5k\u00A6pangasinan\u00A6inupiaq\u00A6chuukesiska\u00A6sichuan yi\u00A6hawaiiska\u00A6lamba\u00A6ibo\u00A6chagatai\u00A6forniriska (till 900)\u00A6papuaspr\u00e5k (annat)\u00A6interlingue\u00A6indonesiska\u00A6lahnda\u00A6dayak\u00A6chibcha\u00A6interlingua\u00A6ladino\u00A6herero\u00A6haida\u00A6dargwa\u00A6armeniska\u00A6athapasiska spr\u00e5k\u00A6ungerska\u00A6haitiska\u00A6dakota\u00A6kroatiska\u00A6hiri motu\u00A6hindi\u00A6dyula\u00A6hebreiska\u00A6asturiska\u00A6haussa\u00A6sorbiska spr\u00e5k\u00A6manx gaeliska\u00A6gujarati\u00A6semitiskt (annat)\u00A6selkup\u00A6irokesiska\u00A6guaran\u00ed\u00A6galiciska\u00A6arawakiska\u00A6geez\u00A6artificiellt (annat)\u00A6skotsk gaeliska\u00A6iranska\u00A6irl\u00e4ndsk gaeliska\u00A6arapaho\u00A6araukanska\u00A6frisiska\u00A6siksika\u00A6germanskt (annat)\u00A6yupiska spr\u00e5k\u00A6arameiska\u00A6franska\u00A6f\u00e4r\u00f6iska\u00A6keltiskt (annat)\u00A6fidjianska\u00A6finska\u00A6fulani\u00A6tuvaluanska\u00A6cebuano\u00A6farsi\u00A6baskiska\u00A6skotska\u00A6estniska\u00A6spanska\u00A6esperanto\u00A6engelska\u00A6grekiska\u00A6altaiskt (annat)\u00A6niuean\u00A6tupispr\u00e5k\u00A6ewe\u00A6tumbuka\u00A6mossi\u00A6dzongkha\u00A6kordofanspr\u00e5k (annat)\u00A6lushai\u00A6finskugriskt (annat)\u00A6divehi\u00A6nias\u00A6mohawk\u00A6lunda\u00A6apachespr\u00e5k\u00A6luise\u00f1o\u00A6hupa\u00A6bini\u00A6tyska\u00A6luba-lulua\u00A6bikol\u00A6washo\u00A6obest\u00e4mt\u00A6waray\u00A6danska\u00A6medelnederl\u00e4ndska (ca 1050-1350)\u00A6walamo\u00A6manobospr\u00e5k\u00A6wakash\u00A6santali\u00A6walesiska\u00A6sasak\u00A6kabardinska\u00A6tjuvasjiska\u00A6kyrkoslaviska\u00A6manipuri\u00A6tjeckiska\u00A6samariska\u00A6cree\u00A6salishspr\u00e5k\u00A6duala\u00A6korsikanska\u00A6nordamerikanskt indianskt (annat)\u00A6manchuriska\u00A6jakutiska\u00A6kawi\u00A6ingusjiska\u00A6gbaya\u00A6sandawe\u00A6chamorro\u00A6indoeuropeiskt (annat)\u00A6bhojpuri\u00A6medelengelska (1100-1500)\u00A6karen\u00A6indiskt (annat)\u00A6tjetjenska\u00A6gayo\u00A6katalanska\u00A6umbundu\u00A6syriska\u00A6kamba\u00A6tsimshian\u00A6fornengelska (ca 450-1100)\u00A6kachin\u00A6kaukasiskt (annat)\u00A6kabyliska\u00A6karakalpakiska\u00A6bosniska\u00A6karibiska\u00A6bretonska\u00A6tibetanska\u00A6bengali\u00A6bambara\u00A6ga\u00A6centralamerikanskt indianskt (annat)\u00A6bislama\u00A6bihari\u00A6bulgariska\u00A6vitryska\u00A6caddo\u00A6basjkiriska\u00A6zulu\u00A6zenaga\u00A6fornprovensalska (till 1500)\u00A6h\u00f6gsorbiska\u00A6azerbajdzjanska\u00A6aymara\u00A6avariska\u00A6assami\u00A6l\u00e5gsorbiska\u00A6arabiska\u00A6iloko\u00A6elamitiska\u00A6kinesiska\u00A6aragonesiska\u00A6prakrit\u00A6amhariska\u00A6newari\u00A6akan\u00A6zhuang\u00A6afrikaans\u00A6avestiska\u00A6abkhaziska\u00A6afar\u00A6yoruba\u00A6algonquinspr\u00e5k\u00A6aleutiska\u00A6mon-khmeriska (annat)\u00A6jiddisch\u00A6dravidiskt (annat)\u00A6berber\u00A6l\u00e5gtyska; l\u00e5gsaxiska\u00A6bemba\u00A6beyja\u00A6tok pisin";

  private static final Hashtable languages;
  static
  {
    languages = new Hashtable();
    Enumeration keys = new StringTokenizer(languagesKeys, "\u00A6");
    Enumeration values = new StringTokenizer(languagesValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         languages.put(key, value);
      }
  }

  private static final String variantsKeys = "REVISED";

  private static final String variantsValues = "Reviderad";

  private static final Hashtable variants;
  static
  {
    variants = new Hashtable();
    Enumeration keys = new StringTokenizer(variantsKeys, "\u00A6");
    Enumeration values = new StringTokenizer(variantsValues, "\u00A6");
    while (keys.hasMoreElements())
      {
         String key = (String) keys.nextElement();
         String value = (String) values.nextElement();
         variants.put(key, value);
      }
  }

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "currenciesDisplayName", currenciesDisplayName },
    { "currenciesSymbol", currenciesSymbol },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "minNumberOfDaysInFirstWeek", "4" },
    { "firstDayOfWeek", "mon" },
    { "eras", eras },
    { "ampms", ampms },
    { "shortDateFormat", "yyyy-MM-dd" },
    { "mediumDateFormat", "yyyy-MM-dd" },
    { "longDateFormat", "'den 'd MMM yyyy" },
    { "fullDateFormat", "'den 'd MMMM yyyy" },
    { "shortTimeFormat", "HH.mm" },
    { "mediumTimeFormat", "HH.mm.ss" },
    { "longTimeFormat", "HH.mm.ss z" },
    { "fullTimeFormat", "'kl. 'HH.mm.ss z" },
    { "zoneStrings", zoneStrings },
    { "territories", territories },
    { "languages", languages },
    { "variants", variants },
  };

  public Object[][] getContents() { return contents; }
}
