/* LocaleInformation_nn.java --
   Copyright (C) 2004  Free Software Foundation, Inc.

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
02111-1307 USA.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */


// This file was automatically generated by gnu.localegen from LDML nn.xml

package gnu.java.locale;

import java.util.ListResourceBundle;

public class LocaleInformation_nn extends ListResourceBundle
{
  private static final String[] shortMonths = {
    "jan",
    "feb",
    "mar",
    "apr",
    "mai",
    "jun",
    "jul",
    "aug",
    "sep",
    "okt",
    "nov",
    "des",
    null,
  };

  private static final String[] months = {
    "januar",
    "februar",
    "mars",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "desember",
    null,
  };

  private static final String[] shortWeekdays = {
    null,
    "su",
    "m\u00e5",
    "ty",
    "on",
    "to",
    "fr",
    "la",
  };

  private static final String[] weekdays = {
    null,
    "sundag",
    "m\u00e5ndag",
    "tysdag",
    "onsdag",
    "torsdag",
    "fredag",
    "laurdag",
  };

  private static final String[] eras = {
    "f.Kr.",
    "e.Kr.",
  };

  private static final class Hashtableterritories extends java.util.Hashtable
  {
    public Hashtableterritories()
      {
        super();
        put("TL", "\u00d8st-Timor");
        put("TK", "Tokelau");
        put("TJ", "Tadsjikistan");
        put("TH", "Thailand");
        put("TG", "Togo");
        put("TF", "Franske s\u00f8romr\u00e5der");
        put("GY", "Guyana");
        put("TD", "Tchad");
        put("TC", "Turks- og Caicos\u00f8yene");
        put("GW", "Guinea-Bissau");
        put("GU", "Guam");
        put("GT", "Guatemala");
        put("GS", "S\u00f8r-Georgia og S\u00f8r-Sandwich-\u00f8yene");
        put("GR", "Hellas");
        put("GQ", "Ekvatorial-Guinea");
        put("GP", "Guadeloupe");
        put("SZ", "Swaziland");
        put("SY", "Syria");
        put("GN", "Guinea");
        put("GM", "Gambia");
        put("GL", "Gr\u00f8nland");
        put("SV", "El Salvador");
        put("ST", "Sao Tome og Principe");
        put("GI", "Gibraltar");
        put("GH", "Ghana");
        put("SR", "Surinam");
        put("GF", "Fransk Guyana");
        put("SP", "Serbia");
        put("GE", "Georgia");
        put("SO", "Somalia");
        put("GD", "Grenada");
        put("SN", "Senegal");
        put("SM", "San Marino");
        put("GB", "Storbritannia");
        put("SL", "Sierra Leone");
        put("GA", "Gabon");
        put("SK", "Slovakia");
        put("SJ", "Svalbard og Jan Mayen");
        put("SI", "Slovenia");
        put("SH", "Saint Helena");
        put("SG", "Singapore");
        put("SE", "Sverige");
        put("SD", "Sudan");
        put("SC", "Seychellene");
        put("SB", "Salomon\u00f8yene");
        put("SA", "Saudi Arabia");
        put("FR", "Frankrike");
        put("FO", "F\u00e6r\u00f8yene");
        put("FM", "Mikronesiaf\u00f8derasjonen");
        put("RW", "Rwanda");
        put("FK", "Falklands\u00f8yene (Malvinas)");
        put("RU", "Den russiske f\u00f8derasjon");
        put("FJ", "Fiji");
        put("FI", "Finland");
        put("RO", "Romania");
        put("RE", "Reunion");
        put("ET", "Etiopia");
        put("ES", "Spania");
        put("ER", "Eritrea");
        put("EH", "Vest-Sahara");
        put("EG", "Egypt");
        put("EE", "Estland");
        put("EC", "Ecuador");
        put("DZ", "Algerie");
        put("QA", "Qatar");
        put("DO", "Den dominikanske republikk");
        put("PY", "Paraguay");
        put("DM", "Dominica");
        put("PW", "Palau");
        put("DK", "Danmark");
        put("DJ", "Djibouti");
        put("PT", "Portugal");
        put("PS", "Palestinsk territorium");
        put("PR", "Puerto Rico");
        put("DE", "Tyskland");
        put("PN", "Pitcairn");
        put("PM", "St. Pierre og Miquelon");
        put("PL", "Polen");
        put("PK", "Pakistan");
        put("PH", "Filippinene");
        put("PG", "Papua Ny-Guinea");
        put("PF", "Fransk Polynesia");
        put("CZ", "Tsjekkia");
        put("PE", "Peru");
        put("CY", "Kypros");
        put("CX", "Christmas\u00f8ya");
        put("CV", "Kapp Verde");
        put("PA", "Panama");
        put("CU", "Cuba");
        put("CR", "Costa Rica");
        put("CO", "Colombia");
        put("CN", "Kina");
        put("CM", "Kamerun");
        put("CL", "Chile");
        put("CK", "Cook\u00f8yene");
        put("CI", "Elfenbenskysten");
        put("CH", "Sveits");
        put("CG", "Kongo");
        put("CF", "Den sentralafrikanske republikk");
        put("CD", "Kongo, Den demokratiske republikken");
        put("CC", "Kokos\u00f8yene (Keeling\u00f8yene)");
        put("OM", "Oman");
        put("CA", "Canada");
        put("BZ", "Belize");
        put("BY", "Hviterussland");
        put("BW", "Botswana");
        put("BV", "Bouvet\u00f8ya");
        put("BT", "Bhutan");
        put("BS", "Bahamas");
        put("BR", "Brasil");
        put("NZ", "New Zealand");
        put("BO", "Bolivia");
        put("BN", "Brunei Darussalam");
        put("BM", "Bermuda");
        put("NU", "Niue");
        put("BJ", "Benin");
        put("BI", "Burundi");
        put("BH", "Bahrain");
        put("NR", "Nauru");
        put("BG", "Bulgaria");
        put("BF", "Burkina Faso");
        put("NP", "Nepal");
        put("BE", "Belgia");
        put("NO", "Noreg");
        put("BD", "Bangladesh");
        put("BB", "Barbados");
        put("ZW", "Zimbabwe");
        put("NL", "Nederland");
        put("BA", "Bosnia og Hercegovina");
        put("NI", "Nicaragua");
        put("NG", "Nigeria");
        put("NF", "Norfolk\u00f8yene");
        put("AZ", "Aserbajdsjan");
        put("NE", "Niger");
        put("NC", "Ny-Caledonia");
        put("AW", "Aruba");
        put("ZM", "Zambia");
        put("NA", "Namibia");
        put("AU", "Australia");
        put("AT", "\u00d8sterrike");
        put("AS", "Amerikansk Samoa");
        put("AR", "Argentina");
        put("AQ", "Antarktis");
        put("MZ", "Mosambik");
        put("AO", "Angola");
        put("MY", "Malaysia");
        put("AN", "De nederlandske antiller");
        put("MX", "Mexico");
        put("AM", "Armenia");
        put("MW", "Malawi");
        put("AL", "Albania");
        put("MV", "Maldivene");
        put("ZA", "S\u00f8r-Afrika");
        put("MU", "Mauritius");
        put("MT", "Malta");
        put("AI", "Anguilla");
        put("MS", "Montserrat");
        put("MR", "Mauritania");
        put("AG", "Antigua og Barbuda");
        put("MQ", "Martinique");
        put("AF", "Afghanistan");
        put("MP", "Nord-Marianene");
        put("AE", "De forente arabiske emiratene");
        put("MO", "Macao S.A.R. (Kina)");
        put("AD", "Andorra");
        put("MN", "Mongolia");
        put("MM", "Myanmar");
        put("ML", "Mali");
        put("MK", "Makedonia, Republikken");
        put("YU", "Jugoslavia");
        put("YT", "Mayotte");
        put("MH", "Marshall\u00f8yene");
        put("MG", "Madagaskar");
        put("MD", "Moldova");
        put("MC", "Monaco");
        put("MA", "Marokko");
        put("YE", "Yemen");
        put("LY", "Libya");
        put("LV", "Latvia");
        put("LU", "Luxembourg");
        put("LT", "Litauen");
        put("LS", "Lesotho");
        put("LR", "Liberia");
        put("LK", "Sri Lanka");
        put("LI", "Liechtenstein");
        put("LC", "St. Lucia");
        put("LB", "Libanon");
        put("LA", "Laos, Den folkedemokratiske republikken");
        put("KZ", "Kasakhstan");
        put("KY", "Cayman\u00f8yene");
        put("KW", "Kuwait");
        put("KR", "S\u00f8r-Korea");
        put("KP", "Nord-Korea");
        put("KN", "St. Christopher og Nevis");
        put("KM", "Komorene");
        put("KI", "Kiribati");
        put("WS", "Samoa");
        put("KH", "Kambodsja");
        put("KG", "Kirgisistan");
        put("KE", "Kenya");
        put("WF", "Wallis og Futuna");
        put("JP", "Japan");
        put("JO", "Jordan");
        put("JM", "Jamaica");
        put("VU", "Vanuatu");
        put("VN", "Vietnam");
        put("VI", "Jomfru\u00f8yene (USA)");
        put("VG", "Jomfru\u00f8yene (britisk)");
        put("VE", "Venezuela");
        put("VC", "St. Vincent og Grenadinene");
        put("VA", "Vatikanstaten");
        put("IT", "Italia");
        put("IS", "Island");
        put("IR", "Iran");
        put("IQ", "Irak");
        put("UZ", "Usbekistan");
        put("IO", "Britiske omr\u00e5der i det indiske hav");
        put("UY", "Uruguay");
        put("IN", "India");
        put("IL", "Israel");
        put("US", "USA");
        put("IE", "Irland");
        put("ID", "Indonesia");
        put("UM", "USAs mindre \u00f8yer");
        put("UG", "Uganda");
        put("UA", "Ukraina");
        put("HU", "Ungarn");
        put("HT", "Haiti");
        put("HR", "Kroatia");
        put("TZ", "Tanzania");
        put("HN", "Honduras");
        put("HM", "Heard- og McDonalds\u00f8yene");
        put("TW", "Taiwan");
        put("TV", "Tuvalu");
        put("HK", "Hong Kong S.A.R. (Kina)");
        put("TT", "Trinidad og Tobago");
        put("TR", "Tyrkia");
        put("TO", "Tonga");
        put("TN", "Tunisia");
        put("TM", "Turkmenistan");
      }
  }

  private static final Object territories = new Hashtableterritories();

  private static final Object[][] contents =
  {
    { "decimalSeparator", "," },
    { "groupingSeparator", "\u00a0" },
    { "shortMonths", shortMonths },
    { "months", months },
    { "shortWeekdays", shortWeekdays },
    { "weekdays", weekdays },
    { "eras", eras },
    { "shortDateFormat", "dd.MM.yy" },
    { "mediumDateFormat", "d. MMM. yyyy" },
    { "longDateFormat", "d. MMMM yyyy" },
    { "fullDateFormat", "EEEE d. MMMM yyyy" },
    { "shortTimeFormat", "HH.mm" },
    { "mediumTimeFormat", "HH.mm.ss" },
    { "longTimeFormat", "HH.mm.ss z" },
    { "fullTimeFormat", "'kl. 'HH.mm.ss z" },
    { "territories", territories },
  };

  public Object[][] getContents() { return contents; }
}
