/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Boolean
#define _Included_java_lang_Boolean

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Boolean */

typedef struct Classjava_lang_Boolean {
  jbool value;
} Classjava_lang_Boolean;
HandleTo(java_lang_Boolean);


#ifdef __cplusplus
}
#endif

#endif
