/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_FileDescriptor
#define _Included_java_io_FileDescriptor

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_FileDescriptor */

typedef struct Classjava_io_FileDescriptor {
  jint fd;
} Classjava_io_FileDescriptor;
HandleTo(java_io_FileDescriptor);

extern jbool java_io_FileDescriptor_valid(struct Hjava_io_FileDescriptor*);
extern void java_io_FileDescriptor_sync(struct Hjava_io_FileDescriptor*);
extern struct Hjava_io_FileDescriptor* java_io_FileDescriptor_initSystemFD(struct Hjava_io_FileDescriptor*, jint);

#ifdef __cplusplus
}
#endif

#endif
