/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Long
#define _Included_java_lang_Long

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Long */

typedef struct Classjava_lang_Long {
#define java_lang_Long_MIN_VALUE 0x8000000000000000
#define java_lang_Long_MAX_VALUE 0x7fffffffffffffff
  jlong value;
} Classjava_lang_Long;
HandleTo(java_lang_Long);


#ifdef __cplusplus
}
#endif

#endif
