/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Math
#define _Included_java_lang_Math

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Math */

typedef struct Classjava_lang_Math {
#define java_lang_Math_E 2.71828
#define java_lang_Math_PI 3.14159
	int __DUMMY__;
} Classjava_lang_Math;
HandleTo(java_lang_Math);

extern jdouble java_lang_Math_sin(jdouble);
extern jdouble java_lang_Math_cos(jdouble);
extern jdouble java_lang_Math_tan(jdouble);
extern jdouble java_lang_Math_asin(jdouble);
extern jdouble java_lang_Math_acos(jdouble);
extern jdouble java_lang_Math_atan(jdouble);
extern jdouble java_lang_Math_exp(jdouble);
extern jdouble java_lang_Math_log(jdouble);
extern jdouble java_lang_Math_sqrt(jdouble);
extern jdouble java_lang_Math_IEEEremainder(jdouble, jdouble);
extern jdouble java_lang_Math_ceil(jdouble);
extern jdouble java_lang_Math_floor(jdouble);
extern jdouble java_lang_Math_rint(jdouble);
extern jdouble java_lang_Math_atan2(jdouble, jdouble);
extern jdouble java_lang_Math_pow(jdouble, jdouble);

#ifdef __cplusplus
}
#endif

#endif
