/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_PrintStream
#define _Included_java_io_PrintStream

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_PrintStream */

typedef struct Classjava_io_PrintStream {
  struct Hjava_io_OutputStream* out;
  jbool autoFlush;
  jbool trouble;
  struct Hjava_io_BufferedWriter* textOut;
  struct Hjava_io_OutputStreamWriter* charOut;
  jbool closing;
} Classjava_io_PrintStream;
HandleTo(java_io_PrintStream);


#ifdef __cplusplus
}
#endif

#endif
