/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_kaffe_lang_UNIXProcess
#define _Included_kaffe_lang_UNIXProcess

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class kaffe_lang_UNIXProcess */

typedef struct Classkaffe_lang_UNIXProcess {
  jbool isalive;
  jint exit_code;
  struct Hjava_io_FileDescriptor* stdin_fd;
  struct Hjava_io_FileDescriptor* stdout_fd;
  struct Hjava_io_FileDescriptor* stderr_fd;
  struct Hjava_io_FileDescriptor* sync_fd;
  jint pid;
  struct Hjava_io_OutputStream* stdin_stream;
  struct Hjava_io_InputStream* raw_stdout;
  struct Hjava_io_InputStream* raw_stderr;
  struct Hjava_lang_ProcessInputStream* piped_stdout_in;
  struct Hjava_lang_ProcessInputStream* piped_stderr_in;
  struct Hjava_io_PipedOutputStream* piped_stdout_out;
  struct Hjava_io_PipedOutputStream* piped_stderr_out;
  jint numReaders;
} Classkaffe_lang_UNIXProcess;
HandleTo(kaffe_lang_UNIXProcess);

extern void kaffe_lang_UNIXProcess_run(struct Hkaffe_lang_UNIXProcess*);
extern jint kaffe_lang_UNIXProcess_forkAndExec(struct Hkaffe_lang_UNIXProcess*, HArrayOfObject*, HArrayOfObject*);
extern void kaffe_lang_UNIXProcess_notifyReaders(struct Hkaffe_lang_UNIXProcess*);
extern void kaffe_lang_UNIXProcess_destroy(struct Hkaffe_lang_UNIXProcess*);

#ifdef __cplusplus
}
#endif

#endif
